import type { StaffMessages } from "./copy";

/**
 * Turkish copy. Must match every key in copy.ts.
 * Sözlük: Öğrenci, Aday, Kayıt, Sınıf, Ders oturumu, Şube, Personel,
 * Giriş yap, Çıkış yap. Etken çatı, kısa cümleler.
 */
export const tr: StaffMessages = {
  brand: {
    name: "Nil Merkezi",
    product: "Eğitim Yönetimi",
  },
  nav: {
    overview: "Ana sayfa",
    dashboard: "Panel",
    reports: "Raporlar",
    forms: "Formlar",
    notifications: "Bildirimler",
    admissions: "Kabul",
    students: "Öğrenciler",
    leads: "Adaylar",
    enrolments: "Kayıtlar",
    placementTests: "Seviye sınavları",
    trialLessons: "Deneme dersleri",
    delivery: "Eğitim",
    courses: "Kurslar",
    classes: "Sınıflar",
    sessions: "Haftam",
    rooms: "Derslikler",
    organisation: "Kişiler ve yerler",
    staffUsers: "Personel",
    branches: "Şubeler",
    departments: "Bölümler",
    setup: "Ayarlar",
    lostReasons: "Kayıp nedenleri",
    actionReasons: "İşlem nedenleri",
    areasOfStudy: "Çalışma alanları",
    customFields: "Özel alanlar",
    system: "Sistem",
    moodleSite: "Moodle",
    systemHealth: "Sistem durumu",
    auditLog: "Denetim kaydı",
    profile: "Profil",
  },
  roles: {
    super_admin: "Süper Yönetici",
    branch_admin: "Şube Yöneticisi",
    vice_manager: "Müdür Yardımcısı",
    hod: "Bölüm Başkanı",
    registrar: "Kayıt Sorumlusu",
    ssa: "Öğrenci Destek",
    teacher: "Öğretmen",
  },
  shell: {
    collapseSidebar: "Kenar çubuğunu daralt",
    expandSidebar: "Kenar çubuğunu genişlet",
    staffNav: "Personel menüsü",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
    displaySize: "Ekran boyutu",
    displayStandard: "Standart",
    displayLarge: "Büyük",
    displayXLarge: "Çok büyük",
    workspace: "Çalışma alanı",
    chooseWorkspace: "Bir şube seçin",
    workspaceHint: "Rolünüz aynı anda tek bir şubede çalışır. Çalışmak istediğiniz şubeyi seçin.",
    noWorkspaces: "Size henüz etkin bir şube atanmadı.",
    notifications: "Bildirimler",
    markAllRead: "Tümünü okundu yap",
    viewAll: "Tüm bildirimleri gör",
    userMenu: "Kullanıcı menüsü",
    signOut: "Çıkış yap",
    signOutEverywhere: "Her yerden çıkış yap",
    roleView: "Rol görünümü",
    roleViewTitle: "Rol görünümü",
    roleViewBody:
      "Uygulamayı daha düşük yetkili bir rol olarak görün. Verileri seçili şube, bölüm veya sınıflarla sınırlayın.",
    viewingAs: "Görüntülenen rol:",
    ownRole: "kendi rolünüz",
    roleViewChanged: "Rol görünümü güncellendi.",
    scopesApplied: "Kapsam uygulandı.",
    roleViewEnded: "Kendi rolünüze döndünüz.",
    returnToRole: "Kendi rolüme dön",
    applyScopes: "Uygula",
    viewAsRole: "Rol olarak görüntüle",
    editRoleView: "Düzenle",
    scopeBranches: "Şubeler",
    scopeBranch: "Şube",
    scopeDepartments: "Bölümler",
    scopeClasses: "Sınıflar",
    allBranches: "Tüm şubeler",
    allDepartments: "Tüm bölümler",
    allClasses: "Tüm sınıflar",
    branchesNoun: "şube",
    departmentsNoun: "bölüm",
    classesNoun: "sınıf",
    searchBranches: "Şube ara",
    searchDepartments: "Bölüm ara",
    searchClasses: "Sınıf ara",
    chooseWorkspaceOption: "Bir şube seçin",
    noAccess: "Erişim yok",
    noAccessHint: "Etkin rolünüz bu sayfayı açamaz. Panelinize dönün.",
    backToDashboard: "Panele dön",
    checkingSession: "Oturum denetleniyor",
    signedInAs: "Giriş yapan",
    search: "Ara veya git",
    breadcrumb: "Sayfa yolu",
    commandPages: "Sayfalar",
    commandPeople: "Personel",
    commandActions: "İşlemler",
    commandEmpty: "Sonuç yok.",
  },
  state: {
    loading: "Yükleniyor",
    notSet: "Belirtilmedi",
    retry: "Yeniden dene",
    empty: "Henüz burada bir şey yok.",
    error403: "Bu sayfaya erişiminiz yok.",
    error404: "Bu kayıt artık yok.",
    error409: "Bu değişiklik daha yeni bir güncellemeyle çakışıyor. Sayfayı yenileyip tekrar deneyin.",
    error422: "İşaretli alanları kontrol edip tekrar deneyin.",
    error429: "Çok fazla istek. Biraz bekleyip tekrar deneyin.",
    error503: "Bu hizmet şu anda etkin değil. Daha sonra tekrar deneyin.",
    errorNetwork: "Ağ bağlantısı kurulamadı. Bağlantınızı kontrol edin.",
    errorGeneric: "İstek başarısız oldu. Tekrar deneyin.",
  },
  status: {
    active: "Etkin",
    disabled: "Devre dışı",
    invited: "Davet edildi",
    canceled: "İptal edildi",
    cancelled: "İptal edildi",
    enrolled: "Kayıtlı",
    completed: "Tamamlandı",
    registered: "Kayıt oldu",
    scheduled: "Planlandı",
    pending: "Bekliyor",
    pending_payment: "Ödeme bekliyor",
    pending_class: "Sınıf bekliyor",
    pending_group: "Grup bekliyor",
    in_process: "Süreçte",
    follow_up: "Takipte",
    future_registration: "İleri tarihli kayıt",
    trial_lesson: "Deneme dersi",
    placement_test: "Seviye sınavı",
    left: "Ayrıldı",
    lost: "Kaybedildi",
    no_show: "Gelmedi",
    healthy: "Sağlıklı",
    degraded: "Kısmen çalışıyor",
    unhealthy: "Sorunlu",
    ok: "Tamam",
    warning: "Uyarı",
    error: "Hata",
    not_configured: "Yapılandırılmadı",
  },
  notifications: {
    title: "Bildirimler",
    description: "Yalnızca sizin gelen kutunuz.",
    all: "Tümü",
    unread: "Okunmamış",
    empty: "Bildiriminiz yok.",
    markRead: "Okundu yap",
    markAllRead: "Tümünü okundu yap",
    delete: "Sil",
    deleteAll: "Tümünü sil",
    deleteAllTitle: "Tüm bildirimler silinsin mi?",
    deleteAllBody: "Bu, sizin kopyalarınızı kalıcı olarak siler. Diğer personelinkiler kalır.",
    read: "Okundu",
    unreadBadge: "Okunmamış",
    markedRead: "Bildirim okundu olarak işaretlendi.",
    allMarkedRead: "Tüm bildirimler okundu olarak işaretlendi.",
    deleted: "Bildirim silindi.",
    allDeleted: "Tüm bildirimler silindi.",
    actionFailed: "Bildirim işlemi başarısız oldu. Tekrar deneyin.",
  },
  profile: {
    title: "Profil",
    description: "Bilgilerinizi, şifrenizi ve etkin oturumlarınızı yönetin.",
    details: "Bilgileriniz",
    role: "Atanan rol",
    email: "E-posta",
    name: "Ad",
    nameNotSet: "Belirtilmedi",
    phone: "Telefon",
    unknownDevice: "Bilinmeyen cihaz",
    password: "Şifre",
    currentPassword: "Mevcut şifre",
    newPassword: "Yeni şifre",
    confirmPassword: "Yeni şifreyi doğrulayın",
    changePassword: "Şifreyi değiştir",
    passwordChanged: "Şifre değiştirildi.",
    passwordFailed: "Şifre değiştirilemedi. Girdiklerinizi kontrol edin.",
    passwordsDiffer: "Yeni şifreler eşleşmiyor.",
    sessions: "Etkin oturumlar",
    sessionsHint: "Tanımadığınız bir oturumu kapatın.",
    thisSession: "Bu oturum",
    lastSeen: "Son görülme",
    issued: "Giriş yapıldı",
    signOutSession: "Oturumu kapat",
    sessionRevoked: "Oturum kapatıldı.",
    signOutEverywhere: "Her yerden çıkış yap",
    signOutEverywhereTitle: "Her yerden çıkış yapılsın mı?",
    signOutEverywhereBody: "Bu, tüm cihazlarda oturumunuzu kapatır. Yeniden giriş yapmanız gerekir.",
  },
  actions: {
    save: "Kaydet",
    cancel: "İptal",
    saving: "Kaydediliyor",
    discardTitle: "Değişiklikler atılsın mı?",
    discardBody: "Değişiklikleriniz kaydedilmedi.",
    discard: "At",
    keepEditing: "Düzenlemeye devam et",
    search: "Ara",
    filter: "Filtrele",
    columns: "Sütunlar",
    selected: "seçili",
    clearSelection: "Seçimi temizle",
    previous: "Önceki",
    next: "Sonraki",
    pageOf: "/",
    create: "Oluştur",
    edit: "Düzenle",
    rowActions: "Satır işlemleri",
    enable: "Etkinleştir",
    disable: "Devre dışı bırak",
    close: "Kapat",
    import: "İçe aktar",
    refresh: "Yenile",
    noReasons: "Önce bu işlem için bir işlem nedeni ekleyin.",
    openActionReasons: "İşlem nedenlerini açın.",
    status: "Durum",
    activeOnly: "Yalnızca etkinler",
    selectAll: "Tüm satırları seç",
    selectRow: "Satırı seç",
    pagination: "Sayfalar",
  },
  catalog: {
    shared: {
      name: "Ad",
      nameRequired: "Bir ad girin.",
      code: "Kod",
      codeHint: "Küçük harf, rakam ve alt çizgi.",
      codePattern: "Yalnızca küçük harf, rakam ve alt çizgi kullanın.",
      sortOrder: "Sıra",
      created: "Oluşturuldu",
      status: "Durum",
      active: "Etkin",
      disabled: "Devre dışı",
      allStatuses: "Tüm durumlar",
      access: "Erişiminiz",
      accessManage: "Yönetim",
      accessView: "Görüntüleme",
      customFields: "Özel alanlar",
      customFieldsEmpty: "Bu kayda uygulanan özel alan yok.",
      enableTitle: "Bu kayıt etkinleştirilsin mi?",
      disableTitle: "Bu kayıt devre dışı bırakılsın mı?",
      enableBody: "Bu kayıt yeniden kullanılabilir olur.",
      createdToast: "Oluşturuldu.",
      updatedToast: "Değişiklikler kaydedildi.",
      enabledToast: "Etkinleştirildi.",
      disabledToast: "Devre dışı bırakıldı.",
      saveChanges: "Değişiklikleri kaydet",
    },
    branches: {
      title: "Şubeler",
      description: "Nil Merkezi'nin faaliyet gösterdiği yerler.",
      empty: "Henüz şube yok.",
      emptyHint: "İlk şubeyi oluşturun.",
      add: "Şube ekle",
      createTitle: "Şube ekle",
      editTitle: "Şubeyi düzenle",
      createDescription: "Etkin bir şube oluşturun.",
      editDescription: "Adı, kodu veya ayarları güncelleyin.",
      createSubmit: "Şube oluştur",
      timezone: "Saat dilimi",
      online: "Çevrim içi şube",
      onlineYes: "Çevrim içi",
      onlineNo: "Yüz yüze",
      searchBranches: "Şube ara",
      disableBody: "Şube yeni iş kabul etmeyi bırakır. Bu şubedeki oturumlar çalışma alanını kaybeder.",
      statisticsTitle: "Etkinlik",
      detailMissing: "Bu şube artık yok.",
      statActiveStudents: "Etkin öğrenciler",
      statOpenLeads: "Açık adaylar",
      statActiveClasses: "Etkin sınıflar",
      statEnrolmentFill: "Dolu koltuklar",
      statEnrolmentCapacity: "Kayıt kapasitesi",
      statPendingEnrolments: "Bekleyen kayıtlar",
      statPlacements: "Planlı seviye sınavları",
      statTrials: "Planlı deneme dersleri",
      statStaff: "Personel",
      bulkDisable: "Seçilenleri devre dışı bırak",
      bulkEnable: "Seçilenleri etkinleştir",
      bulkDone: "Seçim güncellendi.",
    },
    departments: {
      title: "Bölümler",
      description: "Sınıfların ve kursların bağlı olduğu akademik bölümler.",
      empty: "Henüz bölüm yok.",
      emptyHint: "İlk bölümü oluşturun.",
      add: "Bölüm ekle",
      createTitle: "Bölüm ekle",
      editTitle: "Bölümü düzenle",
      createSubmit: "Bölüm oluştur",
      disableBody: "Bölüm yeni işlerde gizlenir.",
    },
    lostReasons: {
      title: "Kayıp nedenleri",
      description: "Bir adayın neden kaybedildiği.",
      empty: "Henüz kayıp nedeni yok.",
      emptyHint: "İlk kayıp nedenini oluşturun.",
      add: "Kayıp nedeni ekle",
      createTitle: "Kayıp nedeni ekle",
      editTitle: "Kayıp nedenini düzenle",
      createSubmit: "Neden oluştur",
      disableBody: "Neden yeni işlerde gizlenir.",
    },
    actionReasons: {
      title: "İşlem nedenleri",
      description: "Korumalı işlemlerin gerektirdiği adlandırılmış nedenler.",
      empty: "Henüz işlem nedeni yok.",
      emptyHint: "İlk nedeni oluşturun veya içe aktarın.",
      add: "İşlem nedeni ekle",
      createTitle: "İşlem nedeni ekle",
      editTitle: "İşlem nedenini düzenle",
      createSubmit: "Neden oluştur",
      disableBody: "Neden yeni işlerde gizlenir.",
      kind: "Tür",
      allKinds: "Tüm türler",
      import: "CSV içe aktar",
      importTitle: "İşlem nedenlerini içe aktar",
      importDescription: "CSV satırlarını yapıştırın veya bir dosya seçin. Önce önizleyin, sonra içe aktarın.",
      chooseFile: "Bir CSV dosyası seçin",
      downloadTemplate: "Şablonu indir",
      orPaste: "Ya da CSV satırlarını yapıştırın",
      importPreview: "Önizleme",
      importRowCount: "satır",
      rowError: "Hata",
      rowErrorColumns: "6 sütun bekleniyordu.",
      rowErrorKind: "Bilinmeyen tür.",
      rowErrorName: "Ad zorunludur.",
      importEmpty: "Önizlemek için CSV satırlarını yapıştırın.",
      importSubmit: "İçe aktar",
      importDone: "İçe aktarma tamamlandı.",
      importCreated: "oluşturuldu",
      importUpdated: "güncellendi",
      csvPlaceholder: "id,action,name,status,sort_order,created_at",
      kindLost: "Kaybedilen aday",
      kindLeft_enrolment: "Kayıttan ayrılma",
      kindCancel_enrolment: "Kaydı iptal etme",
      kindCancel_placement_test: "Seviye sınavını iptal etme",
      kindCancel_trial_lesson: "Deneme dersini iptal etme",
      kindDisable_student: "Öğrenciyi devre dışı bırakma",
      kindDisable_course: "Kursu devre dışı bırakma",
      kindDisable_class: "Sınıfı devre dışı bırakma",
      kindDisable_branch: "Şubeyi devre dışı bırakma",
      kindDisable_department: "Bölümü devre dışı bırakma",
      kindDisable_room: "Dersliği devre dışı bırakma",
      kindDisable_staff: "Personeli devre dışı bırakma",
      kindDisable_area_of_study: "Çalışma alanını devre dışı bırakma",
      kindDisable_custom_field: "Özel alanı devre dışı bırakma",
    },
    areasOfStudy: {
      title: "Çalışma alanları",
      description: "Bir öğrencinin yerleştirilebileceği konular.",
      empty: "Henüz çalışma alanı yok.",
      emptyHint: "İlk çalışma alanını oluşturun.",
      add: "Çalışma alanı ekle",
      createTitle: "Çalışma alanı ekle",
      editTitle: "Çalışma alanını düzenle",
      createSubmit: "Alan oluştur",
      disableBody: "Alan yeni yerleştirmelerde gizlenir.",
      placementCourses: "Seviye sınavı kursları",
      placementCoursesHint: "Seviye sınavlarını içeren Moodle kurslarını seçin.",
      addCourse: "Moodle kursu ekle",
      searchCourses: "Moodle kurslarında ara",
      coursesEmpty: "Eşleşen kurs yok.",
      coursesLoading: "Kurslar yükleniyor",
      coursesError: "Moodle kurslarına ulaşılamıyor.",
    },
    customFields: {
      title: "Özel alanlar",
      description: "Uygulamadaki kayıtlara eklenen ek alanlar.",
      empty: "Henüz özel alan yok.",
      emptyHint: "İlk özel alanı oluşturun.",
      add: "Özel alan ekle",
      createTitle: "Özel alan ekle",
      editTitle: "Özel alanı düzenle",
      createSubmit: "Alan oluştur",
      disableBody: "Alan formlarda gizlenir.",
      entity: "Varlık",
      allEntities: "Tüm varlıklar",
      fieldKey: "Alan anahtarı",
      fieldKeyHint: "Veri modelinde kullanılan küçük harfli tanımlayıcı. Sonradan değiştirilemez.",
      fieldType: "Tür",
      required: "Zorunlu alan",
      requiredYes: "Zorunlu",
      optional: "İsteğe bağlı",
      helpText: "Yardım metni",
      options: "Seçenekler",
      optionsHint: "Her satıra bir seçenek.",
      entityUser_profile: "Personel profili",
      entityStudent: "Öğrenci",
      entityLead: "Aday",
      entityBranch: "Şube",
      entityDepartment: "Bölüm",
      entityClass: "Sınıf",
      entityCourse: "Kurs",
      entityRoom: "Derslik",
    },
  },
  staffUsers: {
    title: "Personel",
    description: "Nil Merkezi'nde çalışan herkes, rolleri, çalıştıkları yer ve nasıl giriş yaptıkları.",
    add: "Personel ekle",
    createTitle: "Personel ekle",
    editTitle: "Personeli düzenle",
    createDescription: "Rol ve kapsamla bir personel hesabı oluşturun.",
    editDescription: "Rolü, profili veya kapsamı güncelleyin.",
    createSubmit: "Personel oluştur",
    empty: "Henüz personel yok.",
    emptyHint: "İlk personeli davet edin.",
    noAccess: "Personel hesaplarını Süper Yönetici ve Şube Yöneticisi yönetir.",
    person: "Kişi",
    email: "E-posta",
    role: "Rol",
    worksAt: "Çalıştığı yer",
    branches: "Şubeler",
    departments: "Bölümler",
    courses: "Kurslar",
    moodle: "Moodle",
    status: "Durum",
    lastSignIn: "Son giriş",
    added: "Eklendi",
    you: "Siz",
    all: "Tümü",
    results: "Sonuçlar",
    clearFilters: "Filtreleri temizle",
    teachersNoMoodle: "Moodle hesabı olmayan öğretmenler",
    allRoles: "Tüm roller",
    allBranches: "Tüm şubeler",
    allDepartments: "Tüm bölümler",
    globalScope: "Tüm şubeler",
    branchScope: "Şube kapsamı",
    branchScopeHint:
      "Müdür Yardımcısı tam olarak bir şube gerektirir. Kayıt Sorumlusu, Öğrenci Destek ve Öğretmen en az bir şube gerektirir.",
    workspaceScopeHint: "Yeni hesaplar çalışma alanı şubenizi içermelidir.",
    invited: "Davet edildi",
    moodleLinked: "Bağlı",
    moodleMissing: "Bağlı değil",
    provisioning: "Hesap açma",
    provisioningInvitation: "Davet bağlantısı",
    provisioningManual: "Elle şifre",
    provisioningHint: "Davet tek kullanımlık bir bağlantı oluşturur. Elle seçeneği geçici bir şifre oluşturur.",
    firstName: "Ad",
    lastName: "Soyad",
    phone: "Telefon",
    address: "Adres",
    nationality: "Uyruk",
    nationalityHint: "Üç harfli ülke kodu.",
    dateOfBirth: "Doğum tarihi",
    notes: "Notlar",
    canTakePlacementTest: "Seviye sınavı yapabilir",
    yourPassword: "Şifreniz",
    yourPasswordHint: "Bu Süper Yönetici değişikliği için kendi şifreniz gerekir.",
    yourPasswordRequired: "Devam etmek için kendi şifrenizi girin.",
    firstNameRequired: "Ad zorunludur.",
    lastNameRequired: "Soyad zorunludur.",
    emailRequired: "Geçerli bir e-posta adresi girin.",
    branchScopeRequired: "En az bir şube seçin.",
    viceManagerScope: "Müdür Yardımcısı tam olarak bir şube gerektirir.",
    invite: "Davet et",
    resendInvite: "Daveti yeniden gönder",
    inviteTitle: "Yeni davet gönderilsin mi?",
    inviteBody: "Önceki davet bağlantısı çalışmayı bırakır.",
    cancelInvite: "Daveti iptal et",
    cancelInviteTitle: "Bu davet iptal edilsin mi?",
    cancelInviteBody: "Davet bağlantısı hemen çalışmayı bırakır.",
    setPassword: "Şifre belirle",
    setPasswordTitle: "Yeni şifre belirlensin mi?",
    setPasswordBody: "Geçici şifre bir kez oluşturulur. Güvenli bir kanaldan paylaşın.",
    moodleAccount: "Moodle hesabı",
    moodleCreate: "Moodle hesabı oluştur",
    moodleLink: "Moodle hesabı bağla",
    moodleReset: "Moodle şifresini sıfırla",
    moodleResetTitle: "Moodle şifresi sıfırlansın mı?",
    moodleResetBody: "Yeni Moodle şifresi bir kez oluşturulur. Güvenli bir kanaldan paylaşın.",
    moodleSearch: "Moodle hesaplarında ara",
    moodleSearchHint: "Ad, kullanıcı adı veya e-postayla arayın.",
    moodleSearchMin: "En az 2 karakter yazın.",
    moodleSearchEmpty: "Eşleşen Moodle hesabı yok.",
    moodleCreateHint: "Bu personele bağlı bir Moodle hesabı oluşturur.",
    moodleLinkHint: "Mevcut bir Moodle hesabını bu personele bağlayın.",
    disableTitle: "Bu personel devre dışı bırakılsın mı?",
    disableBody: "Hesap artık giriş yapamaz.",
    enableTitle: "Bu personel etkinleştirilsin mi?",
    enableBody: "Hesap yeniden giriş yapabilir.",
    bulkDisable: "Seçilenleri devre dışı bırak",
    bulkEnable: "Seçilenleri etkinleştir",
    bulkDone: "Seçim güncellendi.",
    createdToast: "Personel oluşturuldu.",
    updatedToast: "Değişiklikler kaydedildi.",
    invitedToast: "Davet oluşturuldu.",
    cancelledToast: "Davet iptal edildi.",
    passwordToast: "Şifre sıfırlandı.",
    moodleToast: "Moodle hesabı güncellendi.",
    disabledToast: "Personel devre dışı bırakıldı.",
    enabledToast: "Personel etkinleştirildi.",
    secretTitle: "Tek kullanımlık bilgiler",
    secretBody: "Bunları şimdi kopyalayın. Bir daha gösterilmezler.",
    secretShare: "Bilgileri yalnızca güvenli bir kanaldan paylaşın.",
    secretDone: "Tamam",
    copyValue: "Kopyala",
    copied: "Kopyalandı.",
    invitationLink: "Davet bağlantısı",
    temporaryPassword: "Geçici şifre",
    moodlePassword: "Moodle şifresi",
    moreActions: "Diğer işlemler",
    copyEmail: "E-postayı kopyala",
    emailCopied: "E-posta kopyalandı.",
    tabOverview: "Genel bakış",
    tabCourses: "Kurslar",
    tabAvailability: "Uygunluk",
    tabActivity: "Etkinlik",
    sectionContact: "İletişim",
    sectionAccess: "Erişim",
    sectionMore: "Diğer bilgiler",
    neverSignedIn: "Hiç giriş yapmadı",
    statsAdmissions: "Kabul",
    statsTeaching: "Eğitim",
    statLeadsCreated: "Oluşturulan adaylar",
    statLeadsAssigned: "Atanan adaylar",
    statLeadsOpen: "Açık adaylar",
    statLeadsRegistered: "Kayıt olan",
    statLeadsLost: "Kaybedilen",
    statStudentsAssigned: "Atanan öğrenciler",
    statClassesTeaching: "Verdiği sınıflar",
    statSessionsScheduled: "Planlı oturumlar",
    statStudentsTaught: "Ders verilen öğrenciler",
    statsEmpty: "Henüz etkinlik kaydı yok.",
    coursesTitle: "Verebileceği kurslar",
    coursesHint: "Liste boşsa bu öğretmen bir sınıfa atanamaz.",
    coursesSaved: "Kurslar güncellendi.",
    coursesSearchPlaceholder: "Kurs ara",
    placementCapability: "Seviye sınavları",
    placementYes: "Seviye sınavı yapabilir",
    placementNo: "Seviye sınavı yapamaz",
    availabilityTitle: "Uygunluk",
    availabilityHint: "Bu öğretmenin çalıştığı saatleri boyayın. Planlanmış oturumlar değiştirilemez.",
    penAvailable: "Uygun",
    penUnavailable: "Uygun değil",
    penClear: "Temizle",
    showAllHours: "Tüm saatleri göster",
    showWorkHours: "Çalışma saatlerini göster",
    timezoneLabel: "Saat dilimi",
    unsavedBar: "Kaydedilmemiş değişiklikleriniz var.",
    saveChanges: "Değişiklikleri kaydet",
    discardChanges: "At",
    discardTitle: "Uygunluk değişiklikleri atılsın mı?",
    discardBody: "Boyadığınız değişiklikler kaydedilmedi.",
    cellsSaved: "Uygunluk kaydedildi.",
    cellsSkippedBooked: "Planlanmış oturumlar atlandı.",
    weekToday: "Bugün",
    weekPrevious: "Önceki hafta",
    weekNext: "Sonraki hafta",
    bookedSession: "Planlandı",
  },
  moodleSite: {
    title: "Moodle sitesi",
    description: "Kursları, grupları ve yoklamayı yürüten Moodle sitesini bağlayın.",
    noAccess: "Moodle sitesini yalnızca Süper Yönetici yapılandırabilir.",
    connection: "Bağlantı",
    connectionHint: "Moodle için web servisi bilgileri. Belirteç yalnızca yazılabilir.",
    siteUrl: "Site adresi",
    token: "Web servisi belirteci",
    tokenHint: "Güvenle saklanır. Yalnızca belirteci değiştirmek için yeniden girin.",
    tokenKeep: "Mevcut belirteci korumak için boş bırakın.",
    autoCreate: "Öğrenci Moodle hesaplarını otomatik oluştur",
    autoCreateHint: "Açıkken, öğrenci oluşturulduğunda Moodle hesabı da oluşturulmaya çalışılır.",
    ptCourse: "Seviye sınavı Moodle kurs kimliği",
    ptCourseHint: "Seviye sınavının bulunduğu Moodle kursu. Temizlemek için boş bırakın.",
    save: "Değişiklikleri kaydet",
    connect: "Moodle'ı bağla",
    test: "Bağlantıyı test et",
    disconnect: "Bağlantıyı kes",
    disconnectTitle: "Moodle bağlantısı kesilsin mi?",
    disconnectBody: "Kayıtlı belirteç kaldırılır. Yeniden bağlanana kadar kurslar ve gruplar eşitlenmez.",
    saved: "Moodle yapılandırması kaydedildi.",
    disconnected: "Moodle bağlantısı kesildi.",
    testOk: "Bağlantı testi başarılı.",
    testVersionWarn: "Erişilebilir, ancak Moodle sürümü beklenen 4.5.x aralığının dışında.",
    testFailed: "Moodle'a erişilemiyor.",
    statusTitle: "Durum",
    statConfigured: "Yapılandırıldı",
    statToken: "Belirteç kayıtlı",
    statReachable: "Erişilebilir",
    statVersion: "Beklenen sürüm",
    statSitename: "Site adı",
    statRelease: "Sürüm",
    statLastChecked: "Son kontrol",
    statWarnings: "Uyarılar",
    statLastError: "Son hata",
    unknown: "Bilinmiyor",
    yes: "Evet",
    no: "Hayır",
  },
  system: {
    title: "Sistem durumu",
    description: "Temel hizmetlerin ve Moodle entegrasyonunun canlı durumu.",
    noAccess: "Sistem durumunu yalnızca Süper Yönetici görebilir.",
    refresh: "Yenile",
    checked: "Kontrol edildi",
    componentApi: "API",
    componentDatabase: "Veritabanı",
    componentSchema: "Şema kontrolü",
    componentMigration: "Geçişler",
    componentMoodle: "Moodle",
    operational: "Çalışıyor.",
    version: "Sürüm",
    configured: "Yapılandırıldı",
    token: "Belirteç",
    reachable: "Erişilebilir",
    site: "Site",
    release: "Sürüm",
    expected: "Beklenen 4.5.x",
    warnings: "Uyarılar",
  },
  audit: {
    title: "Denetim kaydı",
    description: "Kim, ne zaman, ne yaptı. En yenisi önce.",
    noAccess: "Denetim kayıtlarını yalnızca Süper Yönetici ve Şube Yöneticisi okuyabilir.",
    stream: "Akış",
    allStreams: "Tüm akışlar",
    search: "Kayıtlarda ara",
    empty: "Denetim kaydı yok.",
    emptyHint: "İşlemler gerçekleştikçe burada kaydedilir.",
    payload: "Veri",
    actor: "Yapan",
    system: "Sistem",
    today: "Bugün",
    yesterday: "Dün",
    latest: "Son {n} olay",
    failedSignIn: "Biri",
    groups: {
      all: "Tümü",
      auth: "Girişler",
      admissions: "Kabul",
      teaching: "Eğitim",
      setup: "Kurulum",
    },
    nouns: {
      auth: "hesap",
      branch: "şube",
      department: "bölüm",
      course: "kurs",
      custom_field: "özel alan",
      moodle_site: "Moodle bağlantısı",
      student: "öğrenci",
      lead: "aday",
      placement_test: "seviye sınavı",
      class: "sınıf",
      enrolment: "kayıt",
      room: "salon",
      session: "ders",
    },
    verbs: {
      created: "{noun} oluşturdu",
      updated: "{noun} güncelledi",
      disabled: "{noun} devre dışı bıraktı",
      enabled: "{noun} etkinleştirdi",
      cancelled: "{noun} iptal etti",
      completed: "{noun} tamamladı",
      refreshed: "{noun} yeniledi",
      tested: "{noun} test etti",
      other: "{action}: {noun}",
    },
    actions: {
      login_success: "giriş yaptı",
      login_failed: "giriş yapamadı",
      logout: "çıkış yaptı",
      workspace_switched: "şube değiştirdi",
      role_switched: "rol görünümünü değiştirdi",
      invitation_sent: "davet gönderdi:",
      invitation_accepted: "daveti kabul etti",
      user_created: "personel hesabı oluşturdu:",
      moodle_group_created: "Moodle grubu oluşturdu:",
      moodle_group_deleted: "Moodle grubunu kaldırdı:",
      moodle_group_synced: "Moodle ile eşitledi:",
      moodle_linked: "Moodle hesabı bağladı:",
      converted: "öğrenciye dönüştürdü:",
      enrolled: "öğrenci kaydetti",
    },
    streams: {
      auth: "Giriş",
      branch: "Şube",
      department: "Bölüm",
      course: "Kurs",
      custom_field: "Özel alan",
      moodle_site: "Moodle sitesi",
      student: "Öğrenci",
      lead: "Aday",
      placement_test: "Seviye sınavı",
      class: "Sınıf",
      enrolment: "Kayıt",
      room: "Derslik",
      session: "Ders oturumu",
    },
  },
  dashboard: {
    morning: "Günaydın",
    afternoon: "İyi günler",
    evening: "İyi akşamlar",
    nameSeparator: ", ",
    intro: "Bugün sizi bekleyenler burada.",
    openLeads: "Açık adaylar",
    openLeadsNote: "Henüz kayıt olmamış veya kaybedilmemiş",
    bookings: "Yaklaşan randevular",
    tests: "sınav",
    trials: "deneme",
    waitingSales: "Bekleyen satışlar",
    waitingSalesNote: "Ödeme veya sınıf eksik",
    classFill: "Sınıf doluluğu",
    seatsOf: "/",
    seats: "koltuk dolu",
    activeStudents: "Etkin öğrenciler",
    activeStudentsNote: "Etkin kaydı olanlar",
    today: "Bugün",
    todayEmpty: "Bugün için randevu yok.",
    overdue: "geçmiş randevu sonuç bekliyor",
    openAgenda: "Ajandayı aç",
    attention: "İlgi bekleyenler",
    allClear: "Bekleyen bir şey yok",
    resultsToRecord: "Girilecek sonuçlar",
    unpaid: "Ödenmemiş kurs satışları",
    waitingClass: "Ödendi, sınıf bekliyor",
    unowned: "Sorumlusu olmayan açık adaylar",
    formResponses: "Yeni form yanıtları",
    period: "Dönem",
    periods: {
      "7d": "7 gün",
      "30d": "30 gün",
      "90d": "90 gün",
      "12m": "12 ay",
      all: "Tüm zamanlar",
    },
    vsPrevious: "önceki döneme göre",
    noChange: "Değişiklik yok",
    pts: " puan",
    newLeads: "Yeni adaylar",
    conversion: "Dönüşüm",
    conversionNote: "Sonuçlanan adaylardan kayıt olanlar",
    intake: "Aday akışı",
    intakeNote: "Haftalık yeni adaylar",
    weekOf: "Hafta:",
    outcomes: "Aday sonuçları",
    open: "Açık",
    registered: "Kayıt oldu",
    lost: "Kaybedildi",
    noData: "Bu dönemde aday yok.",
    funnel: "Başvurudan öğrenciye",
    funnelLeads: "Adaylar",
    funnelBooked: "Tamamlanan sınav ve dersler",
    bookingsTitle: "Sınavlar ve deneme dersleri",
    placementTests: "Seviye sınavları",
    trialLessons: "Deneme dersleri",
    completed: "Tamamlandı",
    scheduledLabel: "Planlandı",
    noShow: "Gelmedi",
    cancelled: "İptal edildi",
    showRate: "katılım",
    pipeline: "Aday hattı",
    pipelineEmpty: "Açık aday yok.",
    branches: "Şubeler",
    branch: "Şube",
    students: "Öğrenciler",
    classes: "Sınıflar",
    fill: "Doluluk",
    waiting: "Bekleyen",
    placement: "Seviye sınavı",
    trial: "Deneme dersi",
    myClasses: "Sınıflarım",
    myStudents: "Sınıflarımdaki öğrenciler",
    nextSession: "Sonraki oturum",
    noNextSession: "Planlı oturum yok",
    sessions: "Yaklaşan oturumlar",
    sessionsEmpty: "Henüz planlı oturum yok.",
    classesEmpty: "Size henüz sınıf atanmadı.",
    openMoodle: "Moodle'da aç",
    departmentClasses: "Bölüm sınıfları",
    seatsFree: "Boş koltuklar",
    noTeacher: "Öğretmeni olmayan sınıflar",
    departmentEmpty: "Bölümlerinizde henüz sınıf yok.",
    teachers: "Öğretmenler",
    schedule: "Program",
    unassignedTeacher: "Öğretmen yok",
    enrolled: "kayıtlı",
    loadError: "Bazı rakamlar yüklenemedi.",
  },
  teaching: {
    hourUnit: "sa",
    seats: "koltuk",
    seatsLeft: "boş",
    full: "Dolu",
    allBranches: "Tüm şubeler",
    branch: "Şube",
    required: "Zorunlu.",
    wholeNumber: "Sıfırdan büyük bir tam sayı girin.",
    openMoodle: "Moodle'da aç",
    courses: {
      title: "Kurslar",
      description: "Moodle'dan bağlanan kurslar; saatleri, bölümleri ve güncel talep.",
      empty: "Eşleşen kurs yok.",
      emptyHint: "Satışa başlamak için bir Moodle kursu bağlayın.",
      course: "Kurs",
      department: "Bölüm",
      allDepartments: "Tüm bölümler",
      area: "Çalışma alanı",
      noArea: "Alan yok",
      hours: "Saat",
      totalHours: "Toplam ders saati",
      moodle: "Moodle",
      moodleVisible: "Görünür",
      moodleHidden: "Gizli",
      moodleChecked: "Moodle kontrolü",
      refreshError: "Moodle yenilemesi başarısız",
      refreshAll: "Moodle'dan yenile",
      refreshAllToast: "Kurslar Moodle'dan yenilendi.",
      refreshOne: "Moodle'dan yenile",
      refreshOneToast: "Kurs Moodle'dan yenilendi.",
      link: "Moodle kursu bağla",
      linkTitle: "Bir Moodle kursu bağlayın",
      linkDescription: "Kurslar Moodle'dan gelir. Henüz bağlı olmayan birini seçin ve ders saatlerini belirleyin.",
      linkSubmit: "Kursu bağla",
      linkToast: "Kurs bağlandı.",
      editTitle: "Kursu düzenle",
      editDescription: "Bölüm, saatler, çalışma alanı ve öncesinde gelen kurs.",
      editToast: "Kurs güncellendi.",
      chooseMoodle: "Bir Moodle kursu seçin.",
      noUnmapped: "Tüm Moodle kursları zaten bağlı.",
      searchMoodle: "Moodle kurslarında ara",
      previous: "Öncesinde gelen",
      noPrevious: "Önceki kurs yok",
      attendanceId: "Moodle yoklama etkinliği",
      attendanceHint: "Yoklama almak için gereklidir. Moodle kursundaki yoklama etkinliğinin kimliğidir.",
      noAttendance: "Belirtilmedi, bu yüzden yoklama alınamaz.",
      disable: "Kursu devre dışı bırak",
      disableTitle: "Bu kurs devre dışı bırakılsın mı?",
      disableBody: "Artık satılamaz ve yeni sınıf açılamaz. Mevcut sınıflar kalır.",
      disabledToast: "Kurs devre dışı bırakıldı.",
      enable: "Kursu etkinleştir",
      enableTitle: "Bu kurs etkinleştirilsin mi?",
      enableBody: "Yeniden satılabilir ve yeni sınıf açılabilir.",
      enabledToast: "Kurs etkinleştirildi.",
      demand: "Güncel talep",
      activeClasses: "Etkin sınıflar",
      seatsTaken: "Dolu koltuklar",
      waitingSales: "Bekleyen satışlar",
      interestedLeads: "İlgilenen adaylar",
      classes: "Sınıflar",
      noClasses: "Bu kurs için henüz sınıf yok.",
      writeNote: "Kursları yalnızca Süper Yönetici değiştirir.",
    },
    classes: {
      title: "Sınıflar",
      description: "Tüm sınıflar; öğretmenleri, olağan saatleri, koltukları ve Moodle grubu.",
      empty: "Eşleşen sınıf yok.",
      emptyHint: "Etkin bir kurs için sınıf oluşturun.",
      add: "Sınıf ekle",
      createTitle: "Sınıf ekle",
      editTitle: "Sınıfı düzenle",
      createDescription: "Kurs, tarihler, koltuklar, öğretmenler ve olağan haftalık saat.",
      editDescription: "Tarihler, koltuklar, öğretmenler, olağan saat ve toplantı bağlantısı.",
      createSubmit: "Sınıf oluştur",
      createdToast: "Sınıf oluşturuldu.",
      updatedToast: "Sınıf güncellendi.",
      name: "Sınıf adı",
      course: "Kurs",
      allCourses: "Tüm kurslar",
      kind: "Sınıf türü",
      group: "Grup",
      individual: "Bire bir",
      capacity: "Koltuk",
      starts: "Başlangıç",
      ends: "Bitiş",
      dates: "Tarihler",
      teachers: "Öğretmenler",
      noTeachers: "Bu şubede henüz öğretmen bulunamadı.",
      noTeacher: "Öğretmen yok",
      usualDays: "Olağan günler",
      from: "Başlangıç",
      to: "Bitiş",
      usualTime: "Olağan saat",
      noSchedule: "Olağan saat yok",
      meetingLink: "Toplantı bağlantısı",
      meetingHint: "Çevrim içi sınıflar için. https bağlantısı kullanın.",
      meetingInvalid: "https:// ile başlayan bir bağlantı kullanın",
      endBeforeStart: "Bitiş tarihi başlangıç tarihinden sonra olmalıdır.",
      timeOrder: "Bitiş saati başlangıç saatinden sonra olmalıdır.",
      timeBoth: "İki saati birlikte belirleyin ya da hiçbirini belirlemeyin.",
      daysNeedTime: "Günleri ve saati birlikte seçin.",
      fill: "Koltuk",
      moodleGroup: "Moodle grubu",
      moodleLinked: "Bağlı",
      moodleMissing: "Bağlı değil",
      lastSynced: "Son eşitleme",
      neverSynced: "Hiç eşitlenmedi",
      tabOverview: "Genel bakış",
      tabStudents: "Öğrenciler",
      tabSessions: "Oturumlar",
      tabAttendance: "Yoklama",
      tabGrades: "Notlar",
      disable: "Sınıfı devre dışı bırak",
      disableTitle: "Bu sınıf devre dışı bırakılsın mı?",
      disableBody: "Yeni öğrenci almaz. Kayıtlı öğrenciler ve geçmiş kalır.",
      disabledToast: "Sınıf devre dışı bırakıldı.",
      enable: "Sınıfı etkinleştir",
      enableTitle: "Bu sınıf etkinleştirilsin mi?",
      enableBody: "Yeniden öğrenci alabilir.",
      enabledToast: "Sınıf etkinleştirildi.",
      moodleCreate: "Moodle grubu oluştur",
      moodleLink: "Moodle grubu bağla",
      moodleTitle: "Moodle grubu",
      moodleDescription: "Moodle kursunda yeni bir grup oluşturun veya mevcut bir grubu bağlayın.",
      moodleSearch: "Moodle gruplarında ara",
      moodleBound: "Moodle grubu bağlandı.",
      sync: "Moodle ile eşitle",
      syncTitle: "Moodle eşitlemesi",
      syncDone: "Moodle ile eşitlendi.",
      syncPartial: "Bazı sorunlarla eşitlendi.",
      stepGroup: "Grup",
      stepTeachers: "Öğretmenler",
      stepStudents: "Öğrenciler",
      stepSessions: "Yoklama oturumları",
      stepGrades: "Notlar",
      stepOk: "Tamam",
      stepError: "Başarısız",
      students: "Öğrenciler",
      studentsEmpty: "Bu sınıfta henüz öğrenci yok.",
      addStudents: "Ödemesi yapılmış öğrencileri ekle",
      addStudentsHint: "Bu şubede bu kursu bekleyen ödenmiş kurs satışları.",
      noWaiting: "Burada bu kursu bekleyen ödenmiş satış yok.",
      attachToast: "Öğrenci sınıfa eklendi.",
      noMoodleAccount: "Moodle hesabı yok",
      readOnly: "Bu sınıfı görüntüleyebilirsiniz. Değişiklikleri şube ekibi yapar.",
    },
    sessions: {
      upcoming: "Yaklaşan",
      past: "Geçmiş",
      cancelled: "İptal edilen",
      empty: "Henüz oturum yok.",
      emptyHint: "Öğretmen ve derslik uygunluğuna göre oturum planlayın.",
      plan: "Oturum planla",
      planTitle: "Oturum planla",
      planDescription: "Her gün için saat belirleyin. EMS, öğretmenin ve bir dersliğin birlikte boş olduğu en erken zamanı bulur.",
      weekday: "Gün",
      hours: "Saat",
      addDay: "Gün ekle",
      removeDay: "Günü kaldır",
      fromDate: "Başlangıç",
      toDate: "Bitiş",
      findTimes: "Zaman bul",
      proposed: "Önerilen zamanlar",
      noMatch: "Her gün için uygun zaman yok. Öğretmen veya derslik saatlerini açın ya da günleri değiştirin.",
      book: "Bu oturumları planla",
      bookedToast: "Oturumlar planlandı.",
      reschedule: "Saati değiştir",
      rescheduleTitle: "Oturum saatini değiştir",
      rescheduleDescription: "Yeni bir başlangıç seçin. Öğretmen ve derslik uygunluğuna uymalıdır.",
      movedToast: "Oturum taşındı.",
      cancel: "Oturumu iptal et",
      cancelTitle: "Bu oturum iptal edilsin mi?",
      cancelBody: "Öğrencilerin ve öğretmenin programından çıkar.",
      cancelledToast: "Oturum iptal edildi.",
      length: "Süre",
      room: "Derslik",
      teacher: "Öğretmen",
      online: "Çevrim içi",
      today: "Bugün",
      dayRequired: "En az bir gün ekleyin.",
      dayTwice: "Her gün yalnızca bir kez eklenebilir.",
      rangeInvalid: "Bitiş tarihi başlangıç tarihiyle aynı veya sonra olmalıdır.",
      pastLocked: "Geçmiş oturumlar değiştirilemez.",
      attendance: "Yoklama",
    },
    week: {
      title: "Haftam",
      description: "Bu haftaki oturumlarınız ve her birinin ardından alınacak yoklama.",
      thisWeek: "Bu hafta",
      previous: "Önceki hafta",
      next: "Sonraki hafta",
      sessions: "oturum",
      hours: "saat",
      needAttendance: "yoklama bekliyor",
      empty: "Bu hafta oturum yok.",
      noMoodle: "Henüz Moodle oturumu yok",
      dayOff: "Boş",
    },
    attendance: {
      empty: "Henüz Moodle yoklama oturumu yok.",
      emptyHint: "Programdan oluşturmak için sınıfı Moodle ile eşitleyin.",
      take: "Yoklama al",
      sheetTitle: "Yoklama",
      sheetEmpty: "Bu oturumda henüz öğrenci yok.",
      markAll: "Tümünü geldi işaretle",
      save: "Yoklamayı kaydet",
      savedToast: "Yoklama kaydedildi.",
      notTaken: "Alınmadı",
      taken: "Alındı",
      notMarked: "İşaretlenmedi",
      marked: "işaretli",
      of: "/",
      needsActivity: "Önce kursun Moodle yoklama etkinliğini belirleyin.",
    },
    grades: {
      empty: "Moodle'da henüz not yok.",
      student: "Öğrenci",
      courseGrade: "Kurs notu",
    },
    rooms: {
      title: "Derslikler",
      description: "Her şubedeki derslikler, kapasiteleri ve rezerve edilebilecekleri saatler.",
      add: "Derslik ekle",
      createTitle: "Derslik ekle",
      editTitle: "Dersliği düzenle",
      createDescription: "Dersliğe bir ad verin ve kaç kişilik olduğunu belirtin.",
      name: "Derslik adı",
      capacity: "Koltuk",
      createSubmit: "Derslik oluştur",
      createdToast: "Derslik oluşturuldu.",
      updatedToast: "Derslik güncellendi.",
      empty: "Eşleşen derslik yok.",
      emptyHint: "Sınıf ve sınav planlanabilmesi için bir derslik ekleyin.",
      disable: "Dersliği devre dışı bırak",
      disableTitle: "Bu derslik devre dışı bırakılsın mı?",
      disableBody: "Artık rezerve edilemez. Geçmiş rezervasyonlar kalır.",
      disabledToast: "Derslik devre dışı bırakıldı.",
      enable: "Dersliği etkinleştir",
      enableTitle: "Bu derslik etkinleştirilsin mi?",
      enableBody: "Yeniden rezerve edilebilir.",
      enabledToast: "Derslik etkinleştirildi.",
      availability: "Uygunluk",
      availabilityHint: "Bu dersliğin rezerve edilebileceği saatleri boyayın. Dolu saatler kilitli kalır.",
      availabilityToast: "Uygunluk kaydedildi.",
      unlimited: "Belirtilmedi",
    },
  },
  forms: {
    title: "Formlar",
    description: "Kendi formlarınızı oluşturun, ailelerle veya personelle paylaşın ve her yanıtla ilgilenin.",
    intro: "Giriş",
    yes: "Evet",
    no: "Hayır",
    agreed: "Onaylandı",
    form: "Form",
    tabForms: "Formlarım",
    tabResponses: "Yanıtlar",
    tabToFill: "Doldurulacaklar",
    newForm: "Yeni form",
    newTitle: "Yeni form",
    newDescription: "Boş başlayın veya bir şablon seçin. Yayınlamadan önce her şeyi değiştirebilirsiniz.",
    createSubmit: "Formu oluştur",
    createdToast: "Form oluşturuldu.",
    titleEn: "Başlık (İngilizce)",
    titleAr: "Başlık (Arapça)",
    category: "Kategori",
    template: "Başlangıç",
    blank: "Boş form",
    branch: "Şube",
    allBranchesForm: "Tüm şubeler",
    empty: "Henüz form yok.",
    emptyHint: "Bir Jotform'un veya kâğıt formun yerine bir form oluşturun.",
    responsesEmpty: "Henüz yanıt yok.",
    toFillEmpty: "Şu anda doldurulacak bir şey yok.",
    toFillHint: "Size veya rolünüze atanan formlar burada görünür.",
    status: { draft: "Taslak", active: "Yayında", retired: "Kaldırıldı" },
    categories: {
      admissions: "Kabul",
      student_support: "Öğrenci desteği",
      attendance: "Yoklama",
      consent: "Onay",
      branch_operations: "Şube işleri",
    },
    responseStatus: {
      submitted: "Yeni",
      under_review: "İnceleniyor",
      accepted: "Kabul edildi",
      rejected: "Reddedildi",
      promoted: "İşleme alındı",
      withdrawn: "Geri çekildi",
      quarantined: "Beklemede",
    },
    responses: "Yanıtlar",
    updated: "Güncellendi",
    live: "Yayın bağlantısı",
    notLive: "Paylaşılmadı",
    open: "Aç",
    fill: "Doldur",
    filled: "Gönderildi",
    due: "Kapanış",
    tabBuild: "Tasarım",
    tabShare: "Paylaş",
    tabResponses2: "Yanıtlar",
    editDraft: "Yeni sürüm düzenle",
    editingDraft: "Taslak",
    publishedVersion: "Yayındaki sürüm",
    version: "Sürüm",
    save: "Taslağı kaydet",
    savedToast: "Taslak kaydedildi.",
    unsaved: "Kaydedilmemiş değişiklikler",
    preview: "Önizleme",
    hidePreview: "Önizlemeyi gizle",
    page: "Sayfa",
    addPage: "Sayfa ekle",
    removePage: "Sayfayı kaldır",
    addField: "Soru ekle",
    question: "Soru",
    questionEn: "Soru (İngilizce)",
    questionAr: "Soru (Arapça)",
    help: "Yardım metni",
    required: "Zorunlu",
    options: "Seçenekler",
    addOption: "Seçenek ekle",
    optionEn: "Seçenek (İngilizce)",
    optionAr: "Seçenek (Arapça)",
    moveUp: "Yukarı taşı",
    moveDown: "Aşağı taşı",
    remove: "Kaldır",
    duplicate: "Çoğalt",
    logicNote: "Bu formda koşullu kurallar var. Kaydettiğinizde korunurlar.",
    usedByLogic: "Bu soruyu bir kural kullanıyor. Önce kuralı kaldırın.",
    readOnlyVersion: "Bu sürüm yayında ve değiştirilemez. Düzenlemek için yeni bir sürüm başlatın.",
    problems: "Kaydetmeden önce bunları düzeltin:",
    problemLabel: "Bir sorunun İngilizce metni yok.",
    problemArabic: "Her soru ve seçeneğin Arapça metni de olmalı.",
    recordLinkNote: "Bu soru eski kayıtlara bağlı ve şubeleriniz için seçenek göstermiyor.",
    recordLinkBanner: "Buradaki bir soru eski kayıt bağlantıları kullanıyor. Yayınlamadan önce açıp şube listemize geçirin.",
    useBranchList: "Şube listemizi kullan",
    needsAttention: "ilgi bekliyor",
    problemOptions: "Seçenekli bir soru en az bir seçenek içermeli.",
    problemEmpty: "En az bir soru ekleyin.",
    types: {
      heading: "Başlık",
      instructions: "Açıklama",
      short_text: "Kısa yanıt",
      long_text: "Paragraf",
      email: "E-posta",
      phone: "Telefon",
      number: "Sayı",
      date: "Tarih",
      time: "Saat",
      single_choice: "Tek seçim",
      multiple_choice: "Çoklu seçim",
      yes_no: "Evet veya hayır",
      rating: "Puanlama",
      consent: "Onay",
      entity_reference: "Kayıt bağlantısı",
    },
    typeGroups: { text: "Metin", choice: "Seçenekler", value: "Sayılar ve tarihler", layout: "Düzen" },
    publish: "Yayınla",
    publishTitle: "Bu sürümü yayınla",
    publishDescription: "Kimin yanıtlayabileceğini seçin. Yayın bağlantısı siz kaldırana kadar çalışır.",
    publishSubmit: "Yayınla",
    publishedToast: "Form yayınlandı.",
    slug: "Bağlantı adı",
    slugHint: "Küçük harf, rakam ve tire.",
    audience: "Kim yanıtlayabilir",
    audiencePublic: "Bağlantıya sahip herkes",
    audiencePublicHint: "Aileler ve ziyaretçiler, giriş gerekmez.",
    audienceAuthenticated: "Giriş yapan tüm personel",
    audienceAuthenticatedHint: "Nil Merkezi'ne giriş yapan herkes.",
    audienceAssigned: "Yalnızca atadıklarım",
    audienceAssignedHint: "Ardından rol, şube, bölüm veya kişi seçin.",
    opensAt: "Açılış",
    closesAt: "Kapanış",
    allowMultiple: "Kişi başına birden fazla yanıta izin ver",
    allowDrafts: "Kaydedip sonra tamamlamaya izin ver",
    publicationStatus: { scheduled: "Planlandı", open: "Açık", closed: "Kapalı", retired: "Kaldırıldı" },
    publications: "Bağlantılar",
    noPublications: "Bu form henüz paylaşılmadı.",
    copyLink: "Bağlantıyı kopyala",
    copied: "Bağlantı kopyalandı.",
    openLink: "Aç",
    retire: "Bağlantıyı kaldır",
    retireTitle: "Bu bağlantı kaldırılsın mı?",
    retireBody: "Artık bu bağlantıdan yanıt verilemez. Yanıtlar kalır.",
    retiredToast: "Bağlantı kaldırıldı.",
    assignments: "Atananlar",
    noAssignments: "Henüz kimse atanmadı.",
    assign: "Ata",
    assignTitle: "Bu formu ata",
    assignDescription: "Bu formu kimlerin doldurması gerektiğini seçin. Formu Doldurulacaklar altında bulurlar.",
    assignedToast: "Form atandı.",
    target: "Atanacak",
    targetRole: "Rol",
    targetBranch: "Şube",
    targetDepartment: "Bölüm",
    targetPeople: "Kişiler",
    peopleModeStaff: "Personel",
    peopleModeClass: "Sınıf öğretmenleri",
    peopleClass: "Sınıf",
    staffSearch: "Ada veya e-postaya göre personel ara…",
    noStaffFound: "Personel bulunamadı.",
    classNoTeachers: "Bu sınıfın henüz öğretmeni yok.",
    peopleSelected: "{n} kişi seçildi",
    assignToOne: "1 kişiye ata",
    assignToMany: "{n} kişiye ata",
    publishBlockedRecordLinks: "Yayımlamadan önce Tasarım'da vurgulanan soruyu düzeltin.",
    assignedPeopleToast: "{n} kişi atandı.",
    assignFailures: "Atanamadı:",
    personFallback: "Personel",
    revoke: "Kaldır",
    revokedToast: "Atama kaldırıldı.",
    expires: "Bitiş",
    respondent: "Gönderen",
    anonymous: "Herkese açık bağlantı",
    submitted: "Gönderildi",
    answers: "Yanıtlar",
    noAnswer: "Yanıt yok",
    review: "Karar",
    accept: "Kabul et",
    reject: "Reddet",
    startReview: "İncelemeye al",
    comment: "Not",
    reviewedToast: "Karar kaydedildi.",
    history: "Geçmiş",
    createLead: "Aday oluştur",
    createLeadHint: "Bu başvuruyu yanıtları doldurulmuş olarak Kabul'de bir adaya dönüştürün.",
    leadCreated: "Aday oluşturuldu",
    openLead: "Adayı aç",
    export: "CSV olarak dışa aktar",
    exportedToast: "Dışa aktarma hazır.",
    allForms: "Tüm formlar",
    allStatuses: "Tüm durumlar",
    import: "Jotform'dan içe aktar",
    sentToast: "Teşekkürler. Yanıtınız gönderildi.",
    backToForms: "Formlara dön",
    importer: {
      title: "Jotform'dan içe aktar",
      description: "Geçmiş Jotform yanıtlarını kendi formlarınıza taşıyın, önce kontrol edin ve her satırın kaydını tutun.",
      notConnected: "Bu sunucuda Jotform bağlı değil, bu yüzden formları listelenemiyor. Önceki içe aktarmalar aşağıda kalır.",
      step1: "1. Formları seçin",
      step2: "2. Soruları eşleştirin",
      step3: "3. Kontrol edin, sonra içe aktarın",
      source: "Jotform formu",
      target: "Aktarılacak form",
      noTargets: "Önce bir form yayınlayın; yanıtlar yayındaki bir forma aktarılır.",
      inspect: "Soruları eşleştir",
      field: "Formumuzdaki soru",
      fromJotform: "Jotform sorusu",
      skip: "İçe aktarma",
      offset: "Başlangıç satırı",
      limit: "Satır",
      dryRun: "Satırları kontrol et",
      total: "Satır",
      valid: "Hazır",
      duplicates: "Zaten aktarıldı",
      errors: "Sorunlu",
      sample: "İlk satırlar",
      commit: "Hazır satırları içe aktar",
      importedToast: "İçe aktarma tamamlandı.",
      history: "Geçmiş içe aktarmalar",
      noHistory: "Henüz içe aktarma yok.",
      imported: "Aktarıldı",
      exceptions: "İstisnalar",
      matched: "Eşleşti",
      markMatched: "Eşleşti olarak işaretle",
      markException: "İstisna olarak işaretle",
      reconciledToast: "Satır güncellendi.",
      rowsNeedingReview: "İnceleme bekleyen satırlar",
      submissions: "yanıt",
    },
    roles: {
      student: "Öğrenciler",
      teacher: "Öğretmenler",
      registrar: "Kayıt sorumluları ve öğrenci destek",
      headofdepartment: "Bölüm başkanları",
      branchadmin: "Şube yöneticileri ve müdür yardımcıları",
      superadmin: "Süper yöneticiler",
    },
  },
  admissions: {
    money: {
      toBePaid: "Toplam",
      paid: "Ödenen",
      remaining: "Kalan",
      settled: "Tamamı ödendi",
      paidTooHigh: "Ödenen tutar toplamdan fazla olamaz.",
      invalidAmount: "Sıfır veya daha büyük bir sayı girin.",
    },
    mode: {
      label: "Eğitim şekli",
      online: "Çevrim içi",
      onsite: "Yüz yüze",
      both: "Çevrim içi veya yüz yüze",
      unknown: "Seçilmedi",
      onlineBranch: "Çevrim içi şube",
      onsiteBranch: "Yüz yüze şube",
    },
    leads: {
      title: "Adaylar",
      description: "Bir kursla ilgilenen kişiler, ilk temastan kayda kadar.",
      add: "Aday ekle",
      createTitle: "Aday ekle",
      editTitle: "Adayı düzenle",
      createDescription: "Kimin sorduğunu, ne istediğini ve nasıl ulaşılacağını kaydedin.",
      editDescription: "İletişim bilgilerini, ilgi alanını veya sorumluyu güncelleyin.",
      createSubmit: "Aday oluştur",
      createdToast: "Aday oluşturuldu.",
      updatedToast: "Aday güncellendi.",
      empty: "Eşleşen aday yok.",
      emptyHint: "Bir aday ekleyin veya filtreleri temizleyin.",
      noAccess: "Adaylar kabul personeline aittir.",
      person: "Kişi",
      stage: "Aşama",
      interest: "İlgi",
      owner: "Sorumlu",
      group: "Grup",
      added: "Eklendi",
      branch: "Şube",
      anyMode: "Tüm eğitim şekilleri",
      anyOwner: "Tüm sorumlular",
      unassigned: "Sorumlu yok",
      anyArea: "Tüm çalışma alanları",
      anyType: "Tüm aday türleri",
      allBranches: "Tüm şubeler",
      firstName: "Ad",
      lastName: "Soyad",
      email: "E-posta",
      phone: "Telefon",
      wantsOnline: "Çevrim içi dersler",
      wantsOnsite: "Şubede dersler",
      preferredCourses: "Tercih edilen kurslar",
      anyCourse: "Tercih yok",
      coursesNoun: "kurs",
      areaOfStudy: "Çalışma alanı",
      noArea: "Alan yok",
      source: "Kaynak",
      sourceHint: "Örneğin: web sitesi, şubeye gelen veya tavsiye.",
      notes: "Notlar",
      leadType: "Aday türü",
      typeNew: "Yeni",
      typeOld: "Geri dönen aday",
      typeOldStudent: "Eski öğrenci",
      typeCurrentStudent: "Mevcut öğrenci",
      required: "Zorunlu.",
      invalidEmail: "Geçerli bir e-posta adresi girin.",
      chooseBranch: "Bir şube seçin.",
      journey: "Süreç",
      nextStep: "Sonraki adım",
      stepContact: "İlk temas",
      stepPlacement: "Seviye sınavı",
      stepTrial: "Deneme dersi",
      stepFee: "Kayıt ücreti",
      stepStudent: "Öğrenci",
      stepDone: "Tamamlandı",
      stepNow: "Şimdi",
      stepSkipped: "Atlandı",
      stepLater: "Henüz değil",
      nextBookPlacement: "Doğru seviyeyi bulmak için seviye sınavı planlayın.",
      nextRecordPlacement: "Sınavdan sonra seviye sonucunu girin.",
      nextBookTrial: "Deneme dersi planlayın veya kayıt ücretini girin.",
      nextRecordTrial: "Deneme dersinin nasıl geçtiğini girin.",
      nextFee: "Kayıt ücretini girin.",
      nextConvert: "Ücret girildi. Öğrenci kaydını oluşturun.",
      nextStudent: "Bu aday artık öğrenci.",
      nextLost: "Bu aday kaybedildi olarak kapatıldı.",
      bookPlacement: "Seviye sınavı planla",
      bookTrial: "Deneme dersi planla",
      recordFee: "Kayıt ücretini gir",
      editFee: "Ücreti değiştir",
      convert: "Öğrenci oluştur",
      openStudent: "Öğrenciyi aç",
      markLost: "Kaybedildi olarak işaretle",
      reopen: "Adayı yeniden aç",
      lostTitle: "Bu aday kaybedildi olarak işaretlensin mi?",
      lostBody: "Nedenini seçin. Adayı daha sonra yeniden açabilirsiniz.",
      lostReason: "Kayıp nedeni",
      noLostReasons:
        "Bu hesap için kayıp nedeni yok. Bir yönetici Kayıp nedenleri altında ekleyebilir.",
      openLostReasons: "Kayıp nedenlerini aç.",
      lostToast: "Aday kaybedildi olarak işaretlendi.",
      reopenToast: "Aday yeniden açıldı.",
      lostBecause: "Kayıp nedeni",
      details: "Ayrıntılar",
      placements: "Seviye sınavları",
      trials: "Deneme dersleri",
      fee: "Kayıt ücreti",
      noPlacements: "Henüz seviye sınavı yok.",
      noTrials: "Henüz deneme dersi yok.",
      noFee: "Henüz kayıt ücreti yok.",
      feeTitle: "Kayıt ücreti",
      feeDescription: "Toplamı ve kişinin şimdiye kadar ödediğini girin.",
      feeToast: "Kayıt ücreti kaydedildi.",
      groupMembers: "Birlikte gruplananlar",
      primaryContact: "Ana iletişim",
      convertTitle: "Öğrenci oluştur",
      convertDescription: "EMS'nin istediği kimlik bilgilerini ekleyin. İletişim bilgileri adaydan gelir.",
      convertToast: "Öğrenci oluşturuldu.",
    },
    booking: {
      placementTitle: "Seviye sınavı planla",
      trialTitle: "Deneme dersi planla",
      editTitle: "Randevuyu değiştir",
      when: "Tarih ve saat",
      hour: "Başlangıç saati",
      onTheHour: "Randevular tam saatte başlar.",
      timeZone: "Saat dilimi",
      room: "Derslik",
      chooseRoom: "Bir derslik seçin. Yüz yüze randevular derslik gerektirir.",
      meetingRequired: "Toplantı bağlantısını ekleyin.",
      noRoom: "Henüz derslik yok",
      meetingLink: "Toplantı bağlantısı",
      meetingHint: "https bağlantısı kullanın. Yalnızca çevrim içi şubeler bağlantı kullanır.",
      meetingInvalid: "https:// ile başlayan bir bağlantı kullanın",
      topic: "Ders konusu",
      byCourse: "Bir kurs",
      byArea: "Bir çalışma alanı",
      course: "Kurs",
      chooseCourse: "Bir kurs seçin.",
      chooseArea: "Bir çalışma alanı seçin.",
      placementCourseMissing: "Bu çalışma alanının Moodle'da seviye sınavı kursu yok. Süper Yöneticiden bağlamasını isteyin.",
      book: "Planla",
      saveChanges: "Değişiklikleri kaydet",
      bookedToast: "Randevu kaydedildi.",
      updatedToast: "Randevu güncellendi.",
      moodlePassword: "Sınav için Moodle şifresi",
      resultTitle: "Sonucu gir",
      resultDescription: "Sonucu kaydedin. Randevu tamamlandı olarak kapanır.",
      score: "Puan veya seviye",
      scoreHint: "Örneğin: B1 veya 72.",
      mentor: "Rehber öğretmen",
      noMentors: "Bu şubede öğretmen bulunamadı.",
      recommended: "Önerilen kurs",
      noRecommendation: "Öneri yok",
      notes: "Notlar",
      resultToast: "Sonuç kaydedildi.",
      syncMoodle: "Sonucu Moodle'dan al",
      syncToast: "Sonuç Moodle'dan güncellendi.",
      fromMoodle: "Moodle'dan",
      recordedBy: "Giren",
      noShow: "Gelmedi olarak işaretle",
      noShowTitle: "Gelmedi olarak işaretlensin mi?",
      noShowBody: "Kişi katılmadı. Yeni bir saat planlayabilirsiniz.",
      noShowToast: "Gelmedi olarak işaretlendi.",
      cancel: "Randevuyu iptal et",
      cancelTitle: "Bu randevu iptal edilsin mi?",
      cancelBody: "Nedenini seçin. Zaman aralığı boşa çıkar.",
      cancelToast: "Randevu iptal edildi.",
      change: "Değiştir",
      joinLink: "Toplantı bağlantısını aç",
      result: "Sonuç",
    },
    agenda: {
      placementsTitle: "Seviye sınavları",
      placementsDescription: "Kapsamınızdaki tüm seviye sınavları, güne göre. Bir aday veya öğrenciden planlayın.",
      trialsTitle: "Deneme dersleri",
      trialsDescription: "Kapsamınızdaki tüm deneme dersleri, güne göre. Bir aday veya öğrenciden planlayın.",
      upcoming: "Yaklaşan",
      needsResult: "Sonuç bekliyor",
      completed: "Tamamlandı",
      missed: "Gelmedi",
      cancelled: "İptal edildi",
      today: "Bugün",
      tomorrow: "Yarın",
      emptyUpcoming: "Planlı bir şey yok.",
      emptyNeedsResult: "Geçmiş tüm randevuların sonucu girildi.",
      emptyOther: "Henüz burada bir şey yok.",
      emptyHint: "Bir adayın süreç sayfasından planlayın.",
      subjectLead: "Aday",
      subjectStudent: "Öğrenci",
      allBranches: "Tüm şubeler",
      branch: "Şube",
    },
    students: {
      title: "Öğrenciler",
      description: "Nil Merkezi'ne kayıtlı herkes; kursları, bakiyeleri ve Moodle erişimi.",
      add: "Öğrenci ekle",
      createTitle: "Öğrenci ekle",
      editTitle: "Öğrenciyi düzenle",
      createDescription: "Aday sürecinden gelmeyen bir öğrenci oluşturun.",
      editDescription: "İletişim bilgilerini, kimliği veya sorumluyu güncelleyin.",
      createSubmit: "Öğrenci oluştur",
      createdToast: "Öğrenci oluşturuldu.",
      updatedToast: "Öğrenci güncellendi.",
      empty: "Eşleşen öğrenci yok.",
      emptyHint: "Bir öğrenci ekleyin veya filtreleri temizleyin.",
      noAccess: "Öğrenciler kabul personeline aittir.",
      person: "Kişi",
      branch: "Ana şube",
      owner: "Sorumlu",
      moodle: "Moodle",
      moodleLinked: "Bağlı",
      moodleMissing: "Bağlı değil",
      registration: "Kayıt ücreti",
      noFee: "Ücret yok",
      added: "Eklendi",
      note: "Not",
      allBranches: "Tüm şubeler",
      contact: "İletişim",
      identity: "Kimlik",
      guardians: "Veliler",
      noGuardians: "Kayıtlı veli yok.",
      tabOverview: "Genel bakış",
      tabCourses: "Kurslar",
      tabLearning: "Öğrenme",
      tabBookings: "Sınav ve deneme dersleri",
      tabReport: "Rapor",
      warnings: "EMS notları",
      moodleCreate: "Moodle hesabı oluştur",
      moodleLink: "Moodle hesabı bağla",
      moodleReset: "Moodle şifresini sıfırla",
      moodlePassword: "Moodle şifresi",
      moodleToast: "Moodle hesabı güncellendi.",
      moodleResetTitle: "Moodle şifresi sıfırlansın mı?",
      moodleResetBody: "EMS rastgele yeni bir şifre belirler. Öğrenciyle bir kez paylaşın.",
      disable: "Öğrenciyi devre dışı bırak",
      disableTitle: "Bu öğrenci devre dışı bırakılsın mı?",
      disableBody: "Yeni kayıt alamaz. Geçmişi kalır.",
      disabledToast: "Öğrenci devre dışı bırakıldı.",
      enable: "Öğrenciyi etkinleştir",
      enableTitle: "Bu öğrenci etkinleştirilsin mi?",
      enableBody: "Yeniden kayıt alabilir.",
      enabledToast: "Öğrenci etkinleştirildi.",
      learningEmpty: "Henüz Moodle notu yok.",
      learningClass: "Sınıf",
      learningGrade: "Kurs notu",
      learningCompletion: "Tamamlama",
      learningDone: "Tamamlandı",
      learningOngoing: "Devam ediyor",
      print: "Raporu yazdır",
      reportTitle: "Akademik rapor",
      reportGenerated: "Oluşturulma",
      reportLearningError: "Moodle notları şu anda kullanılamıyor.",
      fromLead: "Adaydan",
    },
    enrolments: {
      title: "Kayıtlar",
      description: "Ödemeden sınıfa kadar kurs satışları. Ödenmiş satışları boş koltuğu olan bir sınıfa ekleyin.",
      empty: "Eşleşen kayıt yok.",
      emptyHint: "Bir öğrenci sayfasından kurs satın.",
      noAccess: "Kayıtlar kabul personeline aittir.",
      waiting: "Bekleyen",
      sell: "Kurs sat",
      saleTitle: "Kurs sat",
      saleDescription: "Bir kurs satışı açın. Ödeme daha sonra gelebilir.",
      saleToast: "Kurs satışı açıldı.",
      student: "Öğrenci",
      findStudent: "Öğrenci ara",
      typeToSearch: "En az iki harf yazın.",
      noStudents: "Eşleşen öğrenci yok.",
      course: "Kurs",
      kind: "Sınıf türü",
      group: "Grup",
      individual: "Bire bir",
      branch: "Şube",
      class: "Sınıf",
      balance: "Bakiye",
      opened: "Açıldı",
      noClass: "Henüz sınıf yok",
      nextLevel: "Sonraki seviye",
      recordPayment: "Ödeme gir",
      paymentTitle: "Ödeme gir",
      paymentDescription: "Toplamı veya öğrencinin şimdiye kadar ödediğini güncelleyin.",
      paymentToast: "Ödeme kaydedildi.",
      attach: "Sınıfa ekle",
      attachTitle: "Bir sınıfa ekle",
      attachDescription: "Bu şubede bu kursun etkin sınıfları. Dolu sınıflar öğrenci almaz.",
      seatsLeft: "boş koltuk",
      full: "Dolu",
      noClasses: "Bu şubede bu kurs için henüz etkin sınıf yok.",
      attachToast: "Öğrenci sınıfa eklendi.",
      moodleRequired: "Öğrencinin sınıfa katılmadan önce bir Moodle hesabı olmalı.",
      complete: "Tamamlandı olarak işaretle",
      completeTitle: "Bu kayıt tamamlandı olarak işaretlensin mi?",
      completeBody: "Öğrenci kursu bitirdiğinde bunu kullanın.",
      completeToast: "Kayıt tamamlandı.",
      leave: "Ayrıldı olarak işaretle",
      leaveTitle: "Bu sonraki seviye satışı ayrıldı olarak işaretlensin mi?",
      leaveBody: "Öğrencinin bu seviyeyi neden almayacağını seçin.",
      leaveToast: "Kayıt ayrıldı olarak işaretlendi.",
      cancel: "Satışı iptal et",
      cancelTitle: "Bu kurs satışı iptal edilsin mi?",
      cancelBody: "Nedenini seçin. Bu işlem geri alınamaz.",
      cancelToast: "Kurs satışı iptal edildi.",
      schedule: "Program",
      teachers: "Öğretmenler",
    },
    identity: {
      nationality: "Uyruk",
      nationalityHint: "Üç harfli kod, örneğin EGY.",
      address: "Adres",
      gender: "Cinsiyet",
      male: "Erkek",
      female: "Kadın",
      dateOfBirth: "Doğum tarihi",
      nationalId: "Kimlik numarası",
      nationalIdHint: "14 hane. Mısır vatandaşları için zorunludur.",
      passport: "Pasaport numarası",
      guardian: "Veli",
      secondGuardian: "İkinci veli",
      guardianHint: "18 yaşından küçük öğrencilerin en az bir velisi olmalı.",
      guardianName: "Ad",
      guardianPhone: "Telefon",
      guardianEmail: "E-posta",
      relationship: "Yakınlık",
      relationshipHint: "Örneğin: Anne, Baba veya Amca.",
      addGuardian: "İkinci veli ekle",
      removeGuardian: "Kaldır",
      invalidNationality: "Üç harfli bir kod kullanın.",
      invalidNationalId: "14 hane kullanın.",
      nationalIdRequired: "Mısır vatandaşları için zorunludur.",
      guardianRequired: "18 yaşından küçük öğrencilerin velisi olmalı.",
      guardianIncomplete: "Tüm veli alanlarını doldurun.",
    },
  },
  dateOfBirth: {
    day: "Gün",
    month: "Ay",
    year: "Yıl",
    monthPlaceholder: "Ay",
    clear: "Tarihi temizle",
    hint: "Örnek: 4 Mart 2012.",
    incompleteDate: "Günü, ayı ve dört haneli yılı girin.",
    invalidDate: "Bu tarih yok. Günü ve ayı kontrol edin.",
    futureDate: "Doğum tarihi gelecekte olamaz.",
    tooEarly: "1900 veya sonrası bir yıl girin.",
    age: "{n} yaşında",
  },
  datePicker: {
    placeholder: "Bir tarih seçin",
    today: "Bugün",
    clear: "Temizle",
    previousMonth: "Önceki ay",
    nextMonth: "Sonraki ay",
    previousYear: "Önceki yıl",
    nextYear: "Sonraki yıl",
    chooseMonth: "Ay ve yıl seçin",
    unavailable: "Seçilemez",
    calendar: "Takvim",
  },
  language: {
    label: "Dil",
  },
  reports: {
    title: "Raporlar",
    description: "Raporu okuyun, sonra dışa aktarın. Rakamlar EMS'den canlı gelir.",
    report: "Rapor",
    tabs: {
      admissions: "Kabul",
      bookings: "Rezervasyonlar",
      enrolments: "Kayıtlar",
      classes: "Sınıflar",
    },
    period: "Dönem",
    asOfToday: "Bugün itibarıyla",
    branch: "Şube",
    allBranches: "Tüm şubeler",
    exportCsv: "CSV aktar",
    truncated: "EMS'den ilk {n} / {total} satır gösteriliyor.",
    showAll: "Tümünü göster ({n})",
    showLess: "Daha az göster",
    emptyTitle: "Raporlanacak bir şey yok",
    emptyAdmissions: "Bu dönemde yeni aday oluşmadı.",
    emptyBookings: "Bu dönemde planlanmış test veya deneme dersi yok.",
    emptyEnrolments: "Kayıt bulunamadı.",
    emptyClasses: "Şu anda aktif sınıf yok.",
    emptyPlacements: "Bu dönemde seviye tespit sınavı yok.",
    emptyTrialLessons: "Bu dönemde deneme dersi yok.",
    emptyTrialResults: "Bu dönemde kaydedilmiş deneme dersi sonucu yok.",
    emptyScores: "Bu dönemde puanlı seviye tespit sınavı yok.",
    emptyLostReasons: "Bu dönemde kaybedilen aday yok.",
    emptyWeekdays: "Planlanmış günü olan sınıf yok.",
    changePeriod: "Dönemi değiştir",
    liveFootnote: "Her rakam, personel API'si üzerinden EMS verilerinden canlı hesaplanır.",
    footnoteAdmissions:
      "Durumlar, seçilen dönemde oluşturulan adayların bugünkü durumlarıdır.",
    footnoteBookings: "Rezervasyonlar planlandığı tarihe göre sayılır.",
    footnoteEnrolments:
      "Kayıtlar kayıt veya iptal tarihine göre sayılır. Tutarlar, para birimi olmadan EMS'de kaydedildiği gibi gruplanır.",
    footnoteClasses: "Aktif sınıfların anlık görünümü.",
    newLeads: "Yeni adaylar",
    registered: "Kayıtlı",
    lost: "Kaybedilen",
    open: "Açık",
    conversion: "Dönüşüm",
    rate: "Oran",
    intake: "Aday akışı",
    intakePerWeek: "Haftalık yeni adaylar",
    intakePerMonth: "Aylık yeni adaylar",
    funnel: "Başvurudan kayda",
    funnelDecided: "Karar verilen",
    bySource: "Kaynağa göre",
    byLostReason: "Kayıp nedenine göre",
    byOwner: "Sorumluya göre",
    byArea: "Çalışma alanına göre",
    byBranch: "Şubeye göre",
    studyMode: "Öğrenim şekli",
    leadType: "Aday türü",
    noSource: "Kaynak yok",
    noReason: "Neden kaydedilmedi",
    noOwner: "Sorumlu yok",
    notSet: "Belirtilmemiş",
    modes: {
      online: "Yalnızca çevrimiçi",
      onsite: "Yalnızca yüz yüze",
      both: "İkisi de",
      unset: "Seçilmedi",
    },
    leadTypes: {
      new: "Yeni",
      old: "Eski",
      old_student: "Eski öğrenci",
      current_student: "Mevcut öğrenci",
    },
    count: "Adet",
    share: "Pay",
    leads: "Adaylar",
    placementTests: "Seviye tespit sınavları",
    trialLessons: "Deneme dersleri",
    scheduled: "Planlandı",
    completed: "Tamamlandı",
    noShow: "Gelmedi",
    cancelled: "İptal edildi",
    showRate: "Katılım oranı",
    scoreSummary: "Seviye tespit puanları",
    scoreAverage: "Ortalama",
    scoreMin: "En düşük",
    scoreMax: "En yüksek",
    scoreBands: "Puan dağılımı",
    trialResults: "Deneme dersi sonuçları",
    trialsByCourse: "Kursa göre deneme dersleri",
    trialToRegistered: "Öğrenciye dönüşen tamamlanmış dersler",
    trials: "Dersler",
    pipeline: "Hatt",
    rightNow: "Şu an",
    inThisPeriod: "Bu dönemde",
    enrolledInPeriod: "Dönemde kaydolan",
    cancelledInPeriod: "Dönemde iptal edilen",
    allTime: "Tüm zamanlar",
    money: "Para",
    billed: "Faturalanan",
    collected: "Tahsil edilen",
    outstanding: "Kalan",
    outstandingPending: "Ödenecek (ödeme bekleniyor)",
    collectionRate: "Tahsilat oranı",
    moneyNote: "Tutarlar, para birimi olmadan EMS'de kaydedildiği gibidir.",
    byCourse: "Kursa göre",
    byKind: "Türe göre",
    kinds: { individual: "Bireysel", group: "Grup" },
    activeClasses: "Aktif sınıflar",
    seatsTaken: "Dolu koltuklar",
    capacity: "Kapasite",
    fill: "Doluluk",
    freeSeats: "Boş koltuklar",
    fillByCourse: "Kursa göre doluluk",
    fillByDepartment: "Bölüme göre doluluk",
    teacherLoad: "Öğretmen yükü",
    noTeacher: "Öğretmen atanmadı",
    endingSoon: "Yakında bitenler",
    endingSoonEmpty: "Önümüzdeki 30 gün içinde biten sınıf yok.",
    daysLeft: "Kalan gün",
    weekdayLoad: "Güne göre sınıflar",
    classes: "Sınıflar",
    students: "Öğrenciler",
    seats: "Koltuklar",
    active: "Aktif",
    pending: "Bekleyen",
    leftCancelled: "Ayrılan / iptal",
    enrolled: "Kayıtlı",
    placements: "Sınavlar",
    score: "Puan",
    course: "Kurs",
    department: "Bölüm",
    name: "Ad",
    endDate: "Bitiş tarihi",
    csv: {
      name: "Ad",
      email: "E-posta",
      phone: "Telefon",
      branch: "Şube",
      source: "Kaynak",
      status: "Durum",
      lostReason: "Kayıp nedeni",
      owner: "Sorumlu",
      area: "Çalışma alanı",
      studyMode: "Öğrenim şekli",
      created: "Oluşturulma",
      type: "Tür",
      person: "Kişi",
      scheduled: "Planlanan",
      result: "Sonuç",
      courseOrArea: "Kurs / alan",
      recommended: "Önerilen kurs",
      student: "Öğrenci",
      course: "Kurs",
      className: "Sınıf",
      enrolled: "Kayıt",
      cancelled: "İptal",
      toBePaid: "Ödenecek",
      paid: "Ödenen",
      remaining: "Kalan",
      department: "Bölüm",
      teachers: "Öğretmenler",
      schedule: "Program",
      capacity: "Kapasite",
      taken: "Dolu",
      fill: "Doluluk %",
      start: "Başlangıç",
      end: "Bitiş",
    },
  },
};
