import type { StaffMessages } from "./copy";

/** Staff app copy in Russian. Keys mirror copy.ts; TypeScript enforces it. */
export const ru: StaffMessages = {
  brand: {
    name: "Nile Center",
    product: "Управление обучением"
  },
  nav: {
    overview: "Главная",
    dashboard: "Панель",
    reports: "Отчёты",
    forms: "Формы",
    notifications: "Уведомления",
    admissions: "Приём",
    students: "Студенты",
    leads: "Заявки",
    enrolments: "Записи на курсы",
    placementTests: "Тесты на уровень",
    trialLessons: "Пробные уроки",
    delivery: "Обучение",
    courses: "Курсы",
    classes: "Группы",
    sessions: "Моя неделя",
    rooms: "Аудитории",
    organisation: "Люди и места",
    staffUsers: "Сотрудники",
    branches: "Филиалы",
    departments: "Кафедры",
    setup: "Настройки",
    lostReasons: "Причины отказа",
    actionReasons: "Причины действий",
    areasOfStudy: "Направления обучения",
    customFields: "Дополнительные поля",
    system: "Система",
    moodleSite: "Moodle",
    systemHealth: "Состояние системы",
    auditLog: "Журнал аудита",
    profile: "Профиль"
  },
  roles: {
    super_admin: "Суперадминистратор",
    branch_admin: "Администратор филиала",
    vice_manager: "Заместитель управляющего",
    hod: "Заведующий кафедрой",
    registrar: "Регистратор",
    ssa: "Консультант по успеваемости",
    teacher: "Преподаватель"
  },
  shell: {
    backTo: "Назад: {page}",
    collapseSidebar: "Свернуть боковую панель",
    expandSidebar: "Развернуть боковую панель",
    staffNav: "Навигация сотрудника",
    openMenu: "Открыть меню",
    closeMenu: "Закрыть меню",
    displaySize: "Размер интерфейса",
    displayStandard: "Обычный",
    displayLarge: "Крупный",
    displayXLarge: "Очень крупный",
    workspace: "Рабочее место",
    chooseWorkspace: "Выберите филиал",
    workspaceHint: "Ваша роль работает в одном филиале за раз. Выберите, где вы хотите работать.",
    noWorkspaces: "Вам пока не назначен ни один активный филиал.",
    notifications: "Уведомления",
    markAllRead: "Отметить все как прочитанные",
    viewAll: "Все уведомления",
    userMenu: "Меню пользователя",
    signOut: "Выйти",
    signOutEverywhere: "Выйти на всех устройствах",
    roleView: "Просмотр роли",
    roleViewTitle: "Просмотр роли",
    roleViewBody: "Посмотрите приложение глазами роли с меньшими правами. Ограничьте данные выбранными филиалами, кафедрами или группами.",
    viewingAs: "Просмотр как",
    ownRole: "ваша роль",
    roleViewChanged: "Просмотр роли обновлён.",
    scopesApplied: "Область применена.",
    roleViewEnded: "Вы вернулись в свою роль.",
    returnToRole: "Вернуться в мою роль",
    applyScopes: "Применить",
    viewAsRole: "Посмотреть как роль",
    editRoleView: "Изменить",
    scopeBranches: "Филиалы",
    scopeBranch: "Филиал",
    scopeDepartments: "Кафедры",
    scopeClasses: "Группы",
    allBranches: "Все филиалы",
    allDepartments: "Все кафедры",
    allClasses: "Все группы",
    branchesNoun: "филиалов",
    departmentsNoun: "кафедр",
    classesNoun: "групп",
    searchBranches: "Поиск филиалов",
    searchDepartments: "Поиск кафедр",
    searchClasses: "Поиск групп",
    chooseWorkspaceOption: "Выберите филиал",
    noAccess: "Нет доступа",
    noAccessHint: "Ваша активная роль не может открыть эту страницу. Вернитесь на панель.",
    backToDashboard: "Вернуться на панель",
    checkingSession: "Проверка сеанса",
    signedInAs: "Вы вошли как",
    search: "Поиск или переход",
    breadcrumb: "Навигационная цепочка",
    commandPages: "Страницы",
    commandPeople: "Сотрудники",
    commandActions: "Действия",
    commandEmpty: "Ничего не найдено."
  },
  state: {
    loading: "Загрузка",
    notSet: "Не указано",
    retry: "Повторить",
    empty: "Здесь пока ничего нет.",
    error403: "У вас нет доступа к этой странице.",
    error404: "Эта запись больше не существует.",
    error409: "Это изменение конфликтует с более новым обновлением. Обновите страницу и повторите.",
    error422: "Проверьте выделенные поля и повторите попытку.",
    error429: "Слишком много запросов. Подождите немного и повторите.",
    error503: "Эта служба сейчас неактивна. Повторите позже.",
    errorNetwork: "Не удалось подключиться к сети. Проверьте соединение.",
    errorGeneric: "Запрос не выполнен. Повторите попытку."
  },
  status: {
    active: "Активен",
    disabled: "Отключён",
    invited: "Приглашён",
    canceled: "Отменено",
    cancelled: "Отменено",
    enrolled: "Зачислен",
    completed: "Завершено",
    registered: "Зарегистрирован",
    scheduled: "Запланировано",
    pending: "Ожидает",
    pending_payment: "Ожидает оплаты",
    pending_class: "Ожидает группы",
    pending_group: "Ожидает набора группы",
    in_process: "В работе",
    follow_up: "Нужен повторный контакт",
    future_registration: "Будущая регистрация",
    trial_lesson: "Пробный урок",
    placement_test: "Тест на уровень",
    left: "Выбыл",
    lost: "Отказ",
    no_show: "Не пришёл",
    healthy: "В норме",
    degraded: "С перебоями",
    unhealthy: "Неисправно",
    ok: "OK",
    warning: "Предупреждение",
    error: "Ошибка",
    not_configured: "Не настроено"
  },
  notifications: {
    title: "Уведомления",
    description: "Только ваши входящие.",
    all: "Все",
    unread: "Непрочитанные",
    empty: "У вас нет уведомлений.",
    markRead: "Отметить прочитанным",
    markAllRead: "Отметить все как прочитанные",
    delete: "Удалить",
    deleteAll: "Удалить все",
    deleteAllTitle: "Удалить все уведомления?",
    deleteAllBody: "Ваши копии будут удалены навсегда. У других сотрудников они останутся.",
    read: "Прочитано",
    unreadBadge: "Не прочитано",
    markedRead: "Уведомление отмечено как прочитанное.",
    allMarkedRead: "Все уведомления отмечены как прочитанные.",
    deleted: "Уведомление удалено.",
    allDeleted: "Все уведомления удалены.",
    actionFailed: "Действие с уведомлением не выполнено. Повторите попытку."
  },
  profile: {
    title: "Профиль",
    description: "Управляйте своими данными, паролем и активными сеансами.",
    details: "Ваши данные",
    role: "Назначенная роль",
    email: "Эл. почта",
    name: "Имя",
    nameNotSet: "Не указано",
    phone: "Телефон",
    unknownDevice: "Неизвестное устройство",
    password: "Пароль",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите новый пароль",
    changePassword: "Сменить пароль",
    passwordChanged: "Пароль изменён.",
    passwordFailed: "Не удалось сменить пароль. Проверьте введённые данные.",
    passwordsDiffer: "Новые пароли не совпадают.",
    sessions: "Активные сеансы",
    sessionsHint: "Завершите сеанс, который вы не узнаёте.",
    thisSession: "Этот сеанс",
    lastSeen: "Последняя активность",
    issued: "Вход выполнен",
    signOutSession: "Завершить сеанс",
    sessionRevoked: "Сеанс завершён.",
    signOutEverywhere: "Выйти на всех устройствах",
    signOutEverywhereTitle: "Выйти на всех устройствах?",
    signOutEverywhereBody: "Вы выйдете на всех устройствах. Потребуется войти снова."
  },
  actions: {
    save: "Сохранить",
    cancel: "Отмена",
    saving: "Сохранение",
    discardTitle: "Отменить изменения?",
    discardBody: "Ваши изменения не сохранены.",
    discard: "Отменить",
    keepEditing: "Продолжить редактирование",
    search: "Поиск",
    filter: "Фильтр",
    columns: "Столбцы",
    selected: "выбрано",
    clearSelection: "Снять выделение",
    previous: "Назад",
    next: "Далее",
    pageOf: "из",
    create: "Создать",
    edit: "Изменить",
    rowActions: "Действия со строкой",
    enable: "Включить",
    disable: "Отключить",
    close: "Закрыть",
    import: "Импорт",
    refresh: "Обновить",
    noReasons: "Сначала добавьте причину для этого действия.",
    openActionReasons: "Открыть причины действий.",
    status: "Статус",
    activeOnly: "Только активные",
    selectAll: "Выбрать все строки",
    selectRow: "Выбрать строку",
    pagination: "Страницы"
  },
  catalog: {
    shared: {
      name: "Название",
      nameRequired: "Введите название.",
      code: "Код",
      codeHint: "Строчные буквы, цифры и подчёркивания.",
      codePattern: "Используйте только строчные буквы, цифры и подчёркивания.",
      sortOrder: "Порядок",
      created: "Создано",
      status: "Статус",
      active: "Активен",
      disabled: "Отключён",
      allStatuses: "Все статусы",
      access: "Ваш доступ",
      accessManage: "Управление",
      accessView: "Просмотр",
      customFields: "Дополнительные поля",
      customFieldsEmpty: "К этой записи не применяются дополнительные поля.",
      enableTitle: "Включить эту запись?",
      disableTitle: "Отключить эту запись?",
      enableBody: "Запись снова станет доступна.",
      createdToast: "Создано.",
      updatedToast: "Изменения сохранены.",
      enabledToast: "Включено.",
      disabledToast: "Отключено.",
      saveChanges: "Сохранить изменения"
    },
    branches: {
      title: "Филиалы",
      description: "Места, где работает Nile Center.",
      empty: "Филиалов пока нет.",
      emptyHint: "Создайте первый филиал.",
      add: "Добавить филиал",
      createTitle: "Добавить филиал",
      editTitle: "Изменить филиал",
      createDescription: "Создайте активный филиал.",
      editDescription: "Измените название, код или настройки.",
      createSubmit: "Создать филиал",
      timezone: "Часовой пояс",
      online: "Онлайн-филиал",
      onlineYes: "Онлайн",
      onlineNo: "Очно",
      searchBranches: "Поиск филиалов",
      disableBody: "Филиал перестанет принимать новую работу. Сеансы в нём потеряют рабочее место.",
      statisticsTitle: "Активность",
      detailMissing: "Этот филиал больше не существует.",
      statActiveStudents: "Активные студенты",
      statOpenLeads: "Открытые заявки",
      statActiveClasses: "Активные группы",
      statEnrolmentFill: "Занятые места",
      statEnrolmentCapacity: "Вместимость",
      statPendingEnrolments: "Записи в ожидании",
      statPlacements: "Запланированные тесты",
      statTrials: "Запланированные пробные уроки",
      statStaff: "Сотрудники",
      bulkDisable: "Отключить выбранные",
      bulkEnable: "Включить выбранные",
      bulkDone: "Выбор обновлён."
    },
    departments: {
      title: "Кафедры",
      description: "Учебные кафедры, к которым относятся группы и курсы.",
      empty: "Кафедр пока нет.",
      emptyHint: "Создайте первую кафедру.",
      add: "Добавить кафедру",
      createTitle: "Добавить кафедру",
      editTitle: "Изменить кафедру",
      createSubmit: "Создать кафедру",
      disableBody: "Кафедра скрыта для новой работы."
    },
    lostReasons: {
      title: "Причины отказа",
      description: "Почему заявка помечена как отказ.",
      empty: "Причин отказа пока нет.",
      emptyHint: "Создайте первую причину отказа.",
      add: "Добавить причину отказа",
      createTitle: "Добавить причину отказа",
      editTitle: "Изменить причину отказа",
      createSubmit: "Создать причину",
      disableBody: "Причина скрыта для новой работы."
    },
    actionReasons: {
      title: "Причины действий",
      description: "Именованные причины для защищённых действий.",
      empty: "Причин действий пока нет.",
      emptyHint: "Создайте или импортируйте первую причину.",
      add: "Добавить причину действия",
      createTitle: "Добавить причину действия",
      editTitle: "Изменить причину действия",
      createSubmit: "Создать причину",
      disableBody: "Причина скрыта для новой работы.",
      kind: "Тип",
      allKinds: "Все типы",
      import: "Импорт CSV",
      importTitle: "Импорт причин действий",
      importDescription: "Вставьте строки CSV или выберите файл. Сначала просмотрите, затем импортируйте.",
      chooseFile: "Выберите файл CSV",
      downloadTemplate: "Скачать шаблон",
      orPaste: "Или вставьте строки CSV",
      importPreview: "Предпросмотр",
      importRowCount: "строк",
      rowError: "Ошибка",
      rowErrorColumns: "Ожидается 6 столбцов.",
      rowErrorKind: "Неизвестный тип.",
      rowErrorName: "Название обязательно.",
      importEmpty: "Вставьте строки CSV для предпросмотра.",
      importSubmit: "Импорт",
      importDone: "Импорт завершён.",
      importCreated: "создано",
      importUpdated: "обновлено",
      csvPlaceholder: "id,action,name,status,sort_order,created_at",
      kindLost: "Отказ по заявке",
      kindLeft_enrolment: "Выход из записи",
      kindCancel_enrolment: "Отмена записи",
      kindCancel_placement_test: "Отмена теста на уровень",
      kindCancel_trial_lesson: "Отмена пробного урока",
      kindDisable_student: "Отключение студента",
      kindDisable_course: "Отключение курса",
      kindDisable_class: "Отключение группы",
      kindDisable_branch: "Отключение филиала",
      kindDisable_department: "Отключение кафедры",
      kindDisable_room: "Отключение аудитории",
      kindDisable_staff: "Отключение сотрудника",
      kindDisable_area_of_study: "Отключение направления",
      kindDisable_custom_field: "Отключение доп. поля"
    },
    areasOfStudy: {
      title: "Направления обучения",
      description: "Предметы, по которым можно распределить студента.",
      empty: "Направлений пока нет.",
      emptyHint: "Создайте первое направление.",
      add: "Добавить направление",
      createTitle: "Добавить направление",
      editTitle: "Изменить направление",
      createSubmit: "Создать направление",
      disableBody: "Направление скрыто для новых распределений.",
      placementCourses: "Курсы тестов на уровень",
      placementCoursesHint: "Выберите курсы Moodle, в которых находятся тесты на уровень.",
      addCourse: "Добавить курс Moodle",
      searchCourses: "Поиск курсов Moodle",
      coursesEmpty: "Нет подходящих курсов.",
      coursesLoading: "Загрузка курсов",
      coursesError: "Курсы Moodle недоступны."
    },
    customFields: {
      title: "Дополнительные поля",
      description: "Дополнительные поля записей во всём приложении.",
      empty: "Дополнительных полей пока нет.",
      emptyHint: "Создайте первое дополнительное поле.",
      add: "Добавить поле",
      createTitle: "Добавить поле",
      editTitle: "Изменить поле",
      createSubmit: "Создать поле",
      disableBody: "Поле скрыто в формах.",
      entity: "Объект",
      allEntities: "Все объекты",
      fieldKey: "Ключ поля",
      fieldKeyHint: "Идентификатор строчными буквами для модели данных. Позже изменить нельзя.",
      fieldType: "Тип",
      required: "Обязательное поле",
      requiredYes: "Обязательное",
      optional: "Необязательное",
      helpText: "Подсказка",
      options: "Варианты",
      optionsHint: "Один вариант в строке.",
      entityUser_profile: "Профиль сотрудника",
      entityStudent: "Студент",
      entityLead: "Заявка",
      entityBranch: "Филиал",
      entityDepartment: "Кафедра",
      entityClass: "Группа",
      entityCourse: "Курс",
      entityRoom: "Аудитория"
    }
  },
  staffUsers: {
    title: "Сотрудники",
    description: "Все, кто работает в Nile Center: роль, место работы и способ входа.",
    add: "Добавить сотрудника",
    createTitle: "Добавить сотрудника",
    editTitle: "Изменить сотрудника",
    createDescription: "Создайте учётную запись сотрудника с ролью и областью.",
    editDescription: "Измените роль, профиль или область.",
    createSubmit: "Создать сотрудника",
    empty: "Сотрудников пока нет.",
    emptyHint: "Пригласите первого сотрудника.",
    noAccess: "Учётными записями сотрудников управляют суперадминистратор и администратор филиала.",
    person: "Человек",
    email: "Эл. почта",
    role: "Роль",
    worksAt: "Место работы",
    branches: "Филиалы",
    departments: "Кафедры",
    courses: "Курсы",
    moodle: "Moodle",
    status: "Статус",
    lastSignIn: "Последний вход",
    added: "Добавлен",
    you: "Вы",
    all: "Все",
    results: "Результаты",
    clearFilters: "Сбросить фильтры",
    teachersNoMoodle: "Преподаватели без Moodle",
    allRoles: "Все роли",
    allBranches: "Все филиалы",
    allDepartments: "Все кафедры",
    globalScope: "Все филиалы",
    branchScope: "Область филиалов",
    branchScopeHint: "Заместителю управляющего нужен ровно один филиал. Регистратору, консультанту и преподавателю — хотя бы один.",
    workspaceScopeHint: "Новые учётные записи должны включать ваш рабочий филиал.",
    invited: "Приглашён",
    moodleLinked: "Привязан",
    moodleMissing: "Не привязан",
    provisioning: "Способ создания",
    provisioningInvitation: "Ссылка-приглашение",
    provisioningManual: "Пароль вручную",
    provisioningHint: "Приглашение создаёт одноразовую ссылку. Вручную создаётся временный пароль.",
    firstName: "Имя",
    lastName: "Фамилия",
    phone: "Телефон",
    address: "Адрес",
    nationality: "Гражданство",
    nationalityHint: "Трёхбуквенный код страны.",
    dateOfBirth: "Дата рождения",
    notes: "Заметки",
    canTakePlacementTest: "Может проводить тесты на уровень",
    yourPassword: "Ваш пароль",
    yourPasswordHint: "Для этого изменения суперадминистратора нужен ваш пароль.",
    yourPasswordRequired: "Введите свой пароль, чтобы продолжить.",
    firstNameRequired: "Имя обязательно.",
    lastNameRequired: "Фамилия обязательна.",
    emailRequired: "Введите корректный адрес эл. почты.",
    branchScopeRequired: "Выберите хотя бы один филиал.",
    viceManagerScope: "Заместителю управляющего нужен ровно один филиал.",
    invite: "Пригласить",
    resendInvite: "Отправить приглашение повторно",
    inviteTitle: "Отправить новое приглашение?",
    inviteBody: "Прежняя ссылка-приглашение перестанет работать.",
    cancelInvite: "Отменить приглашение",
    cancelInviteTitle: "Отменить это приглашение?",
    cancelInviteBody: "Ссылка-приглашение сразу перестанет работать.",
    setPassword: "Задать пароль",
    setPasswordTitle: "Задать новый пароль?",
    setPasswordBody: "Временный пароль создаётся один раз. Передайте его по защищённому каналу.",
    moodleAccount: "Учётная запись Moodle",
    moodleCreate: "Создать учётную запись Moodle",
    moodleLink: "Привязать учётную запись Moodle",
    moodleReset: "Сбросить пароль Moodle",
    moodleResetTitle: "Сбросить пароль Moodle?",
    moodleResetBody: "Новый пароль Moodle создаётся один раз. Передайте его по защищённому каналу.",
    moodleSearch: "Поиск учётных записей Moodle",
    moodleSearchHint: "Поиск по имени, логину или эл. почте.",
    moodleSearchMin: "Введите не менее 2 символов.",
    moodleSearchEmpty: "Нет подходящих учётных записей Moodle.",
    moodleCreateHint: "Создаёт учётную запись Moodle, привязанную к этому сотруднику.",
    moodleLinkHint: "Привяжите существующую учётную запись Moodle к этому сотруднику.",
    disableTitle: "Отключить этого сотрудника?",
    disableBody: "Учётная запись больше не сможет входить.",
    enableTitle: "Включить этого сотрудника?",
    enableBody: "Учётная запись снова сможет входить.",
    bulkDisable: "Отключить выбранных",
    bulkEnable: "Включить выбранных",
    bulkDone: "Выбор обновлён.",
    createdToast: "Сотрудник создан.",
    updatedToast: "Изменения сохранены.",
    invitedToast: "Приглашение создано.",
    cancelledToast: "Приглашение отменено.",
    passwordToast: "Пароль сброшен.",
    moodleToast: "Учётная запись Moodle обновлена.",
    disabledToast: "Сотрудник отключён.",
    enabledToast: "Сотрудник включён.",
    secretTitle: "Одноразовые данные для входа",
    secretBody: "Скопируйте их сейчас. Повторно они не показываются.",
    secretShare: "Передавайте данные для входа только по защищённому каналу.",
    secretDone: "Готово",
    copyValue: "Копировать",
    copied: "Скопировано.",
    invitationLink: "Ссылка-приглашение",
    temporaryPassword: "Временный пароль",
    moodlePassword: "Пароль Moodle",
    moreActions: "Другие действия",
    copyEmail: "Копировать эл. почту",
    emailCopied: "Эл. почта скопирована.",
    tabOverview: "Обзор",
    tabCourses: "Курсы",
    tabAvailability: "Доступность",
    tabActivity: "Активность",
    sectionContact: "Контакты",
    sectionAccess: "Доступ",
    sectionMore: "Подробнее",
    neverSignedIn: "Ни разу не входил",
    statsAdmissions: "Приём",
    statsTeaching: "Обучение",
    statLeadsCreated: "Создано заявок",
    statLeadsAssigned: "Назначено заявок",
    statLeadsOpen: "Открытые заявки",
    statLeadsRegistered: "Зарегистрировано",
    statLeadsLost: "Отказы",
    statStudentsAssigned: "Назначено студентов",
    statClassesTeaching: "Ведёт групп",
    statSessionsScheduled: "Запланировано занятий",
    statStudentsTaught: "Обучено студентов",
    statsEmpty: "Активность пока не записана.",
    coursesTitle: "Курсы, которые может вести",
    coursesHint: "Пустой список означает, что преподавателя нельзя назначить в группу.",
    coursesSaved: "Курсы обновлены.",
    coursesSearchPlaceholder: "Поиск курсов",
    placementCapability: "Тесты на уровень",
    placementYes: "Может проводить тесты на уровень",
    placementNo: "Не может проводить тесты на уровень",
    availabilityTitle: "Доступность",
    availabilityHint: "Отметьте часы работы преподавателя. Забронированные занятия изменить нельзя.",
    penAvailable: "Доступен",
    penUnavailable: "Недоступен",
    penClear: "Очистить",
    showAllHours: "Показать все часы",
    showWorkHours: "Показать рабочие часы",
    timezoneLabel: "Часовой пояс",
    unsavedBar: "Есть несохранённые изменения.",
    saveChanges: "Сохранить изменения",
    discardChanges: "Отменить",
    discardTitle: "Отменить изменения доступности?",
    discardBody: "Отмеченные изменения не сохранены.",
    cellsSaved: "Доступность сохранена.",
    cellsSkippedBooked: "Забронированные занятия пропущены.",
    weekToday: "Сегодня",
    weekPrevious: "Предыдущая неделя",
    weekNext: "Следующая неделя",
    bookedSession: "Забронировано"
  },
  moodleSite: {
    title: "Сайт Moodle",
    description: "Подключите сайт Moodle, на котором работают курсы, группы и посещаемость.",
    noAccess: "Только суперадминистратор может настраивать сайт Moodle.",
    connection: "Подключение",
    connectionHint: "Данные веб-сервиса для экземпляра Moodle. Токен можно только записать.",
    siteUrl: "URL сайта",
    token: "Токен веб-сервиса",
    tokenHint: "Хранится в защищённом виде. Вводите заново только для смены токена.",
    tokenKeep: "Оставьте пустым, чтобы сохранить текущий токен.",
    autoCreate: "Автоматически создавать учётные записи студентов в Moodle",
    autoCreateHint: "Если включено, при создании студента также создаётся учётная запись в Moodle.",
    ptCourse: "ID курса Moodle для теста на уровень",
    ptCourseHint: "Курс Moodle, в котором проходит тест на уровень. Оставьте пустым, чтобы очистить.",
    save: "Сохранить изменения",
    connect: "Подключить Moodle",
    test: "Проверить подключение",
    disconnect: "Отключить",
    disconnectTitle: "Отключить Moodle?",
    disconnectBody: "Сохранённый токен будет удалён. Курсы и группы перестанут синхронизироваться до повторного подключения.",
    saved: "Настройки Moodle сохранены.",
    disconnected: "Moodle отключён.",
    testOk: "Проверка подключения прошла успешно.",
    testVersionWarn: "Доступен, но версия Moodle вне ожидаемого диапазона 4.5.x.",
    testFailed: "Moodle недоступен.",
    statusTitle: "Статус",
    statConfigured: "Настроено",
    statToken: "Токен сохранён",
    statReachable: "Доступен",
    statVersion: "Версия ожидаемая",
    statSitename: "Название сайта",
    statRelease: "Выпуск",
    statLastChecked: "Последняя проверка",
    statWarnings: "Предупреждения",
    statLastError: "Последняя ошибка",
    unknown: "Неизвестно",
    yes: "Да",
    no: "Нет"
  },
  system: {
    title: "Состояние системы",
    description: "Текущее состояние основных служб и интеграции с Moodle.",
    noAccess: "Только суперадминистратор может просматривать состояние системы.",
    refresh: "Обновить",
    checked: "Проверено",
    componentApi: "API",
    componentDatabase: "База данных",
    componentSchema: "Проверка схемы",
    componentMigration: "Миграции",
    componentMoodle: "Moodle",
    operational: "Работает.",
    version: "Версия",
    configured: "Настроено",
    token: "Токен",
    reachable: "Доступен",
    site: "Сайт",
    release: "Выпуск",
    expected: "Ожидается 4.5.x",
    warnings: "Предупреждения"
  },
  audit: {
    title: "Журнал аудита",
    description: "Кто, что и когда сделал. Сначала новые.",
    noAccess: "Только суперадминистратор и администратор филиала могут читать события аудита.",
    stream: "Поток",
    allStreams: "Все потоки",
    search: "Поиск событий",
    empty: "Событий аудита нет.",
    emptyHint: "Действия записываются здесь по мере выполнения.",
    payload: "Данные",
    actor: "Исполнитель",
    system: "Система",
    today: "Сегодня",
    yesterday: "Вчера",
    latest: "Последние события: {n}",
    failedSignIn: "Кто-то",
    groups: {
      all: "Все",
      auth: "Входы",
      admissions: "Приём",
      teaching: "Обучение",
      setup: "Настройки"
    },
    nouns: {
      auth: "учётную запись",
      branch: "филиал",
      department: "кафедру",
      course: "курс",
      custom_field: "доп. поле",
      moodle_site: "подключение к Moodle",
      student: "студента",
      lead: "заявку",
      placement_test: "тест на уровень",
      class: "группу",
      enrolment: "запись",
      room: "аудиторию",
      session: "занятие"
    },
    verbs: {
      created: "создал(а) {noun}",
      updated: "изменил(а) {noun}",
      disabled: "отключил(а) {noun}",
      enabled: "включил(а) {noun}",
      cancelled: "отменил(а) {noun}",
      completed: "завершил(а) {noun}",
      refreshed: "обновил(а) {noun}",
      tested: "проверил(а) {noun}",
      other: "{action}: {noun}"
    },
    actions: {
      login_success: "вошёл(а) в систему",
      login_failed: "не смог(ла) войти",
      logout: "вышел(а) из системы",
      workspace_switched: "сменил(а) филиал",
      role_switched: "изменил(а) просмотр роли",
      invitation_sent: "отправил(а) приглашение:",
      invitation_accepted: "принял(а) приглашение",
      user_created: "создал(а) учётную запись сотрудника",
      moodle_group_created: "создал(а) группу Moodle для",
      moodle_group_deleted: "удалил(а) группу Moodle для",
      moodle_group_synced: "синхронизировал(а) с Moodle:",
      moodle_linked: "привязал(а) учётную запись Moodle для",
      converted: "перевёл(а) в студенты:",
      enrolled: "записал(а) студента"
    },
    streams: {
      auth: "Вход",
      branch: "Филиал",
      department: "Кафедра",
      course: "Курс",
      custom_field: "Доп. поле",
      moodle_site: "Сайт Moodle",
      student: "Студент",
      lead: "Заявка",
      placement_test: "Тест на уровень",
      class: "Группа",
      enrolment: "Запись",
      room: "Аудитория",
      session: "Занятие"
    }
  },
  dashboard: {
    morning: "Доброе утро",
    afternoon: "Добрый день",
    evening: "Добрый вечер",
    nameSeparator: ", ",
    intro: "Вот что требует вашего внимания сегодня.",
    openLeads: "Открытые заявки",
    openLeadsNote: "Ещё не зарегистрированы и не отказались",
    bookings: "Предстоящие записи",
    tests: "тестов",
    trials: "пробных",
    waitingSales: "Ожидающие продажи",
    waitingSalesNote: "Нет оплаты или группы",
    classFill: "Заполненность групп",
    seatsOf: "из",
    seats: "мест занято",
    activeStudents: "Активные студенты",
    activeStudentsNote: "С активной записью",
    today: "Сегодня",
    todayEmpty: "На сегодня ничего не запланировано.",
    overdue: "прошедших записей ждут результата",
    openAgenda: "Открыть расписание",
    attention: "Требует внимания",
    allClear: "Всё в порядке",
    resultsToRecord: "Результаты для записи",
    unpaid: "Неоплаченные продажи курсов",
    waitingClass: "Оплачено, ждут группу",
    unowned: "Открытые заявки без ответственного",
    formResponses: "Новые ответы на формы",
    period: "Период",
    periods: {
      "7d": "7 дней",
      "30d": "30 дней",
      "90d": "90 дней",
      "12m": "12 месяцев",
      all: "За всё время"
    },
    vsPrevious: "к прошлому периоду",
    noChange: "Без изменений",
    pts: " п.п.",
    newLeads: "Новые заявки",
    conversion: "Конверсия",
    conversionNote: "Доля зарегистрированных среди решённых заявок",
    intake: "Поступление заявок",
    intakeNote: "Новые заявки по неделям",
    weekOf: "Неделя",
    outcomes: "Итоги заявок",
    open: "Открыта",
    registered: "Зарегистрирован",
    lost: "Отказ",
    noData: "За этот период заявок нет.",
    funnel: "От обращения до студента",
    funnelLeads: "Заявки",
    funnelBooked: "Проведены тесты и пробные",
    bookingsTitle: "Тесты и пробные уроки",
    placementTests: "Тесты на уровень",
    trialLessons: "Пробные уроки",
    completed: "Проведено",
    scheduledLabel: "Запланировано",
    noShow: "Не пришли",
    cancelled: "Отменено",
    showRate: "пришли",
    pipeline: "Воронка заявок",
    pipelineEmpty: "Открытых заявок нет.",
    branches: "Филиалы",
    branch: "Филиал",
    students: "Студенты",
    classes: "Группы",
    fill: "Заполненность",
    waiting: "Ожидают",
    placement: "Тест на уровень",
    trial: "Пробный урок",
    myClasses: "Мои группы",
    myStudents: "Студенты моих групп",
    nextSession: "Следующее занятие",
    noNextSession: "Занятий не запланировано",
    sessions: "Предстоящие занятия",
    sessionsEmpty: "Занятий пока не запланировано.",
    classesEmpty: "Вам пока не назначены группы.",
    openMoodle: "Открыть в Moodle",
    departmentClasses: "Группы кафедры",
    seatsFree: "Свободные места",
    noTeacher: "Группы без преподавателя",
    departmentEmpty: "В ваших кафедрах пока нет групп.",
    teachers: "Преподаватели",
    schedule: "Расписание",
    unassignedTeacher: "Нет преподавателя",
    enrolled: "записано",
    loadError: "Некоторые показатели не загрузились."
  },
  teaching: {
    hourUnit: "ч",
    seats: "мест",
    seatsLeft: "осталось",
    full: "Мест нет",
    allBranches: "Все филиалы",
    branch: "Филиал",
    required: "Обязательно.",
    wholeNumber: "Введите целое число больше нуля.",
    openMoodle: "Открыть в Moodle",
    courses: {
      title: "Курсы",
      description: "Курсы из Moodle с часами, кафедрой и текущим спросом.",
      empty: "Нет подходящих курсов.",
      emptyHint: "Привяжите курс Moodle, чтобы начать продажи.",
      course: "Курс",
      department: "Кафедра",
      allDepartments: "Все кафедры",
      area: "Направление",
      noArea: "Без направления",
      hours: "Часы",
      totalHours: "Всего учебных часов",
      moodle: "Moodle",
      moodleVisible: "Виден",
      moodleHidden: "Скрыт",
      moodleChecked: "Проверено в Moodle",
      refreshError: "Не удалось обновить из Moodle",
      refreshAll: "Обновить из Moodle",
      refreshAllToast: "Курсы обновлены из Moodle.",
      refreshOne: "Обновить из Moodle",
      refreshOneToast: "Курс обновлён из Moodle.",
      link: "Привязать курс Moodle",
      linkTitle: "Привязать курс Moodle",
      linkDescription: "Курсы берутся из Moodle. Выберите ещё не привязанный курс и укажите учебные часы.",
      linkSubmit: "Привязать курс",
      linkToast: "Курс привязан.",
      editTitle: "Изменить курс",
      editDescription: "Кафедра, часы, направление и предшествующий курс.",
      editToast: "Курс обновлён.",
      chooseMoodle: "Выберите курс Moodle.",
      noUnmapped: "Все курсы Moodle уже привязаны.",
      searchMoodle: "Поиск курсов Moodle",
      previous: "Идёт после",
      noPrevious: "Нет предыдущего курса",
      attendanceId: "Элемент посещаемости Moodle",
      attendanceHint: "Нужен для отметки посещаемости. Это ID элемента посещаемости в курсе Moodle.",
      noAttendance: "Не указан, поэтому отмечать посещаемость нельзя.",
      disable: "Отключить курс",
      disableTitle: "Отключить этот курс?",
      disableBody: "Его больше нельзя продавать и открывать новые группы. Существующие группы остаются.",
      disabledToast: "Курс отключён.",
      enable: "Включить курс",
      enableTitle: "Включить этот курс?",
      enableBody: "Его снова можно продавать и открывать новые группы.",
      enabledToast: "Курс включён.",
      demand: "Текущий спрос",
      activeClasses: "Активные группы",
      seatsTaken: "Занято мест",
      waitingSales: "Ожидающие продажи",
      interestedLeads: "Заинтересованные заявки",
      classes: "Группы",
      noClasses: "По этому курсу пока нет групп.",
      writeNote: "Изменять курсы может только суперадминистратор."
    },
    classes: {
      title: "Группы",
      description: "Все группы с преподавателями, обычным временем, местами и группой Moodle.",
      empty: "Нет подходящих групп.",
      emptyHint: "Создайте группу для активного курса.",
      add: "Добавить группу",
      createTitle: "Добавить группу",
      editTitle: "Изменить группу",
      createDescription: "Курс, даты, места, преподаватели и обычное время в неделю.",
      editDescription: "Даты, места, преподаватели, обычное время и ссылка на встречу.",
      createSubmit: "Создать группу",
      createdToast: "Группа создана.",
      updatedToast: "Группа обновлена.",
      name: "Название группы",
      course: "Курс",
      allCourses: "Все курсы",
      kind: "Тип группы",
      group: "Группа",
      individual: "Индивидуально",
      capacity: "Места",
      starts: "Начало",
      ends: "Окончание",
      dates: "Даты",
      teachers: "Преподаватели",
      noTeachers: "В этом филиале пока нет преподавателей.",
      noTeacher: "Нет преподавателя",
      usualDays: "Обычные дни",
      from: "С",
      to: "До",
      usualTime: "Обычное время",
      noSchedule: "Нет обычного времени",
      meetingLink: "Ссылка на встречу",
      meetingHint: "Для онлайн-групп. Используйте ссылку https.",
      meetingInvalid: "Используйте ссылку, начинающуюся с https://",
      endBeforeStart: "Дата окончания должна быть позже даты начала.",
      timeOrder: "Время окончания должно быть позже времени начала.",
      timeBoth: "Укажите оба времени или ни одного.",
      daysNeedTime: "Выберите дни и время вместе.",
      fill: "Места",
      moodleGroup: "Группа Moodle",
      moodleLinked: "Привязана",
      moodleMissing: "Не привязана",
      lastSynced: "Последняя синхронизация",
      neverSynced: "Не синхронизировалась",
      tabOverview: "Обзор",
      tabStudents: "Студенты",
      tabSessions: "Занятия",
      tabAttendance: "Посещаемость",
      tabGrades: "Оценки",
      disable: "Отключить группу",
      disableTitle: "Отключить эту группу?",
      disableBody: "Новые студенты не принимаются. Записанные студенты и история сохраняются.",
      disabledToast: "Группа отключена.",
      enable: "Включить группу",
      enableTitle: "Включить эту группу?",
      enableBody: "Группа снова сможет принимать студентов.",
      enabledToast: "Группа включена.",
      moodleCreate: "Создать группу Moodle",
      moodleLink: "Привязать группу Moodle",
      moodleTitle: "Группа Moodle",
      moodleDescription: "Создайте новую группу в курсе Moodle или привяжите существующую.",
      moodleSearch: "Поиск групп Moodle",
      moodleBound: "Группа Moodle привязана.",
      sync: "Синхронизировать с Moodle",
      syncTitle: "Синхронизация с Moodle",
      syncDone: "Синхронизировано с Moodle.",
      syncPartial: "Синхронизировано с ошибками.",
      stepGroup: "Группа",
      stepTeachers: "Преподаватели",
      stepStudents: "Студенты",
      stepSessions: "Занятия посещаемости",
      stepGrades: "Оценки",
      stepOk: "Готово",
      stepError: "Ошибка",
      students: "Студенты",
      studentsEmpty: "В этой группе пока нет студентов.",
      addStudents: "Добавить оплативших студентов",
      addStudentsHint: "Оплаченные продажи этого курса в этом филиале, ожидающие группу.",
      noWaiting: "Здесь нет оплаченных продаж этого курса в ожидании.",
      attachToast: "Студент добавлен в группу.",
      noMoodleAccount: "Нет учётной записи Moodle",
      readOnly: "Вы можете просматривать эту группу. Изменения вносит команда филиала."
    },
    sessions: {
      upcoming: "Предстоящие",
      past: "Прошедшие",
      cancelled: "Отменённые",
      empty: "Занятий пока нет.",
      emptyHint: "Запланируйте занятия по доступности преподавателя и аудитории.",
      plan: "Запланировать занятия",
      planTitle: "Запланировать занятия",
      planDescription: "Укажите часы на каждый день недели. EMS найдёт самое раннее время, когда свободны и преподаватель, и аудитория.",
      weekday: "День",
      hours: "Часы",
      addDay: "Добавить день",
      removeDay: "Удалить день",
      fromDate: "С",
      toDate: "До",
      findTimes: "Найти время",
      proposed: "Предлагаемое время",
      noMatch: "Нет времени, подходящего для всех дней. Освободите часы преподавателя или аудитории либо измените дни.",
      book: "Забронировать эти занятия",
      bookedToast: "Занятия забронированы.",
      reschedule: "Изменить время",
      rescheduleTitle: "Изменить время занятия",
      rescheduleDescription: "Выберите новое время начала. Оно должно подходить преподавателю и аудитории.",
      movedToast: "Занятие перенесено.",
      cancel: "Отменить занятие",
      cancelTitle: "Отменить это занятие?",
      cancelBody: "Оно исчезнет из расписания студентов и преподавателя.",
      cancelledToast: "Занятие отменено.",
      length: "Длительность",
      room: "Аудитория",
      teacher: "Преподаватель",
      online: "Онлайн",
      today: "Сегодня",
      dayRequired: "Добавьте хотя бы один день.",
      dayTwice: "Каждый день можно указать только один раз.",
      rangeInvalid: "Дата окончания должна быть не раньше даты начала.",
      pastLocked: "Прошедшие занятия изменить нельзя.",
      attendance: "Посещаемость"
    },
    week: {
      title: "Моя неделя",
      description: "Ваши занятия на неделю и посещаемость, которую нужно отметить после каждого.",
      thisWeek: "Эта неделя",
      previous: "Предыдущая неделя",
      next: "Следующая неделя",
      sessions: "занятий",
      hours: "ч",
      needAttendance: "ждут отметки посещаемости",
      empty: "На этой неделе занятий нет.",
      noMoodle: "Нет занятия в Moodle",
      dayOff: "Свободно"
    },
    attendance: {
      empty: "Занятий посещаемости в Moodle пока нет.",
      emptyHint: "Синхронизируйте группу с Moodle, чтобы создать их по расписанию.",
      take: "Отметить посещаемость",
      sheetTitle: "Посещаемость",
      sheetEmpty: "На этом занятии пока нет студентов.",
      markAll: "Отметить всех присутствующими",
      save: "Сохранить посещаемость",
      savedToast: "Посещаемость сохранена.",
      notTaken: "Не отмечено",
      taken: "Отмечено",
      notMarked: "Не отмечен",
      marked: "отмечено",
      of: "из",
      needsActivity: "Сначала укажите элемент посещаемости Moodle для курса."
    },
    grades: {
      empty: "В Moodle пока нет оценок.",
      student: "Студент",
      courseGrade: "Оценка за курс"
    },
    rooms: {
      title: "Аудитории",
      description: "Аудитории филиалов, количество мест и часы для бронирования.",
      add: "Добавить аудиторию",
      createTitle: "Добавить аудиторию",
      editTitle: "Изменить аудиторию",
      createDescription: "Укажите название аудитории и количество мест.",
      name: "Название аудитории",
      capacity: "Места",
      createSubmit: "Создать аудиторию",
      createdToast: "Аудитория создана.",
      updatedToast: "Аудитория обновлена.",
      empty: "Нет подходящих аудиторий.",
      emptyHint: "Добавьте аудиторию, чтобы бронировать группы и тесты.",
      disable: "Отключить аудиторию",
      disableTitle: "Отключить эту аудиторию?",
      disableBody: "Её больше нельзя бронировать. Прошлые брони остаются.",
      disabledToast: "Аудитория отключена.",
      enable: "Включить аудиторию",
      enableTitle: "Включить эту аудиторию?",
      enableBody: "Её снова можно бронировать.",
      enabledToast: "Аудитория включена.",
      availability: "Доступность",
      availabilityHint: "Отметьте часы, когда аудиторию можно бронировать. Забронированные часы заблокированы.",
      availabilityToast: "Доступность сохранена.",
      unlimited: "Не указано"
    }
  },
  forms: {
    title: "Формы",
    description: "Создавайте свои формы, делитесь ими с семьями или сотрудниками и работайте с каждым ответом.",
    intro: "Вступление",
    yes: "Да",
    no: "Нет",
    agreed: "Согласен",
    form: "Форма",
    tabForms: "Мои формы",
    tabResponses: "Ответы",
    tabToFill: "Заполнить",
    newForm: "Новая форма",
    newTitle: "Новая форма",
    newDescription: "Начните с пустой формы или шаблона. До публикации можно изменить всё.",
    createSubmit: "Создать форму",
    createdToast: "Форма создана.",
    titleEn: "Заголовок (английский)",
    titleAr: "Заголовок (арабский)",
    category: "Категория",
    template: "Начать с",
    blank: "Пустая форма",
    branch: "Филиал",
    allBranchesForm: "Все филиалы",
    empty: "Форм пока нет.",
    emptyHint: "Создайте форму вместо Jotform или бумажного бланка.",
    responsesEmpty: "Ответов пока нет.",
    toFillEmpty: "Сейчас нечего заполнять.",
    toFillHint: "Здесь появляются формы, назначенные вам или вашей роли.",
    status: {
      draft: "Черновик",
      active: "Опубликована",
      retired: "Выведена из работы"
    },
    categories: {
      admissions: "Приём",
      student_support: "Поддержка студентов",
      attendance: "Посещаемость",
      consent: "Согласие",
      branch_operations: "Работа филиала"
    },
    responseStatus: {
      submitted: "Новый",
      under_review: "На рассмотрении",
      accepted: "Принят",
      rejected: "Отклонён",
      promoted: "Обработан",
      withdrawn: "Отозван",
      quarantined: "Отложен"
    },
    responses: "Ответы",
    updated: "Обновлено",
    live: "Открытая ссылка",
    notLive: "Не опубликована",
    open: "Открыть",
    fill: "Заполнить",
    filled: "Отправлено",
    due: "Закрывается",
    tabBuild: "Конструктор",
    tabShare: "Доступ",
    tabResponses2: "Ответы",
    editDraft: "Редактировать новую версию",
    editingDraft: "Черновик",
    publishedVersion: "Опубликованная версия",
    version: "Версия",
    save: "Сохранить черновик",
    savedToast: "Черновик сохранён.",
    unsaved: "Несохранённые изменения",
    preview: "Предпросмотр",
    hidePreview: "Скрыть предпросмотр",
    page: "Страница",
    addPage: "Добавить страницу",
    removePage: "Удалить страницу",
    addField: "Добавить вопрос",
    question: "Вопрос",
    questionEn: "Вопрос (английский)",
    questionAr: "Вопрос (арабский)",
    help: "Подсказка",
    required: "Обязательный",
    options: "Варианты",
    addOption: "Добавить вариант",
    optionEn: "Вариант (английский)",
    optionAr: "Вариант (арабский)",
    moveUp: "Вверх",
    moveDown: "Вниз",
    remove: "Удалить",
    duplicate: "Дублировать",
    logicNote: "В этой форме есть условные правила. При сохранении они сохраняются.",
    usedByLogic: "Этот вопрос используется в правиле. Сначала удалите правило.",
    readOnlyVersion: "Эта версия опубликована и не может меняться. Создайте новую версию для редактирования.",
    problems: "Исправьте перед сохранением:",
    problemLabel: "У вопроса нет текста на английском.",
    problemArabic: "Каждому вопросу и варианту нужен и арабский текст.",
    recordLinkNote: "Этот вопрос ссылается на старые записи и не показывает варианты для ваших филиалов.",
    recordLinkBanner: "Здесь есть вопрос со старыми ссылками на записи. Откройте его и переключите на список филиалов перед публикацией.",
    useBranchList: "Использовать наш список филиалов",
    needsAttention: "требует внимания",
    problemOptions: "Вопросу с выбором нужен хотя бы один вариант.",
    problemEmpty: "Добавьте хотя бы один вопрос.",
    types: {
      heading: "Заголовок",
      instructions: "Инструкции",
      short_text: "Короткий ответ",
      long_text: "Абзац",
      email: "Эл. почта",
      phone: "Телефон",
      number: "Число",
      date: "Дата",
      time: "Время",
      single_choice: "Один вариант",
      multiple_choice: "Несколько вариантов",
      yes_no: "Да или нет",
      rating: "Оценка",
      consent: "Согласие",
      entity_reference: "Ссылка на запись"
    },
    typeGroups: {
      text: "Текст",
      choice: "Выбор",
      value: "Числа и даты",
      layout: "Оформление"
    },
    publish: "Опубликовать",
    publishTitle: "Опубликовать эту версию",
    publishDescription: "Выберите, кто может отвечать. Открытая ссылка работает, пока вы её не выведете из работы.",
    publishSubmit: "Опубликовать",
    publishedToast: "Форма опубликована.",
    slug: "Имя ссылки",
    slugHint: "Строчные буквы, цифры и дефисы.",
    audience: "Кто может отвечать",
    audiencePublic: "Любой, у кого есть ссылка",
    audiencePublicHint: "Семьи и посетители, без входа.",
    audienceAuthenticated: "Любой вошедший сотрудник",
    audienceAuthenticatedHint: "Все, кто входит в Nile Center.",
    audienceAssigned: "Только назначенные мной",
    audienceAssignedHint: "Далее выберите роли, филиалы, кафедры или людей.",
    opensAt: "Открывается",
    closesAt: "Закрывается",
    allowMultiple: "Разрешить несколько ответов от одного человека",
    allowDrafts: "Разрешить сохранить и закончить позже",
    publicationStatus: {
      scheduled: "Запланировано",
      open: "Открыта",
      closed: "Закрыта",
      retired: "Выведена из работы"
    },
    publications: "Ссылки",
    noPublications: "Эта форма пока не опубликована.",
    copyLink: "Копировать ссылку",
    copied: "Ссылка скопирована.",
    openLink: "Открыть",
    retire: "Вывести ссылку из работы",
    retireTitle: "Вывести эту ссылку из работы?",
    retireBody: "Отвечать по ней будет нельзя. Ответы сохранятся.",
    retiredToast: "Ссылка выведена из работы.",
    assignments: "Назначено",
    noAssignments: "Пока никто не назначен.",
    assign: "Назначить",
    assignTitle: "Назначить эту форму",
    assignDescription: "Выберите, кто должен заполнить форму. Они найдут её в разделе «Заполнить».",
    assignedToast: "Форма назначена.",
    target: "Назначить",
    targetRole: "Роль",
    targetBranch: "Филиал",
    targetDepartment: "Кафедра",
    targetPeople: "Люди",
    peopleModeStaff: "Сотрудник",
    peopleModeClass: "Преподаватели группы",
    peopleClass: "Группа",
    staffSearch: "Поиск сотрудников по имени или эл. почте…",
    noStaffFound: "Сотрудники не найдены.",
    classNoTeachers: "В этой группе пока нет преподавателей.",
    peopleSelected: "Выбрано: {n}",
    assignToOne: "Назначить 1 человеку",
    assignToMany: "Назначить людям: {n}",
    publishBlockedRecordLinks: "Перед публикацией исправьте выделенный вопрос в конструкторе.",
    assignedPeopleToast: "Назначено: {n}.",
    assignFailures: "Не удалось назначить:",
    personFallback: "Сотрудник",
    revoke: "Удалить",
    revokedToast: "Назначение удалено.",
    expires: "До",
    respondent: "С",
    anonymous: "Открытая ссылка",
    submitted: "Отправлено",
    answers: "Ответы",
    noAnswer: "Нет ответа",
    review: "Решение",
    accept: "Принять",
    reject: "Отклонить",
    startReview: "Отметить «На рассмотрении»",
    comment: "Заметка",
    reviewedToast: "Решение сохранено.",
    history: "История",
    createLead: "Создать заявку",
    createLeadHint: "Превратите это обращение в заявку в разделе «Приём» с заполненными ответами.",
    leadCreated: "Заявка создана",
    openLead: "Открыть заявку",
    export: "Экспорт CSV",
    exportedToast: "Экспорт готов.",
    allForms: "Все формы",
    allStatuses: "Все статусы",
    import: "Импорт из Jotform",
    backToForms: "Назад к формам",
    importer: {
      title: "Импорт из Jotform",
      description: "Перенесите прошлые ответы Jotform в свои формы, сначала проверьте их и сохраните запись о каждой строке.",
      notConnected: "Jotform не подключён на этом сервере, поэтому его формы нельзя показать. Уже выполненные импорты остаются ниже.",
      step1: "1. Выберите формы",
      step2: "2. Сопоставьте вопросы",
      step3: "3. Проверьте и импортируйте",
      source: "Форма Jotform",
      target: "В эту форму",
      noTargets: "Сначала опубликуйте форму: ответы импортируются в опубликованную форму.",
      inspect: "Сопоставьте вопросы",
      field: "Вопрос в нашей форме",
      fromJotform: "Вопрос Jotform",
      skip: "Не импортировать",
      offset: "Начать со строки",
      limit: "Строк",
      dryRun: "Проверить строки",
      total: "Строки",
      valid: "Готово",
      duplicates: "Уже импортировано",
      errors: "С ошибками",
      sample: "Первые строки",
      commit: "Импортировать готовые строки",
      importedToast: "Импорт завершён.",
      history: "Прошлые импорты",
      noHistory: "Импортов пока нет.",
      imported: "Импортировано",
      exceptions: "Исключения",
      matched: "Сопоставлено",
      markMatched: "Отметить сопоставленной",
      markException: "Отметить исключением",
      reconciledToast: "Строка обновлена.",
      rowsNeedingReview: "Строки на проверку",
      submissions: "ответов"
    },
    roles: {
      student: "Студенты",
      teacher: "Преподаватели",
      registrar: "Регистраторы и консультанты",
      headofdepartment: "Заведующие кафедрами",
      branchadmin: "Администраторы филиалов и заместители",
      superadmin: "Суперадминистраторы"
    }
  },
  admissions: {
    money: {
      toBePaid: "Итого",
      paid: "Оплачено",
      remaining: "Остаток",
      settled: "Оплачено полностью",
      paidTooHigh: "Оплата не может превышать итоговую сумму.",
      invalidAmount: "Введите число не меньше нуля."
    },
    mode: {
      label: "Формат обучения",
      online: "Онлайн",
      onsite: "Очно",
      both: "Онлайн или очно",
      unknown: "Не выбран",
      onlineBranch: "Онлайн-филиал",
      onsiteBranch: "Очный филиал"
    },
    leads: {
      title: "Заявки",
      description: "Люди, которые интересовались курсом: от первого контакта до регистрации.",
      add: "Добавить заявку",
      createTitle: "Добавить заявку",
      editTitle: "Изменить заявку",
      createDescription: "Запишите, кто обратился, что ему нужно и как с ним связаться.",
      editDescription: "Измените контакты, интерес или ответственного.",
      createSubmit: "Создать заявку",
      createdToast: "Заявка создана.",
      updatedToast: "Заявка обновлена.",
      empty: "Нет подходящих заявок.",
      emptyHint: "Добавьте заявку или сбросьте фильтры.",
      noAccess: "Заявками занимаются сотрудники приёма.",
      person: "Человек",
      stage: "Этап",
      interest: "Интерес",
      owner: "Ответственный",
      group: "Группа",
      added: "Добавлена",
      branch: "Филиал",
      anyMode: "Любой формат",
      anyOwner: "Любой ответственный",
      unassigned: "Без ответственного",
      anyArea: "Любое направление",
      anyType: "Любой тип заявки",
      allBranches: "Все филиалы",
      firstName: "Имя",
      lastName: "Фамилия",
      email: "Эл. почта",
      phone: "Телефон",
      wantsOnline: "Онлайн-занятия",
      wantsOnsite: "Занятия в филиале",
      preferredCourses: "Желаемые курсы",
      anyCourse: "Без предпочтений",
      coursesNoun: "курсов",
      areaOfStudy: "Направление",
      noArea: "Без направления",
      source: "Источник",
      sourceHint: "Например: сайт, личный визит или рекомендация.",
      notes: "Заметки",
      leadType: "Тип заявки",
      typeNew: "Новая",
      typeOld: "Повторное обращение",
      typeOldStudent: "Бывший студент",
      typeCurrentStudent: "Текущий студент",
      required: "Обязательно.",
      invalidEmail: "Введите корректный адрес эл. почты.",
      chooseBranch: "Выберите филиал.",
      journey: "Путь",
      nextStep: "Следующий шаг",
      stepContact: "Первый контакт",
      stepPlacement: "Тест на уровень",
      stepTrial: "Пробный урок",
      stepFee: "Регистрационный взнос",
      stepStudent: "Студент",
      stepDone: "Готово",
      stepNow: "Сейчас",
      stepSkipped: "Пропущено",
      stepLater: "Ещё нет",
      nextBookPlacement: "Запишите на тест, чтобы определить уровень.",
      nextRecordPlacement: "После теста запишите результат.",
      nextBookTrial: "Запишите на пробный урок или внесите регистрационный взнос.",
      nextRecordTrial: "Запишите, как прошёл пробный урок.",
      nextFee: "Внесите регистрационный взнос.",
      nextConvert: "Взнос записан. Создайте запись студента.",
      nextStudent: "Эта заявка стала студентом.",
      nextLost: "Эта заявка закрыта как отказ.",
      bookPlacement: "Записать на тест",
      bookTrial: "Записать на пробный урок",
      recordFee: "Внести регистрационный взнос",
      editFee: "Изменить взнос",
      convert: "Создать студента",
      openStudent: "Открыть студента",
      markLost: "Отметить отказ",
      reopen: "Открыть заявку снова",
      lostTitle: "Отметить эту заявку как отказ?",
      lostBody: "Выберите причину. Позже заявку можно открыть снова.",
      lostReason: "Причина отказа",
      noLostReasons: "Для этой учётной записи нет причин отказа. Администратор может добавить их в разделе «Причины отказа».",
      openLostReasons: "Открыть причины отказа.",
      lostToast: "Заявка отмечена как отказ.",
      reopenToast: "Заявка открыта снова.",
      lostBecause: "Причина отказа",
      details: "Подробности",
      placements: "Тесты на уровень",
      trials: "Пробные уроки",
      fee: "Регистрационный взнос",
      noPlacements: "Тестов на уровень пока нет.",
      noTrials: "Пробных уроков пока нет.",
      noFee: "Регистрационного взноса пока нет.",
      feeTitle: "Регистрационный взнос",
      feeDescription: "Укажите общую сумму и сколько человек уже оплатил.",
      feeToast: "Регистрационный взнос сохранён.",
      groupMembers: "В группе с",
      primaryContact: "Основной контакт",
      convertTitle: "Создать студента",
      convertDescription: "Добавьте данные личности, которые нужны EMS. Контакты берутся из заявки.",
      convertToast: "Студент создан."
    },
    booking: {
      placementTitle: "Записать на тест",
      trialTitle: "Записать на пробный урок",
      editTitle: "Изменить запись",
      when: "Дата и время",
      hour: "Время начала",
      onTheHour: "Записи начинаются в начале часа.",
      timeZone: "Часовой пояс",
      room: "Аудитория",
      chooseRoom: "Выберите аудиторию. Для очной записи она обязательна.",
      meetingRequired: "Добавьте ссылку на встречу.",
      noRoom: "Аудитории пока нет",
      meetingLink: "Ссылка на встречу",
      meetingHint: "Используйте ссылку https. Ссылки используются только в онлайн-филиалах.",
      meetingInvalid: "Используйте ссылку, начинающуюся с https://",
      topic: "Тема урока",
      byCourse: "Курс",
      byArea: "Направление обучения",
      course: "Курс",
      chooseCourse: "Выберите курс.",
      chooseArea: "Выберите направление обучения.",
      placementCourseMissing: "Для этого направления нет курса теста в Moodle. Попросите суперадминистратора привязать курс.",
      book: "Записать",
      saveChanges: "Сохранить изменения",
      bookedToast: "Запись сохранена.",
      updatedToast: "Запись обновлена.",
      moodlePassword: "Пароль Moodle для теста",
      resultTitle: "Записать результат",
      resultDescription: "Сохраните итог. Запись закроется как проведённая.",
      score: "Балл или уровень",
      scoreHint: "Например: B1 или 72.",
      mentor: "Наставник",
      noMentors: "В этом филиале нет преподавателей.",
      recommended: "Рекомендуемый курс",
      noRecommendation: "Без рекомендации",
      notes: "Заметки",
      resultToast: "Результат сохранён.",
      syncMoodle: "Получить результат из Moodle",
      syncToast: "Результат обновлён из Moodle.",
      fromMoodle: "Из Moodle",
      recordedBy: "Записал(а)",
      noShow: "Отметить неявку",
      noShowTitle: "Отметить неявку?",
      noShowBody: "Человек не пришёл. Можно записать на другое время.",
      noShowToast: "Неявка отмечена.",
      cancel: "Отменить запись",
      cancelTitle: "Отменить эту запись?",
      cancelBody: "Выберите причину. Время освободится.",
      cancelToast: "Запись отменена.",
      change: "Изменить",
      joinLink: "Открыть ссылку на встречу",
      result: "Результат"
    },
    agenda: {
      placementsTitle: "Тесты на уровень",
      placementsDescription: "Все тесты на уровень в вашей области по дням. Записывайте со страницы заявки или студента.",
      trialsTitle: "Пробные уроки",
      trialsDescription: "Все пробные уроки в вашей области по дням. Записывайте со страницы заявки или студента.",
      upcoming: "Предстоящие",
      needsResult: "Нужен результат",
      completed: "Проведены",
      missed: "Неявка",
      cancelled: "Отменены",
      today: "Сегодня",
      tomorrow: "Завтра",
      emptyUpcoming: "Записей нет.",
      emptyNeedsResult: "У всех прошедших записей есть результат.",
      emptyOther: "Здесь пока ничего нет.",
      emptyHint: "Записывайте со страницы пути заявки.",
      subjectLead: "Заявка",
      subjectStudent: "Студент",
      allBranches: "Все филиалы",
      branch: "Филиал"
    },
    students: {
      title: "Студенты",
      description: "Все зарегистрированные в Nile Center: курсы, баланс и доступ к Moodle.",
      add: "Добавить студента",
      createTitle: "Добавить студента",
      editTitle: "Изменить студента",
      createDescription: "Создайте студента, который пришёл не через заявку.",
      editDescription: "Измените контакты, личные данные или ответственного.",
      createSubmit: "Создать студента",
      createdToast: "Студент создан.",
      updatedToast: "Студент обновлён.",
      empty: "Нет подходящих студентов.",
      emptyHint: "Добавьте студента или сбросьте фильтры.",
      noAccess: "Студентами занимаются сотрудники приёма.",
      person: "Человек",
      branch: "Основной филиал",
      owner: "Ответственный",
      moodle: "Moodle",
      moodleLinked: "Привязан",
      moodleMissing: "Не привязан",
      registration: "Регистрационный взнос",
      noFee: "Без взноса",
      added: "Добавлен",
      note: "Заметка",
      allBranches: "Все филиалы",
      contact: "Контакты",
      identity: "Личные данные",
      guardians: "Опекуны",
      noGuardians: "Опекуны не указаны.",
      tabOverview: "Обзор",
      tabCourses: "Курсы",
      tabLearning: "Учёба",
      tabBookings: "Тесты и пробные уроки",
      tabReport: "Отчёт",
      warnings: "Заметки из EMS",
      moodleCreate: "Создать учётную запись Moodle",
      moodleLink: "Привязать учётную запись Moodle",
      moodleReset: "Сбросить пароль Moodle",
      moodlePassword: "Пароль Moodle",
      moodleToast: "Учётная запись Moodle обновлена.",
      moodleResetTitle: "Сбросить пароль Moodle?",
      moodleResetBody: "EMS задаст новый случайный пароль. Передайте его студенту один раз.",
      disable: "Отключить студента",
      disableTitle: "Отключить этого студента?",
      disableBody: "Новые записи будут недоступны. История сохранится.",
      disabledToast: "Студент отключён.",
      enable: "Включить студента",
      enableTitle: "Включить этого студента?",
      enableBody: "Студент снова сможет записываться на курсы.",
      enabledToast: "Студент включён.",
      learningEmpty: "Оценок в Moodle пока нет.",
      learningClass: "Группа",
      learningGrade: "Оценка за курс",
      learningCompletion: "Прохождение",
      learningDone: "Завершён",
      learningOngoing: "В процессе",
      print: "Распечатать отчёт",
      reportTitle: "Академический отчёт",
      reportGenerated: "Создан",
      reportLearningError: "Оценки Moodle сейчас недоступны.",
      fromLead: "Из заявки"
    },
    enrolments: {
      title: "Записи на курсы",
      description: "Продажи курсов от оплаты до группы. Добавляйте оплаченные продажи в группы со свободными местами.",
      empty: "Нет подходящих записей.",
      emptyHint: "Продайте курс со страницы студента.",
      noAccess: "Записями на курсы занимаются сотрудники приёма.",
      waiting: "Ожидают",
      sell: "Продать курс",
      saleTitle: "Продать курс",
      saleDescription: "Откройте продажу курса. Оплата может поступить позже.",
      saleToast: "Продажа курса открыта.",
      student: "Студент",
      findStudent: "Поиск студентов",
      typeToSearch: "Введите не менее двух букв.",
      noStudents: "Нет подходящих студентов.",
      course: "Курс",
      kind: "Тип группы",
      group: "Группа",
      individual: "Индивидуально",
      branch: "Филиал",
      class: "Группа",
      balance: "Остаток",
      opened: "Открыта",
      noClass: "Группы пока нет",
      nextLevel: "Следующий уровень",
      recordPayment: "Внести оплату",
      paymentTitle: "Внести оплату",
      paymentDescription: "Измените итоговую сумму или сколько студент уже оплатил.",
      paymentToast: "Оплата сохранена.",
      attach: "Добавить в группу",
      attachTitle: "Добавить в группу",
      attachDescription: "Активные группы этого курса в этом филиале. В заполненные группы студентов больше не принимают.",
      seatsLeft: "мест осталось",
      full: "Мест нет",
      noClasses: "В этом филиале пока нет активной группы этого курса.",
      attachToast: "Студент добавлен в группу.",
      moodleRequired: "Перед вступлением в группу студенту нужна учётная запись Moodle.",
      complete: "Отметить завершённой",
      completeTitle: "Отметить эту запись завершённой?",
      completeBody: "Используйте, когда студент окончил курс.",
      completeToast: "Запись завершена.",
      leave: "Отметить выбытие",
      leaveTitle: "Отметить выбытие для этой продажи следующего уровня?",
      leaveBody: "Выберите, почему студент не будет проходить этот уровень.",
      leaveToast: "Запись отмечена как выбытие.",
      cancel: "Отменить продажу",
      cancelTitle: "Отменить эту продажу курса?",
      cancelBody: "Выберите причину. Это действие нельзя отменить.",
      cancelToast: "Продажа курса отменена.",
      schedule: "Расписание",
      teachers: "Преподаватели"
    },
    identity: {
      nationality: "Гражданство",
      nationalityHint: "Трёхбуквенный код, например EGY.",
      address: "Адрес",
      gender: "Пол",
      male: "Мужской",
      female: "Женский",
      dateOfBirth: "Дата рождения",
      nationalId: "Национальный ID",
      nationalIdHint: "14 цифр. Обязательно для граждан Египта.",
      passport: "Номер паспорта",
      guardian: "Опекун",
      secondGuardian: "Второй опекун",
      guardianHint: "Студентам младше 18 лет нужен хотя бы один опекун.",
      guardianName: "Имя",
      guardianPhone: "Телефон",
      guardianEmail: "Эл. почта",
      relationship: "Кем приходится",
      relationshipHint: "Например: мать, отец или дядя.",
      addGuardian: "Добавить второго опекуна",
      removeGuardian: "Удалить",
      invalidNationality: "Используйте трёхбуквенный код.",
      invalidNationalId: "Используйте 14 цифр.",
      nationalIdRequired: "Обязательно для граждан Египта.",
      guardianRequired: "Студентам младше 18 лет нужен опекун.",
      guardianIncomplete: "Заполните все поля опекуна."
    }
  },
  dateOfBirth: {
    day: "День",
    month: "Месяц",
    year: "Год",
    monthPlaceholder: "Месяц",
    clear: "Очистить дату",
    hint: "Например: 4 марта 2012.",
    incompleteDate: "Введите день, месяц и год из четырёх цифр.",
    invalidDate: "Такой даты нет. Проверьте день и месяц.",
    futureDate: "Дата рождения не может быть в будущем.",
    tooEarly: "Введите год не раньше 1900.",
    age: "Возраст: {n}"
  },
  datePicker: {
    placeholder: "Выберите дату",
    today: "Сегодня",
    clear: "Очистить",
    previousMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    previousYear: "Предыдущий год",
    nextYear: "Следующий год",
    chooseMonth: "Выберите месяц и год",
    unavailable: "Недоступно",
    calendar: "Календарь"
  },
  language: {
    label: "Язык"
  },
  reports: {
    title: "Отчёты",
    description: "Просмотрите отчёт, затем экспортируйте его. Данные поступают из EMS в реальном времени.",
    report: "Отчёт",
    tabs: {
      admissions: "Приём",
      bookings: "Записи",
      enrolments: "Записи на курсы",
      classes: "Группы"
    },
    period: "Период",
    asOfToday: "На сегодня",
    branch: "Филиал",
    allBranches: "Все филиалы",
    exportCsv: "Экспорт CSV",
    truncated: "Показаны первые {n} из {total} строк из EMS.",
    showAll: "Показать все {n}",
    showLess: "Свернуть",
    emptyTitle: "Нет данных для отчёта",
    emptyAdmissions: "За этот период заявки не создавались.",
    emptyBookings: "За этот период тесты и пробные уроки не планировались.",
    emptyEnrolments: "Записи на курсы не найдены.",
    emptyClasses: "Сейчас нет активных групп.",
    emptyPlacements: "За этот период нет тестов на уровень.",
    emptyTrialLessons: "За этот период нет пробных уроков.",
    emptyTrialResults: "За этот период не записано результатов пробных уроков.",
    emptyScores: "За этот период нет оценённых тестов на уровень.",
    emptyLostReasons: "За этот период нет отказов.",
    emptyWeekdays: "Ни у одной группы нет дней занятий.",
    changePeriod: "Изменить период",
    liveFootnote: "Все показатели вычисляются в реальном времени по данным EMS через API сотрудников.",
    footnoteAdmissions: "Статусы — текущие статусы заявок, созданных в выбранном периоде.",
    footnoteBookings: "Записи учитываются по запланированной дате.",
    footnoteEnrolments: "Записи на курсы учитываются по дате зачисления или отмены. Суммы сгруппированы как в EMS, без валюты.",
    footnoteClasses: "Срез активных групп на текущий момент.",
    newLeads: "Новые заявки",
    registered: "Зарегистрированы",
    lost: "Отказы",
    open: "Открытые",
    conversion: "Конверсия",
    rate: "Доля",
    intake: "Поступление заявок",
    intakePerWeek: "Новые заявки по неделям",
    intakePerMonth: "Новые заявки по месяцам",
    funnel: "От обращения до регистрации",
    funnelDecided: "Решено",
    bySource: "По источнику",
    byLostReason: "По причине отказа",
    byOwner: "По ответственному",
    byArea: "По направлению",
    byBranch: "По филиалу",
    studyMode: "Формат обучения",
    leadType: "Тип заявки",
    noSource: "Без источника",
    noReason: "Причина не указана",
    noOwner: "Без ответственного",
    notSet: "Не указано",
    modes: {
      online: "Только онлайн",
      onsite: "Только очно",
      both: "Оба формата",
      unset: "Не выбран"
    },
    leadTypes: {
      new: "Новая",
      old: "Старая",
      old_student: "Бывший студент",
      current_student: "Текущий студент"
    },
    count: "Количество",
    share: "Доля",
    leads: "Заявки",
    placementTests: "Тесты на уровень",
    trialLessons: "Пробные уроки",
    scheduled: "Запланировано",
    completed: "Проведено",
    noShow: "Неявка",
    cancelled: "Отменено",
    showRate: "Явка",
    scoreSummary: "Баллы тестов на уровень",
    scoreAverage: "Средний",
    scoreMin: "Минимальный",
    scoreMax: "Максимальный",
    scoreBands: "Распределение баллов",
    trialResults: "Результаты пробных уроков",
    trialsByCourse: "Пробные уроки по курсам",
    trialToRegistered: "Проведённые пробные уроки, после которых стали студентами",
    trials: "Пробные",
    pipeline: "Воронка",
    rightNow: "Сейчас",
    inThisPeriod: "За этот период",
    enrolledInPeriod: "Зачислено за период",
    cancelledInPeriod: "Отменено за период",
    allTime: "За всё время",
    money: "Деньги",
    billed: "Выставлено",
    collected: "Получено",
    outstanding: "Задолженность",
    outstandingPending: "Ещё к оплате (ожидает оплаты)",
    collectionRate: "Доля сбора",
    moneyNote: "Суммы указаны как в EMS, без валюты.",
    byCourse: "По курсу",
    byKind: "По типу",
    kinds: {
      individual: "Индивидуально",
      group: "Группа"
    },
    activeClasses: "Активные группы",
    seatsTaken: "Занято мест",
    capacity: "Вместимость",
    fill: "Заполненность",
    freeSeats: "Свободные места",
    fillByCourse: "Заполненность по курсам",
    fillByDepartment: "Заполненность по кафедрам",
    teacherLoad: "Нагрузка преподавателей",
    noTeacher: "Преподаватель не назначен",
    endingSoon: "Скоро заканчиваются",
    endingSoonEmpty: "В ближайшие 30 дней группы не заканчиваются.",
    daysLeft: "Осталось дней",
    weekdayLoad: "Группы по дням недели",
    classes: "Группы",
    students: "Студенты",
    seats: "Места",
    active: "Активные",
    pending: "Ожидают",
    leftCancelled: "Выбыли / отменены",
    enrolled: "Зачислены",
    placements: "Тесты",
    score: "Балл",
    course: "Курс",
    department: "Кафедра",
    name: "Название",
    endDate: "Дата окончания",
    csv: {
      name: "Имя",
      email: "Эл. почта",
      phone: "Телефон",
      branch: "Филиал",
      source: "Источник",
      status: "Статус",
      lostReason: "Причина отказа",
      owner: "Ответственный",
      area: "Направление",
      studyMode: "Формат обучения",
      created: "Создано",
      type: "Тип",
      person: "Человек",
      scheduled: "Запланировано",
      result: "Результат",
      courseOrArea: "Курс / направление",
      recommended: "Рекомендуемый курс",
      student: "Студент",
      course: "Курс",
      className: "Группа",
      enrolled: "Зачислен",
      cancelled: "Отменено",
      toBePaid: "К оплате",
      paid: "Оплачено",
      remaining: "Остаток",
      department: "Кафедра",
      teachers: "Преподаватели",
      schedule: "Расписание",
      capacity: "Вместимость",
      taken: "Занято",
      fill: "Заполненность %",
      start: "Начало",
      end: "Окончание"
    }
  }
};
