import type { StaffMessages } from "./copy";

/** Staff app copy in Urdu. Keys mirror copy.ts; TypeScript enforces it. */
export const ur: StaffMessages = {
  brand: {
    name: "نائل سینٹر",
    product: "تعلیمی انتظام"
  },
  nav: {
    overview: "ہوم",
    dashboard: "ڈیش بورڈ",
    reports: "رپورٹس",
    forms: "فارمز",
    notifications: "اطلاعات",
    admissions: "داخلے",
    students: "طلبہ",
    leads: "امیدوار",
    enrolments: "اندراجات",
    placementTests: "لیول ٹیسٹ",
    trialLessons: "آزمائشی اسباق",
    delivery: "تدریس",
    courses: "کورسز",
    classes: "کلاسیں",
    sessions: "میرا ہفتہ",
    rooms: "کمرے",
    organisation: "افراد اور مقامات",
    staffUsers: "عملہ",
    branches: "شاخیں",
    departments: "شعبے",
    setup: "سیٹ اپ",
    lostReasons: "امیدوار کھونے کی وجوہات",
    actionReasons: "کارروائی کی وجوہات",
    areasOfStudy: "شعبہ ہائے تعلیم",
    customFields: "اضافی فیلڈز",
    system: "سسٹم",
    moodleSite: "Moodle",
    systemHealth: "سسٹم کی صحت",
    auditLog: "آڈٹ لاگ",
    profile: "پروفائل"
  },
  roles: {
    super_admin: "سپر ایڈمن",
    branch_admin: "برانچ ایڈمن",
    vice_manager: "نائب مینیجر",
    hod: "صدرِ شعبہ",
    registrar: "رجسٹرار",
    ssa: "طلبہ کامیابی مشیر",
    teacher: "استاد"
  },
  shell: {
    backTo: "{page} پر واپس جائیں",
    collapseSidebar: "سائیڈ بار سمیٹیں",
    expandSidebar: "سائیڈ بار پھیلائیں",
    staffNav: "عملے کی نیویگیشن",
    openMenu: "مینو کھولیں",
    closeMenu: "مینو بند کریں",
    displaySize: "ڈسپلے سائز",
    displayStandard: "معیاری",
    displayLarge: "بڑا",
    displayXLarge: "بہت بڑا",
    workspace: "ورک اسپیس",
    chooseWorkspace: "شاخ منتخب کریں",
    workspaceHint: "آپ کا کردار ایک وقت میں ایک شاخ میں کام کرتا ہے۔ منتخب کریں کہ کہاں کام کرنا ہے۔",
    noWorkspaces: "ابھی تک آپ کو کوئی فعال شاخ تفویض نہیں کی گئی۔",
    notifications: "اطلاعات",
    markAllRead: "سب کو پڑھا ہوا نشان زد کریں",
    viewAll: "تمام اطلاعات دیکھیں",
    userMenu: "صارف مینو",
    signOut: "سائن آؤٹ",
    signOutEverywhere: "ہر جگہ سے سائن آؤٹ",
    roleView: "کردار کا منظر",
    roleViewTitle: "کردار کا منظر",
    roleViewBody: "ایپ کو کم اختیار والے کردار کی نظر سے دیکھیں۔ ڈیٹا کو منتخب شاخوں، شعبوں یا کلاسوں تک محدود کریں۔",
    viewingAs: "بطور دیکھ رہے ہیں",
    ownRole: "آپ کا کردار",
    roleViewChanged: "کردار کا منظر اپ ڈیٹ ہو گیا۔",
    scopesApplied: "دائرہ لاگو ہو گیا۔",
    roleViewEnded: "آپ اپنے کردار میں واپس آ گئے ہیں۔",
    returnToRole: "اپنے کردار میں واپس جائیں",
    applyScopes: "لاگو کریں",
    viewAsRole: "بطور کردار دیکھیں",
    editRoleView: "ترمیم",
    scopeBranches: "شاخیں",
    scopeBranch: "شاخ",
    scopeDepartments: "شعبے",
    scopeClasses: "کلاسیں",
    allBranches: "تمام شاخیں",
    allDepartments: "تمام شعبے",
    allClasses: "تمام کلاسیں",
    branchesNoun: "شاخیں",
    departmentsNoun: "شعبے",
    classesNoun: "کلاسیں",
    searchBranches: "شاخیں تلاش کریں",
    searchDepartments: "شعبے تلاش کریں",
    searchClasses: "کلاسیں تلاش کریں",
    chooseWorkspaceOption: "ایک شاخ منتخب کریں",
    noAccess: "رسائی نہیں",
    noAccessHint: "آپ کا موجودہ کردار یہ صفحہ نہیں کھول سکتا۔ اپنے ڈیش بورڈ پر واپس جائیں۔",
    backToDashboard: "ڈیش بورڈ پر واپس جائیں",
    checkingSession: "سیشن چیک ہو رہا ہے",
    signedInAs: "بطور سائن ان",
    search: "تلاش کریں یا جائیں",
    breadcrumb: "راستہ",
    commandPages: "صفحات",
    commandPeople: "عملہ",
    commandActions: "کارروائیاں",
    commandEmpty: "کوئی نتیجہ نہیں۔"
  },
  state: {
    loading: "لوڈ ہو رہا ہے",
    notSet: "درج نہیں",
    retry: "دوبارہ کوشش کریں",
    empty: "یہاں ابھی کچھ نہیں ہے۔",
    error403: "آپ کو اس صفحے تک رسائی نہیں ہے۔",
    error404: "یہ ریکارڈ اب موجود نہیں ہے۔",
    error409: "یہ تبدیلی ایک نئی اپ ڈیٹ سے متصادم ہے۔ صفحہ دوبارہ لوڈ کر کے کوشش کریں۔",
    error422: "نمایاں فیلڈز چیک کریں اور دوبارہ کوشش کریں۔",
    error429: "بہت زیادہ درخواستیں۔ تھوڑا انتظار کر کے دوبارہ کوشش کریں۔",
    error503: "یہ سروس ابھی فعال نہیں ہے۔ بعد میں کوشش کریں۔",
    errorNetwork: "نیٹ ورک کنکشن ناکام ہو گیا۔ اپنا کنکشن چیک کریں۔",
    errorGeneric: "درخواست ناکام ہو گئی۔ دوبارہ کوشش کریں۔"
  },
  status: {
    active: "فعال",
    disabled: "غیر فعال",
    invited: "مدعو",
    canceled: "منسوخ",
    cancelled: "منسوخ",
    enrolled: "داخل",
    completed: "مکمل",
    registered: "رجسٹرڈ",
    scheduled: "طے شدہ",
    pending: "زیرِ التوا",
    pending_payment: "ادائیگی باقی",
    pending_class: "کلاس باقی",
    pending_group: "گروپ باقی",
    in_process: "کارروائی جاری",
    follow_up: "دوبارہ رابطہ",
    future_registration: "آئندہ رجسٹریشن",
    trial_lesson: "آزمائشی سبق",
    placement_test: "لیول ٹیسٹ",
    left: "چھوڑ دیا",
    lost: "کھو گیا",
    no_show: "غیر حاضر",
    healthy: "درست",
    degraded: "کمزور",
    unhealthy: "خراب",
    ok: "ٹھیک",
    warning: "انتباہ",
    error: "خرابی",
    not_configured: "ترتیب نہیں دیا گیا"
  },
  notifications: {
    title: "اطلاعات",
    description: "صرف آپ کا ان باکس۔",
    all: "سب",
    unread: "نہ پڑھی ہوئی",
    empty: "آپ کے لیے کوئی اطلاع نہیں۔",
    markRead: "پڑھا ہوا نشان زد کریں",
    markAllRead: "سب کو پڑھا ہوا نشان زد کریں",
    delete: "حذف کریں",
    deleteAll: "سب حذف کریں",
    deleteAllTitle: "تمام اطلاعات حذف کریں؟",
    deleteAllBody: "اس سے آپ کی کاپیاں مستقل طور پر حذف ہو جائیں گی۔ دوسرے عملے کی کاپیاں برقرار رہیں گی۔",
    read: "پڑھی ہوئی",
    unreadBadge: "نہ پڑھی ہوئی",
    markedRead: "اطلاع پڑھی ہوئی نشان زد ہو گئی۔",
    allMarkedRead: "تمام اطلاعات پڑھی ہوئی نشان زد ہو گئیں۔",
    deleted: "اطلاع حذف ہو گئی۔",
    allDeleted: "تمام اطلاعات حذف ہو گئیں۔",
    actionFailed: "اطلاع پر کارروائی ناکام ہو گئی۔ دوبارہ کوشش کریں۔"
  },
  profile: {
    title: "پروفائل",
    description: "اپنی تفصیلات، پاس ورڈ اور فعال سیشنز کا انتظام کریں۔",
    details: "آپ کی تفصیلات",
    role: "تفویض کردہ کردار",
    email: "ای میل",
    name: "نام",
    nameNotSet: "درج نہیں",
    phone: "فون",
    unknownDevice: "نامعلوم آلہ",
    password: "پاس ورڈ",
    currentPassword: "موجودہ پاس ورڈ",
    newPassword: "نیا پاس ورڈ",
    confirmPassword: "نئے پاس ورڈ کی تصدیق کریں",
    changePassword: "پاس ورڈ تبدیل کریں",
    passwordChanged: "پاس ورڈ تبدیل ہو گیا۔",
    passwordFailed: "پاس ورڈ تبدیل نہیں ہو سکا۔ اپنی معلومات چیک کریں۔",
    passwordsDiffer: "نئے پاس ورڈ ایک جیسے نہیں ہیں۔",
    sessions: "فعال سیشنز",
    sessionsHint: "جو سیشن آپ نہیں پہچانتے اسے سائن آؤٹ کریں۔",
    thisSession: "یہ سیشن",
    lastSeen: "آخری بار دیکھا گیا",
    issued: "سائن ان",
    signOutSession: "سیشن سائن آؤٹ کریں",
    sessionRevoked: "سیشن سائن آؤٹ ہو گیا۔",
    signOutEverywhere: "ہر جگہ سے سائن آؤٹ",
    signOutEverywhereTitle: "ہر جگہ سے سائن آؤٹ کریں؟",
    signOutEverywhereBody: "اس سے آپ ہر آلے سے سائن آؤٹ ہو جائیں گے۔ آپ کو دوبارہ سائن ان کرنا ہو گا۔"
  },
  actions: {
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    saving: "محفوظ ہو رہا ہے",
    discardTitle: "تبدیلیاں رد کریں؟",
    discardBody: "آپ کی تبدیلیاں محفوظ نہیں ہوئیں۔",
    discard: "رد کریں",
    keepEditing: "ترمیم جاری رکھیں",
    search: "تلاش",
    filter: "فلٹر",
    columns: "کالم",
    selected: "منتخب",
    clearSelection: "انتخاب ختم کریں",
    previous: "پچھلا",
    next: "اگلا",
    pageOf: "/",
    create: "بنائیں",
    edit: "ترمیم",
    rowActions: "قطار کی کارروائیاں",
    enable: "فعال کریں",
    disable: "غیر فعال کریں",
    close: "بند کریں",
    import: "درآمد کریں",
    refresh: "تازہ کریں",
    noReasons: "پہلے اس کارروائی کے لیے ایک وجہ شامل کریں۔",
    openActionReasons: "کارروائی کی وجوہات کھولیں۔",
    status: "حیثیت",
    activeOnly: "صرف فعال",
    selectAll: "تمام قطاریں منتخب کریں",
    selectRow: "قطار منتخب کریں",
    pagination: "صفحات"
  },
  catalog: {
    shared: {
      name: "نام",
      nameRequired: "نام درج کریں۔",
      code: "کوڈ",
      codeHint: "چھوٹے حروف، اعداد اور انڈر اسکور۔",
      codePattern: "صرف چھوٹے حروف، اعداد اور انڈر اسکور استعمال کریں۔",
      sortOrder: "ترتیب",
      created: "بنایا گیا",
      status: "حیثیت",
      active: "فعال",
      disabled: "غیر فعال",
      allStatuses: "تمام حیثیتیں",
      access: "آپ کی رسائی",
      accessManage: "انتظام",
      accessView: "دیکھنا",
      customFields: "اضافی فیلڈز",
      customFieldsEmpty: "اس ریکارڈ پر کوئی اضافی فیلڈ لاگو نہیں ہوتی۔",
      enableTitle: "یہ ریکارڈ فعال کریں؟",
      disableTitle: "یہ ریکارڈ غیر فعال کریں؟",
      enableBody: "یہ ریکارڈ دوبارہ دستیاب ہو جائے گا۔",
      createdToast: "بن گیا۔",
      updatedToast: "تبدیلیاں محفوظ ہو گئیں۔",
      enabledToast: "فعال ہو گیا۔",
      disabledToast: "غیر فعال ہو گیا۔",
      saveChanges: "تبدیلیاں محفوظ کریں"
    },
    branches: {
      title: "شاخیں",
      description: "وہ مقامات جہاں نائل سینٹر کام کرتا ہے۔",
      empty: "ابھی کوئی شاخ نہیں۔",
      emptyHint: "پہلی شاخ بنائیں۔",
      add: "شاخ شامل کریں",
      createTitle: "شاخ شامل کریں",
      editTitle: "شاخ میں ترمیم کریں",
      createDescription: "ایک فعال شاخ بنائیں۔",
      editDescription: "نام، کوڈ یا ترتیبات اپ ڈیٹ کریں۔",
      createSubmit: "شاخ بنائیں",
      timezone: "ٹائم زون",
      online: "آن لائن شاخ",
      onlineYes: "آن لائن",
      onlineNo: "بالمشافہ",
      searchBranches: "شاخیں تلاش کریں",
      disableBody: "یہ شاخ نیا کام لینا بند کر دے گی۔ اس پر موجود سیشنز اپنی ورک اسپیس کھو دیں گے۔",
      statisticsTitle: "سرگرمی",
      detailMissing: "یہ شاخ اب موجود نہیں ہے۔",
      statActiveStudents: "فعال طلبہ",
      statOpenLeads: "کھلے امیدوار",
      statActiveClasses: "فعال کلاسیں",
      statEnrolmentFill: "بھری ہوئی نشستیں",
      statEnrolmentCapacity: "اندراج کی گنجائش",
      statPendingEnrolments: "زیرِ التوا اندراجات",
      statPlacements: "طے شدہ لیول ٹیسٹ",
      statTrials: "طے شدہ آزمائشی اسباق",
      statStaff: "عملہ",
      bulkDisable: "منتخب کو غیر فعال کریں",
      bulkEnable: "منتخب کو فعال کریں",
      bulkDone: "انتخاب اپ ڈیٹ ہو گیا۔"
    },
    departments: {
      title: "شعبے",
      description: "وہ تعلیمی شعبے جن کے تحت کلاسیں اور کورسز ہیں۔",
      empty: "ابھی کوئی شعبہ نہیں۔",
      emptyHint: "پہلا شعبہ بنائیں۔",
      add: "شعبہ شامل کریں",
      createTitle: "شعبہ شامل کریں",
      editTitle: "شعبے میں ترمیم کریں",
      createSubmit: "شعبہ بنائیں",
      disableBody: "یہ شعبہ نئے کام کے لیے چھپا دیا گیا ہے۔"
    },
    lostReasons: {
      title: "امیدوار کھونے کی وجوہات",
      description: "امیدوار کو کھویا ہوا کیوں نشان زد کیا گیا۔",
      empty: "ابھی کوئی وجہ نہیں۔",
      emptyHint: "پہلی وجہ بنائیں۔",
      add: "وجہ شامل کریں",
      createTitle: "وجہ شامل کریں",
      editTitle: "وجہ میں ترمیم کریں",
      createSubmit: "وجہ بنائیں",
      disableBody: "یہ وجہ نئے کام کے لیے چھپا دی گئی ہے۔"
    },
    actionReasons: {
      title: "کارروائی کی وجوہات",
      description: "محفوظ کارروائیوں کے لیے درکار نامزد وجوہات۔",
      empty: "ابھی کارروائی کی کوئی وجہ نہیں۔",
      emptyHint: "پہلی وجہ بنائیں یا درآمد کریں۔",
      add: "کارروائی کی وجہ شامل کریں",
      createTitle: "کارروائی کی وجہ شامل کریں",
      editTitle: "کارروائی کی وجہ میں ترمیم کریں",
      createSubmit: "وجہ بنائیں",
      disableBody: "یہ وجہ نئے کام کے لیے چھپا دی گئی ہے۔",
      kind: "قسم",
      allKinds: "تمام اقسام",
      import: "CSV درآمد کریں",
      importTitle: "کارروائی کی وجوہات درآمد کریں",
      importDescription: "CSV قطاریں چسپاں کریں یا فائل منتخب کریں۔ پہلے پیش منظر دیکھیں، پھر درآمد کریں۔",
      chooseFile: "CSV فائل منتخب کریں",
      downloadTemplate: "ٹیمپلیٹ ڈاؤن لوڈ کریں",
      orPaste: "یا CSV قطاریں چسپاں کریں",
      importPreview: "پیش منظر",
      importRowCount: "قطاریں",
      rowError: "خرابی",
      rowErrorColumns: "6 کالم درکار ہیں۔",
      rowErrorKind: "نامعلوم قسم۔",
      rowErrorName: "نام لازمی ہے۔",
      importEmpty: "پیش منظر کے لیے CSV قطاریں چسپاں کریں۔",
      importSubmit: "درآمد کریں",
      importDone: "درآمد مکمل ہو گئی۔",
      importCreated: "بنائے گئے",
      importUpdated: "اپ ڈیٹ ہوئے",
      csvPlaceholder: "id,action,name,status,sort_order,created_at",
      kindLost: "امیدوار کھو گیا",
      kindLeft_enrolment: "اندراج چھوڑ دیا",
      kindCancel_enrolment: "اندراج منسوخ کریں",
      kindCancel_placement_test: "لیول ٹیسٹ منسوخ کریں",
      kindCancel_trial_lesson: "آزمائشی سبق منسوخ کریں",
      kindDisable_student: "طالب علم غیر فعال کریں",
      kindDisable_course: "کورس غیر فعال کریں",
      kindDisable_class: "کلاس غیر فعال کریں",
      kindDisable_branch: "شاخ غیر فعال کریں",
      kindDisable_department: "شعبہ غیر فعال کریں",
      kindDisable_room: "کمرہ غیر فعال کریں",
      kindDisable_staff: "عملہ غیر فعال کریں",
      kindDisable_area_of_study: "شعبۂ تعلیم غیر فعال کریں",
      kindDisable_custom_field: "اضافی فیلڈ غیر فعال کریں"
    },
    areasOfStudy: {
      title: "شعبہ ہائے تعلیم",
      description: "وہ مضامین جن میں طالب علم کو رکھا جا سکتا ہے۔",
      empty: "ابھی کوئی شعبۂ تعلیم نہیں۔",
      emptyHint: "پہلا شعبۂ تعلیم بنائیں۔",
      add: "شعبۂ تعلیم شامل کریں",
      createTitle: "شعبۂ تعلیم شامل کریں",
      editTitle: "شعبۂ تعلیم میں ترمیم کریں",
      createSubmit: "شعبہ بنائیں",
      disableBody: "یہ شعبہ نئی درجہ بندی کے لیے چھپا دیا گیا ہے۔",
      placementCourses: "لیول ٹیسٹ کے کورسز",
      placementCoursesHint: "وہ Moodle کورسز منتخب کریں جن میں لیول ٹیسٹ ہیں۔",
      addCourse: "Moodle کورس شامل کریں",
      searchCourses: "Moodle کورسز تلاش کریں",
      coursesEmpty: "کوئی کورس نہیں ملا۔",
      coursesLoading: "کورسز لوڈ ہو رہے ہیں",
      coursesError: "Moodle کورسز دستیاب نہیں ہیں۔"
    },
    customFields: {
      title: "اضافی فیلڈز",
      description: "پوری ایپ میں ریکارڈز پر اضافی فیلڈز۔",
      empty: "ابھی کوئی اضافی فیلڈ نہیں۔",
      emptyHint: "پہلی اضافی فیلڈ بنائیں۔",
      add: "اضافی فیلڈ شامل کریں",
      createTitle: "اضافی فیلڈ شامل کریں",
      editTitle: "اضافی فیلڈ میں ترمیم کریں",
      createSubmit: "فیلڈ بنائیں",
      disableBody: "یہ فیلڈ فارمز سے چھپا دی گئی ہے۔",
      entity: "ریکارڈ کی قسم",
      allEntities: "تمام اقسام",
      fieldKey: "فیلڈ کی کلید",
      fieldKeyHint: "ڈیٹا ماڈل میں استعمال ہونے والا چھوٹے حروف کا شناخت کنندہ۔ بعد میں تبدیل نہیں ہو سکتا۔",
      fieldType: "قسم",
      required: "لازمی فیلڈ",
      requiredYes: "لازمی",
      optional: "اختیاری",
      helpText: "مددگار متن",
      options: "اختیارات",
      optionsHint: "ہر سطر میں ایک اختیار۔",
      entityUser_profile: "عملے کا پروفائل",
      entityStudent: "طالب علم",
      entityLead: "امیدوار",
      entityBranch: "شاخ",
      entityDepartment: "شعبہ",
      entityClass: "کلاس",
      entityCourse: "کورس",
      entityRoom: "کمرہ"
    }
  },
  staffUsers: {
    title: "عملہ",
    description: "نائل سینٹر میں کام کرنے والا ہر فرد، اس کا کردار، کام کی جگہ اور سائن ان کا طریقہ۔",
    add: "رکنِ عملہ شامل کریں",
    createTitle: "رکنِ عملہ شامل کریں",
    editTitle: "رکنِ عملہ میں ترمیم کریں",
    createDescription: "کردار اور دائرے کے ساتھ عملے کا اکاؤنٹ بنائیں۔",
    editDescription: "کردار، پروفائل یا دائرہ اپ ڈیٹ کریں۔",
    createSubmit: "رکنِ عملہ بنائیں",
    empty: "ابھی عملے کا کوئی صارف نہیں۔",
    emptyHint: "عملے کے پہلے صارف کو مدعو کریں۔",
    noAccess: "عملے کے اکاؤنٹس کا انتظام سپر ایڈمن اور برانچ ایڈمن کرتے ہیں۔",
    person: "فرد",
    email: "ای میل",
    role: "کردار",
    worksAt: "کام کی جگہ",
    branches: "شاخیں",
    departments: "شعبے",
    courses: "کورسز",
    moodle: "Moodle",
    status: "حیثیت",
    lastSignIn: "آخری سائن ان",
    added: "شامل کیا گیا",
    you: "آپ",
    all: "سب",
    results: "نتائج",
    clearFilters: "فلٹر صاف کریں",
    teachersNoMoodle: "Moodle کے بغیر اساتذہ",
    allRoles: "تمام کردار",
    allBranches: "تمام شاخیں",
    allDepartments: "تمام شعبے",
    globalScope: "تمام شاخیں",
    branchScope: "شاخوں کا دائرہ",
    branchScopeHint: "نائب مینیجر کو صرف ایک شاخ چاہیے۔ رجسٹرار، مشیر اور استاد کو کم از کم ایک چاہیے۔",
    workspaceScopeHint: "نئے اکاؤنٹس میں آپ کی ورک اسپیس شاخ شامل ہونی چاہیے۔",
    invited: "مدعو",
    moodleLinked: "منسلک",
    moodleMissing: "منسلک نہیں",
    provisioning: "اکاؤنٹ بنانے کا طریقہ",
    provisioningInvitation: "دعوت کا لنک",
    provisioningManual: "دستی پاس ورڈ",
    provisioningHint: "دعوت ایک بار استعمال ہونے والا لنک بناتی ہے۔ دستی طریقہ عارضی پاس ورڈ بناتا ہے۔",
    firstName: "پہلا نام",
    lastName: "آخری نام",
    phone: "فون",
    address: "پتہ",
    nationality: "قومیت",
    nationalityHint: "ملک کا تین حرفی کوڈ۔",
    dateOfBirth: "تاریخِ پیدائش",
    notes: "نوٹس",
    canTakePlacementTest: "لیول ٹیسٹ لے سکتا ہے",
    yourPassword: "آپ کا پاس ورڈ",
    yourPasswordHint: "سپر ایڈمن کی اس تبدیلی کے لیے آپ کا اپنا پاس ورڈ درکار ہے۔",
    yourPasswordRequired: "جاری رکھنے کے لیے اپنا پاس ورڈ درج کریں۔",
    firstNameRequired: "پہلا نام لازمی ہے۔",
    lastNameRequired: "آخری نام لازمی ہے۔",
    emailRequired: "درست ای میل پتہ درج کریں۔",
    branchScopeRequired: "کم از کم ایک شاخ منتخب کریں۔",
    viceManagerScope: "نائب مینیجر کو صرف ایک شاخ چاہیے۔",
    invite: "مدعو کریں",
    resendInvite: "دعوت دوبارہ بھیجیں",
    inviteTitle: "نئی دعوت بھیجیں؟",
    inviteBody: "پچھلا دعوتی لنک کام کرنا بند کر دے گا۔",
    cancelInvite: "دعوت منسوخ کریں",
    cancelInviteTitle: "یہ دعوت منسوخ کریں؟",
    cancelInviteBody: "دعوتی لنک فوراً کام کرنا بند کر دے گا۔",
    setPassword: "پاس ورڈ سیٹ کریں",
    setPasswordTitle: "نیا پاس ورڈ سیٹ کریں؟",
    setPasswordBody: "عارضی پاس ورڈ صرف ایک بار بنتا ہے۔ اسے محفوظ ذریعے سے شیئر کریں۔",
    moodleAccount: "Moodle اکاؤنٹ",
    moodleCreate: "Moodle اکاؤنٹ بنائیں",
    moodleLink: "Moodle اکاؤنٹ منسلک کریں",
    moodleReset: "Moodle پاس ورڈ ری سیٹ کریں",
    moodleResetTitle: "Moodle پاس ورڈ ری سیٹ کریں؟",
    moodleResetBody: "نیا Moodle پاس ورڈ صرف ایک بار بنتا ہے۔ اسے محفوظ ذریعے سے شیئر کریں۔",
    moodleSearch: "Moodle اکاؤنٹس تلاش کریں",
    moodleSearchHint: "نام، یوزر نیم یا ای میل سے تلاش کریں۔",
    moodleSearchMin: "کم از کم 2 حروف لکھیں۔",
    moodleSearchEmpty: "کوئی Moodle اکاؤنٹ نہیں ملا۔",
    moodleCreateHint: "اس رکنِ عملہ سے منسلک Moodle اکاؤنٹ بناتا ہے۔",
    moodleLinkHint: "موجودہ Moodle اکاؤنٹ کو اس رکنِ عملہ سے منسلک کریں۔",
    disableTitle: "اس رکنِ عملہ کو غیر فعال کریں؟",
    disableBody: "یہ اکاؤنٹ اب سائن ان نہیں کر سکے گا۔",
    enableTitle: "اس رکنِ عملہ کو فعال کریں؟",
    enableBody: "یہ اکاؤنٹ دوبارہ سائن ان کر سکے گا۔",
    bulkDisable: "منتخب کو غیر فعال کریں",
    bulkEnable: "منتخب کو فعال کریں",
    bulkDone: "انتخاب اپ ڈیٹ ہو گیا۔",
    createdToast: "رکنِ عملہ بن گیا۔",
    updatedToast: "تبدیلیاں محفوظ ہو گئیں۔",
    invitedToast: "دعوت بن گئی۔",
    cancelledToast: "دعوت منسوخ ہو گئی۔",
    passwordToast: "پاس ورڈ ری سیٹ ہو گیا۔",
    moodleToast: "Moodle اکاؤنٹ اپ ڈیٹ ہو گیا۔",
    disabledToast: "رکنِ عملہ غیر فعال ہو گیا۔",
    enabledToast: "رکنِ عملہ فعال ہو گیا۔",
    secretTitle: "ایک بار کی اسناد",
    secretBody: "انہیں ابھی کاپی کریں۔ یہ دوبارہ نہیں دکھائی جائیں گی۔",
    secretShare: "اسناد صرف محفوظ ذریعے سے شیئر کریں۔",
    secretDone: "ہو گیا",
    copyValue: "کاپی کریں",
    copied: "کاپی ہو گیا۔",
    invitationLink: "دعوت کا لنک",
    temporaryPassword: "عارضی پاس ورڈ",
    moodlePassword: "Moodle پاس ورڈ",
    moreActions: "مزید کارروائیاں",
    copyEmail: "ای میل کاپی کریں",
    emailCopied: "ای میل کاپی ہو گئی۔",
    tabOverview: "جائزہ",
    tabCourses: "کورسز",
    tabAvailability: "دستیابی",
    tabActivity: "سرگرمی",
    sectionContact: "رابطہ",
    sectionAccess: "رسائی",
    sectionMore: "مزید تفصیلات",
    neverSignedIn: "کبھی سائن ان نہیں کیا",
    statsAdmissions: "داخلے",
    statsTeaching: "تدریس",
    statLeadsCreated: "بنائے گئے امیدوار",
    statLeadsAssigned: "تفویض کردہ امیدوار",
    statLeadsOpen: "کھلے امیدوار",
    statLeadsRegistered: "رجسٹرڈ",
    statLeadsLost: "کھو گئے",
    statStudentsAssigned: "تفویض کردہ طلبہ",
    statClassesTeaching: "زیرِ تدریس کلاسیں",
    statSessionsScheduled: "طے شدہ سیشنز",
    statStudentsTaught: "پڑھائے گئے طلبہ",
    statsEmpty: "ابھی کوئی سرگرمی درج نہیں ہوئی۔",
    coursesTitle: "پڑھانے کے قابل کورسز",
    coursesHint: "خالی فہرست کا مطلب ہے کہ اس استاد کو کسی کلاس میں تفویض نہیں کیا جا سکتا۔",
    coursesSaved: "کورسز اپ ڈیٹ ہو گئے۔",
    coursesSearchPlaceholder: "کورسز تلاش کریں",
    placementCapability: "لیول ٹیسٹ",
    placementYes: "لیول ٹیسٹ لے سکتا ہے",
    placementNo: "لیول ٹیسٹ نہیں لے سکتا",
    availabilityTitle: "دستیابی",
    availabilityHint: "اس استاد کے کام کے اوقات نشان زد کریں۔ بک شدہ سیشنز تبدیل نہیں ہو سکتے۔",
    penAvailable: "دستیاب",
    penUnavailable: "دستیاب نہیں",
    penClear: "صاف کریں",
    showAllHours: "تمام اوقات دکھائیں",
    showWorkHours: "کام کے اوقات دکھائیں",
    timezoneLabel: "ٹائم زون",
    unsavedBar: "آپ کی تبدیلیاں محفوظ نہیں ہوئیں۔",
    saveChanges: "تبدیلیاں محفوظ کریں",
    discardChanges: "رد کریں",
    discardTitle: "دستیابی کی تبدیلیاں رد کریں؟",
    discardBody: "آپ کی نشان زد تبدیلیاں محفوظ نہیں ہوئیں۔",
    cellsSaved: "دستیابی محفوظ ہو گئی۔",
    cellsSkippedBooked: "بک شدہ سیشنز چھوڑ دیے گئے۔",
    weekToday: "آج",
    weekPrevious: "پچھلا ہفتہ",
    weekNext: "اگلا ہفتہ",
    bookedSession: "بک شدہ"
  },
  moodleSite: {
    title: "Moodle سائٹ",
    description: "وہ Moodle سائٹ منسلک کریں جس پر کورسز، گروپس اور حاضری چلتے ہیں۔",
    noAccess: "صرف سپر ایڈمن Moodle سائٹ ترتیب دے سکتا ہے۔",
    connection: "کنکشن",
    connectionHint: "Moodle کے لیے ویب سروس اسناد۔ ٹوکن صرف لکھا جا سکتا ہے۔",
    siteUrl: "سائٹ کا URL",
    token: "ویب سروس ٹوکن",
    tokenHint: "محفوظ طریقے سے رکھا گیا ہے۔ صرف ٹوکن بدلنے کے لیے دوبارہ درج کریں۔",
    tokenKeep: "موجودہ ٹوکن رکھنے کے لیے خالی چھوڑ دیں۔",
    autoCreate: "طلبہ کے Moodle اکاؤنٹس خود بخود بنائیں",
    autoCreateHint: "فعال ہونے پر طالب علم بناتے وقت Moodle اکاؤنٹ بنانے کی بھی کوشش ہوتی ہے۔",
    ptCourse: "لیول ٹیسٹ کا Moodle کورس ID",
    ptCourseHint: "وہ Moodle کورس جس میں لیول ٹیسٹ ہوتا ہے۔ صاف کرنے کے لیے خالی چھوڑ دیں۔",
    save: "تبدیلیاں محفوظ کریں",
    connect: "Moodle منسلک کریں",
    test: "کنکشن ٹیسٹ کریں",
    disconnect: "منقطع کریں",
    disconnectTitle: "Moodle منقطع کریں؟",
    disconnectBody: "محفوظ ٹوکن ہٹا دیا جائے گا۔ دوبارہ منسلک ہونے تک کورسز اور گروپس کی ہم آہنگی رک جائے گی۔",
    saved: "Moodle کی ترتیب محفوظ ہو گئی۔",
    disconnected: "Moodle منقطع ہو گیا۔",
    testOk: "کنکشن ٹیسٹ کامیاب رہا۔",
    testVersionWarn: "رسائی ممکن ہے، مگر Moodle کا ورژن متوقع 4.5.x حد سے باہر ہے۔",
    testFailed: "Moodle تک رسائی ممکن نہیں۔",
    statusTitle: "حیثیت",
    statConfigured: "ترتیب شدہ",
    statToken: "ٹوکن محفوظ",
    statReachable: "رسائی ممکن",
    statVersion: "متوقع ورژن",
    statSitename: "سائٹ کا نام",
    statRelease: "ریلیز",
    statLastChecked: "آخری جانچ",
    statWarnings: "انتباہات",
    statLastError: "آخری خرابی",
    unknown: "نامعلوم",
    yes: "ہاں",
    no: "نہیں"
  },
  system: {
    title: "سسٹم کی صحت",
    description: "بنیادی سروسز اور Moodle انضمام کی موجودہ حالت۔",
    noAccess: "صرف سپر ایڈمن سسٹم کی صحت دیکھ سکتا ہے۔",
    refresh: "تازہ کریں",
    checked: "جانچا گیا",
    componentApi: "API",
    componentDatabase: "ڈیٹا بیس",
    componentSchema: "اسکیما کی جانچ",
    componentMigration: "مائیگریشنز",
    componentMoodle: "Moodle",
    operational: "درست کام کر رہا ہے۔",
    version: "ورژن",
    configured: "ترتیب شدہ",
    token: "ٹوکن",
    reachable: "رسائی ممکن",
    site: "سائٹ",
    release: "ریلیز",
    expected: "متوقع 4.5.x",
    warnings: "انتباہات"
  },
  audit: {
    title: "آڈٹ لاگ",
    description: "کس نے کب کیا کیا۔ تازہ ترین پہلے۔",
    noAccess: "صرف سپر ایڈمن اور برانچ ایڈمن آڈٹ کے واقعات پڑھ سکتے ہیں۔",
    stream: "سلسلہ",
    allStreams: "تمام سلسلے",
    search: "واقعات تلاش کریں",
    empty: "کوئی آڈٹ واقعہ نہیں۔",
    emptyHint: "کارروائیاں ہوتے ہی یہاں درج ہوتی ہیں۔",
    payload: "ڈیٹا",
    actor: "کرنے والا",
    system: "سسٹم",
    today: "آج",
    yesterday: "کل",
    latest: "تازہ ترین {n} واقعات",
    failedSignIn: "کسی نے",
    groups: {
      all: "سب",
      auth: "سائن انز",
      admissions: "داخلے",
      teaching: "تدریس",
      setup: "سیٹ اپ"
    },
    nouns: {
      auth: "اکاؤنٹ",
      branch: "شاخ",
      department: "شعبہ",
      course: "کورس",
      custom_field: "اضافی فیلڈ",
      moodle_site: "Moodle کنکشن",
      student: "طالب علم",
      lead: "امیدوار",
      placement_test: "لیول ٹیسٹ",
      class: "کلاس",
      enrolment: "اندراج",
      room: "کمرہ",
      session: "سیشن"
    },
    verbs: {
      created: "نے {noun} بنایا",
      updated: "نے {noun} اپ ڈیٹ کیا",
      disabled: "نے {noun} غیر فعال کیا",
      enabled: "نے {noun} فعال کیا",
      cancelled: "نے {noun} منسوخ کیا",
      completed: "نے {noun} مکمل کیا",
      refreshed: "نے {noun} تازہ کیا",
      tested: "نے {noun} ٹیسٹ کیا",
      other: "{action}: {noun}"
    },
    actions: {
      login_success: "نے سائن ان کیا",
      login_failed: "سائن ان نہیں کر سکا",
      logout: "نے سائن آؤٹ کیا",
      workspace_switched: "نے شاخ تبدیل کی",
      role_switched: "نے کردار کا منظر تبدیل کیا",
      invitation_sent: "نے دعوت بھیجی:",
      invitation_accepted: "نے دعوت قبول کی",
      user_created: "نے عملے کا اکاؤنٹ بنایا:",
      moodle_group_created: "نے Moodle گروپ بنایا:",
      moodle_group_deleted: "نے Moodle گروپ ہٹایا:",
      moodle_group_synced: "نے Moodle سے ہم آہنگ کیا:",
      moodle_linked: "نے Moodle اکاؤنٹ منسلک کیا:",
      converted: "نے طالب علم میں تبدیل کیا:",
      enrolled: "نے طالب علم کا اندراج کیا"
    },
    streams: {
      auth: "سائن ان",
      branch: "شاخ",
      department: "شعبہ",
      course: "کورس",
      custom_field: "اضافی فیلڈ",
      moodle_site: "Moodle سائٹ",
      student: "طالب علم",
      lead: "امیدوار",
      placement_test: "لیول ٹیسٹ",
      class: "کلاس",
      enrolment: "اندراج",
      room: "کمرہ",
      session: "سیشن"
    }
  },
  dashboard: {
    morning: "صبح بخیر",
    afternoon: "سہ پہر بخیر",
    evening: "شام بخیر",
    nameSeparator: "، ",
    intro: "آج آپ کی توجہ کے منتظر کام یہ ہیں۔",
    openLeads: "کھلے امیدوار",
    openLeadsNote: "ابھی رجسٹرڈ یا کھوئے نہیں",
    bookings: "آنے والی بکنگز",
    tests: "ٹیسٹ",
    trials: "آزمائشی",
    waitingSales: "منتظر فروخت",
    waitingSalesNote: "ادائیگی یا کلاس ابھی باقی ہے",
    classFill: "کلاسیں کتنی بھری ہیں",
    seatsOf: "/",
    seats: "نشستیں بھری ہوئی",
    activeStudents: "فعال طلبہ",
    activeStudentsNote: "فعال ریکارڈ کے ساتھ",
    today: "آج",
    todayEmpty: "آج کے لیے کچھ بک نہیں۔",
    overdue: "پچھلی بکنگز کا نتیجہ درج کرنا باقی ہے",
    openAgenda: "شیڈول کھولیں",
    attention: "توجہ درکار",
    allClear: "سب ٹھیک ہے",
    resultsToRecord: "درج کرنے کے نتائج",
    unpaid: "غیر ادا شدہ کورس فروخت",
    waitingClass: "ادا شدہ، کلاس کے منتظر",
    unowned: "بغیر ذمہ دار کے کھلے امیدوار",
    formResponses: "فارم کے نئے جوابات",
    period: "مدت",
    periods: {
      "7d": "7 دن",
      "30d": "30 دن",
      "90d": "90 دن",
      "12m": "12 مہینے",
      all: "تمام عرصہ"
    },
    vsPrevious: "پچھلی مدت کے مقابلے میں",
    noChange: "کوئی تبدیلی نہیں",
    pts: " پوائنٹس",
    newLeads: "نئے امیدوار",
    conversion: "تبدیلی کی شرح",
    conversionNote: "طے شدہ امیدواروں میں سے رجسٹرڈ",
    intake: "امیدواروں کی آمد",
    intakeNote: "ہر ہفتے نئے امیدوار",
    weekOf: "ہفتہ",
    outcomes: "امیدواروں کے نتائج",
    open: "کھلا",
    registered: "رجسٹرڈ",
    lost: "کھو گیا",
    noData: "اس مدت میں کوئی امیدوار نہیں۔",
    funnel: "پوچھ گچھ سے طالب علم تک",
    funnelLeads: "امیدوار",
    funnelBooked: "ٹیسٹ اور آزمائشی اسباق مکمل",
    bookingsTitle: "ٹیسٹ اور آزمائشی اسباق",
    placementTests: "لیول ٹیسٹ",
    trialLessons: "آزمائشی اسباق",
    completed: "مکمل",
    scheduledLabel: "طے شدہ",
    noShow: "غیر حاضر",
    cancelled: "منسوخ",
    showRate: "حاضر ہوئے",
    pipeline: "امیدواروں کی پائپ لائن",
    pipelineEmpty: "کوئی کھلا امیدوار نہیں۔",
    branches: "شاخیں",
    branch: "شاخ",
    students: "طلبہ",
    classes: "کلاسیں",
    fill: "بھرنے کی شرح",
    waiting: "منتظر",
    placement: "لیول ٹیسٹ",
    trial: "آزمائشی سبق",
    myClasses: "میری کلاسیں",
    myStudents: "میری کلاسوں کے طلبہ",
    nextSession: "اگلا سیشن",
    noNextSession: "کوئی سیشن بک نہیں",
    sessions: "آنے والے سیشنز",
    sessionsEmpty: "ابھی کوئی سیشن بک نہیں ہوا۔",
    classesEmpty: "ابھی آپ کو کوئی کلاس تفویض نہیں کی گئی۔",
    openMoodle: "Moodle میں کھولیں",
    departmentClasses: "شعبے کی کلاسیں",
    seatsFree: "خالی نشستیں",
    noTeacher: "بغیر استاد کی کلاسیں",
    departmentEmpty: "آپ کے شعبوں میں ابھی کوئی کلاس نہیں۔",
    teachers: "اساتذہ",
    schedule: "نظام الاوقات",
    unassignedTeacher: "کوئی استاد نہیں",
    enrolled: "داخل",
    loadError: "کچھ اعداد و شمار لوڈ نہیں ہو سکے۔"
  },
  teaching: {
    hourUnit: "گھنٹے",
    seats: "نشستیں",
    seatsLeft: "باقی",
    full: "بھری ہوئی",
    allBranches: "تمام شاخیں",
    branch: "شاخ",
    required: "لازمی۔",
    wholeNumber: "صفر سے بڑا مکمل عدد درج کریں۔",
    openMoodle: "Moodle میں کھولیں",
    courses: {
      title: "کورسز",
      description: "Moodle سے منسلک کورسز، ان کے گھنٹے، شعبہ اور موجودہ طلب۔",
      empty: "کوئی کورس نہیں ملا۔",
      emptyHint: "فروخت شروع کرنے کے لیے Moodle کورس منسلک کریں۔",
      course: "کورس",
      department: "شعبہ",
      allDepartments: "تمام شعبے",
      area: "شعبۂ تعلیم",
      noArea: "کوئی شعبہ نہیں",
      hours: "گھنٹے",
      totalHours: "کل تدریسی گھنٹے",
      moodle: "Moodle",
      moodleVisible: "نظر آتا ہے",
      moodleHidden: "چھپا ہوا",
      moodleChecked: "Moodle میں جانچا گیا",
      refreshError: "Moodle سے تازہ کاری ناکام",
      refreshAll: "Moodle سے تازہ کریں",
      refreshAllToast: "کورسز Moodle سے تازہ ہو گئے۔",
      refreshOne: "Moodle سے تازہ کریں",
      refreshOneToast: "کورس Moodle سے تازہ ہو گیا۔",
      link: "Moodle کورس منسلک کریں",
      linkTitle: "ایک Moodle کورس منسلک کریں",
      linkDescription: "کورسز Moodle سے آتے ہیں۔ ایسا کورس منتخب کریں جو ابھی منسلک نہیں اور اس کے تدریسی گھنٹے درج کریں۔",
      linkSubmit: "کورس منسلک کریں",
      linkToast: "کورس منسلک ہو گیا۔",
      editTitle: "کورس میں ترمیم کریں",
      editDescription: "شعبہ، گھنٹے، شعبۂ تعلیم اور اس سے پہلے والا کورس۔",
      editToast: "کورس اپ ڈیٹ ہو گیا۔",
      chooseMoodle: "ایک Moodle کورس منتخب کریں۔",
      noUnmapped: "ہر Moodle کورس پہلے سے منسلک ہے۔",
      searchMoodle: "Moodle کورسز تلاش کریں",
      previous: "اس کے بعد آتا ہے",
      noPrevious: "کوئی پچھلا کورس نہیں",
      attendanceId: "Moodle حاضری سرگرمی",
      attendanceHint: "حاضری لگانے کے لیے ضروری ہے۔ یہ Moodle کورس میں حاضری سرگرمی کا ID ہے۔",
      noAttendance: "درج نہیں، اس لیے حاضری نہیں لگ سکتی۔",
      disable: "کورس غیر فعال کریں",
      disableTitle: "یہ کورس غیر فعال کریں؟",
      disableBody: "اسے اب فروخت نہیں کیا جا سکے گا اور نئی کلاسیں نہیں بنیں گی۔ موجودہ کلاسیں برقرار رہیں گی۔",
      disabledToast: "کورس غیر فعال ہو گیا۔",
      enable: "کورس فعال کریں",
      enableTitle: "یہ کورس فعال کریں؟",
      enableBody: "اسے دوبارہ فروخت کیا جا سکے گا اور نئی کلاسیں بن سکیں گی۔",
      enabledToast: "کورس فعال ہو گیا۔",
      demand: "موجودہ طلب",
      activeClasses: "فعال کلاسیں",
      seatsTaken: "بھری ہوئی نشستیں",
      waitingSales: "منتظر فروخت",
      interestedLeads: "دلچسپی رکھنے والے امیدوار",
      classes: "کلاسیں",
      noClasses: "اس کورس کی ابھی کوئی کلاس نہیں۔",
      writeNote: "صرف سپر ایڈمن کورسز تبدیل کر سکتا ہے۔"
    },
    classes: {
      title: "کلاسیں",
      description: "ہر کلاس اپنے اساتذہ، معمول کے وقت، نشستوں اور Moodle گروپ کے ساتھ۔",
      empty: "کوئی کلاس نہیں ملی۔",
      emptyHint: "کسی فعال کورس کے لیے کلاس بنائیں۔",
      add: "کلاس شامل کریں",
      createTitle: "کلاس شامل کریں",
      editTitle: "کلاس میں ترمیم کریں",
      createDescription: "کورس، تاریخیں، نشستیں، اساتذہ اور ہفتہ وار معمول کا وقت۔",
      editDescription: "تاریخیں، نشستیں، اساتذہ، معمول کا وقت اور میٹنگ لنک۔",
      createSubmit: "کلاس بنائیں",
      createdToast: "کلاس بن گئی۔",
      updatedToast: "کلاس اپ ڈیٹ ہو گئی۔",
      name: "کلاس کا نام",
      course: "کورس",
      allCourses: "تمام کورسز",
      kind: "کلاس کی قسم",
      group: "گروپ",
      individual: "انفرادی",
      capacity: "نشستیں",
      starts: "شروع",
      ends: "اختتام",
      dates: "تاریخیں",
      teachers: "اساتذہ",
      noTeachers: "اس شاخ میں ابھی کوئی استاد نہیں۔",
      noTeacher: "کوئی استاد نہیں",
      usualDays: "معمول کے دن",
      from: "سے",
      to: "تک",
      usualTime: "معمول کا وقت",
      noSchedule: "کوئی معمول کا وقت نہیں",
      meetingLink: "میٹنگ لنک",
      meetingHint: "آن لائن کلاسوں کے لیے۔ https لنک استعمال کریں۔",
      meetingInvalid: "ایسا لنک استعمال کریں جو https:// سے شروع ہو",
      endBeforeStart: "اختتامی تاریخ آغاز کی تاریخ کے بعد ہونی چاہیے۔",
      timeOrder: "اختتامی وقت آغاز کے وقت کے بعد ہونا چاہیے۔",
      timeBoth: "دونوں اوقات درج کریں، یا کوئی بھی نہیں۔",
      daysNeedTime: "دن اور وقت ایک ساتھ منتخب کریں۔",
      fill: "نشستیں",
      moodleGroup: "Moodle گروپ",
      moodleLinked: "منسلک",
      moodleMissing: "منسلک نہیں",
      lastSynced: "آخری ہم آہنگی",
      neverSynced: "کبھی ہم آہنگ نہیں ہوا",
      tabOverview: "جائزہ",
      tabStudents: "طلبہ",
      tabSessions: "سیشنز",
      tabAttendance: "حاضری",
      tabGrades: "گریڈز",
      disable: "کلاس غیر فعال کریں",
      disableTitle: "یہ کلاس غیر فعال کریں؟",
      disableBody: "اب نئے طلبہ داخل نہیں ہوں گے۔ داخل طلبہ اور ریکارڈ برقرار رہیں گے۔",
      disabledToast: "کلاس غیر فعال ہو گئی۔",
      enable: "کلاس فعال کریں",
      enableTitle: "یہ کلاس فعال کریں؟",
      enableBody: "یہ دوبارہ طلبہ لے سکے گی۔",
      enabledToast: "کلاس فعال ہو گئی۔",
      moodleCreate: "Moodle گروپ بنائیں",
      moodleLink: "Moodle گروپ منسلک کریں",
      moodleTitle: "Moodle گروپ",
      moodleDescription: "Moodle کورس میں نیا گروپ بنائیں، یا موجودہ گروپ منسلک کریں۔",
      moodleSearch: "Moodle گروپس تلاش کریں",
      moodleBound: "Moodle گروپ منسلک ہو گیا۔",
      sync: "Moodle سے ہم آہنگ کریں",
      syncTitle: "Moodle ہم آہنگی",
      syncDone: "Moodle سے ہم آہنگ ہو گیا۔",
      syncPartial: "کچھ مسائل کے ساتھ ہم آہنگ ہوا۔",
      stepGroup: "گروپ",
      stepTeachers: "اساتذہ",
      stepStudents: "طلبہ",
      stepSessions: "حاضری کے سیشنز",
      stepGrades: "گریڈز",
      stepOk: "مکمل",
      stepError: "ناکام",
      students: "طلبہ",
      studentsEmpty: "اس کلاس میں ابھی کوئی طالب علم نہیں۔",
      addStudents: "ادائیگی کرنے والے طلبہ شامل کریں",
      addStudentsHint: "اس شاخ میں اس کورس کی ادا شدہ فروخت جو کلاس کی منتظر ہے۔",
      noWaiting: "یہاں اس کورس کی کوئی ادا شدہ فروخت منتظر نہیں۔",
      attachToast: "طالب علم کلاس میں شامل ہو گیا۔",
      noMoodleAccount: "کوئی Moodle اکاؤنٹ نہیں",
      readOnly: "آپ یہ کلاس دیکھ سکتے ہیں۔ تبدیلیاں شاخ کی ٹیم کرتی ہے۔"
    },
    sessions: {
      upcoming: "آنے والے",
      past: "گزشتہ",
      cancelled: "منسوخ",
      empty: "ابھی کوئی سیشن نہیں۔",
      emptyHint: "استاد اور کمرے کی دستیابی سے سیشنز کی منصوبہ بندی کریں۔",
      plan: "سیشنز کی منصوبہ بندی",
      planTitle: "سیشنز کی منصوبہ بندی",
      planDescription: "ہر ہفتے کے دن کے لیے گھنٹے درج کریں۔ EMS سب سے پہلا وقت تلاش کرتا ہے جب استاد اور کمرہ دونوں خالی ہوں۔",
      weekday: "دن",
      hours: "گھنٹے",
      addDay: "دن شامل کریں",
      removeDay: "دن ہٹائیں",
      fromDate: "سے",
      toDate: "تک",
      findTimes: "اوقات تلاش کریں",
      proposed: "تجویز کردہ اوقات",
      noMatch: "کوئی وقت ہر دن کے لیے موزوں نہیں۔ استاد یا کمرے کے اوقات خالی کریں، یا دن تبدیل کریں۔",
      book: "یہ سیشنز بک کریں",
      bookedToast: "سیشنز بک ہو گئے۔",
      reschedule: "وقت تبدیل کریں",
      rescheduleTitle: "سیشن کا وقت تبدیل کریں",
      rescheduleDescription: "نیا آغاز منتخب کریں۔ یہ استاد اور کمرے کی دستیابی کے مطابق ہونا چاہیے۔",
      movedToast: "سیشن منتقل ہو گیا۔",
      cancel: "سیشن منسوخ کریں",
      cancelTitle: "یہ سیشن منسوخ کریں؟",
      cancelBody: "یہ طلبہ اور استاد کے شیڈول سے ہٹ جائے گا۔",
      cancelledToast: "سیشن منسوخ ہو گیا۔",
      length: "دورانیہ",
      room: "کمرہ",
      teacher: "استاد",
      online: "آن لائن",
      today: "آج",
      dayRequired: "کم از کم ایک دن شامل کریں۔",
      dayTwice: "ہر دن صرف ایک بار آ سکتا ہے۔",
      rangeInvalid: "اختتامی تاریخ آغاز کی تاریخ یا اس کے بعد ہونی چاہیے۔",
      pastLocked: "گزشتہ سیشنز تبدیل نہیں ہو سکتے۔",
      attendance: "حاضری"
    },
    week: {
      title: "میرا ہفتہ",
      description: "اس ہفتے کے آپ کے سیشنز، ہر ایک کے بعد حاضری لگانی ہے۔",
      thisWeek: "یہ ہفتہ",
      previous: "پچھلا ہفتہ",
      next: "اگلا ہفتہ",
      sessions: "سیشنز",
      hours: "گھنٹے",
      needAttendance: "حاضری باقی",
      empty: "اس ہفتے کوئی سیشن نہیں۔",
      noMoodle: "ابھی Moodle سیشن نہیں",
      dayOff: "خالی"
    },
    attendance: {
      empty: "ابھی Moodle میں حاضری کے سیشنز نہیں۔",
      emptyHint: "شیڈول سے انہیں بنانے کے لیے کلاس کو Moodle سے ہم آہنگ کریں۔",
      take: "حاضری لگائیں",
      sheetTitle: "حاضری",
      sheetEmpty: "اس سیشن میں ابھی کوئی طالب علم نہیں۔",
      markAll: "سب کو حاضر نشان زد کریں",
      save: "حاضری محفوظ کریں",
      savedToast: "حاضری محفوظ ہو گئی۔",
      notTaken: "نہیں لگی",
      taken: "لگ گئی",
      notMarked: "نشان زد نہیں",
      marked: "نشان زد",
      of: "/",
      needsActivity: "پہلے کورس کی Moodle حاضری سرگرمی درج کریں۔"
    },
    grades: {
      empty: "ابھی Moodle میں کوئی گریڈ نہیں۔",
      student: "طالب علم",
      courseGrade: "کورس گریڈ"
    },
    rooms: {
      title: "کمرے",
      description: "ہر شاخ کے کمرے، ان کی نشستیں اور بکنگ کے اوقات۔",
      add: "کمرہ شامل کریں",
      createTitle: "کمرہ شامل کریں",
      editTitle: "کمرے میں ترمیم کریں",
      createDescription: "کمرے کا نام اور اس میں بیٹھنے کی گنجائش درج کریں۔",
      name: "کمرے کا نام",
      capacity: "نشستیں",
      createSubmit: "کمرہ بنائیں",
      createdToast: "کمرہ بن گیا۔",
      updatedToast: "کمرہ اپ ڈیٹ ہو گیا۔",
      empty: "کوئی کمرہ نہیں ملا۔",
      emptyHint: "کمرہ شامل کریں تاکہ کلاسیں اور ٹیسٹ بک ہو سکیں۔",
      disable: "کمرہ غیر فعال کریں",
      disableTitle: "یہ کمرہ غیر فعال کریں؟",
      disableBody: "اب اسے بک نہیں کیا جا سکے گا۔ پچھلی بکنگز برقرار رہیں گی۔",
      disabledToast: "کمرہ غیر فعال ہو گیا۔",
      enable: "کمرہ فعال کریں",
      enableTitle: "یہ کمرہ فعال کریں؟",
      enableBody: "اسے دوبارہ بک کیا جا سکے گا۔",
      enabledToast: "کمرہ فعال ہو گیا۔",
      availability: "دستیابی",
      availabilityHint: "وہ اوقات نشان زد کریں جب یہ کمرہ بک ہو سکتا ہے۔ بک شدہ اوقات مقفل رہتے ہیں۔",
      availabilityToast: "دستیابی محفوظ ہو گئی۔",
      unlimited: "درج نہیں"
    }
  },
  forms: {
    title: "فارمز",
    description: "اپنے فارمز بنائیں، انہیں خاندانوں یا عملے کے ساتھ شیئر کریں اور ہر جواب پر کارروائی کریں۔",
    intro: "تعارف",
    yes: "ہاں",
    no: "نہیں",
    agreed: "متفق",
    form: "فارم",
    tabForms: "میرے فارمز",
    tabResponses: "جوابات",
    tabToFill: "پُر کرنا ہے",
    newForm: "نیا فارم",
    newTitle: "نیا فارم",
    newDescription: "خالی فارم یا ٹیمپلیٹ سے شروع کریں۔ شائع کرنے سے پہلے سب کچھ بدل سکتے ہیں۔",
    createSubmit: "فارم بنائیں",
    createdToast: "فارم بن گیا۔",
    titleEn: "عنوان (انگریزی)",
    titleAr: "عنوان (عربی)",
    category: "زمرہ",
    template: "یہاں سے شروع کریں",
    blank: "خالی فارم",
    branch: "شاخ",
    allBranchesForm: "ہر شاخ",
    empty: "ابھی کوئی فارم نہیں۔",
    emptyHint: "Jotform یا کاغذی فارم کی جگہ نیا فارم بنائیں۔",
    responsesEmpty: "ابھی کوئی جواب نہیں۔",
    toFillEmpty: "ابھی پُر کرنے کے لیے کچھ نہیں۔",
    toFillHint: "آپ کو یا آپ کے کردار کو تفویض کردہ فارمز یہاں دکھائی دیتے ہیں۔",
    status: {
      draft: "مسودہ",
      active: "شائع شدہ",
      retired: "ختم شدہ"
    },
    categories: {
      admissions: "داخلے",
      student_support: "طلبہ کی معاونت",
      attendance: "حاضری",
      consent: "رضامندی",
      branch_operations: "شاخ کے امور"
    },
    responseStatus: {
      submitted: "نیا",
      under_review: "زیرِ جائزہ",
      accepted: "قبول",
      rejected: "مسترد",
      promoted: "کارروائی ہو گئی",
      withdrawn: "واپس لیا گیا",
      quarantined: "روکا گیا"
    },
    responses: "جوابات",
    updated: "اپ ڈیٹ",
    live: "عوامی لنک",
    notLive: "شیئر نہیں ہوا",
    open: "کھولیں",
    fill: "پُر کریں",
    filled: "بھیجا گیا",
    due: "بند ہوتا ہے",
    tabBuild: "بنائیں",
    tabShare: "شیئر",
    tabResponses2: "جوابات",
    editDraft: "نیا ورژن ترمیم کریں",
    editingDraft: "مسودہ",
    publishedVersion: "شائع شدہ ورژن",
    version: "ورژن",
    save: "مسودہ محفوظ کریں",
    savedToast: "مسودہ محفوظ ہو گیا۔",
    unsaved: "غیر محفوظ تبدیلیاں",
    preview: "پیش منظر",
    hidePreview: "پیش منظر چھپائیں",
    page: "صفحہ",
    addPage: "صفحہ شامل کریں",
    removePage: "صفحہ ہٹائیں",
    addField: "سوال شامل کریں",
    question: "سوال",
    questionEn: "سوال (انگریزی)",
    questionAr: "سوال (عربی)",
    help: "مددگار متن",
    required: "لازمی",
    options: "اختیارات",
    addOption: "اختیار شامل کریں",
    optionEn: "اختیار (انگریزی)",
    optionAr: "اختیار (عربی)",
    moveUp: "اوپر کریں",
    moveDown: "نیچے کریں",
    remove: "ہٹائیں",
    duplicate: "نقل بنائیں",
    logicNote: "اس فارم میں مشروط اصول ہیں۔ محفوظ کرنے پر وہ برقرار رہتے ہیں۔",
    usedByLogic: "ایک اصول یہ سوال استعمال کرتا ہے۔ پہلے اصول ہٹائیں۔",
    readOnlyVersion: "یہ ورژن شائع ہو چکا ہے اور تبدیل نہیں ہو سکتا۔ ترمیم کے لیے نیا ورژن شروع کریں۔",
    problems: "محفوظ کرنے سے پہلے یہ درست کریں:",
    problemLabel: "ایک سوال میں انگریزی متن نہیں ہے۔",
    problemArabic: "ہر سوال اور اختیار کو عربی متن بھی چاہیے۔",
    recordLinkNote: "یہ سوال پرانے ریکارڈز سے منسلک ہے اور آپ کی شاخوں کے لیے کوئی اختیار نہیں دکھاتا۔",
    recordLinkBanner: "یہاں ایک سوال پرانے ریکارڈ لنکس استعمال کرتا ہے۔ شائع کرنے سے پہلے اسے کھول کر اپنی شاخوں کی فہرست پر منتقل کریں۔",
    useBranchList: "ہماری شاخوں کی فہرست استعمال کریں",
    needsAttention: "توجہ درکار",
    problemOptions: "انتخابی سوال کو کم از کم ایک اختیار چاہیے۔",
    problemEmpty: "کم از کم ایک سوال شامل کریں۔",
    types: {
      heading: "سرخی",
      instructions: "ہدایات",
      short_text: "مختصر جواب",
      long_text: "پیراگراف",
      email: "ای میل",
      phone: "فون",
      number: "عدد",
      date: "تاریخ",
      time: "وقت",
      single_choice: "ایک انتخاب",
      multiple_choice: "متعدد انتخاب",
      yes_no: "ہاں یا نہیں",
      rating: "درجہ بندی",
      consent: "رضامندی",
      entity_reference: "ریکارڈ لنک"
    },
    typeGroups: {
      text: "متن",
      choice: "انتخاب",
      value: "اعداد اور تاریخیں",
      layout: "ترتیب"
    },
    publish: "شائع کریں",
    publishTitle: "یہ ورژن شائع کریں",
    publishDescription: "منتخب کریں کہ کون جواب دے سکتا ہے۔ عوامی لنک اس وقت تک کام کرتا ہے جب تک آپ اسے ختم نہ کریں۔",
    publishSubmit: "شائع کریں",
    publishedToast: "فارم شائع ہو گیا۔",
    slug: "لنک کا نام",
    slugHint: "چھوٹے حروف، اعداد اور ڈیش۔",
    audience: "کون جواب دے سکتا ہے",
    audiencePublic: "لنک رکھنے والا کوئی بھی",
    audiencePublicHint: "خاندان اور مہمان، سائن ان کے بغیر۔",
    audienceAuthenticated: "سائن ان کیا ہوا کوئی بھی رکنِ عملہ",
    audienceAuthenticatedHint: "نائل سینٹر میں سائن ان کرنے والا ہر فرد۔",
    audienceAssigned: "صرف وہ لوگ جنہیں میں تفویض کروں",
    audienceAssignedHint: "اس کے بعد کردار، شاخیں، شعبے یا افراد منتخب کریں۔",
    opensAt: "کھلتا ہے",
    closesAt: "بند ہوتا ہے",
    allowMultiple: "ہر فرد کو ایک سے زیادہ جواب کی اجازت دیں",
    allowDrafts: "لوگوں کو محفوظ کر کے بعد میں مکمل کرنے دیں",
    publicationStatus: {
      scheduled: "طے شدہ",
      open: "کھلا",
      closed: "بند",
      retired: "ختم شدہ"
    },
    publications: "لنکس",
    noPublications: "یہ فارم ابھی شیئر نہیں ہوا۔",
    copyLink: "لنک کاپی کریں",
    copied: "لنک کاپی ہو گیا۔",
    openLink: "کھولیں",
    retire: "لنک ختم کریں",
    retireTitle: "یہ لنک ختم کریں؟",
    retireBody: "اس کے ذریعے مزید جواب نہیں دیے جا سکیں گے۔ جوابات برقرار رہیں گے۔",
    retiredToast: "لنک ختم ہو گیا۔",
    assignments: "تفویض کردہ",
    noAssignments: "ابھی کسی کو تفویض نہیں کیا گیا۔",
    assign: "تفویض کریں",
    assignTitle: "یہ فارم تفویض کریں",
    assignDescription: "منتخب کریں کہ یہ فارم کون پُر کرے۔ انہیں یہ \"پُر کرنا ہے\" میں ملے گا۔",
    assignedToast: "فارم تفویض ہو گیا۔",
    target: "تفویض کریں",
    targetRole: "کردار",
    targetBranch: "شاخ",
    targetDepartment: "شعبہ",
    targetPeople: "افراد",
    peopleModeStaff: "رکنِ عملہ",
    peopleModeClass: "کسی کلاس کے اساتذہ",
    peopleClass: "کلاس",
    staffSearch: "نام یا ای میل سے عملہ تلاش کریں…",
    noStaffFound: "کوئی رکنِ عملہ نہیں ملا۔",
    classNoTeachers: "اس کلاس میں ابھی کوئی استاد نہیں۔",
    peopleSelected: "{n} منتخب",
    assignToOne: "1 فرد کو تفویض کریں",
    assignToMany: "{n} افراد کو تفویض کریں",
    publishBlockedRecordLinks: "شائع کرنے سے پہلے \"بنائیں\" میں نمایاں سوال درست کریں۔",
    assignedPeopleToast: "{n} تفویض ہو گئے۔",
    assignFailures: "تفویض نہیں ہو سکا:",
    personFallback: "رکنِ عملہ",
    revoke: "ہٹائیں",
    revokedToast: "تفویض ہٹا دی گئی۔",
    expires: "تک",
    respondent: "سے",
    anonymous: "عوامی لنک",
    submitted: "بھیجا گیا",
    answers: "جوابات",
    noAnswer: "کوئی جواب نہیں",
    review: "فیصلہ",
    accept: "قبول کریں",
    reject: "مسترد کریں",
    startReview: "زیرِ جائزہ نشان زد کریں",
    comment: "نوٹ",
    reviewedToast: "فیصلہ محفوظ ہو گیا۔",
    history: "تاریخچہ",
    createLead: "امیدوار بنائیں",
    createLeadHint: "اس پوچھ گچھ کو داخلوں میں امیدوار بنائیں، جوابات خود بخود بھر جائیں گے۔",
    leadCreated: "امیدوار بن گیا",
    openLead: "امیدوار کھولیں",
    export: "CSV برآمد کریں",
    exportedToast: "برآمد تیار ہے۔",
    allForms: "تمام فارمز",
    allStatuses: "تمام حیثیتیں",
    import: "Jotform سے درآمد کریں",
    backToForms: "فارمز پر واپس جائیں",
    importer: {
      title: "Jotform سے درآمد کریں",
      description: "Jotform کے پرانے جوابات اپنے فارمز میں لائیں، پہلے انہیں جانچیں، پھر ہر قطار کا ریکارڈ رکھیں۔",
      notConnected: "اس سرور پر Jotform منسلک نہیں، اس لیے اس کے فارمز کی فہرست نہیں بن سکتی۔ پہلے کی گئی درآمدات نیچے موجود ہیں۔",
      step1: "1. فارمز منتخب کریں",
      step2: "2. سوالات ملائیں",
      step3: "3. جانچیں، پھر درآمد کریں",
      source: "Jotform فارم",
      target: "اس فارم میں",
      noTargets: "پہلے ایک فارم شائع کریں؛ جوابات شائع شدہ فارم میں درآمد ہوتے ہیں۔",
      inspect: "سوالات ملائیں",
      field: "ہمارے فارم کا سوال",
      fromJotform: "Jotform کا سوال",
      skip: "درآمد نہ کریں",
      offset: "اس قطار سے شروع کریں",
      limit: "قطاریں",
      dryRun: "قطاریں جانچیں",
      total: "قطاریں",
      valid: "تیار",
      duplicates: "پہلے سے درآمد شدہ",
      errors: "مسائل کے ساتھ",
      sample: "پہلی قطاریں",
      commit: "تیار قطاریں درآمد کریں",
      importedToast: "درآمد مکمل ہو گئی۔",
      history: "پچھلی درآمدات",
      noHistory: "ابھی کوئی درآمد نہیں۔",
      imported: "درآمد شدہ",
      exceptions: "استثنا",
      matched: "ملا ہوا",
      markMatched: "ملا ہوا نشان زد کریں",
      markException: "استثنا نشان زد کریں",
      reconciledToast: "قطار اپ ڈیٹ ہو گئی۔",
      rowsNeedingReview: "جائزے کی منتظر قطاریں",
      submissions: "جوابات"
    },
    roles: {
      student: "طلبہ",
      teacher: "اساتذہ",
      registrar: "رجسٹرار اور مشیر",
      headofdepartment: "صدورِ شعبہ",
      branchadmin: "برانچ ایڈمن اور نائب مینیجر",
      superadmin: "سپر ایڈمنز"
    }
  },
  admissions: {
    money: {
      toBePaid: "کل",
      paid: "ادا شدہ",
      remaining: "باقی",
      settled: "مکمل ادا شدہ",
      paidTooHigh: "ادا شدہ رقم کل سے زیادہ نہیں ہو سکتی۔",
      invalidAmount: "صفر یا اس سے زیادہ عدد درج کریں۔"
    },
    mode: {
      label: "طریقۂ تعلیم",
      online: "آن لائن",
      onsite: "بالمشافہ",
      both: "آن لائن یا بالمشافہ",
      unknown: "منتخب نہیں",
      onlineBranch: "آن لائن شاخ",
      onsiteBranch: "بالمشافہ شاخ"
    },
    leads: {
      title: "امیدوار",
      description: "وہ لوگ جنہوں نے کورس کے بارے میں پوچھا، پہلے رابطے سے رجسٹریشن تک۔",
      add: "امیدوار شامل کریں",
      createTitle: "امیدوار شامل کریں",
      editTitle: "امیدوار میں ترمیم کریں",
      createDescription: "درج کریں کہ کس نے پوچھا، وہ کیا چاہتے ہیں اور ان سے کیسے رابطہ ہو۔",
      editDescription: "رابطے کی تفصیلات، دلچسپی یا ذمہ دار اپ ڈیٹ کریں۔",
      createSubmit: "امیدوار بنائیں",
      createdToast: "امیدوار بن گیا۔",
      updatedToast: "امیدوار اپ ڈیٹ ہو گیا۔",
      empty: "کوئی امیدوار نہیں ملا۔",
      emptyHint: "امیدوار شامل کریں یا فلٹر صاف کریں۔",
      noAccess: "امیدواروں کا انتظام داخلہ عملہ کرتا ہے۔",
      person: "فرد",
      stage: "مرحلہ",
      interest: "دلچسپی",
      owner: "ذمہ دار",
      group: "گروپ",
      added: "شامل کیا گیا",
      branch: "شاخ",
      anyMode: "کوئی بھی طریقۂ تعلیم",
      anyOwner: "کوئی بھی ذمہ دار",
      unassigned: "کوئی ذمہ دار نہیں",
      anyArea: "کوئی بھی شعبۂ تعلیم",
      anyType: "امیدوار کی کوئی بھی قسم",
      allBranches: "تمام شاخیں",
      firstName: "پہلا نام",
      lastName: "آخری نام",
      email: "ای میل",
      phone: "فون",
      wantsOnline: "آن لائن کلاسیں",
      wantsOnsite: "شاخ میں کلاسیں",
      preferredCourses: "پسندیدہ کورسز",
      anyCourse: "کوئی ترجیح نہیں",
      coursesNoun: "کورسز",
      areaOfStudy: "شعبۂ تعلیم",
      noArea: "کوئی شعبہ نہیں",
      source: "ذریعہ",
      sourceHint: "مثلاً: ویب سائٹ، براہِ راست آمد یا حوالہ۔",
      notes: "نوٹس",
      leadType: "امیدوار کی قسم",
      typeNew: "نیا",
      typeOld: "دوبارہ آنے والا امیدوار",
      typeOldStudent: "سابق طالب علم",
      typeCurrentStudent: "موجودہ طالب علم",
      required: "لازمی۔",
      invalidEmail: "درست ای میل پتہ درج کریں۔",
      chooseBranch: "شاخ منتخب کریں۔",
      journey: "سفر",
      nextStep: "اگلا قدم",
      stepContact: "پہلا رابطہ",
      stepPlacement: "لیول ٹیسٹ",
      stepTrial: "آزمائشی سبق",
      stepFee: "رجسٹریشن فیس",
      stepStudent: "طالب علم",
      stepDone: "مکمل",
      stepNow: "اب",
      stepSkipped: "چھوڑ دیا",
      stepLater: "ابھی نہیں",
      nextBookPlacement: "درست سطح جاننے کے لیے لیول ٹیسٹ بک کریں۔",
      nextRecordPlacement: "ٹیسٹ کے بعد نتیجہ درج کریں۔",
      nextBookTrial: "آزمائشی سبق بک کریں، یا رجسٹریشن فیس درج کریں۔",
      nextRecordTrial: "درج کریں کہ آزمائشی سبق کیسا رہا۔",
      nextFee: "رجسٹریشن فیس درج کریں۔",
      nextConvert: "فیس درج ہو گئی۔ طالب علم کا ریکارڈ بنائیں۔",
      nextStudent: "یہ امیدوار اب طالب علم ہے۔",
      nextLost: "یہ امیدوار کھویا ہوا قرار دے کر بند کر دیا گیا ہے۔",
      bookPlacement: "لیول ٹیسٹ بک کریں",
      bookTrial: "آزمائشی سبق بک کریں",
      recordFee: "رجسٹریشن فیس درج کریں",
      editFee: "فیس تبدیل کریں",
      convert: "طالب علم بنائیں",
      openStudent: "طالب علم کھولیں",
      markLost: "کھویا ہوا نشان زد کریں",
      reopen: "امیدوار دوبارہ کھولیں",
      lostTitle: "اس امیدوار کو کھویا ہوا نشان زد کریں؟",
      lostBody: "وجہ منتخب کریں۔ آپ بعد میں امیدوار دوبارہ کھول سکتے ہیں۔",
      lostReason: "کھونے کی وجہ",
      noLostReasons: "اس اکاؤنٹ کے لیے کوئی وجہ دستیاب نہیں۔ ایڈمنسٹریٹر انہیں \"امیدوار کھونے کی وجوہات\" میں شامل کر سکتا ہے۔",
      openLostReasons: "کھونے کی وجوہات کھولیں۔",
      lostToast: "امیدوار کھویا ہوا نشان زد ہو گیا۔",
      reopenToast: "امیدوار دوبارہ کھل گیا۔",
      lostBecause: "کھونے کی وجہ",
      details: "تفصیلات",
      placements: "لیول ٹیسٹ",
      trials: "آزمائشی اسباق",
      fee: "رجسٹریشن فیس",
      noPlacements: "ابھی کوئی لیول ٹیسٹ نہیں۔",
      noTrials: "ابھی کوئی آزمائشی سبق نہیں۔",
      noFee: "ابھی کوئی رجسٹریشن فیس نہیں۔",
      feeTitle: "رجسٹریشن فیس",
      feeDescription: "کل رقم اور اب تک ادا کی گئی رقم درج کریں۔",
      feeToast: "رجسٹریشن فیس محفوظ ہو گئی۔",
      groupMembers: "اس کے ساتھ گروپ میں",
      primaryContact: "بنیادی رابطہ",
      convertTitle: "طالب علم بنائیں",
      convertDescription: "EMS کو درکار شناختی تفصیلات شامل کریں۔ رابطے کی تفصیلات امیدوار سے آتی ہیں۔",
      convertToast: "طالب علم بن گیا۔"
    },
    booking: {
      placementTitle: "لیول ٹیسٹ بک کریں",
      trialTitle: "آزمائشی سبق بک کریں",
      editTitle: "بکنگ تبدیل کریں",
      when: "تاریخ اور وقت",
      hour: "آغاز کا وقت",
      onTheHour: "بکنگز پورے گھنٹے پر شروع ہوتی ہیں۔",
      timeZone: "ٹائم زون",
      room: "کمرہ",
      chooseRoom: "کمرہ منتخب کریں۔ بالمشافہ بکنگ کے لیے ضروری ہے۔",
      meetingRequired: "میٹنگ لنک شامل کریں۔",
      noRoom: "ابھی کوئی کمرہ نہیں",
      meetingLink: "میٹنگ لنک",
      meetingHint: "https لنک استعمال کریں۔ صرف آن لائن شاخیں لنک استعمال کرتی ہیں۔",
      meetingInvalid: "ایسا لنک استعمال کریں جو https:// سے شروع ہو",
      topic: "سبق کا موضوع",
      byCourse: "ایک کورس",
      byArea: "ایک شعبۂ تعلیم",
      course: "کورس",
      chooseCourse: "کورس منتخب کریں۔",
      chooseArea: "شعبۂ تعلیم منتخب کریں۔",
      placementCourseMissing: "اس شعبۂ تعلیم کا Moodle میں کوئی لیول کورس نہیں۔ سپر ایڈمن سے ایک منسلک کرنے کو کہیں۔",
      book: "بک کریں",
      saveChanges: "تبدیلیاں محفوظ کریں",
      bookedToast: "بکنگ محفوظ ہو گئی۔",
      updatedToast: "بکنگ اپ ڈیٹ ہو گئی۔",
      moodlePassword: "ٹیسٹ کے لیے Moodle پاس ورڈ",
      resultTitle: "نتیجہ درج کریں",
      resultDescription: "نتیجہ محفوظ کریں۔ بکنگ مکمل ہو کر بند ہو جائے گی۔",
      score: "اسکور یا سطح",
      scoreHint: "مثلاً: B1 یا 72۔",
      mentor: "رہنما استاد",
      noMentors: "اس شاخ میں کوئی استاد نہیں ملا۔",
      recommended: "تجویز کردہ کورس",
      noRecommendation: "کوئی تجویز نہیں",
      notes: "نوٹس",
      resultToast: "نتیجہ محفوظ ہو گیا۔",
      syncMoodle: "Moodle سے نتیجہ حاصل کریں",
      syncToast: "نتیجہ Moodle سے اپ ڈیٹ ہو گیا۔",
      fromMoodle: "Moodle سے",
      recordedBy: "درج کرنے والا",
      noShow: "غیر حاضر نشان زد کریں",
      noShowTitle: "غیر حاضر نشان زد کریں؟",
      noShowBody: "یہ فرد حاضر نہیں ہوا۔ آپ نیا وقت بک کر سکتے ہیں۔",
      noShowToast: "غیر حاضر نشان زد ہو گیا۔",
      cancel: "بکنگ منسوخ کریں",
      cancelTitle: "یہ بکنگ منسوخ کریں؟",
      cancelBody: "وجہ منتخب کریں۔ یہ وقت خالی ہو جائے گا۔",
      cancelToast: "بکنگ منسوخ ہو گئی۔",
      change: "تبدیل کریں",
      joinLink: "میٹنگ لنک کھولیں",
      result: "نتیجہ"
    },
    agenda: {
      placementsTitle: "لیول ٹیسٹ",
      placementsDescription: "آپ کے دائرے کے تمام لیول ٹیسٹ، دن کے حساب سے۔ انہیں امیدوار یا طالب علم کے صفحے سے بک کریں۔",
      trialsTitle: "آزمائشی اسباق",
      trialsDescription: "آپ کے دائرے کے تمام آزمائشی اسباق، دن کے حساب سے۔ انہیں امیدوار یا طالب علم کے صفحے سے بک کریں۔",
      upcoming: "آنے والے",
      needsResult: "نتیجہ باقی",
      completed: "مکمل",
      missed: "غیر حاضر",
      cancelled: "منسوخ",
      today: "آج",
      tomorrow: "کل",
      emptyUpcoming: "کچھ بک نہیں۔",
      emptyNeedsResult: "ہر پچھلی بکنگ کا نتیجہ درج ہے۔",
      emptyOther: "یہاں ابھی کچھ نہیں ہے۔",
      emptyHint: "امیدوار کے سفر کے صفحے سے بک کریں۔",
      subjectLead: "امیدوار",
      subjectStudent: "طالب علم",
      allBranches: "تمام شاخیں",
      branch: "شاخ"
    },
    students: {
      title: "طلبہ",
      description: "نائل سینٹر میں رجسٹرڈ ہر فرد، ان کے کورسز، بقایا اور Moodle رسائی۔",
      add: "طالب علم شامل کریں",
      createTitle: "طالب علم شامل کریں",
      editTitle: "طالب علم میں ترمیم کریں",
      createDescription: "ایسا طالب علم بنائیں جو امیدوار کے ذریعے نہیں آیا۔",
      editDescription: "رابطے کی تفصیلات، شناخت یا ذمہ دار اپ ڈیٹ کریں۔",
      createSubmit: "طالب علم بنائیں",
      createdToast: "طالب علم بن گیا۔",
      updatedToast: "طالب علم اپ ڈیٹ ہو گیا۔",
      empty: "کوئی طالب علم نہیں ملا۔",
      emptyHint: "طالب علم شامل کریں یا فلٹر صاف کریں۔",
      noAccess: "طلبہ کا انتظام داخلہ عملہ کرتا ہے۔",
      person: "فرد",
      branch: "اصل شاخ",
      owner: "ذمہ دار",
      moodle: "Moodle",
      moodleLinked: "منسلک",
      moodleMissing: "منسلک نہیں",
      registration: "رجسٹریشن فیس",
      noFee: "کوئی فیس نہیں",
      added: "شامل کیا گیا",
      note: "نوٹ",
      allBranches: "تمام شاخیں",
      contact: "رابطہ",
      identity: "شناخت",
      guardians: "سرپرست",
      noGuardians: "کوئی سرپرست درج نہیں۔",
      tabOverview: "جائزہ",
      tabCourses: "کورسز",
      tabLearning: "تعلیم",
      tabBookings: "لیول ٹیسٹ اور آزمائشی اسباق",
      tabReport: "رپورٹ",
      warnings: "EMS سے نوٹس",
      moodleCreate: "Moodle اکاؤنٹ بنائیں",
      moodleLink: "Moodle اکاؤنٹ منسلک کریں",
      moodleReset: "Moodle پاس ورڈ ری سیٹ کریں",
      moodlePassword: "Moodle پاس ورڈ",
      moodleToast: "Moodle اکاؤنٹ اپ ڈیٹ ہو گیا۔",
      moodleResetTitle: "Moodle پاس ورڈ ری سیٹ کریں؟",
      moodleResetBody: "EMS ایک نیا بے ترتیب پاس ورڈ سیٹ کرتا ہے۔ اسے طالب علم کے ساتھ ایک بار شیئر کریں۔",
      disable: "طالب علم غیر فعال کریں",
      disableTitle: "اس طالب علم کو غیر فعال کریں؟",
      disableBody: "نئے اندراجات نہیں ہو سکیں گے۔ ان کا ریکارڈ برقرار رہے گا۔",
      disabledToast: "طالب علم غیر فعال ہو گیا۔",
      enable: "طالب علم فعال کریں",
      enableTitle: "اس طالب علم کو فعال کریں؟",
      enableBody: "نئے اندراجات دوبارہ ہو سکیں گے۔",
      enabledToast: "طالب علم فعال ہو گیا۔",
      learningEmpty: "ابھی Moodle میں کوئی گریڈ نہیں۔",
      learningClass: "کلاس",
      learningGrade: "کورس گریڈ",
      learningCompletion: "تکمیل",
      learningDone: "مکمل",
      learningOngoing: "جاری",
      print: "رپورٹ پرنٹ کریں",
      reportTitle: "تعلیمی رپورٹ",
      reportGenerated: "تیار کی گئی",
      reportLearningError: "Moodle گریڈز ابھی دستیاب نہیں۔",
      fromLead: "امیدوار سے"
    },
    enrolments: {
      title: "اندراجات",
      description: "ادائیگی سے کلاس تک کورس کی فروخت۔ ادا شدہ فروخت کو خالی نشستوں والی کلاس میں شامل کریں۔",
      empty: "کوئی اندراج نہیں ملا۔",
      emptyHint: "طالب علم کے صفحے سے کورس فروخت کریں۔",
      noAccess: "اندراجات کا انتظام داخلہ عملہ کرتا ہے۔",
      waiting: "منتظر",
      sell: "کورس فروخت کریں",
      saleTitle: "کورس فروخت کریں",
      saleDescription: "کورس کی فروخت شروع کریں۔ ادائیگی بعد میں ہو سکتی ہے۔",
      saleToast: "کورس کی فروخت شروع ہو گئی۔",
      student: "طالب علم",
      findStudent: "طلبہ تلاش کریں",
      typeToSearch: "کم از کم دو حروف لکھیں۔",
      noStudents: "کوئی طالب علم نہیں ملا۔",
      course: "کورس",
      kind: "کلاس کی قسم",
      group: "گروپ",
      individual: "انفرادی",
      branch: "شاخ",
      class: "کلاس",
      balance: "بقایا",
      opened: "شروع کی گئی",
      noClass: "ابھی کوئی کلاس نہیں",
      nextLevel: "اگلی سطح",
      recordPayment: "ادائیگی درج کریں",
      paymentTitle: "ادائیگی درج کریں",
      paymentDescription: "کل رقم یا طالب علم کی اب تک کی ادائیگی اپ ڈیٹ کریں۔",
      paymentToast: "ادائیگی محفوظ ہو گئی۔",
      attach: "کلاس میں شامل کریں",
      attachTitle: "کسی کلاس میں شامل کریں",
      attachDescription: "اس شاخ میں اس کورس کی فعال کلاسیں۔ بھری ہوئی کلاسیں مزید طلبہ نہیں لیتیں۔",
      seatsLeft: "نشستیں باقی",
      full: "بھری ہوئی",
      noClasses: "اس شاخ میں ابھی اس کورس کی کوئی فعال کلاس نہیں۔",
      attachToast: "طالب علم کلاس میں شامل ہو گیا۔",
      moodleRequired: "کلاس میں شامل ہونے سے پہلے طالب علم کا Moodle اکاؤنٹ ضروری ہے۔",
      complete: "مکمل نشان زد کریں",
      completeTitle: "یہ اندراج مکمل نشان زد کریں؟",
      completeBody: "یہ اس وقت استعمال کریں جب طالب علم کورس مکمل کر لے۔",
      completeToast: "اندراج مکمل ہو گیا۔",
      leave: "چھوڑا ہوا نشان زد کریں",
      leaveTitle: "اگلی سطح کی اس فروخت کو چھوڑا ہوا نشان زد کریں؟",
      leaveBody: "منتخب کریں کہ طالب علم یہ سطح کیوں نہیں لے گا۔",
      leaveToast: "اندراج چھوڑا ہوا نشان زد ہو گیا۔",
      cancel: "فروخت منسوخ کریں",
      cancelTitle: "کورس کی یہ فروخت منسوخ کریں؟",
      cancelBody: "وجہ منتخب کریں۔ یہ واپس نہیں ہو سکتا۔",
      cancelToast: "کورس کی فروخت منسوخ ہو گئی۔",
      schedule: "نظام الاوقات",
      teachers: "اساتذہ"
    },
    identity: {
      nationality: "قومیت",
      nationalityHint: "تین حرفی کوڈ، مثلاً EGY۔",
      address: "پتہ",
      gender: "جنس",
      male: "مرد",
      female: "عورت",
      dateOfBirth: "تاریخِ پیدائش",
      nationalId: "قومی شناختی نمبر",
      nationalIdHint: "14 ہندسے۔ مصری شہریوں کے لیے لازمی۔",
      passport: "پاسپورٹ نمبر",
      guardian: "سرپرست",
      secondGuardian: "دوسرا سرپرست",
      guardianHint: "18 سال سے کم عمر طلبہ کے لیے کم از کم ایک سرپرست ضروری ہے۔",
      guardianName: "نام",
      guardianPhone: "فون",
      guardianEmail: "ای میل",
      relationship: "رشتہ",
      relationshipHint: "مثلاً: والدہ، والد یا چچا۔",
      addGuardian: "دوسرا سرپرست شامل کریں",
      removeGuardian: "ہٹائیں",
      invalidNationality: "تین حرفی کوڈ استعمال کریں۔",
      invalidNationalId: "14 ہندسے استعمال کریں۔",
      nationalIdRequired: "مصری شہریوں کے لیے لازمی۔",
      guardianRequired: "18 سال سے کم عمر طلبہ کے لیے سرپرست ضروری ہے۔",
      guardianIncomplete: "سرپرست کی ہر فیلڈ پُر کریں۔"
    }
  },
  dateOfBirth: {
    day: "دن",
    month: "مہینہ",
    year: "سال",
    monthPlaceholder: "مہینہ",
    clear: "تاریخ صاف کریں",
    hint: "مثلاً: 4 مارچ 2012۔",
    incompleteDate: "دن، مہینہ اور چار ہندسوں کا سال درج کریں۔",
    invalidDate: "یہ تاریخ موجود نہیں۔ دن اور مہینہ چیک کریں۔",
    futureDate: "تاریخِ پیدائش مستقبل کی نہیں ہو سکتی۔",
    tooEarly: "1900 یا اس کے بعد کا سال درج کریں۔",
    age: "{n} سال کی عمر"
  },
  datePicker: {
    placeholder: "تاریخ منتخب کریں",
    today: "آج",
    clear: "صاف کریں",
    previousMonth: "پچھلا مہینہ",
    nextMonth: "اگلا مہینہ",
    previousYear: "پچھلا سال",
    nextYear: "اگلا سال",
    chooseMonth: "مہینہ اور سال منتخب کریں",
    unavailable: "دستیاب نہیں",
    calendar: "کیلنڈر"
  },
  language: {
    label: "زبان"
  },
  reports: {
    title: "رپورٹس",
    description: "رپورٹ پڑھیں، پھر برآمد کریں۔ اعداد و شمار براہِ راست EMS سے آتے ہیں۔",
    report: "رپورٹ",
    tabs: {
      admissions: "داخلے",
      bookings: "بکنگز",
      enrolments: "اندراجات",
      classes: "کلاسیں"
    },
    period: "مدت",
    asOfToday: "آج تک",
    branch: "شاخ",
    allBranches: "تمام شاخیں",
    exportCsv: "CSV برآمد کریں",
    truncated: "EMS کی {total} قطاروں میں سے پہلی {n} دکھائی جا رہی ہیں۔",
    showAll: "تمام {n} دکھائیں",
    showLess: "کم دکھائیں",
    emptyTitle: "رپورٹ کے لیے کچھ نہیں",
    emptyAdmissions: "اس مدت میں کوئی امیدوار نہیں بنایا گیا۔",
    emptyBookings: "اس مدت میں کوئی لیول ٹیسٹ یا آزمائشی سبق طے نہیں ہوا۔",
    emptyEnrolments: "کوئی اندراج نہیں ملا۔",
    emptyClasses: "ابھی کوئی فعال کلاس نہیں۔",
    emptyPlacements: "اس مدت میں کوئی لیول ٹیسٹ نہیں۔",
    emptyTrialLessons: "اس مدت میں کوئی آزمائشی سبق نہیں۔",
    emptyTrialResults: "اس مدت میں آزمائشی اسباق کا کوئی نتیجہ درج نہیں ہوا۔",
    emptyScores: "اس مدت میں اسکور والے کوئی لیول ٹیسٹ نہیں۔",
    emptyLostReasons: "اس مدت میں کوئی امیدوار نہیں کھویا۔",
    emptyWeekdays: "کسی کلاس کے دن طے نہیں ہیں۔",
    changePeriod: "مدت تبدیل کریں",
    liveFootnote: "ہر عدد عملے کے API کے ذریعے EMS ڈیٹا سے براہِ راست نکالا جاتا ہے۔",
    footnoteAdmissions: "حیثیتیں منتخب مدت میں بنائے گئے امیدواروں کی آج کی حیثیتیں ہیں۔",
    footnoteBookings: "بکنگز ان کی طے شدہ تاریخ کے حساب سے گنی جاتی ہیں۔",
    footnoteEnrolments: "اندراجات داخلے یا منسوخی کی تاریخ کے حساب سے گنے جاتے ہیں۔ رقم EMS کے ریکارڈ کے مطابق بغیر کرنسی کے دکھائی جاتی ہے۔",
    footnoteClasses: "فعال کلاسوں کا اس لمحے کا جائزہ۔",
    newLeads: "نئے امیدوار",
    registered: "رجسٹرڈ",
    lost: "کھو گئے",
    open: "کھلے",
    conversion: "تبدیلی کی شرح",
    rate: "شرح",
    intake: "امیدواروں کی آمد",
    intakePerWeek: "ہر ہفتے نئے امیدوار",
    intakePerMonth: "ہر مہینے نئے امیدوار",
    funnel: "پوچھ گچھ سے رجسٹریشن تک",
    funnelDecided: "طے شدہ",
    bySource: "ذریعے کے حساب سے",
    byLostReason: "کھونے کی وجہ کے حساب سے",
    byOwner: "ذمہ دار کے حساب سے",
    byArea: "شعبۂ تعلیم کے حساب سے",
    byBranch: "شاخ کے حساب سے",
    studyMode: "طریقۂ تعلیم",
    leadType: "امیدوار کی قسم",
    noSource: "کوئی ذریعہ نہیں",
    noReason: "کوئی وجہ درج نہیں",
    noOwner: "کوئی ذمہ دار نہیں",
    notSet: "درج نہیں",
    modes: {
      online: "صرف آن لائن",
      onsite: "صرف بالمشافہ",
      both: "دونوں",
      unset: "منتخب نہیں"
    },
    leadTypes: {
      new: "نیا",
      old: "پرانا",
      old_student: "سابق طالب علم",
      current_student: "موجودہ طالب علم"
    },
    count: "تعداد",
    share: "حصہ",
    leads: "امیدوار",
    placementTests: "لیول ٹیسٹ",
    trialLessons: "آزمائشی اسباق",
    scheduled: "طے شدہ",
    completed: "مکمل",
    noShow: "غیر حاضر",
    cancelled: "منسوخ",
    showRate: "حاضری کی شرح",
    scoreSummary: "لیول ٹیسٹ کے اسکور",
    scoreAverage: "اوسط",
    scoreMin: "کم ترین",
    scoreMax: "بلند ترین",
    scoreBands: "اسکور کی تقسیم",
    trialResults: "آزمائشی اسباق کے نتائج",
    trialsByCourse: "کورس کے حساب سے آزمائشی اسباق",
    trialToRegistered: "مکمل آزمائشی اسباق جن کے بعد طالب علم بنے",
    trials: "آزمائشی",
    pipeline: "پائپ لائن",
    rightNow: "ابھی",
    inThisPeriod: "اس مدت میں",
    enrolledInPeriod: "مدت میں داخل",
    cancelledInPeriod: "مدت میں منسوخ",
    allTime: "تمام عرصہ",
    money: "رقم",
    billed: "بل کی گئی",
    collected: "وصول شدہ",
    outstanding: "واجب الادا",
    outstandingPending: "ابھی ادا کرنا باقی (ادائیگی کے منتظر)",
    collectionRate: "وصولی کی شرح",
    moneyNote: "رقوم EMS کے ریکارڈ کے مطابق ہیں، بغیر کرنسی کے۔",
    byCourse: "کورس کے حساب سے",
    byKind: "قسم کے حساب سے",
    kinds: {
      individual: "انفرادی",
      group: "گروپ"
    },
    activeClasses: "فعال کلاسیں",
    seatsTaken: "بھری ہوئی نشستیں",
    capacity: "گنجائش",
    fill: "بھرنے کی شرح",
    freeSeats: "خالی نشستیں",
    fillByCourse: "کورس کے حساب سے بھرنے کی شرح",
    fillByDepartment: "شعبے کے حساب سے بھرنے کی شرح",
    teacherLoad: "اساتذہ کا کام کا بوجھ",
    noTeacher: "کوئی استاد تفویض نہیں",
    endingSoon: "جلد ختم ہونے والی",
    endingSoonEmpty: "اگلے 30 دنوں میں کوئی کلاس ختم نہیں ہو رہی۔",
    daysLeft: "باقی دن",
    weekdayLoad: "ہفتے کے دن کے حساب سے کلاسیں",
    classes: "کلاسیں",
    students: "طلبہ",
    seats: "نشستیں",
    active: "فعال",
    pending: "زیرِ التوا",
    leftCancelled: "چھوڑ دیا / منسوخ",
    enrolled: "داخل",
    placements: "لیول ٹیسٹ",
    score: "اسکور",
    course: "کورس",
    department: "شعبہ",
    name: "نام",
    endDate: "اختتامی تاریخ",
    csv: {
      name: "نام",
      email: "ای میل",
      phone: "فون",
      branch: "شاخ",
      source: "ذریعہ",
      status: "حیثیت",
      lostReason: "کھونے کی وجہ",
      owner: "ذمہ دار",
      area: "شعبۂ تعلیم",
      studyMode: "طریقۂ تعلیم",
      created: "بنایا گیا",
      type: "قسم",
      person: "فرد",
      scheduled: "طے شدہ",
      result: "نتیجہ",
      courseOrArea: "کورس / شعبہ",
      recommended: "تجویز کردہ کورس",
      student: "طالب علم",
      course: "کورس",
      className: "کلاس",
      enrolled: "داخل",
      cancelled: "منسوخ",
      toBePaid: "قابلِ ادا",
      paid: "ادا شدہ",
      remaining: "باقی",
      department: "شعبہ",
      teachers: "اساتذہ",
      schedule: "نظام الاوقات",
      capacity: "گنجائش",
      taken: "بھری ہوئی",
      fill: "بھرنے کی شرح %",
      start: "آغاز",
      end: "اختتام"
    }
  }
};
