/**
 * Staff app copy. Glossary: Student, Lead, Enrolment, Class, Session, Branch,
 * Staff user, Sign in, Sign out. Write in active voice. Keep one instruction
 * per sentence and at most 20 words per string. Use one term per concept.
 *
 * This file is the English source. Every other language must match its keys
 * (see copy.ar.ts). Components read the live `copy` object, which i18n.ts
 * updates in place when the language changes.
 */
const en = {
  brand: {
    name: "Nile Center",
    product: "Education Management",
  },
  nav: {
    overview: "Home",
    dashboard: "Dashboard",
    reports: "Reports",
    forms: "Forms",
    notifications: "Notifications",
    admissions: "Admissions",
    students: "Students",
    leads: "Leads",
    enrolments: "Enrolments",
    placementTests: "Placement tests",
    trialLessons: "Trial lessons",
    delivery: "Teaching",
    courses: "Courses",
    classes: "Classes",
    sessions: "My week",
    rooms: "Rooms",
    organisation: "People and places",
    staffUsers: "Staff",
    branches: "Branches",
    departments: "Departments",
    setup: "Setup",
    lostReasons: "Lost reasons",
    actionReasons: "Action reasons",
    areasOfStudy: "Areas of study",
    customFields: "Custom fields",
    system: "System",
    moodleSite: "Moodle",
    systemHealth: "System health",
    auditLog: "Audit log",
    profile: "Profile",
  },
  roles: {
    super_admin: "Super Admin",
    branch_admin: "Branch Admin",
    vice_manager: "Vice Manager",
    hod: "Head of Department",
    registrar: "Registrar",
    ssa: "SSA",
    teacher: "Teacher",
  },
  shell: {
    backTo: "Back to {page}",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    staffNav: "Staff navigation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    displaySize: "Display size",
    displayStandard: "Standard",
    displayLarge: "Large",
    displayXLarge: "Extra large",
    workspace: "Workspace",
    chooseWorkspace: "Choose a branch",
    workspaceHint:
      "Your role works inside one branch at a time. Select where you want to work.",
    noWorkspaces: "No active branches are assigned to you yet.",
    notifications: "Notifications",
    markAllRead: "Mark all read",
    viewAll: "View all notifications",
    userMenu: "User menu",
    signOut: "Sign out",
    signOutEverywhere: "Sign out everywhere",
    roleView: "Role view",
    roleViewTitle: "Role view",
    roleViewBody:
      "See the app as a lower-privilege role. Limit data to selected branches, departments, or classes.",
    viewingAs: "Viewing as",
    ownRole: "your role",
    roleViewChanged: "Role view updated.",
    scopesApplied: "Scope applied.",
    roleViewEnded: "You are back in your own role.",
    returnToRole: "Return to my role",
    applyScopes: "Apply",
    viewAsRole: "View as role",
    editRoleView: "Edit",
    scopeBranches: "Branches",
    scopeBranch: "Branch",
    scopeDepartments: "Departments",
    scopeClasses: "Classes",
    allBranches: "All branches",
    allDepartments: "All departments",
    allClasses: "All classes",
    branchesNoun: "branches",
    departmentsNoun: "departments",
    classesNoun: "classes",
    searchBranches: "Search branches",
    searchDepartments: "Search departments",
    searchClasses: "Search classes",
    chooseWorkspaceOption: "Select a branch",
    noAccess: "No access",
    noAccessHint:
      "Your active role cannot open this page. Return to your dashboard.",
    backToDashboard: "Back to dashboard",
    checkingSession: "Checking session",
    signedInAs: "Signed in as",
    search: "Search or jump to",
    breadcrumb: "Breadcrumb",
    commandPages: "Pages",
    commandPeople: "Staff",
    commandActions: "Actions",
    commandEmpty: "No results.",
  },
  state: {
    loading: "Loading",
    notSet: "Not set",
    retry: "Retry",
    empty: "Nothing here yet.",
    error403: "You do not have access to this page.",
    error404: "This record no longer exists.",
    error409: "This change conflicts with a newer update. Reload and retry.",
    error422: "Check the highlighted fields and try again.",
    error429: "Too many requests. Wait a moment and try again.",
    error503: "This service is not active right now. Try again later.",
    errorNetwork: "The network connection failed. Check your connection.",
    errorGeneric: "The request failed. Try again.",
  },
  status: {
    active: "Active",
    disabled: "Disabled",
    invited: "Invited",
    canceled: "Cancelled",
    cancelled: "Cancelled",
    enrolled: "Enrolled",
    completed: "Completed",
    registered: "Registered",
    scheduled: "Scheduled",
    pending: "Pending",
    pending_payment: "Pending payment",
    pending_class: "Pending class",
    pending_group: "Pending group",
    in_process: "In process",
    follow_up: "Follow up",
    future_registration: "Future registration",
    trial_lesson: "Trial lesson",
    placement_test: "Placement test",
    left: "Left",
    lost: "Lost",
    no_show: "No show",
    healthy: "Healthy",
    degraded: "Degraded",
    unhealthy: "Unhealthy",
    ok: "OK",
    warning: "Warning",
    error: "Error",
    not_configured: "Not configured",
  },
  notifications: {
    title: "Notifications",
    description: "Your inbox only.",
    all: "All",
    unread: "Unread",
    empty: "You have no notifications.",
    markRead: "Mark read",
    markAllRead: "Mark all read",
    delete: "Delete",
    deleteAll: "Delete all",
    deleteAllTitle: "Delete all notifications?",
    deleteAllBody:
      "This permanently deletes your copies. Other staff keep theirs.",
    read: "Read",
    unreadBadge: "Unread",
    markedRead: "Notification marked as read.",
    allMarkedRead: "All notifications marked read.",
    deleted: "Notification deleted.",
    allDeleted: "All notifications deleted.",
    actionFailed: "The notification action failed. Try again.",
  },
  profile: {
    title: "Profile",
    description: "Manage your details, password, and active sessions.",
    details: "Your details",
    role: "Assigned role",
    email: "Email",
    name: "Name",
    nameNotSet: "Not set",
    phone: "Phone",
    unknownDevice: "Unknown device",
    password: "Password",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    changePassword: "Change password",
    passwordChanged: "Password changed.",
    passwordFailed: "The password change failed. Check your entries.",
    passwordsDiffer: "The new passwords do not match.",
    sessions: "Active sessions",
    sessionsHint: "Sign out a session you do not recognize.",
    thisSession: "This session",
    lastSeen: "Last seen",
    issued: "Signed in",
    signOutSession: "Sign out session",
    sessionRevoked: "Session signed out.",
    signOutEverywhere: "Sign out everywhere",
    signOutEverywhereTitle: "Sign out everywhere?",
    signOutEverywhereBody:
      "This signs you out on every device. You will need to sign in again.",
  },
  actions: {
    save: "Save",
    cancel: "Cancel",
    saving: "Saving",
    discardTitle: "Discard changes?",
    discardBody: "Your changes are not saved.",
    discard: "Discard",
    keepEditing: "Keep editing",
    search: "Search",
    filter: "Filter",
    columns: "Columns",
    selected: "selected",
    clearSelection: "Clear selection",
    previous: "Previous",
    next: "Next",
    pageOf: "of",
    create: "Create",
    edit: "Edit",
    rowActions: "Row actions",
    enable: "Enable",
    disable: "Disable",
    close: "Close",
    import: "Import",
    refresh: "Refresh",
    noReasons: "Add an action reason for this action first.",
    openActionReasons: "Open action reasons.",
    status: "Status",
    activeOnly: "Active only",
    selectAll: "Select all rows",
    selectRow: "Select row",
    pagination: "Pages",
  },
  catalog: {
    shared: {
      name: "Name",
      nameRequired: "Enter a name.",
      code: "Code",
      codeHint: "Lowercase letters, numbers, and underscores.",
      codePattern: "Use lowercase letters, numbers, and underscores only.",
      sortOrder: "Sort order",
      created: "Created",
      status: "Status",
      active: "Active",
      disabled: "Disabled",
      allStatuses: "All statuses",
      access: "Your access",
      accessManage: "Manage",
      accessView: "View",
      customFields: "Custom fields",
      customFieldsEmpty: "No custom fields apply to this record.",
      enableTitle: "Enable this record?",
      disableTitle: "Disable this record?",
      enableBody: "This record becomes available again.",
      createdToast: "Created.",
      updatedToast: "Changes saved.",
      enabledToast: "Enabled.",
      disabledToast: "Disabled.",
      saveChanges: "Save changes",
    },
    branches: {
      title: "Branches",
      description: "Sites where Nile Center operates.",
      empty: "No branches yet.",
      emptyHint: "Create the first branch.",
      add: "Add branch",
      createTitle: "Add branch",
      editTitle: "Edit branch",
      createDescription: "Create an active branch.",
      editDescription: "Update name, code, or settings.",
      createSubmit: "Create branch",
      timezone: "Timezone",
      online: "Online branch",
      onlineYes: "Online",
      onlineNo: "Onsite",
      searchBranches: "Search branches",
      disableBody:
        "The branch stops accepting new work. Sessions on it lose their workspace.",
      statisticsTitle: "Activity",
      detailMissing: "This branch no longer exists.",
      statActiveStudents: "Active students",
      statOpenLeads: "Open leads",
      statActiveClasses: "Active classes",
      statEnrolmentFill: "Seats filled",
      statEnrolmentCapacity: "Enrolment capacity",
      statPendingEnrolments: "Pending enrolments",
      statPlacements: "Scheduled placements",
      statTrials: "Scheduled trials",
      statStaff: "Staff",
      bulkDisable: "Disable selected",
      bulkEnable: "Enable selected",
      bulkDone: "Selection updated.",
    },
    departments: {
      title: "Departments",
      description: "Academic departments behind classes and courses.",
      empty: "No departments yet.",
      emptyHint: "Create the first department.",
      add: "Add department",
      createTitle: "Add department",
      editTitle: "Edit department",
      createSubmit: "Create department",
      disableBody: "The department is hidden from new work.",
    },
    lostReasons: {
      title: "Lost reasons",
      description: "Why a lead is marked lost.",
      empty: "No lost reasons yet.",
      emptyHint: "Create the first lost reason.",
      add: "Add lost reason",
      createTitle: "Add lost reason",
      editTitle: "Edit lost reason",
      createSubmit: "Create reason",
      disableBody: "The reason is hidden from new work.",
    },
    actionReasons: {
      title: "Action reasons",
      description: "Named reasons required by guarded actions.",
      empty: "No action reasons yet.",
      emptyHint: "Create or import the first reason.",
      add: "Add action reason",
      createTitle: "Add action reason",
      editTitle: "Edit action reason",
      createSubmit: "Create reason",
      disableBody: "The reason is hidden from new work.",
      kind: "Kind",
      allKinds: "All kinds",
      import: "Import CSV",
      importTitle: "Import action reasons",
      importDescription:
        "Paste CSV rows or choose a file. Preview them first, then import.",
      chooseFile: "Choose a CSV file",
      downloadTemplate: "Download template",
      orPaste: "Or paste CSV rows",
      importPreview: "Preview",
      importRowCount: "rows",
      rowError: "Error",
      rowErrorColumns: "Expected 6 columns.",
      rowErrorKind: "Unknown kind.",
      rowErrorName: "Name is required.",
      importEmpty: "Paste CSV rows to preview them.",
      importSubmit: "Import",
      importDone: "Import finished.",
      importCreated: "created",
      importUpdated: "updated",
      csvPlaceholder: "id,action,name,status,sort_order,created_at",
      kindLost: "Lost lead",
      kindLeft_enrolment: "Left enrolment",
      kindCancel_enrolment: "Cancel enrolment",
      kindCancel_placement_test: "Cancel placement test",
      kindCancel_trial_lesson: "Cancel trial lesson",
      kindDisable_student: "Disable student",
      kindDisable_course: "Disable course",
      kindDisable_class: "Disable class",
      kindDisable_branch: "Disable branch",
      kindDisable_department: "Disable department",
      kindDisable_room: "Disable room",
      kindDisable_staff: "Disable staff",
      kindDisable_area_of_study: "Disable area of study",
      kindDisable_custom_field: "Disable custom field",
    },
    areasOfStudy: {
      title: "Areas of study",
      description: "Subjects a student can be placed into.",
      empty: "No areas of study yet.",
      emptyHint: "Create the first area of study.",
      add: "Add area of study",
      createTitle: "Add area of study",
      editTitle: "Edit area of study",
      createSubmit: "Create area",
      disableBody: "The area is hidden from new placements.",
      placementCourses: "Placement test courses",
      placementCoursesHint:
        "Pick Moodle courses that hold the placement tests.",
      addCourse: "Add Moodle course",
      searchCourses: "Search Moodle courses",
      coursesEmpty: "No courses match.",
      coursesLoading: "Loading courses",
      coursesError: "Moodle courses are unavailable.",
    },
    customFields: {
      title: "Custom fields",
      description: "Extra fields on records across the app.",
      empty: "No custom fields yet.",
      emptyHint: "Create the first custom field.",
      add: "Add custom field",
      createTitle: "Add custom field",
      editTitle: "Edit custom field",
      createSubmit: "Create field",
      disableBody: "The field is hidden from forms.",
      entity: "Entity",
      allEntities: "All entities",
      fieldKey: "Field key",
      fieldKeyHint:
        "Lowercase identifier used in the data model. Cannot be changed later.",
      fieldType: "Type",
      required: "Required field",
      requiredYes: "Required",
      optional: "Optional",
      helpText: "Help text",
      options: "Options",
      optionsHint: "One option per line.",
      entityUser_profile: "Staff profile",
      entityStudent: "Student",
      entityLead: "Lead",
      entityBranch: "Branch",
      entityDepartment: "Department",
      entityClass: "Class",
      entityCourse: "Course",
      entityRoom: "Room",
    },
  },
  staffUsers: {
    title: "Staff",
    description:
      "Everyone who works at Nile Center, their role, where they work, and how they sign in.",
    add: "Add staff member",
    createTitle: "Add staff member",
    editTitle: "Edit staff member",
    createDescription: "Create a staff account with a role and scope.",
    editDescription: "Update role, profile, or scope.",
    createSubmit: "Create staff member",
    empty: "No staff users yet.",
    emptyHint: "Invite the first staff user.",
    noAccess: "Staff accounts are managed by Super Admin and Branch Admin.",
    person: "Person",
    email: "Email",
    role: "Role",
    worksAt: "Works at",
    branches: "Branches",
    departments: "Departments",
    courses: "Courses",
    moodle: "Moodle",
    status: "Status",
    lastSignIn: "Last sign-in",
    added: "Added",
    you: "You",
    all: "All",
    results: "Results",
    clearFilters: "Clear filters",
    teachersNoMoodle: "Teachers without Moodle",
    allRoles: "All roles",
    allBranches: "All branches",
    allDepartments: "All departments",
    globalScope: "All branches",
    branchScope: "Branch scope",
    branchScopeHint:
      "Vice Manager needs exactly one branch. Registrar, SSA, and Teacher need at least one.",
    workspaceScopeHint: "New accounts must include your workspace branch.",
    invited: "Invited",
    moodleLinked: "Linked",
    moodleMissing: "Not linked",
    provisioning: "Provisioning",
    provisioningInvitation: "Invitation link",
    provisioningManual: "Manual password",
    provisioningHint:
      "Invitation creates a one-time link. Manual creates a temporary password.",
    firstName: "First name",
    lastName: "Last name",
    phone: "Phone",
    address: "Address",
    nationality: "Nationality",
    nationalityHint: "Three-letter country code.",
    dateOfBirth: "Date of birth",
    notes: "Notes",
    canTakePlacementTest: "Can take placement tests",
    yourPassword: "Your password",
    yourPasswordHint:
      "This Super Admin change needs your own password to continue.",
    yourPasswordRequired: "Enter your own password to continue.",
    firstNameRequired: "First name is required.",
    lastNameRequired: "Last name is required.",
    emailRequired: "Enter a valid email address.",
    branchScopeRequired: "Select at least one branch.",
    viceManagerScope: "Vice Manager needs exactly one branch.",
    invite: "Invite",
    resendInvite: "Resend invitation",
    inviteTitle: "Send a new invitation?",
    inviteBody: "The previous invitation link stops working.",
    cancelInvite: "Cancel invitation",
    cancelInviteTitle: "Cancel this invitation?",
    cancelInviteBody: "The invitation link stops working immediately.",
    setPassword: "Set password",
    setPasswordTitle: "Set a new password?",
    setPasswordBody:
      "A temporary password is generated once. Share it through a secure channel.",
    moodleAccount: "Moodle account",
    moodleCreate: "Create Moodle account",
    moodleLink: "Link Moodle account",
    moodleReset: "Reset Moodle password",
    moodleResetTitle: "Reset the Moodle password?",
    moodleResetBody:
      "A new Moodle password is generated once. Share it through a secure channel.",
    moodleSearch: "Search Moodle accounts",
    moodleSearchHint: "Search by name, username, or email.",
    moodleSearchMin: "Type at least 2 characters.",
    moodleSearchEmpty: "No Moodle accounts match.",
    moodleCreateHint: "Creates a Moodle account linked to this staff user.",
    moodleLinkHint: "Link an existing Moodle account to this staff user.",
    disableTitle: "Disable this staff user?",
    disableBody: "The account can no longer sign in.",
    enableTitle: "Enable this staff user?",
    enableBody: "The account can sign in again.",
    bulkDisable: "Disable selected",
    bulkEnable: "Enable selected",
    bulkDone: "Selection updated.",
    createdToast: "Staff user created.",
    updatedToast: "Changes saved.",
    invitedToast: "Invitation created.",
    cancelledToast: "Invitation cancelled.",
    passwordToast: "Password reset.",
    moodleToast: "Moodle account updated.",
    disabledToast: "Staff user disabled.",
    enabledToast: "Staff user enabled.",
    secretTitle: "One-time credentials",
    secretBody: "Copy these now. They are not shown again.",
    secretShare: "Share credentials through a secure channel only.",
    secretDone: "Done",
    copyValue: "Copy",
    copied: "Copied.",
    invitationLink: "Invitation link",
    temporaryPassword: "Temporary password",
    moodlePassword: "Moodle password",
    moreActions: "More actions",
    copyEmail: "Copy email",
    emailCopied: "Email copied.",
    tabOverview: "Overview",
    tabCourses: "Courses",
    tabAvailability: "Availability",
    tabActivity: "Activity",
    sectionContact: "Contact",
    sectionAccess: "Access",
    sectionMore: "More details",
    neverSignedIn: "Never signed in",
    statsAdmissions: "Admissions",
    statsTeaching: "Teaching",
    statLeadsCreated: "Leads created",
    statLeadsAssigned: "Leads assigned",
    statLeadsOpen: "Open leads",
    statLeadsRegistered: "Registered",
    statLeadsLost: "Lost",
    statStudentsAssigned: "Students assigned",
    statClassesTeaching: "Classes teaching",
    statSessionsScheduled: "Sessions scheduled",
    statStudentsTaught: "Students taught",
    statsEmpty: "No activity recorded yet.",
    coursesTitle: "Teachable courses",
    coursesHint:
      "An empty list means this teacher cannot be assigned to a class.",
    coursesSaved: "Courses updated.",
    coursesSearchPlaceholder: "Search courses",
    placementCapability: "Placement tests",
    placementYes: "Can take placement tests",
    placementNo: "Cannot take placement tests",
    availabilityTitle: "Availability",
    availabilityHint:
      "Paint the hours this teacher works. Booked sessions cannot be changed.",
    penAvailable: "Available",
    penUnavailable: "Unavailable",
    penClear: "Clear",
    showAllHours: "Show all hours",
    showWorkHours: "Show working hours",
    timezoneLabel: "Timezone",
    unsavedBar: "You have unsaved changes.",
    saveChanges: "Save changes",
    discardChanges: "Discard",
    discardTitle: "Discard availability changes?",
    discardBody: "Your painted changes are not saved.",
    cellsSaved: "Availability saved.",
    cellsSkippedBooked: "Booked sessions were skipped.",
    weekToday: "Today",
    weekPrevious: "Previous week",
    weekNext: "Next week",
    bookedSession: "Booked",
  },
  moodleSite: {
    title: "Moodle site",
    description:
      "Connect the Moodle site that backs courses, groups, and attendance.",
    noAccess: "Only Super Admin can configure the Moodle site.",
    connection: "Connection",
    connectionHint:
      "Web service credentials for the Moodle instance. The token is write-only.",
    siteUrl: "Site URL",
    token: "Web service token",
    tokenHint: "Stored securely. Re-enter it only to rotate the token.",
    tokenKeep: "Leave blank to keep the current token.",
    autoCreate: "Auto-create student Moodle accounts",
    autoCreateHint:
      "When on, creating a student also tries Moodle create.",
    ptCourse: "Placement-test Moodle course id",
    ptCourseHint:
      "Moodle course that hosts the placement test. Leave blank to clear.",
    save: "Save changes",
    connect: "Connect Moodle",
    test: "Test connection",
    disconnect: "Disconnect",
    disconnectTitle: "Disconnect Moodle?",
    disconnectBody:
      "The stored token is removed. Courses and groups stop syncing until reconnected.",
    saved: "Moodle configuration saved.",
    disconnected: "Moodle disconnected.",
    testOk: "Connection test succeeded.",
    testVersionWarn:
      "Reachable, but the Moodle version is outside the expected 4.5.x range.",
    testFailed: "Moodle is not reachable.",
    statusTitle: "Status",
    statConfigured: "Configured",
    statToken: "Token stored",
    statReachable: "Reachable",
    statVersion: "Version expected",
    statSitename: "Site name",
    statRelease: "Release",
    statLastChecked: "Last checked",
    statWarnings: "Warnings",
    statLastError: "Last error",
    unknown: "Unknown",
    yes: "Yes",
    no: "No",
  },
  system: {
    title: "System health",
    description: "Live status of core services and the Moodle integration.",
    noAccess: "Only Super Admin can view system health.",
    refresh: "Refresh",
    checked: "Checked",
    componentApi: "API",
    componentDatabase: "Database",
    componentSchema: "Schema check",
    componentMigration: "Migrations",
    componentMoodle: "Moodle",
    operational: "Operational.",
    version: "Version",
    configured: "Configured",
    token: "Token",
    reachable: "Reachable",
    site: "Site",
    release: "Release",
    expected: "Expected 4.5.x",
    warnings: "Warnings",
  },
  audit: {
    title: "Audit log",
    description: "Who did what, and when. Newest first.",
    noAccess: "Only Super Admin and Branch Admin can read audit events.",
    stream: "Stream",
    allStreams: "All streams",
    search: "Search events",
    empty: "No audit events.",
    emptyHint: "Actions are recorded here as they happen.",
    payload: "Payload",
    actor: "Actor",
    system: "System",
    today: "Today",
    yesterday: "Yesterday",
    latest: "Latest {n} events",
    failedSignIn: "Someone",
    groups: {
      all: "All",
      auth: "Sign-ins",
      admissions: "Admissions",
      teaching: "Teaching",
      setup: "Setup",
    },
    nouns: {
      auth: "account",
      branch: "branch",
      department: "department",
      course: "course",
      custom_field: "custom field",
      moodle_site: "Moodle connection",
      student: "student",
      lead: "lead",
      placement_test: "placement test",
      class: "class",
      enrolment: "enrolment",
      room: "room",
      session: "session",
    },
    verbs: {
      created: "created {noun}",
      updated: "updated {noun}",
      disabled: "disabled {noun}",
      enabled: "enabled {noun}",
      cancelled: "cancelled {noun}",
      completed: "completed {noun}",
      refreshed: "refreshed {noun}",
      tested: "tested the {noun}",
      other: "{action} on {noun}",
    },
    actions: {
      login_success: "signed in",
      login_failed: "failed to sign in",
      logout: "signed out",
      workspace_switched: "switched branch",
      role_switched: "changed role view",
      invitation_sent: "sent an invitation to",
      invitation_accepted: "accepted the invitation",
      user_created: "created the staff account",
      moodle_group_created: "created the Moodle group for",
      moodle_group_deleted: "removed the Moodle group for",
      moodle_group_synced: "synced with Moodle:",
      moodle_linked: "linked a Moodle account for",
      converted: "converted to a student:",
      enrolled: "enrolled a student",
    },
    streams: {
      auth: "Sign in",
      branch: "Branch",
      department: "Department",
      course: "Course",
      custom_field: "Custom field",
      moodle_site: "Moodle site",
      student: "Student",
      lead: "Lead",
      placement_test: "Placement test",
      class: "Class",
      enrolment: "Enrolment",
      room: "Room",
      session: "Session",
    },
  },
  dashboard: {
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening",
    nameSeparator: ", ",
    intro: "Here is what needs you today.",
    openLeads: "Open leads",
    openLeadsNote: "Not registered or lost yet",
    bookings: "Bookings ahead",
    tests: "tests",
    trials: "trials",
    waitingSales: "Waiting sales",
    waitingSalesNote: "Payment or class still missing",
    classFill: "Class fill",
    seatsOf: "of",
    seats: "seats taken",
    activeStudents: "Active students",
    activeStudentsNote: "With an active record",
    today: "Today",
    todayEmpty: "Nothing booked for today.",
    overdue: "past bookings need a result",
    openAgenda: "Open agenda",
    attention: "Needs attention",
    allClear: "All clear",
    resultsToRecord: "Results to record",
    unpaid: "Unpaid course sales",
    waitingClass: "Paid, waiting for a class",
    unowned: "Open leads without an owner",
    formResponses: "New form responses",
    period: "Period",
    periods: {
      "7d": "7 days",
      "30d": "30 days",
      "90d": "90 days",
      "12m": "12 months",
      all: "All time",
    },
    vsPrevious: "vs previous",
    noChange: "No change",
    pts: " pts",
    newLeads: "New leads",
    conversion: "Conversion",
    conversionNote: "Registered out of decided leads",
    intake: "Lead intake",
    intakeNote: "New leads per week",
    weekOf: "Week of",
    outcomes: "Lead outcomes",
    open: "Open",
    registered: "Registered",
    lost: "Lost",
    noData: "No leads in this period.",
    funnel: "From enquiry to student",
    funnelLeads: "Leads",
    funnelBooked: "Tests and trials done",
    bookingsTitle: "Tests and trials",
    placementTests: "Placement tests",
    trialLessons: "Trial lessons",
    completed: "Completed",
    scheduledLabel: "Scheduled",
    noShow: "No show",
    cancelled: "Cancelled",
    showRate: "showed up",
    pipeline: "Lead pipeline",
    pipelineEmpty: "No open leads.",
    branches: "Branches",
    branch: "Branch",
    students: "Students",
    classes: "Classes",
    fill: "Fill",
    waiting: "Waiting",
    placement: "Placement test",
    trial: "Trial lesson",
    myClasses: "My classes",
    myStudents: "Students in my classes",
    nextSession: "Next session",
    noNextSession: "No session booked",
    sessions: "Upcoming sessions",
    sessionsEmpty: "No sessions booked yet.",
    classesEmpty: "No classes assigned to you yet.",
    openMoodle: "Open in Moodle",
    departmentClasses: "Department classes",
    seatsFree: "Free seats",
    noTeacher: "Classes without a teacher",
    departmentEmpty: "No classes in your departments yet.",
    teachers: "Teachers",
    schedule: "Schedule",
    unassignedTeacher: "No teacher",
    enrolled: "enrolled",
    loadError: "Some numbers could not load.",
  },
  teaching: {
    hourUnit: "h",
    seats: "seats",
    seatsLeft: "left",
    full: "Full",
    allBranches: "All branches",
    branch: "Branch",
    required: "Required.",
    wholeNumber: "Use a whole number above zero.",
    openMoodle: "Open in Moodle",
    courses: {
      title: "Courses",
      description: "Courses linked from Moodle, with their hours, department, and live demand.",
      empty: "No courses match.",
      emptyHint: "Link a Moodle course to start selling it.",
      course: "Course",
      department: "Department",
      allDepartments: "All departments",
      area: "Area of study",
      noArea: "No area",
      hours: "Hours",
      totalHours: "Total teaching hours",
      moodle: "Moodle",
      moodleVisible: "Visible",
      moodleHidden: "Hidden",
      moodleChecked: "Moodle checked",
      refreshError: "Moodle refresh failed",
      refreshAll: "Refresh from Moodle",
      refreshAllToast: "Courses refreshed from Moodle.",
      refreshOne: "Refresh from Moodle",
      refreshOneToast: "Course refreshed from Moodle.",
      link: "Link Moodle course",
      linkTitle: "Link a Moodle course",
      linkDescription:
        "Courses come from Moodle. Pick one that is not linked yet and set its teaching hours.",
      linkSubmit: "Link course",
      linkToast: "Course linked.",
      editTitle: "Edit course",
      editDescription: "Department, hours, area of study, and which course comes before it.",
      editToast: "Course updated.",
      chooseMoodle: "Choose a Moodle course.",
      noUnmapped: "Every Moodle course is already linked.",
      searchMoodle: "Search Moodle courses",
      previous: "Comes after",
      noPrevious: "No previous course",
      attendanceId: "Moodle attendance activity",
      attendanceHint: "Needed for taking attendance. It is the attendance activity ID in the Moodle course.",
      noAttendance: "Not set, so attendance cannot be taken.",
      disable: "Disable course",
      disableTitle: "Disable this course?",
      disableBody: "It can no longer be sold or get new classes. Existing classes stay.",
      disabledToast: "Course disabled.",
      enable: "Enable course",
      enableTitle: "Enable this course?",
      enableBody: "It can be sold and get new classes again.",
      enabledToast: "Course enabled.",
      demand: "Demand now",
      activeClasses: "Active classes",
      seatsTaken: "Seats taken",
      waitingSales: "Waiting sales",
      interestedLeads: "Interested leads",
      classes: "Classes",
      noClasses: "No classes for this course yet.",
      writeNote: "Only Super Admin changes courses.",
    },
    classes: {
      title: "Classes",
      description: "Every class with its teachers, usual time, seats, and Moodle group.",
      empty: "No classes match.",
      emptyHint: "Create a class for an active course.",
      add: "Add class",
      createTitle: "Add class",
      editTitle: "Edit class",
      createDescription: "Course, dates, seats, teachers, and the usual weekly time.",
      editDescription: "Dates, seats, teachers, usual time, and meeting link.",
      createSubmit: "Create class",
      createdToast: "Class created.",
      updatedToast: "Class updated.",
      name: "Class name",
      course: "Course",
      allCourses: "All courses",
      kind: "Class type",
      group: "Group",
      individual: "One to one",
      capacity: "Seats",
      starts: "Starts",
      ends: "Ends",
      dates: "Dates",
      teachers: "Teachers",
      noTeachers: "No teachers found for this branch yet.",
      noTeacher: "No teacher",
      usualDays: "Usual days",
      from: "From",
      to: "To",
      usualTime: "Usual time",
      noSchedule: "No usual time",
      meetingLink: "Meeting link",
      meetingHint: "For online classes. Use an https link.",
      meetingInvalid: "Use a link that starts with https://",
      endBeforeStart: "The end date must be after the start date.",
      timeOrder: "The end time must be after the start time.",
      timeBoth: "Set both times, or neither.",
      daysNeedTime: "Pick the days and the time together.",
      fill: "Seats",
      moodleGroup: "Moodle group",
      moodleLinked: "Linked",
      moodleMissing: "Not linked",
      lastSynced: "Last synced",
      neverSynced: "Never synced",
      tabOverview: "Overview",
      tabStudents: "Students",
      tabSessions: "Sessions",
      tabAttendance: "Attendance",
      tabGrades: "Grades",
      disable: "Disable class",
      disableTitle: "Disable this class?",
      disableBody: "It takes no new students. Enrolled students and history stay.",
      disabledToast: "Class disabled.",
      enable: "Enable class",
      enableTitle: "Enable this class?",
      enableBody: "It can take students again.",
      enabledToast: "Class enabled.",
      moodleCreate: "Create Moodle group",
      moodleLink: "Link Moodle group",
      moodleTitle: "Moodle group",
      moodleDescription: "Create a new group in the Moodle course, or link one that already exists.",
      moodleSearch: "Search Moodle groups",
      moodleBound: "Moodle group linked.",
      sync: "Sync with Moodle",
      syncTitle: "Moodle sync",
      syncDone: "Synced with Moodle.",
      syncPartial: "Synced with some problems.",
      stepGroup: "Group",
      stepTeachers: "Teachers",
      stepStudents: "Students",
      stepSessions: "Attendance sessions",
      stepGrades: "Grades",
      stepOk: "Done",
      stepError: "Failed",
      students: "Students",
      studentsEmpty: "No students in this class yet.",
      addStudents: "Add paid students",
      addStudentsHint: "Paid course sales waiting for this course in this branch.",
      noWaiting: "No paid sales are waiting for this course here.",
      attachToast: "Student added to the class.",
      noMoodleAccount: "No Moodle account",
      readOnly: "You can view this class. Changes belong to the branch team.",
    },
    sessions: {
      upcoming: "Upcoming",
      past: "Past",
      cancelled: "Cancelled",
      empty: "No sessions yet.",
      emptyHint: "Plan sessions from teacher and room availability.",
      plan: "Plan sessions",
      planTitle: "Plan sessions",
      planDescription:
        "Set hours for each weekday. EMS finds the earliest time when the teacher and a room are both free.",
      weekday: "Day",
      hours: "Hours",
      addDay: "Add a day",
      removeDay: "Remove day",
      fromDate: "From",
      toDate: "To",
      findTimes: "Find times",
      proposed: "Proposed times",
      noMatch:
        "No time works for every day. Free up teacher or room hours, or change the days.",
      book: "Book these sessions",
      bookedToast: "Sessions booked.",
      reschedule: "Change time",
      rescheduleTitle: "Change session time",
      rescheduleDescription: "Pick a new start. It must fit the teacher and room availability.",
      movedToast: "Session moved.",
      cancel: "Cancel session",
      cancelTitle: "Cancel this session?",
      cancelBody: "It leaves the schedule for students and the teacher.",
      cancelledToast: "Session cancelled.",
      length: "Length",
      room: "Room",
      teacher: "Teacher",
      online: "Online",
      today: "Today",
      dayRequired: "Add at least one day.",
      dayTwice: "Each day can appear once.",
      rangeInvalid: "The end date must be on or after the start date.",
      pastLocked: "Past sessions cannot be changed.",
      attendance: "Attendance",
    },
    week: {
      title: "My week",
      description: "Your sessions for the week, with attendance to take after each one.",
      thisWeek: "This week",
      previous: "Previous week",
      next: "Next week",
      sessions: "sessions",
      hours: "hours",
      needAttendance: "need attendance",
      empty: "No sessions this week.",
      noMoodle: "No Moodle session yet",
      dayOff: "Free",
    },
    attendance: {
      empty: "No Moodle attendance sessions yet.",
      emptyHint: "Sync the class with Moodle to create them from the schedule.",
      take: "Take attendance",
      sheetTitle: "Attendance",
      sheetEmpty: "No students on this session yet.",
      markAll: "Mark all present",
      save: "Save attendance",
      savedToast: "Attendance saved.",
      notTaken: "Not taken",
      taken: "Taken",
      notMarked: "Not marked",
      marked: "marked",
      of: "of",
      needsActivity: "Set the course's Moodle attendance activity first.",
    },
    grades: {
      empty: "No grades in Moodle yet.",
      student: "Student",
      courseGrade: "Course grade",
    },
    rooms: {
      title: "Rooms",
      description: "Rooms in each branch, their seats, and the hours they can be booked.",
      add: "Add room",
      createTitle: "Add room",
      editTitle: "Edit room",
      createDescription: "Name the room and how many people it seats.",
      name: "Room name",
      capacity: "Seats",
      createSubmit: "Create room",
      createdToast: "Room created.",
      updatedToast: "Room updated.",
      empty: "No rooms match.",
      emptyHint: "Add a room so classes and tests can be booked.",
      disable: "Disable room",
      disableTitle: "Disable this room?",
      disableBody: "It can no longer be booked. Past bookings stay.",
      disabledToast: "Room disabled.",
      enable: "Enable room",
      enableTitle: "Enable this room?",
      enableBody: "It can be booked again.",
      enabledToast: "Room enabled.",
      availability: "Availability",
      availabilityHint: "Paint the hours this room can be booked. Booked hours stay locked.",
      availabilityToast: "Availability saved.",
      unlimited: "Not set",
    },
  },
  forms: {
    title: "Forms",
    description: "Build your own forms, share them with families or staff, and act on every response.",
    intro: "Introduction",
    yes: "Yes",
    no: "No",
    agreed: "Agreed",
    form: "Form",
    tabForms: "My forms",
    tabResponses: "Responses",
    tabToFill: "To fill",
    newForm: "New form",
    newTitle: "New form",
    newDescription: "Start blank or from a template. You can change everything before you publish.",
    createSubmit: "Create form",
    createdToast: "Form created.",
    titleEn: "Title (English)",
    titleAr: "Title (Arabic)",
    category: "Category",
    template: "Start from",
    blank: "Blank form",
    branch: "Branch",
    allBranchesForm: "Every branch",
    empty: "No forms yet.",
    emptyHint: "Create a form to replace a Jotform or a paper sheet.",
    responsesEmpty: "No responses yet.",
    toFillEmpty: "Nothing to fill right now.",
    toFillHint: "Forms assigned to you or your role appear here.",
    status: { draft: "Draft", active: "Live", retired: "Retired" },
    categories: {
      admissions: "Admissions",
      student_support: "Student support",
      attendance: "Attendance",
      consent: "Consent",
      branch_operations: "Branch operations",
    },
    responseStatus: {
      submitted: "New",
      under_review: "In review",
      accepted: "Accepted",
      rejected: "Rejected",
      promoted: "Acted on",
      withdrawn: "Withdrawn",
      quarantined: "Held",
    },
    responses: "Responses",
    updated: "Updated",
    live: "Live link",
    notLive: "Not shared",
    open: "Open",
    fill: "Fill in",
    filled: "Sent",
    due: "Closes",
    tabBuild: "Build",
    tabShare: "Share",
    tabResponses2: "Responses",
    editDraft: "Edit a new version",
    editingDraft: "Draft",
    publishedVersion: "Live version",
    version: "Version",
    save: "Save draft",
    savedToast: "Draft saved.",
    unsaved: "Unsaved changes",
    preview: "Preview",
    hidePreview: "Hide preview",
    page: "Page",
    addPage: "Add page",
    removePage: "Remove page",
    addField: "Add a question",
    question: "Question",
    questionEn: "Question (English)",
    questionAr: "Question (Arabic)",
    help: "Help text",
    required: "Required",
    options: "Choices",
    addOption: "Add choice",
    optionEn: "Choice (English)",
    optionAr: "Choice (Arabic)",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    duplicate: "Duplicate",
    logicNote: "This form has conditional rules. They are kept when you save.",
    usedByLogic: "A rule uses this question. Remove the rule first.",
    readOnlyVersion: "This version is live and cannot change. Start a new version to edit.",
    problems: "Fix these before saving:",
    problemLabel: "A question has no English text.",
    problemArabic: "Every question and choice needs Arabic text too.",
    recordLinkNote: "This question links to old records and shows no choices for your branches.",
    recordLinkBanner: "A question here uses old record links. Open it and switch to your branch list before publishing.",
    useBranchList: "Use our branch list",
    needsAttention: "needs attention",
    problemOptions: "A choice question needs at least one choice.",
    problemEmpty: "Add at least one question.",
    types: {
      heading: "Heading",
      instructions: "Instructions",
      short_text: "Short answer",
      long_text: "Paragraph",
      email: "Email",
      phone: "Phone",
      number: "Number",
      date: "Date",
      time: "Time",
      single_choice: "One choice",
      multiple_choice: "Several choices",
      yes_no: "Yes or no",
      rating: "Rating",
      consent: "Consent",
      entity_reference: "Record link",
    },
    typeGroups: { text: "Text", choice: "Choices", value: "Numbers and dates", layout: "Layout" },
    publish: "Publish",
    publishTitle: "Publish this version",
    publishDescription: "Choose who can answer. A live link keeps working until you retire it.",
    publishSubmit: "Publish",
    publishedToast: "Form published.",
    slug: "Link name",
    slugHint: "Lowercase letters, numbers, and dashes.",
    audience: "Who can answer",
    audiencePublic: "Anyone with the link",
    audiencePublicHint: "Families and visitors, no sign-in.",
    audienceAuthenticated: "Any signed-in staff",
    audienceAuthenticatedHint: "Everyone who signs in to Nile Center.",
    audienceAssigned: "Only people I assign",
    audienceAssignedHint: "Pick roles, branches, departments, or people next.",
    opensAt: "Opens",
    closesAt: "Closes",
    allowMultiple: "Allow more than one response per person",
    allowDrafts: "Let people save and finish later",
    publicationStatus: { scheduled: "Scheduled", open: "Open", closed: "Closed", retired: "Retired" },
    publications: "Links",
    noPublications: "This form is not shared yet.",
    copyLink: "Copy link",
    copied: "Link copied.",
    openLink: "Open",
    retire: "Retire link",
    retireTitle: "Retire this link?",
    retireBody: "People can no longer answer through it. Responses stay.",
    retiredToast: "Link retired.",
    assignments: "Assigned to",
    noAssignments: "Nobody is assigned yet.",
    assign: "Assign",
    assignTitle: "Assign this form",
    assignDescription: "Choose who should fill in this form. They'll find it under To fill.",
    assignedToast: "Form assigned.",
    target: "Assign to",
    targetRole: "Role",
    targetBranch: "Branch",
    targetDepartment: "Department",
    targetPeople: "People",
    peopleModeStaff: "Staff member",
    peopleModeClass: "Teachers of a class",
    peopleClass: "Class",
    staffSearch: "Search staff by name or email…",
    noStaffFound: "No staff found.",
    classNoTeachers: "This class has no teachers yet.",
    peopleSelected: "{n} selected",
    assignToOne: "Assign to 1 person",
    assignToMany: "Assign to {n} people",
    publishBlockedRecordLinks: "Fix the highlighted question in Build before publishing.",
    assignedPeopleToast: "{n} assigned.",
    assignFailures: "Couldn't assign:",
    personFallback: "Staff member",
    revoke: "Remove",
    revokedToast: "Assignment removed.",
    expires: "Until",
    respondent: "From",
    anonymous: "Public link",
    submitted: "Sent",
    answers: "Answers",
    noAnswer: "No answer",
    review: "Decision",
    accept: "Accept",
    reject: "Reject",
    startReview: "Mark in review",
    comment: "Note",
    reviewedToast: "Decision saved.",
    history: "History",
    createLead: "Create lead",
    createLeadHint: "Turn this enquiry into a lead in Admissions, with the answers filled in.",
    leadCreated: "Lead created",
    openLead: "Open lead",
    export: "Export CSV",
    exportedToast: "Export ready.",
    allForms: "All forms",
    allStatuses: "All statuses",
    import: "Import from Jotform",
    sentToast: "Thank you. Your response was sent.",
    backToForms: "Back to forms",
    importer: {
      title: "Import from Jotform",
      description: "Bring past Jotform responses into your own forms, check them first, then keep a record of every row.",
      notConnected: "Jotform is not connected on this server, so its forms cannot be listed. Imports already made stay below.",
      step1: "1. Choose forms",
      step2: "2. Match questions",
      step3: "3. Check, then import",
      source: "Jotform form",
      target: "Into this form",
      noTargets: "Publish a form first; responses import into a live form.",
      inspect: "Match questions",
      field: "Question in our form",
      fromJotform: "Jotform question",
      skip: "Do not import",
      offset: "Start at row",
      limit: "Rows",
      dryRun: "Check rows",
      total: "Rows",
      valid: "Ready",
      duplicates: "Already imported",
      errors: "With problems",
      sample: "First rows",
      commit: "Import ready rows",
      importedToast: "Import finished.",
      history: "Past imports",
      noHistory: "No imports yet.",
      imported: "Imported",
      exceptions: "Exceptions",
      matched: "Matched",
      markMatched: "Mark matched",
      markException: "Mark exception",
      reconciledToast: "Row updated.",
      rowsNeedingReview: "Rows needing review",
      submissions: "responses",
    },
    roles: {
      student: "Students",
      teacher: "Teachers",
      registrar: "Registrars and SSAs",
      headofdepartment: "Heads of department",
      branchadmin: "Branch admins and vice managers",
      superadmin: "Super Admins",
    },
  },
  admissions: {
    money: {
      toBePaid: "Total",
      paid: "Paid",
      remaining: "Remaining",
      settled: "Paid in full",
      paidTooHigh: "Paid cannot be more than the total.",
      invalidAmount: "Enter a number of zero or more.",
    },
    mode: {
      label: "Study mode",
      online: "Online",
      onsite: "Onsite",
      both: "Online or onsite",
      unknown: "Not chosen",
      onlineBranch: "Online branch",
      onsiteBranch: "Onsite branch",
    },
    leads: {
      title: "Leads",
      description:
        "People who asked about a course, from first contact to registration.",
      add: "Add lead",
      createTitle: "Add lead",
      editTitle: "Edit lead",
      createDescription: "Record who asked, what they want, and how to reach them.",
      editDescription: "Update contact details, interest, or owner.",
      createSubmit: "Create lead",
      createdToast: "Lead created.",
      updatedToast: "Lead updated.",
      empty: "No leads match.",
      emptyHint: "Add a lead or clear the filters.",
      noAccess: "Leads belong to admissions staff.",
      person: "Person",
      stage: "Stage",
      interest: "Interest",
      owner: "Owner",
      group: "Group",
      added: "Added",
      branch: "Branch",
      anyMode: "Any study mode",
      anyOwner: "Any owner",
      unassigned: "No owner",
      anyArea: "Any area of study",
      anyType: "Any lead type",
      allBranches: "All branches",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      phone: "Phone",
      wantsOnline: "Online classes",
      wantsOnsite: "Classes at the branch",
      preferredCourses: "Preferred courses",
      anyCourse: "No preference",
      coursesNoun: "courses",
      areaOfStudy: "Area of study",
      noArea: "No area",
      source: "Source",
      sourceHint: "For example: website, walk-in, or referral.",
      notes: "Notes",
      leadType: "Lead type",
      typeNew: "New",
      typeOld: "Returning lead",
      typeOldStudent: "Former student",
      typeCurrentStudent: "Current student",
      required: "Required.",
      invalidEmail: "Enter a valid email address.",
      chooseBranch: "Choose a branch.",
      journey: "Journey",
      nextStep: "Next step",
      stepContact: "First contact",
      stepPlacement: "Placement test",
      stepTrial: "Trial lesson",
      stepFee: "Registration fee",
      stepStudent: "Student",
      stepDone: "Done",
      stepNow: "Now",
      stepSkipped: "Skipped",
      stepLater: "Not yet",
      nextBookPlacement: "Book a placement test to find the right level.",
      nextRecordPlacement: "Record the placement result after the test.",
      nextBookTrial: "Book a trial lesson, or record the registration fee.",
      nextRecordTrial: "Record how the trial lesson went.",
      nextFee: "Record the registration fee.",
      nextConvert: "The fee is recorded. Create the student record.",
      nextStudent: "This lead is now a student.",
      nextLost: "This lead is closed as lost.",
      bookPlacement: "Book placement test",
      bookTrial: "Book trial lesson",
      recordFee: "Record registration fee",
      editFee: "Change fee",
      convert: "Create student",
      openStudent: "Open student",
      markLost: "Mark as lost",
      reopen: "Reopen lead",
      lostTitle: "Mark this lead as lost?",
      lostBody: "Choose why. You can reopen the lead later.",
      lostReason: "Lost reason",
      noLostReasons:
        "No lost reasons are available for this account. An administrator can add them under Lost reasons.",
      openLostReasons: "Open lost reasons.",
      lostToast: "Lead marked as lost.",
      reopenToast: "Lead reopened.",
      lostBecause: "Lost because",
      details: "Details",
      placements: "Placement tests",
      trials: "Trial lessons",
      fee: "Registration fee",
      noPlacements: "No placement tests yet.",
      noTrials: "No trial lessons yet.",
      noFee: "No registration fee yet.",
      feeTitle: "Registration fee",
      feeDescription: "Record the total and what the person paid so far.",
      feeToast: "Registration fee saved.",
      groupMembers: "Grouped with",
      primaryContact: "Main contact",
      convertTitle: "Create student",
      convertDescription:
        "Add the identity details EMS needs. Contact details come from the lead.",
      convertToast: "Student created.",
    },
    booking: {
      placementTitle: "Book placement test",
      trialTitle: "Book trial lesson",
      editTitle: "Change booking",
      when: "Date and time",
      hour: "Start time",
      onTheHour: "Bookings start on the hour.",
      timeZone: "Time zone",
      room: "Room",
      chooseRoom: "Choose a room. Onsite bookings need one.",
      meetingRequired: "Add the meeting link.",
      noRoom: "No room yet",
      meetingLink: "Meeting link",
      meetingHint: "Use an https link. Only online branches use links.",
      meetingInvalid: "Use a link that starts with https://",
      topic: "Lesson topic",
      byCourse: "A course",
      byArea: "An area of study",
      course: "Course",
      chooseCourse: "Choose a course.",
      chooseArea: "Choose an area of study.",
      placementCourseMissing:
        "This area of study has no placement course in Moodle. Ask Super Admin to link one.",
      book: "Book",
      saveChanges: "Save changes",
      bookedToast: "Booking saved.",
      updatedToast: "Booking updated.",
      moodlePassword: "Moodle password for the test",
      resultTitle: "Record result",
      resultDescription: "Save the outcome. The booking closes as completed.",
      score: "Score or level",
      scoreHint: "For example: B1 or 72.",
      mentor: "Mentoring teacher",
      noMentors: "No teachers found for this branch.",
      recommended: "Recommended course",
      noRecommendation: "No recommendation",
      notes: "Notes",
      resultToast: "Result saved.",
      syncMoodle: "Get result from Moodle",
      syncToast: "Result updated from Moodle.",
      fromMoodle: "From Moodle",
      recordedBy: "Recorded by",
      noShow: "Mark as no-show",
      noShowTitle: "Mark as no-show?",
      noShowBody: "The person did not attend. You can book a new time.",
      noShowToast: "Marked as no-show.",
      cancel: "Cancel booking",
      cancelTitle: "Cancel this booking?",
      cancelBody: "Choose why. The time slot becomes free.",
      cancelToast: "Booking cancelled.",
      change: "Change",
      joinLink: "Open meeting link",
      result: "Result",
    },
    agenda: {
      placementsTitle: "Placement tests",
      placementsDescription:
        "Every placement test in your scope, by day. Book them from a lead or student.",
      trialsTitle: "Trial lessons",
      trialsDescription:
        "Every trial lesson in your scope, by day. Book them from a lead or student.",
      upcoming: "Upcoming",
      needsResult: "Needs result",
      completed: "Completed",
      missed: "No show",
      cancelled: "Cancelled",
      today: "Today",
      tomorrow: "Tomorrow",
      emptyUpcoming: "Nothing booked.",
      emptyNeedsResult: "Every past booking has a result.",
      emptyOther: "Nothing here yet.",
      emptyHint: "Book from a lead journey page.",
      subjectLead: "Lead",
      subjectStudent: "Student",
      allBranches: "All branches",
      branch: "Branch",
    },
    students: {
      title: "Students",
      description:
        "Everyone registered with Nile Center, their courses, balance, and Moodle access.",
      add: "Add student",
      createTitle: "Add student",
      editTitle: "Edit student",
      createDescription: "Create a student who did not come through a lead.",
      editDescription: "Update contact details, identity, or owner.",
      createSubmit: "Create student",
      createdToast: "Student created.",
      updatedToast: "Student updated.",
      empty: "No students match.",
      emptyHint: "Add a student or clear the filters.",
      noAccess: "Students belong to admissions staff.",
      person: "Person",
      branch: "Home branch",
      owner: "Owner",
      moodle: "Moodle",
      moodleLinked: "Linked",
      moodleMissing: "Not linked",
      registration: "Registration fee",
      noFee: "No fee",
      added: "Added",
      note: "Note",
      allBranches: "All branches",
      contact: "Contact",
      identity: "Identity",
      guardians: "Guardians",
      noGuardians: "No guardians recorded.",
      tabOverview: "Overview",
      tabCourses: "Courses",
      tabLearning: "Learning",
      tabBookings: "Placement and trials",
      tabReport: "Report",
      warnings: "Notes from EMS",
      moodleCreate: "Create Moodle account",
      moodleLink: "Link Moodle account",
      moodleReset: "Reset Moodle password",
      moodlePassword: "Moodle password",
      moodleToast: "Moodle account updated.",
      moodleResetTitle: "Reset the Moodle password?",
      moodleResetBody: "EMS sets a new random password. Share it with the student once.",
      disable: "Disable student",
      disableTitle: "Disable this student?",
      disableBody: "They cannot get new enrolments. Their history stays.",
      disabledToast: "Student disabled.",
      enable: "Enable student",
      enableTitle: "Enable this student?",
      enableBody: "They can get new enrolments again.",
      enabledToast: "Student enabled.",
      learningEmpty: "No Moodle grades yet.",
      learningClass: "Class",
      learningGrade: "Course grade",
      learningCompletion: "Completion",
      learningDone: "Completed",
      learningOngoing: "In progress",
      print: "Print report",
      reportTitle: "Academic report",
      reportGenerated: "Generated",
      reportLearningError: "Moodle grades are not available right now.",
      fromLead: "From lead",
    },
    enrolments: {
      title: "Enrolments",
      description:
        "Course sales from payment to class. Add paid sales to a class with free seats.",
      empty: "No enrolments match.",
      emptyHint: "Sell a course from a student page.",
      noAccess: "Enrolments belong to admissions staff.",
      waiting: "Waiting",
      sell: "Sell a course",
      saleTitle: "Sell a course",
      saleDescription: "Open a course sale. Payment can follow later.",
      saleToast: "Course sale opened.",
      student: "Student",
      findStudent: "Search students",
      typeToSearch: "Type at least two letters.",
      noStudents: "No students match.",
      course: "Course",
      kind: "Class type",
      group: "Group",
      individual: "One to one",
      branch: "Branch",
      class: "Class",
      balance: "Balance",
      opened: "Opened",
      noClass: "No class yet",
      nextLevel: "Next level",
      recordPayment: "Record payment",
      paymentTitle: "Record payment",
      paymentDescription: "Update the total or what the student paid so far.",
      paymentToast: "Payment saved.",
      attach: "Add to class",
      attachTitle: "Add to a class",
      attachDescription:
        "Active classes for this course in this branch. Full classes take no more students.",
      seatsLeft: "seats left",
      full: "Full",
      noClasses: "No active class for this course in this branch yet.",
      attachToast: "Student added to the class.",
      moodleRequired: "The student needs a Moodle account before joining a class.",
      complete: "Mark completed",
      completeTitle: "Mark this enrolment completed?",
      completeBody: "Use this when the student finished the course.",
      completeToast: "Enrolment completed.",
      leave: "Mark as left",
      leaveTitle: "Mark this next-level sale as left?",
      leaveBody: "Choose why the student will not take this level.",
      leaveToast: "Enrolment marked as left.",
      cancel: "Cancel sale",
      cancelTitle: "Cancel this course sale?",
      cancelBody: "Choose why. This cannot be undone.",
      cancelToast: "Course sale cancelled.",
      schedule: "Schedule",
      teachers: "Teachers",
    },
    identity: {
      nationality: "Nationality",
      nationalityHint: "Three-letter code, for example EGY.",
      address: "Address",
      gender: "Gender",
      male: "Male",
      female: "Female",
      dateOfBirth: "Date of birth",
      nationalId: "National ID",
      nationalIdHint: "14 digits. Required for Egyptian nationals.",
      passport: "Passport number",
      guardian: "Guardian",
      secondGuardian: "Second guardian",
      guardianHint: "Students under 18 need at least one guardian.",
      guardianName: "Name",
      guardianPhone: "Phone",
      guardianEmail: "Email",
      relationship: "Relationship",
      relationshipHint: "For example: Mother, Father, or Uncle.",
      addGuardian: "Add a second guardian",
      removeGuardian: "Remove",
      invalidNationality: "Use a three-letter code.",
      invalidNationalId: "Use 14 digits.",
      nationalIdRequired: "Required for Egyptian nationals.",
      guardianRequired: "Students under 18 need a guardian.",
      guardianIncomplete: "Fill in every guardian field.",
    },
  },
  dateOfBirth: {
    day: "Day",
    month: "Month",
    year: "Year",
    monthPlaceholder: "Month",
    clear: "Clear date",
    hint: "For example: 4 March 2012.",
    incompleteDate: "Enter the day, month, and a four-digit year.",
    invalidDate: "This date does not exist. Check the day and month.",
    futureDate: "The date of birth cannot be in the future.",
    tooEarly: "Enter a year from 1900.",
    age: "{n} years old",
  },
  datePicker: {
    placeholder: "Choose a date",
    today: "Today",
    clear: "Clear",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    previousYear: "Previous year",
    nextYear: "Next year",
    chooseMonth: "Choose month and year",
    unavailable: "Not available",
    calendar: "Calendar",
  },
  language: {
    label: "Language",
  },
  reports: {
    title: "Reports",
    description: "Read a report, then export it. Figures come live from EMS.",
    report: "Report",
    tabs: {
      admissions: "Admissions",
      bookings: "Bookings",
      enrolments: "Enrolments",
      classes: "Classes",
    },
    period: "Period",
    asOfToday: "As of today",
    branch: "Branch",
    allBranches: "All branches",
    exportCsv: "Export CSV",
    truncated: "Showing the first {n} of {total} rows from EMS.",
    showAll: "Show all {n}",
    showLess: "Show less",
    emptyTitle: "Nothing to report",
    emptyAdmissions: "No leads were created in this period.",
    emptyBookings: "No placements or trials were scheduled in this period.",
    emptyEnrolments: "No enrolments found.",
    emptyClasses: "No active classes right now.",
    emptyPlacements: "No placement tests in this period.",
    emptyTrialLessons: "No trial lessons in this period.",
    emptyTrialResults: "No trial results recorded in this period.",
    emptyScores: "No scored placement tests in this period.",
    emptyLostReasons: "No lost leads in this period.",
    emptyWeekdays: "No classes have scheduled days.",
    changePeriod: "Change period",
    liveFootnote: "Every figure is computed live from EMS data through the staff API.",
    footnoteAdmissions:
      "Statuses are today's statuses of leads created in the selected window.",
    footnoteBookings: "Bookings are counted by their scheduled date.",
    footnoteEnrolments:
      "Enrolments are counted by their enrolled or cancelled date. Money is grouped as recorded in EMS, without a currency.",
    footnoteClasses: "A point-in-time read of active classes.",
    newLeads: "New leads",
    registered: "Registered",
    lost: "Lost",
    open: "Open",
    conversion: "Conversion",
    rate: "Rate",
    intake: "Lead intake",
    intakePerWeek: "New leads per week",
    intakePerMonth: "New leads per month",
    funnel: "From enquiry to registration",
    funnelDecided: "Decided",
    bySource: "By source",
    byLostReason: "By lost reason",
    byOwner: "By owner",
    byArea: "By area of study",
    byBranch: "By branch",
    studyMode: "Study mode",
    leadType: "Lead type",
    noSource: "No source",
    noReason: "No reason recorded",
    noOwner: "No owner",
    notSet: "Not set",
    modes: {
      online: "Online only",
      onsite: "Onsite only",
      both: "Both",
      unset: "Not chosen",
    },
    leadTypes: {
      new: "New",
      old: "Old",
      old_student: "Former student",
      current_student: "Current student",
    },
    count: "Count",
    share: "Share",
    leads: "Leads",
    placementTests: "Placement tests",
    trialLessons: "Trial lessons",
    scheduled: "Scheduled",
    completed: "Completed",
    noShow: "No show",
    cancelled: "Cancelled",
    showRate: "Show rate",
    scoreSummary: "Placement scores",
    scoreAverage: "Average",
    scoreMin: "Lowest",
    scoreMax: "Highest",
    scoreBands: "Score distribution",
    trialResults: "Trial results",
    trialsByCourse: "Trials by course",
    trialToRegistered: "Completed trials that became students",
    trials: "Trials",
    pipeline: "Pipeline",
    rightNow: "Right now",
    inThisPeriod: "In this period",
    enrolledInPeriod: "Enrolled in period",
    cancelledInPeriod: "Cancelled in period",
    allTime: "All time",
    money: "Money",
    billed: "Billed",
    collected: "Collected",
    outstanding: "Outstanding",
    outstandingPending: "Still to pay (awaiting payment)",
    collectionRate: "Collection rate",
    moneyNote: "Amounts are as recorded in EMS, without a currency.",
    byCourse: "By course",
    byKind: "By kind",
    kinds: { individual: "Individual", group: "Group" },
    activeClasses: "Active classes",
    seatsTaken: "Seats taken",
    capacity: "Capacity",
    fill: "Fill",
    freeSeats: "Free seats",
    fillByCourse: "Fill by course",
    fillByDepartment: "Fill by department",
    teacherLoad: "Teacher load",
    noTeacher: "No teacher assigned",
    endingSoon: "Ending soon",
    endingSoonEmpty: "No classes end in the next 30 days.",
    daysLeft: "Days left",
    weekdayLoad: "Classes by weekday",
    classes: "Classes",
    students: "Students",
    seats: "Seats",
    active: "Active",
    pending: "Pending",
    leftCancelled: "Left / cancelled",
    enrolled: "Enrolled",
    placements: "Placements",
    score: "Score",
    course: "Course",
    department: "Department",
    name: "Name",
    endDate: "End date",
    csv: {
      name: "Name",
      email: "Email",
      phone: "Phone",
      branch: "Branch",
      source: "Source",
      status: "Status",
      lostReason: "Lost reason",
      owner: "Owner",
      area: "Area of study",
      studyMode: "Study mode",
      created: "Created",
      type: "Type",
      person: "Person",
      scheduled: "Scheduled",
      result: "Result",
      courseOrArea: "Course / area",
      recommended: "Recommended course",
      student: "Student",
      course: "Course",
      className: "Class",
      enrolled: "Enrolled",
      cancelled: "Cancelled",
      toBePaid: "To be paid",
      paid: "Paid",
      remaining: "Remaining",
      department: "Department",
      teachers: "Teachers",
      schedule: "Schedule",
      capacity: "Capacity",
      taken: "Taken",
      fill: "Fill %",
      start: "Start",
      end: "End",
    },
  },
};

export type StaffMessages = typeof en;

export const enMessages: StaffMessages = en;

/** Live copy for the active language. i18n.ts replaces leaf values in place. */
export const copy: StaffMessages = structuredClone(en);
