import type { StaffMessages } from "./copy";

/**
 * Arabic copy. Must match every key in copy.ts.
 * Glossary: طالب، عميل محتمل، التحاق، فصل، حصة، فرع، موظف، تسجيل الدخول، تسجيل الخروج.
 */
export const ar: StaffMessages = {
  brand: {
    name: "مركز النيل",
    product: "إدارة التعليم",
  },
  nav: {
    overview: "الرئيسية",
    dashboard: "لوحة المتابعة",
    reports: "التقارير",
    forms: "الاستمارات",
    notifications: "الإشعارات",
    admissions: "القبول",
    students: "الطلاب",
    leads: "العملاء المحتملون",
    enrolments: "الالتحاقات",
    placementTests: "اختبارات تحديد المستوى",
    trialLessons: "الحصص التجريبية",
    delivery: "التدريس",
    courses: "الدورات",
    classes: "الفصول",
    sessions: "أسبوعي",
    rooms: "القاعات",
    organisation: "الأشخاص والفروع",
    staffUsers: "الموظفون",
    branches: "الفروع",
    departments: "الأقسام",
    setup: "الإعداد",
    lostReasons: "أسباب فقد العميل",
    actionReasons: "أسباب الإجراءات",
    areasOfStudy: "مجالات الدراسة",
    customFields: "الحقول المخصصة",
    system: "النظام",
    moodleSite: "مودل",
    systemHealth: "حالة النظام",
    auditLog: "سجل التدقيق",
    profile: "الملف الشخصي",
  },
  roles: {
    super_admin: "المدير العام",
    branch_admin: "مدير الفرع",
    vice_manager: "نائب المدير",
    hod: "رئيس القسم",
    registrar: "المسجّل",
    ssa: "SSA",
    teacher: "المعلم",
  },
  shell: {
    backTo: "العودة إلى {page}",
    collapseSidebar: "طيّ الشريط الجانبي",
    expandSidebar: "توسيع الشريط الجانبي",
    staffNav: "تنقل الموظفين",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    displaySize: "حجم العرض",
    displayStandard: "عادي",
    displayLarge: "كبير",
    displayXLarge: "كبير جدًا",
    workspace: "مساحة العمل",
    chooseWorkspace: "اختر فرعًا",
    workspaceHint: "يعمل دورك داخل فرع واحد في كل مرة. اختر الفرع الذي تريد العمل فيه.",
    noWorkspaces: "لا توجد فروع نشطة مخصصة لك بعد.",
    notifications: "الإشعارات",
    markAllRead: "تعليم الكل كمقروء",
    viewAll: "عرض كل الإشعارات",
    userMenu: "قائمة المستخدم",
    signOut: "تسجيل الخروج",
    signOutEverywhere: "تسجيل الخروج من كل الأجهزة",
    roleView: "عرض الدور",
    roleViewTitle: "عرض الدور",
    roleViewBody: "اعرض التطبيق بصلاحيات دور أقل. حدّد البيانات بفروع أو أقسام أو فصول معينة.",
    viewingAs: "تعرض بصفة",
    ownRole: "دورك",
    roleViewChanged: "تم تحديث عرض الدور.",
    scopesApplied: "تم تطبيق النطاق.",
    roleViewEnded: "عدت إلى دورك.",
    returnToRole: "العودة إلى دوري",
    applyScopes: "تطبيق",
    viewAsRole: "العرض بدور آخر",
    editRoleView: "تعديل",
    scopeBranches: "الفروع",
    scopeBranch: "الفرع",
    scopeDepartments: "الأقسام",
    scopeClasses: "الفصول",
    allBranches: "كل الفروع",
    allDepartments: "كل الأقسام",
    allClasses: "كل الفصول",
    branchesNoun: "فروع",
    departmentsNoun: "أقسام",
    classesNoun: "فصول",
    searchBranches: "ابحث في الفروع",
    searchDepartments: "ابحث في الأقسام",
    searchClasses: "ابحث في الفصول",
    chooseWorkspaceOption: "اختر فرعًا",
    noAccess: "لا توجد صلاحية",
    noAccessHint: "لا يمكن لدورك الحالي فتح هذه الصفحة. عد إلى لوحة المتابعة.",
    backToDashboard: "العودة إلى لوحة المتابعة",
    checkingSession: "جارٍ التحقق من الجلسة",
    signedInAs: "مسجّل الدخول باسم",
    search: "ابحث أو انتقل إلى",
    breadcrumb: "مسار التنقل",
    commandPages: "الصفحات",
    commandPeople: "الموظفون",
    commandActions: "الإجراءات",
    commandEmpty: "لا توجد نتائج.",
  },
  state: {
    loading: "جارٍ التحميل",
    notSet: "غير محدد",
    retry: "إعادة المحاولة",
    empty: "لا يوجد شيء هنا بعد.",
    error403: "ليست لديك صلاحية لهذه الصفحة.",
    error404: "هذا السجل لم يعد موجودًا.",
    error409: "يتعارض هذا التغيير مع تحديث أحدث. أعد التحميل وحاول مرة أخرى.",
    error422: "راجع الحقول المحددة وحاول مرة أخرى.",
    error429: "طلبات كثيرة جدًا. انتظر قليلًا وحاول مرة أخرى.",
    error503: "هذه الخدمة غير متاحة الآن. حاول لاحقًا.",
    errorNetwork: "فشل الاتصال بالشبكة. تحقق من اتصالك.",
    errorGeneric: "فشل الطلب. حاول مرة أخرى.",
  },
  status: {
    active: "نشط",
    disabled: "معطل",
    invited: "مدعو",
    canceled: "ملغى",
    cancelled: "ملغى",
    enrolled: "ملتحق",
    completed: "مكتمل",
    registered: "مسجّل",
    scheduled: "مجدول",
    pending: "قيد الانتظار",
    pending_payment: "بانتظار الدفع",
    pending_class: "بانتظار فصل",
    pending_group: "بانتظار مجموعة",
    in_process: "قيد المعالجة",
    follow_up: "متابعة",
    future_registration: "تسجيل لاحق",
    trial_lesson: "حصة تجريبية",
    placement_test: "اختبار تحديد المستوى",
    left: "منسحب",
    lost: "مفقود",
    no_show: "لم يحضر",
    healthy: "سليم",
    degraded: "متراجع",
    unhealthy: "متعطل",
    ok: "سليم",
    warning: "تحذير",
    error: "خطأ",
    not_configured: "غير مُعد",
  },
  notifications: {
    title: "الإشعارات",
    description: "صندوق الوارد الخاص بك فقط.",
    all: "الكل",
    unread: "غير مقروءة",
    empty: "لا توجد إشعارات.",
    markRead: "تعليم كمقروء",
    markAllRead: "تعليم الكل كمقروء",
    delete: "حذف",
    deleteAll: "حذف الكل",
    deleteAllTitle: "حذف كل الإشعارات؟",
    deleteAllBody: "يحذف هذا نسختك نهائيًا. يحتفظ باقي الموظفين بنسخهم.",
    read: "مقروء",
    unreadBadge: "غير مقروء",
    markedRead: "تم تعليم الإشعار كمقروء.",
    allMarkedRead: "تم تعليم كل الإشعارات كمقروءة.",
    deleted: "تم حذف الإشعار.",
    allDeleted: "تم حذف كل الإشعارات.",
    actionFailed: "فشل إجراء الإشعار. حاول مرة أخرى.",
  },
  profile: {
    title: "الملف الشخصي",
    description: "أدر بياناتك وكلمة المرور والجلسات النشطة.",
    details: "بياناتك",
    role: "الدور المخصص",
    email: "البريد الإلكتروني",
    name: "الاسم",
    nameNotSet: "غير محدد",
    phone: "الهاتف",
    unknownDevice: "جهاز غير معروف",
    password: "كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    changePassword: "تغيير كلمة المرور",
    passwordChanged: "تم تغيير كلمة المرور.",
    passwordFailed: "فشل تغيير كلمة المرور. راجع ما أدخلته.",
    passwordsDiffer: "كلمتا المرور الجديدتان غير متطابقتين.",
    sessions: "الجلسات النشطة",
    sessionsHint: "سجّل الخروج من أي جلسة لا تعرفها.",
    thisSession: "هذه الجلسة",
    lastSeen: "آخر ظهور",
    issued: "تسجيل الدخول",
    signOutSession: "إنهاء الجلسة",
    sessionRevoked: "تم إنهاء الجلسة.",
    signOutEverywhere: "تسجيل الخروج من كل الأجهزة",
    signOutEverywhereTitle: "تسجيل الخروج من كل الأجهزة؟",
    signOutEverywhereBody: "يسجّل هذا خروجك من كل جهاز. ستحتاج إلى تسجيل الدخول مرة أخرى.",
  },
  actions: {
    save: "حفظ",
    cancel: "إلغاء",
    saving: "جارٍ الحفظ",
    discardTitle: "تجاهل التغييرات؟",
    discardBody: "تغييراتك غير محفوظة.",
    discard: "تجاهل",
    keepEditing: "متابعة التعديل",
    search: "بحث",
    filter: "تصفية",
    columns: "الأعمدة",
    selected: "محدد",
    clearSelection: "إلغاء التحديد",
    previous: "السابق",
    next: "التالي",
    pageOf: "من",
    create: "إنشاء",
    edit: "تعديل",
    rowActions: "إجراءات الصف",
    enable: "تفعيل",
    disable: "تعطيل",
    close: "إغلاق",
    import: "استيراد",
    refresh: "تحديث",
    noReasons: "أضف سببًا لهذا الإجراء أولًا.",
    openActionReasons: "افتح أسباب الإجراءات.",
    status: "الحالة",
    activeOnly: "النشطة فقط",
    selectAll: "تحديد كل الصفوف",
    selectRow: "تحديد الصف",
    pagination: "الصفحات",
  },
  catalog: {
    shared: {
      name: "الاسم",
      nameRequired: "أدخل اسمًا.",
      code: "الرمز",
      codeHint: "أحرف لاتينية صغيرة وأرقام وشرطة سفلية.",
      codePattern: "استخدم أحرفًا لاتينية صغيرة وأرقامًا وشرطة سفلية فقط.",
      sortOrder: "ترتيب العرض",
      created: "تاريخ الإنشاء",
      status: "الحالة",
      active: "نشط",
      disabled: "معطل",
      allStatuses: "كل الحالات",
      access: "صلاحيتك",
      accessManage: "إدارة",
      accessView: "عرض",
      customFields: "الحقول المخصصة",
      customFieldsEmpty: "لا توجد حقول مخصصة لهذا السجل.",
      enableTitle: "تفعيل هذا السجل؟",
      disableTitle: "تعطيل هذا السجل؟",
      enableBody: "يصبح هذا السجل متاحًا مرة أخرى.",
      createdToast: "تم الإنشاء.",
      updatedToast: "تم حفظ التغييرات.",
      enabledToast: "تم التفعيل.",
      disabledToast: "تم التعطيل.",
      saveChanges: "حفظ التغييرات",
    },
    branches: {
      title: "الفروع",
      description: "المواقع التي يعمل فيها مركز النيل.",
      empty: "لا توجد فروع بعد.",
      emptyHint: "أنشئ أول فرع.",
      add: "إضافة فرع",
      createTitle: "إضافة فرع",
      editTitle: "تعديل الفرع",
      createDescription: "أنشئ فرعًا نشطًا.",
      editDescription: "حدّث الاسم أو الرمز أو الإعدادات.",
      createSubmit: "إنشاء الفرع",
      timezone: "المنطقة الزمنية",
      online: "فرع عبر الإنترنت",
      onlineYes: "عبر الإنترنت",
      onlineNo: "حضوري",
      searchBranches: "ابحث في الفروع",
      disableBody: "يتوقف الفرع عن قبول عمل جديد. تفقد الجلسات المرتبطة به مساحة العمل.",
      statisticsTitle: "النشاط",
      detailMissing: "هذا الفرع لم يعد موجودًا.",
      statActiveStudents: "الطلاب النشطون",
      statOpenLeads: "العملاء المحتملون المفتوحون",
      statActiveClasses: "الفصول النشطة",
      statEnrolmentFill: "المقاعد المشغولة",
      statEnrolmentCapacity: "سعة الالتحاق",
      statPendingEnrolments: "الالتحاقات المعلقة",
      statPlacements: "اختبارات المستوى المجدولة",
      statTrials: "الحصص التجريبية المجدولة",
      statStaff: "الموظفون",
      bulkDisable: "تعطيل المحدد",
      bulkEnable: "تفعيل المحدد",
      bulkDone: "تم تحديث التحديد.",
    },
    departments: {
      title: "الأقسام",
      description: "الأقسام الأكاديمية التي تتبعها الفصول والدورات.",
      empty: "لا توجد أقسام بعد.",
      emptyHint: "أنشئ أول قسم.",
      add: "إضافة قسم",
      createTitle: "إضافة قسم",
      editTitle: "تعديل القسم",
      createSubmit: "إنشاء القسم",
      disableBody: "يُخفى القسم من العمل الجديد.",
    },
    lostReasons: {
      title: "أسباب فقد العميل",
      description: "سبب تحويل العميل المحتمل إلى مفقود.",
      empty: "لا توجد أسباب بعد.",
      emptyHint: "أنشئ أول سبب.",
      add: "إضافة سبب",
      createTitle: "إضافة سبب فقد",
      editTitle: "تعديل سبب الفقد",
      createSubmit: "إنشاء السبب",
      disableBody: "يُخفى السبب من العمل الجديد.",
    },
    actionReasons: {
      title: "أسباب الإجراءات",
      description: "أسباب مسمّاة تطلبها الإجراءات المحمية.",
      empty: "لا توجد أسباب إجراءات بعد.",
      emptyHint: "أنشئ أو استورد أول سبب.",
      add: "إضافة سبب إجراء",
      createTitle: "إضافة سبب إجراء",
      editTitle: "تعديل سبب الإجراء",
      createSubmit: "إنشاء السبب",
      disableBody: "يُخفى السبب من العمل الجديد.",
      kind: "النوع",
      allKinds: "كل الأنواع",
      import: "استيراد CSV",
      importTitle: "استيراد أسباب الإجراءات",
      importDescription: "الصق صفوف CSV أو اختر ملفًا. راجع المعاينة أولًا ثم استورد.",
      chooseFile: "اختر ملف CSV",
      downloadTemplate: "تنزيل القالب",
      orPaste: "أو الصق صفوف CSV",
      importPreview: "معاينة",
      importRowCount: "صفوف",
      rowError: "خطأ",
      rowErrorColumns: "المتوقع 6 أعمدة.",
      rowErrorKind: "نوع غير معروف.",
      rowErrorName: "الاسم مطلوب.",
      importEmpty: "الصق صفوف CSV لمعاينتها.",
      importSubmit: "استيراد",
      importDone: "اكتمل الاستيراد.",
      importCreated: "تم إنشاؤها",
      importUpdated: "تم تحديثها",
      csvPlaceholder: "id,action,name,status,sort_order,created_at",
      kindLost: "فقد عميل محتمل",
      kindLeft_enrolment: "انسحاب من التحاق",
      kindCancel_enrolment: "إلغاء التحاق",
      kindCancel_placement_test: "إلغاء اختبار تحديد المستوى",
      kindCancel_trial_lesson: "إلغاء حصة تجريبية",
      kindDisable_student: "تعطيل طالب",
      kindDisable_course: "تعطيل دورة",
      kindDisable_class: "تعطيل فصل",
      kindDisable_branch: "تعطيل فرع",
      kindDisable_department: "تعطيل قسم",
      kindDisable_room: "تعطيل قاعة",
      kindDisable_staff: "تعطيل موظف",
      kindDisable_area_of_study: "تعطيل مجال دراسة",
      kindDisable_custom_field: "تعطيل حقل مخصص",
    },
    areasOfStudy: {
      title: "مجالات الدراسة",
      description: "المواد التي يمكن تحديد مستوى الطالب فيها.",
      empty: "لا توجد مجالات دراسة بعد.",
      emptyHint: "أنشئ أول مجال دراسة.",
      add: "إضافة مجال دراسة",
      createTitle: "إضافة مجال دراسة",
      editTitle: "تعديل مجال الدراسة",
      createSubmit: "إنشاء المجال",
      disableBody: "يُخفى المجال من اختبارات المستوى الجديدة.",
      placementCourses: "دورات اختبار تحديد المستوى",
      placementCoursesHint: "اختر دورات Moodle التي تحتوي على اختبارات تحديد المستوى.",
      addCourse: "إضافة دورة Moodle",
      searchCourses: "ابحث في دورات Moodle",
      coursesEmpty: "لا توجد دورات مطابقة.",
      coursesLoading: "جارٍ تحميل الدورات",
      coursesError: "دورات Moodle غير متاحة.",
    },
    customFields: {
      title: "الحقول المخصصة",
      description: "حقول إضافية على السجلات في التطبيق.",
      empty: "لا توجد حقول مخصصة بعد.",
      emptyHint: "أنشئ أول حقل مخصص.",
      add: "إضافة حقل مخصص",
      createTitle: "إضافة حقل مخصص",
      editTitle: "تعديل الحقل المخصص",
      createSubmit: "إنشاء الحقل",
      disableBody: "يُخفى الحقل من النماذج.",
      entity: "السجل",
      allEntities: "كل السجلات",
      fieldKey: "مفتاح الحقل",
      fieldKeyHint: "معرّف بأحرف لاتينية صغيرة يُستخدم في نموذج البيانات. لا يمكن تغييره لاحقًا.",
      fieldType: "النوع",
      required: "حقل إلزامي",
      requiredYes: "إلزامي",
      optional: "اختياري",
      helpText: "نص المساعدة",
      options: "الخيارات",
      optionsHint: "خيار واحد في كل سطر.",
      entityUser_profile: "ملف الموظف",
      entityStudent: "طالب",
      entityLead: "عميل محتمل",
      entityBranch: "فرع",
      entityDepartment: "قسم",
      entityClass: "فصل",
      entityCourse: "دورة",
      entityRoom: "قاعة",
    },
  },
  staffUsers: {
    title: "الموظفون",
    description: "كل من يعمل في مركز النيل، ودوره، ومكان عمله، وطريقة دخوله.",
    add: "إضافة موظف",
    createTitle: "إضافة موظف",
    editTitle: "تعديل الموظف",
    createDescription: "أنشئ حساب موظف بدور ونطاق.",
    editDescription: "حدّث الدور أو الملف الشخصي أو النطاق.",
    createSubmit: "إنشاء الموظف",
    empty: "لا يوجد موظفون بعد.",
    emptyHint: "ادعُ أول موظف.",
    noAccess: "يدير المدير العام ومدير الفرع حسابات الموظفين.",
    person: "الشخص",
    email: "البريد الإلكتروني",
    role: "الدور",
    worksAt: "مكان العمل",
    branches: "الفروع",
    departments: "الأقسام",
    courses: "الدورات",
    moodle: "Moodle",
    status: "الحالة",
    lastSignIn: "آخر دخول",
    added: "تاريخ الإضافة",
    you: "أنت",
    all: "الكل",
    results: "النتائج",
    clearFilters: "مسح التصفية",
    teachersNoMoodle: "معلمون بلا حساب مودل",
    allRoles: "كل الأدوار",
    allBranches: "كل الفروع",
    allDepartments: "كل الأقسام",
    globalScope: "كل الفروع",
    branchScope: "نطاق الفروع",
    branchScopeHint: "يحتاج نائب المدير إلى فرع واحد بالضبط. يحتاج المسجّل وSSA والمعلم إلى فرع واحد على الأقل.",
    workspaceScopeHint: "يجب أن تتضمن الحسابات الجديدة فرع مساحة عملك.",
    invited: "مدعو",
    moodleLinked: "مرتبط",
    moodleMissing: "غير مرتبط",
    provisioning: "طريقة الإنشاء",
    provisioningInvitation: "رابط دعوة",
    provisioningManual: "كلمة مرور يدوية",
    provisioningHint: "تنشئ الدعوة رابطًا لمرة واحدة. ينشئ الخيار اليدوي كلمة مرور مؤقتة.",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    phone: "الهاتف",
    address: "العنوان",
    nationality: "الجنسية",
    nationalityHint: "رمز الدولة من ثلاثة أحرف.",
    dateOfBirth: "تاريخ الميلاد",
    notes: "ملاحظات",
    canTakePlacementTest: "يمكنه إجراء اختبارات تحديد المستوى",
    yourPassword: "كلمة مرورك",
    yourPasswordHint: "يحتاج هذا التغيير من المدير العام إلى كلمة مرورك للمتابعة.",
    yourPasswordRequired: "أدخل كلمة مرورك للمتابعة.",
    firstNameRequired: "الاسم الأول مطلوب.",
    lastNameRequired: "اسم العائلة مطلوب.",
    emailRequired: "أدخل بريدًا إلكترونيًا صالحًا.",
    branchScopeRequired: "اختر فرعًا واحدًا على الأقل.",
    viceManagerScope: "يحتاج نائب المدير إلى فرع واحد بالضبط.",
    invite: "دعوة",
    resendInvite: "إعادة إرسال الدعوة",
    inviteTitle: "إرسال دعوة جديدة؟",
    inviteBody: "يتوقف رابط الدعوة السابق عن العمل.",
    cancelInvite: "إلغاء الدعوة",
    cancelInviteTitle: "إلغاء هذه الدعوة؟",
    cancelInviteBody: "يتوقف رابط الدعوة عن العمل فورًا.",
    setPassword: "تعيين كلمة مرور",
    setPasswordTitle: "تعيين كلمة مرور جديدة؟",
    setPasswordBody: "تُنشأ كلمة مرور مؤقتة مرة واحدة. شاركها عبر قناة آمنة.",
    moodleAccount: "حساب Moodle",
    moodleCreate: "إنشاء حساب Moodle",
    moodleLink: "ربط حساب Moodle",
    moodleReset: "إعادة تعيين كلمة مرور Moodle",
    moodleResetTitle: "إعادة تعيين كلمة مرور Moodle؟",
    moodleResetBody: "تُنشأ كلمة مرور Moodle جديدة مرة واحدة. شاركها عبر قناة آمنة.",
    moodleSearch: "ابحث في حسابات Moodle",
    moodleSearchHint: "ابحث بالاسم أو اسم المستخدم أو البريد الإلكتروني.",
    moodleSearchMin: "اكتب حرفين على الأقل.",
    moodleSearchEmpty: "لا توجد حسابات Moodle مطابقة.",
    moodleCreateHint: "ينشئ حساب Moodle مرتبطًا بهذا الموظف.",
    moodleLinkHint: "اربط حساب Moodle موجودًا بهذا الموظف.",
    disableTitle: "تعطيل هذا الموظف؟",
    disableBody: "لن يتمكن الحساب من تسجيل الدخول.",
    enableTitle: "تفعيل هذا الموظف؟",
    enableBody: "يمكن للحساب تسجيل الدخول مرة أخرى.",
    bulkDisable: "تعطيل المحدد",
    bulkEnable: "تفعيل المحدد",
    bulkDone: "تم تحديث التحديد.",
    createdToast: "تم إنشاء الموظف.",
    updatedToast: "تم حفظ التغييرات.",
    invitedToast: "تم إنشاء الدعوة.",
    cancelledToast: "تم إلغاء الدعوة.",
    passwordToast: "تمت إعادة تعيين كلمة المرور.",
    moodleToast: "تم تحديث حساب Moodle.",
    disabledToast: "تم تعطيل الموظف.",
    enabledToast: "تم تفعيل الموظف.",
    secretTitle: "بيانات دخول لمرة واحدة",
    secretBody: "انسخها الآن. لن تظهر مرة أخرى.",
    secretShare: "شارك بيانات الدخول عبر قناة آمنة فقط.",
    secretDone: "تم",
    copyValue: "نسخ",
    copied: "تم النسخ.",
    invitationLink: "رابط الدعوة",
    temporaryPassword: "كلمة المرور المؤقتة",
    moodlePassword: "كلمة مرور Moodle",
    moreActions: "إجراءات أخرى",
    copyEmail: "نسخ البريد",
    emailCopied: "تم نسخ البريد.",
    tabOverview: "نظرة عامة",
    tabCourses: "الدورات",
    tabAvailability: "التوفر",
    tabActivity: "النشاط",
    sectionContact: "التواصل",
    sectionAccess: "الصلاحيات",
    sectionMore: "تفاصيل إضافية",
    neverSignedIn: "لم يسجّل الدخول",
    statsAdmissions: "القبول",
    statsTeaching: "التدريس",
    statLeadsCreated: "عملاء محتملون أُنشئوا",
    statLeadsAssigned: "عملاء محتملون مخصصون",
    statLeadsOpen: "عملاء محتملون مفتوحون",
    statLeadsRegistered: "مسجّلون",
    statLeadsLost: "مفقودون",
    statStudentsAssigned: "طلاب مخصصون",
    statClassesTeaching: "فصول يدرّسها",
    statSessionsScheduled: "حصص مجدولة",
    statStudentsTaught: "طلاب درّسهم",
    statsEmpty: "لا يوجد نشاط مسجّل بعد.",
    coursesTitle: "الدورات التي يدرّسها",
    coursesHint: "القائمة الفارغة تعني أنه لا يمكن تعيين هذا المعلم لأي فصل.",
    coursesSaved: "تم تحديث الدورات.",
    coursesSearchPlaceholder: "ابحث في الدورات",
    placementCapability: "اختبارات تحديد المستوى",
    placementYes: "يمكنه إجراء اختبارات تحديد المستوى",
    placementNo: "لا يمكنه إجراء اختبارات تحديد المستوى",
    availabilityTitle: "التوفر",
    availabilityHint: "حدّد الساعات التي يعمل فيها هذا المعلم. لا يمكن تغيير الحصص المحجوزة.",
    penAvailable: "متاح",
    penUnavailable: "غير متاح",
    penClear: "مسح",
    showAllHours: "عرض كل الساعات",
    showWorkHours: "عرض ساعات العمل",
    timezoneLabel: "المنطقة الزمنية",
    unsavedBar: "لديك تغييرات غير محفوظة.",
    saveChanges: "حفظ التغييرات",
    discardChanges: "تجاهل",
    discardTitle: "تجاهل تغييرات التوفر؟",
    discardBody: "التغييرات التي حددتها غير محفوظة.",
    cellsSaved: "تم حفظ التوفر.",
    cellsSkippedBooked: "تم تخطي الحصص المحجوزة.",
    weekToday: "اليوم",
    weekPrevious: "الأسبوع السابق",
    weekNext: "الأسبوع التالي",
    bookedSession: "محجوز",
  },
  moodleSite: {
    title: "موقع Moodle",
    description: "اربط موقع Moodle الذي تعتمد عليه الدورات والمجموعات والحضور.",
    noAccess: "يمكن للمدير العام فقط إعداد موقع Moodle.",
    connection: "الاتصال",
    connectionHint: "بيانات خدمة الويب لموقع Moodle. الرمز للكتابة فقط.",
    siteUrl: "رابط الموقع",
    token: "رمز خدمة الويب",
    tokenHint: "يُحفظ بأمان. أعد إدخاله فقط لتغيير الرمز.",
    tokenKeep: "اتركه فارغًا للاحتفاظ بالرمز الحالي.",
    autoCreate: "إنشاء حسابات Moodle للطلاب تلقائيًا",
    autoCreateHint: "عند التفعيل، يحاول إنشاء الطالب إنشاء حساب Moodle أيضًا.",
    ptCourse: "رقم دورة Moodle لاختبار تحديد المستوى",
    ptCourseHint: "دورة Moodle التي تستضيف اختبار تحديد المستوى. اتركه فارغًا للمسح.",
    save: "حفظ التغييرات",
    connect: "ربط Moodle",
    test: "اختبار الاتصال",
    disconnect: "قطع الاتصال",
    disconnectTitle: "قطع الاتصال بـ Moodle؟",
    disconnectBody: "يُحذف الرمز المحفوظ. تتوقف مزامنة الدورات والمجموعات حتى إعادة الربط.",
    saved: "تم حفظ إعدادات Moodle.",
    disconnected: "تم قطع الاتصال بـ Moodle.",
    testOk: "نجح اختبار الاتصال.",
    testVersionWarn: "الموقع متاح، لكن إصدار Moodle خارج النطاق المتوقع 4.5.x.",
    testFailed: "تعذّر الوصول إلى Moodle.",
    statusTitle: "الحالة",
    statConfigured: "مُعد",
    statToken: "الرمز محفوظ",
    statReachable: "متاح",
    statVersion: "الإصدار متوقع",
    statSitename: "اسم الموقع",
    statRelease: "الإصدار",
    statLastChecked: "آخر فحص",
    statWarnings: "التحذيرات",
    statLastError: "آخر خطأ",
    unknown: "غير معروف",
    yes: "نعم",
    no: "لا",
  },
  system: {
    title: "حالة النظام",
    description: "الحالة المباشرة للخدمات الأساسية وتكامل Moodle.",
    noAccess: "يمكن للمدير العام فقط عرض حالة النظام.",
    refresh: "تحديث",
    checked: "آخر فحص",
    componentApi: "واجهة البرمجة",
    componentDatabase: "قاعدة البيانات",
    componentSchema: "فحص المخطط",
    componentMigration: "الترحيلات",
    componentMoodle: "Moodle",
    operational: "يعمل.",
    version: "الإصدار",
    configured: "مُعد",
    token: "الرمز",
    reachable: "متاح",
    site: "الموقع",
    release: "الإصدار",
    expected: "المتوقع 4.5.x",
    warnings: "التحذيرات",
  },
  audit: {
    title: "سجل التدقيق",
    description: "من فعل ماذا ومتى. الأحدث أولًا.",
    noAccess: "يمكن للمدير العام ومدير الفرع فقط قراءة سجل التدقيق.",
    stream: "المسار",
    allStreams: "كل المسارات",
    search: "ابحث في الأحداث",
    empty: "لا توجد أحداث تدقيق.",
    emptyHint: "تُسجَّل الإجراءات هنا عند حدوثها.",
    payload: "البيانات",
    actor: "المنفّذ",
    system: "النظام",
    today: "اليوم",
    yesterday: "أمس",
    latest: "آخر {n} حدث",
    failedSignIn: "مستخدم",
    groups: {
      all: "الكل",
      auth: "تسجيل الدخول",
      admissions: "القبول",
      teaching: "التدريس",
      setup: "الإعداد",
    },
    nouns: {
      auth: "حساب",
      branch: "فرع",
      department: "قسم",
      course: "دورة",
      custom_field: "حقل مخصص",
      moodle_site: "اتصال Moodle",
      student: "طالب",
      lead: "عميل محتمل",
      placement_test: "اختبار تحديد مستوى",
      class: "فصل",
      enrolment: "التحاق",
      room: "قاعة",
      session: "حصة",
    },
    verbs: {
      created: "أنشأ {noun}",
      updated: "عدّل {noun}",
      disabled: "عطّل {noun}",
      enabled: "فعّل {noun}",
      cancelled: "ألغى {noun}",
      completed: "أكمل {noun}",
      refreshed: "حدّث {noun}",
      tested: "اختبر {noun}",
      other: "{action}: {noun}",
    },
    actions: {
      login_success: "سجّل الدخول",
      login_failed: "فشل في تسجيل الدخول",
      logout: "سجّل الخروج",
      workspace_switched: "غيّر الفرع",
      role_switched: "غيّر عرض الدور",
      invitation_sent: "أرسل دعوة إلى",
      invitation_accepted: "قبل الدعوة",
      user_created: "أنشأ حساب الموظف",
      moodle_group_created: "أنشأ مجموعة Moodle لـ",
      moodle_group_deleted: "حذف مجموعة Moodle لـ",
      moodle_group_synced: "زامن مع Moodle:",
      moodle_linked: "ربط حساب Moodle لـ",
      converted: "حوّل إلى طالب:",
      enrolled: "ألحق طالبًا",
    },
    streams: {
      auth: "تسجيل الدخول",
      branch: "فرع",
      department: "قسم",
      course: "دورة",
      custom_field: "حقل مخصص",
      moodle_site: "موقع Moodle",
      student: "طالب",
      lead: "عميل محتمل",
      placement_test: "اختبار تحديد المستوى",
      class: "فصل",
      enrolment: "التحاق",
      room: "قاعة",
      session: "حصة",
    },
  },
  dashboard: {
    morning: "صباح الخير",
    afternoon: "مساء الخير",
    evening: "مساء الخير",
    nameSeparator: "، ",
    intro: "هذا ما يحتاج إليك اليوم.",
    openLeads: "العملاء المحتملون المفتوحون",
    openLeadsNote: "لم يُسجَّلوا ولم يُفقدوا بعد",
    bookings: "الحجوزات القادمة",
    tests: "اختبارات",
    trials: "دروس تجريبية",
    waitingSales: "مبيعات بانتظار إجراء",
    waitingSalesNote: "ينقصها الدفع أو الفصل",
    classFill: "امتلاء الفصول",
    seatsOf: "من",
    seats: "مقعدًا مشغولًا",
    activeStudents: "الطلاب النشطون",
    activeStudentsNote: "بسجل نشط",
    today: "اليوم",
    todayEmpty: "لا توجد حجوزات اليوم.",
    overdue: "حجوزات سابقة بانتظار النتيجة",
    openAgenda: "فتح الجدول",
    attention: "يحتاج إلى متابعة",
    allClear: "لا شيء معلّق",
    resultsToRecord: "نتائج بانتظار التسجيل",
    unpaid: "مبيعات دورات غير مدفوعة",
    waitingClass: "مدفوعة وبانتظار فصل",
    unowned: "عملاء مفتوحون بلا مسؤول",
    formResponses: "ردود استمارات جديدة",
    period: "الفترة",
    periods: {
      "7d": "7 أيام",
      "30d": "30 يومًا",
      "90d": "90 يومًا",
      "12m": "12 شهرًا",
      all: "كل الوقت",
    },
    vsPrevious: "مقارنة بالسابق",
    noChange: "بلا تغيير",
    pts: " نقطة",
    newLeads: "عملاء جدد",
    conversion: "نسبة التحويل",
    conversionNote: "المسجّلون من العملاء المحسومين",
    intake: "تدفق العملاء",
    intakeNote: "عملاء جدد كل أسبوع",
    weekOf: "أسبوع",
    outcomes: "نتائج العملاء",
    open: "مفتوح",
    registered: "مسجّل",
    lost: "مفقود",
    noData: "لا يوجد عملاء في هذه الفترة.",
    funnel: "من الاستفسار إلى الطالب",
    funnelLeads: "العملاء",
    funnelBooked: "اختبارات وحصص منجزة",
    bookingsTitle: "الاختبارات والحصص التجريبية",
    placementTests: "اختبارات تحديد المستوى",
    trialLessons: "الحصص التجريبية",
    completed: "منجز",
    scheduledLabel: "مجدول",
    noShow: "لم يحضر",
    cancelled: "ملغى",
    showRate: "نسبة الحضور",
    pipeline: "مسار العملاء المحتملين",
    pipelineEmpty: "لا يوجد عملاء مفتوحون.",
    branches: "الفروع",
    branch: "الفرع",
    students: "الطلاب",
    classes: "الفصول",
    fill: "الامتلاء",
    waiting: "بانتظار إجراء",
    placement: "اختبار تحديد المستوى",
    trial: "درس تجريبي",
    myClasses: "فصولي",
    myStudents: "الطلاب في فصولي",
    nextSession: "الحصة القادمة",
    noNextSession: "لا توجد حصة محجوزة",
    sessions: "الحصص القادمة",
    sessionsEmpty: "لا توجد حصص محجوزة بعد.",
    classesEmpty: "لم تُسند إليك فصول بعد.",
    openMoodle: "فتح في Moodle",
    departmentClasses: "فصول القسم",
    seatsFree: "المقاعد المتاحة",
    noTeacher: "فصول بلا معلم",
    departmentEmpty: "لا توجد فصول في أقسامك بعد.",
    teachers: "المعلمون",
    schedule: "الجدول",
    unassignedTeacher: "بلا معلم",
    enrolled: "ملتحقون",
    loadError: "تعذّر تحميل بعض الأرقام.",
  },
  teaching: {
    hourUnit: "س",
    seats: "مقاعد",
    seatsLeft: "متبقية",
    full: "ممتلئ",
    allBranches: "كل الفروع",
    branch: "الفرع",
    required: "مطلوب.",
    wholeNumber: "استخدم عددًا صحيحًا أكبر من صفر.",
    openMoodle: "فتح في Moodle",
    courses: {
      title: "الدورات",
      description: "الدورات المرتبطة من Moodle، بساعاتها وقسمها والطلب الحالي عليها.",
      empty: "لا توجد دورات مطابقة.",
      emptyHint: "اربط دورة من Moodle لتبدأ بيعها.",
      course: "الدورة",
      department: "القسم",
      allDepartments: "كل الأقسام",
      area: "مجال الدراسة",
      noArea: "بلا مجال",
      hours: "الساعات",
      totalHours: "إجمالي ساعات التدريس",
      moodle: "Moodle",
      moodleVisible: "ظاهرة",
      moodleHidden: "مخفية",
      moodleChecked: "آخر تحقق من Moodle",
      refreshError: "تعذّر التحديث من Moodle",
      refreshAll: "التحديث من Moodle",
      refreshAllToast: "تم تحديث الدورات من Moodle.",
      refreshOne: "التحديث من Moodle",
      refreshOneToast: "تم تحديث الدورة من Moodle.",
      link: "ربط دورة من Moodle",
      linkTitle: "ربط دورة من Moodle",
      linkDescription: "الدورات تأتي من Moodle. اختر دورة غير مرتبطة وحدد ساعات تدريسها.",
      linkSubmit: "ربط الدورة",
      linkToast: "تم ربط الدورة.",
      editTitle: "تعديل الدورة",
      editDescription: "القسم والساعات ومجال الدراسة والدورة السابقة لها.",
      editToast: "تم تحديث الدورة.",
      chooseMoodle: "اختر دورة من Moodle.",
      noUnmapped: "كل دورات Moodle مرتبطة بالفعل.",
      searchMoodle: "ابحث في دورات Moodle",
      previous: "تأتي بعد",
      noPrevious: "بلا دورة سابقة",
      attendanceId: "نشاط الحضور في Moodle",
      attendanceHint: "مطلوب لتسجيل الحضور. هو رقم نشاط الحضور في دورة Moodle.",
      noAttendance: "غير محدد، لذا لا يمكن تسجيل الحضور.",
      disable: "تعطيل الدورة",
      disableTitle: "تعطيل هذه الدورة؟",
      disableBody: "لن يمكن بيعها أو إنشاء فصول جديدة لها. تبقى الفصول الحالية.",
      disabledToast: "تم تعطيل الدورة.",
      enable: "تفعيل الدورة",
      enableTitle: "تفعيل هذه الدورة؟",
      enableBody: "يمكن بيعها وإنشاء فصول لها مرة أخرى.",
      enabledToast: "تم تفعيل الدورة.",
      demand: "الطلب الآن",
      activeClasses: "الفصول النشطة",
      seatsTaken: "المقاعد المشغولة",
      waitingSales: "مبيعات بانتظار إجراء",
      interestedLeads: "عملاء مهتمون",
      classes: "الفصول",
      noClasses: "لا توجد فصول لهذه الدورة بعد.",
      writeNote: "المدير العام وحده يعدّل الدورات.",
    },
    classes: {
      title: "الفصول",
      description: "كل فصل بمعلميه ووقته المعتاد ومقاعده ومجموعته في Moodle.",
      empty: "لا توجد فصول مطابقة.",
      emptyHint: "أنشئ فصلًا لدورة نشطة.",
      add: "إضافة فصل",
      createTitle: "إضافة فصل",
      editTitle: "تعديل الفصل",
      createDescription: "الدورة والتواريخ والمقاعد والمعلمون والوقت الأسبوعي المعتاد.",
      editDescription: "التواريخ والمقاعد والمعلمون والوقت المعتاد ورابط الاجتماع.",
      createSubmit: "إنشاء الفصل",
      createdToast: "تم إنشاء الفصل.",
      updatedToast: "تم تحديث الفصل.",
      name: "اسم الفصل",
      course: "الدورة",
      allCourses: "كل الدورات",
      kind: "نوع الفصل",
      group: "مجموعة",
      individual: "فردي",
      capacity: "المقاعد",
      starts: "يبدأ",
      ends: "ينتهي",
      dates: "التواريخ",
      teachers: "المعلمون",
      noTeachers: "لا يوجد معلمون لهذا الفرع بعد.",
      noTeacher: "بلا معلم",
      usualDays: "الأيام المعتادة",
      from: "من",
      to: "إلى",
      usualTime: "الوقت المعتاد",
      noSchedule: "بلا وقت معتاد",
      meetingLink: "رابط الاجتماع",
      meetingHint: "للفصول عن بُعد. استخدم رابط https.",
      meetingInvalid: "استخدم رابطًا يبدأ بـ https://",
      endBeforeStart: "يجب أن يكون تاريخ الانتهاء بعد تاريخ البدء.",
      timeOrder: "يجب أن يكون وقت الانتهاء بعد وقت البدء.",
      timeBoth: "حدد الوقتين معًا أو اتركهما.",
      daysNeedTime: "اختر الأيام والوقت معًا.",
      fill: "المقاعد",
      moodleGroup: "مجموعة Moodle",
      moodleLinked: "مرتبطة",
      moodleMissing: "غير مرتبطة",
      lastSynced: "آخر مزامنة",
      neverSynced: "لم تتم المزامنة",
      tabOverview: "نظرة عامة",
      tabStudents: "الطلاب",
      tabSessions: "الحصص",
      tabAttendance: "الحضور",
      tabGrades: "الدرجات",
      disable: "تعطيل الفصل",
      disableTitle: "تعطيل هذا الفصل؟",
      disableBody: "لن يقبل طلابًا جددًا. يبقى الطلاب الملتحقون والسجل.",
      disabledToast: "تم تعطيل الفصل.",
      enable: "تفعيل الفصل",
      enableTitle: "تفعيل هذا الفصل؟",
      enableBody: "يمكنه قبول طلاب مرة أخرى.",
      enabledToast: "تم تفعيل الفصل.",
      moodleCreate: "إنشاء مجموعة في Moodle",
      moodleLink: "ربط مجموعة من Moodle",
      moodleTitle: "مجموعة Moodle",
      moodleDescription: "أنشئ مجموعة جديدة في دورة Moodle، أو اربط مجموعة موجودة.",
      moodleSearch: "ابحث في مجموعات Moodle",
      moodleBound: "تم ربط مجموعة Moodle.",
      sync: "المزامنة مع Moodle",
      syncTitle: "مزامنة Moodle",
      syncDone: "تمت المزامنة مع Moodle.",
      syncPartial: "تمت المزامنة مع بعض المشكلات.",
      stepGroup: "المجموعة",
      stepTeachers: "المعلمون",
      stepStudents: "الطلاب",
      stepSessions: "جلسات الحضور",
      stepGrades: "الدرجات",
      stepOk: "تم",
      stepError: "فشل",
      students: "الطلاب",
      studentsEmpty: "لا يوجد طلاب في هذا الفصل بعد.",
      addStudents: "إضافة طلاب دفعوا",
      addStudentsHint: "مبيعات مدفوعة بانتظار هذه الدورة في هذا الفرع.",
      noWaiting: "لا توجد مبيعات مدفوعة بانتظار هذه الدورة هنا.",
      attachToast: "تمت إضافة الطالب إلى الفصل.",
      noMoodleAccount: "بلا حساب Moodle",
      readOnly: "يمكنك عرض هذا الفصل. التعديلات من اختصاص فريق الفرع.",
    },
    sessions: {
      upcoming: "القادمة",
      past: "السابقة",
      cancelled: "الملغاة",
      empty: "لا توجد حصص بعد.",
      emptyHint: "خطط الحصص من أوقات المعلم والقاعة المتاحة.",
      plan: "تخطيط الحصص",
      planTitle: "تخطيط الحصص",
      planDescription: "حدد الساعات لكل يوم. يجد النظام أقرب وقت يكون فيه المعلم وقاعة متاحين.",
      weekday: "اليوم",
      hours: "الساعات",
      addDay: "إضافة يوم",
      removeDay: "إزالة اليوم",
      fromDate: "من",
      toDate: "إلى",
      findTimes: "البحث عن أوقات",
      proposed: "الأوقات المقترحة",
      noMatch: "لا يوجد وقت يناسب كل الأيام. أتح ساعات للمعلم أو القاعة، أو غيّر الأيام.",
      book: "حجز هذه الحصص",
      bookedToast: "تم حجز الحصص.",
      reschedule: "تغيير الوقت",
      rescheduleTitle: "تغيير وقت الحصة",
      rescheduleDescription: "اختر بداية جديدة. يجب أن تناسب أوقات المعلم والقاعة.",
      movedToast: "تم نقل الحصة.",
      cancel: "إلغاء الحصة",
      cancelTitle: "إلغاء هذه الحصة؟",
      cancelBody: "ستُزال من جدول الطلاب والمعلم.",
      cancelledToast: "تم إلغاء الحصة.",
      length: "المدة",
      room: "القاعة",
      teacher: "المعلم",
      online: "عن بُعد",
      today: "اليوم",
      dayRequired: "أضف يومًا واحدًا على الأقل.",
      dayTwice: "يظهر كل يوم مرة واحدة.",
      rangeInvalid: "يجب أن يكون تاريخ الانتهاء في يوم البدء أو بعده.",
      pastLocked: "لا يمكن تعديل الحصص السابقة.",
      attendance: "الحضور",
    },
    week: {
      title: "أسبوعي",
      description: "حصصك هذا الأسبوع، مع الحضور المطلوب تسجيله بعد كل حصة.",
      thisWeek: "هذا الأسبوع",
      previous: "الأسبوع السابق",
      next: "الأسبوع التالي",
      sessions: "حصص",
      hours: "ساعات",
      needAttendance: "بانتظار الحضور",
      empty: "لا توجد حصص هذا الأسبوع.",
      noMoodle: "لا توجد جلسة Moodle بعد",
      dayOff: "فارغ",
    },
    attendance: {
      empty: "لا توجد جلسات حضور في Moodle بعد.",
      emptyHint: "زامن الفصل مع Moodle لإنشائها من الجدول.",
      take: "تسجيل الحضور",
      sheetTitle: "الحضور",
      sheetEmpty: "لا يوجد طلاب في هذه الجلسة بعد.",
      markAll: "تحديد الكل حاضرًا",
      save: "حفظ الحضور",
      savedToast: "تم حفظ الحضور.",
      notTaken: "لم يُسجَّل",
      taken: "سُجِّل",
      notMarked: "غير محدد",
      marked: "محدد",
      of: "من",
      needsActivity: "حدد نشاط الحضور في Moodle لهذه الدورة أولًا.",
    },
    grades: {
      empty: "لا توجد درجات في Moodle بعد.",
      student: "الطالب",
      courseGrade: "درجة الدورة",
    },
    rooms: {
      title: "القاعات",
      description: "قاعات كل فرع ومقاعدها والساعات المتاحة لحجزها.",
      add: "إضافة قاعة",
      createTitle: "إضافة قاعة",
      editTitle: "تعديل القاعة",
      createDescription: "سمِّ القاعة وحدد عدد مقاعدها.",
      name: "اسم القاعة",
      capacity: "المقاعد",
      createSubmit: "إنشاء القاعة",
      createdToast: "تم إنشاء القاعة.",
      updatedToast: "تم تحديث القاعة.",
      empty: "لا توجد قاعات مطابقة.",
      emptyHint: "أضف قاعة ليمكن حجز الفصول والاختبارات.",
      disable: "تعطيل القاعة",
      disableTitle: "تعطيل هذه القاعة؟",
      disableBody: "لن يمكن حجزها. تبقى الحجوزات السابقة.",
      disabledToast: "تم تعطيل القاعة.",
      enable: "تفعيل القاعة",
      enableTitle: "تفعيل هذه القاعة؟",
      enableBody: "يمكن حجزها مرة أخرى.",
      enabledToast: "تم تفعيل القاعة.",
      availability: "الأوقات المتاحة",
      availabilityHint: "لوّن الساعات التي يمكن فيها حجز القاعة. الساعات المحجوزة مقفلة.",
      availabilityToast: "تم حفظ الأوقات المتاحة.",
      unlimited: "غير محدد",
    },
  },
  forms: {
    title: "الاستمارات",
    description: "صمّم استماراتك، وشاركها مع الأسر أو الموظفين، وتابع كل رد.",
    intro: "مقدمة",
    yes: "نعم",
    no: "لا",
    agreed: "موافق",
    form: "الاستمارة",
    tabForms: "استماراتي",
    tabResponses: "الردود",
    tabToFill: "للتعبئة",
    newForm: "استمارة جديدة",
    newTitle: "استمارة جديدة",
    newDescription: "ابدأ من الصفر أو من قالب. يمكنك تغيير كل شيء قبل النشر.",
    createSubmit: "إنشاء الاستمارة",
    createdToast: "تم إنشاء الاستمارة.",
    titleEn: "العنوان (بالإنجليزية)",
    titleAr: "العنوان (بالعربية)",
    category: "الفئة",
    template: "البدء من",
    blank: "استمارة فارغة",
    branch: "الفرع",
    allBranchesForm: "كل الفروع",
    empty: "لا توجد استمارات بعد.",
    emptyHint: "أنشئ استمارة بدلًا من Jotform أو ورقة.",
    responsesEmpty: "لا توجد ردود بعد.",
    toFillEmpty: "لا شيء للتعبئة الآن.",
    toFillHint: "تظهر هنا الاستمارات المسندة إليك أو إلى دورك.",
    status: { draft: "مسودة", active: "منشورة", retired: "متوقفة" },
    categories: {
      admissions: "القبول",
      student_support: "دعم الطلاب",
      attendance: "الحضور",
      consent: "الموافقات",
      branch_operations: "عمليات الفرع",
    },
    responseStatus: {
      submitted: "جديد",
      under_review: "قيد المراجعة",
      accepted: "مقبول",
      rejected: "مرفوض",
      promoted: "تم التنفيذ",
      withdrawn: "مسحوب",
      quarantined: "محتجز",
    },
    responses: "الردود",
    updated: "آخر تحديث",
    live: "رابط منشور",
    notLive: "غير منشورة",
    open: "فتح",
    fill: "تعبئة",
    filled: "أُرسلت",
    due: "تُغلق",
    tabBuild: "التصميم",
    tabShare: "المشاركة",
    tabResponses2: "الردود",
    editDraft: "تعديل نسخة جديدة",
    editingDraft: "مسودة",
    publishedVersion: "النسخة المنشورة",
    version: "النسخة",
    save: "حفظ المسودة",
    savedToast: "تم حفظ المسودة.",
    unsaved: "تغييرات غير محفوظة",
    preview: "معاينة",
    hidePreview: "إخفاء المعاينة",
    page: "الصفحة",
    addPage: "إضافة صفحة",
    removePage: "إزالة الصفحة",
    addField: "إضافة سؤال",
    question: "السؤال",
    questionEn: "السؤال (بالإنجليزية)",
    questionAr: "السؤال (بالعربية)",
    help: "نص مساعد",
    required: "إجباري",
    options: "الخيارات",
    addOption: "إضافة خيار",
    optionEn: "الخيار (بالإنجليزية)",
    optionAr: "الخيار (بالعربية)",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    remove: "إزالة",
    duplicate: "تكرار",
    logicNote: "لهذه الاستمارة قواعد شرطية. تبقى كما هي عند الحفظ.",
    usedByLogic: "تستخدم قاعدة هذا السؤال. احذف القاعدة أولًا.",
    readOnlyVersion: "هذه النسخة منشورة ولا يمكن تغييرها. ابدأ نسخة جديدة للتعديل.",
    problems: "أصلح ما يلي قبل الحفظ:",
    problemLabel: "يوجد سؤال بلا نص إنجليزي.",
    problemArabic: "كل سؤال وخيار يحتاج نصًا عربيًا أيضًا.",
    recordLinkNote: "يرتبط هذا السؤال بسجلات قديمة ولا يعرض خيارات لفروعك.",
    recordLinkBanner: "سؤال هنا يستخدم روابط سجلات قديمة. افتحه وبدّله إلى قائمة فروعنا قبل النشر.",
    useBranchList: "استخدام قائمة فروعنا",
    needsAttention: "يحتاج إلى مراجعة",
    problemOptions: "سؤال الاختيار يحتاج خيارًا واحدًا على الأقل.",
    problemEmpty: "أضف سؤالًا واحدًا على الأقل.",
    types: {
      heading: "عنوان",
      instructions: "تعليمات",
      short_text: "إجابة قصيرة",
      long_text: "فقرة",
      email: "بريد إلكتروني",
      phone: "هاتف",
      number: "رقم",
      date: "تاريخ",
      time: "وقت",
      single_choice: "خيار واحد",
      multiple_choice: "عدة خيارات",
      yes_no: "نعم أو لا",
      rating: "تقييم",
      consent: "موافقة",
      entity_reference: "ربط بسجل",
    },
    typeGroups: { text: "نص", choice: "خيارات", value: "أرقام وتواريخ", layout: "تنسيق" },
    publish: "نشر",
    publishTitle: "نشر هذه النسخة",
    publishDescription: "اختر من يمكنه الرد. يبقى الرابط يعمل حتى توقفه.",
    publishSubmit: "نشر",
    publishedToast: "تم نشر الاستمارة.",
    slug: "اسم الرابط",
    slugHint: "أحرف إنجليزية صغيرة وأرقام وشرطات.",
    audience: "من يمكنه الرد",
    audiencePublic: "أي شخص لديه الرابط",
    audiencePublicHint: "الأسر والزوار، بلا تسجيل دخول.",
    audienceAuthenticated: "أي موظف مسجّل الدخول",
    audienceAuthenticatedHint: "كل من يسجّل الدخول إلى مركز النيل.",
    audienceAssigned: "من أسندها إليهم فقط",
    audienceAssignedHint: "اختر الأدوار أو الفروع أو الأقسام أو الأشخاص بعد ذلك.",
    opensAt: "تُفتح",
    closesAt: "تُغلق",
    allowMultiple: "السماح بأكثر من رد للشخص الواحد",
    allowDrafts: "السماح بالحفظ والإكمال لاحقًا",
    publicationStatus: { scheduled: "مجدولة", open: "مفتوحة", closed: "مغلقة", retired: "متوقفة" },
    publications: "الروابط",
    noPublications: "لم تُشارك هذه الاستمارة بعد.",
    copyLink: "نسخ الرابط",
    copied: "تم نسخ الرابط.",
    openLink: "فتح",
    retire: "إيقاف الرابط",
    retireTitle: "إيقاف هذا الرابط؟",
    retireBody: "لن يمكن الرد من خلاله. تبقى الردود.",
    retiredToast: "تم إيقاف الرابط.",
    assignments: "مسندة إلى",
    noAssignments: "لم تُسند لأحد بعد.",
    assign: "إسناد",
    assignTitle: "إسناد هذه الاستمارة",
    assignDescription: "اختر من يجب أن يعبئ هذا النموذج. سيجدونه ضمن «للتعبئة».",
    assignedToast: "تم إسناد الاستمارة.",
    target: "إسناد إلى",
    targetRole: "دور",
    targetBranch: "فرع",
    targetDepartment: "قسم",
    targetPeople: "أشخاص",
    peopleModeStaff: "موظف",
    peopleModeClass: "معلمو صف",
    peopleClass: "الصف",
    staffSearch: "ابحث في الموظفين بالاسم أو البريد…",
    noStaffFound: "لا يوجد موظفون.",
    classNoTeachers: "لا يوجد معلمون في هذا الصف بعد.",
    peopleSelected: "تم تحديد {n}",
    assignToOne: "إسناد إلى شخص واحد",
    assignToMany: "إسناد إلى {n} أشخاص",
    publishBlockedRecordLinks: "أصلح السؤال المميَّز في «التصميم» قبل النشر.",
    assignedPeopleToast: "تم إسناد {n}.",
    assignFailures: "تعذّر الإسناد:",
    personFallback: "موظف",
    revoke: "إزالة",
    revokedToast: "تمت إزالة الإسناد.",
    expires: "حتى",
    respondent: "المرسل",
    anonymous: "رابط عام",
    submitted: "أُرسل",
    answers: "الإجابات",
    noAnswer: "بلا إجابة",
    review: "القرار",
    accept: "قبول",
    reject: "رفض",
    startReview: "وضع قيد المراجعة",
    comment: "ملاحظة",
    reviewedToast: "تم حفظ القرار.",
    history: "السجل",
    createLead: "إنشاء عميل محتمل",
    createLeadHint: "حوّل هذا الاستفسار إلى عميل محتمل في القبول مع تعبئة الإجابات.",
    leadCreated: "تم إنشاء العميل المحتمل",
    openLead: "فتح العميل المحتمل",
    export: "تصدير CSV",
    exportedToast: "التصدير جاهز.",
    allForms: "كل الاستمارات",
    allStatuses: "كل الحالات",
    import: "الاستيراد من Jotform",
    backToForms: "العودة إلى النماذج",
    importer: {
      title: "الاستيراد من Jotform",
      description: "انقل ردود Jotform السابقة إلى استماراتك، وراجعها أولًا، واحتفظ بسجل لكل صف.",
      notConnected: "Jotform غير متصل على هذا الخادم، لذا لا يمكن عرض استماراته. تبقى عمليات الاستيراد السابقة أدناه.",
      step1: "1. اختيار الاستمارات",
      step2: "2. مطابقة الأسئلة",
      step3: "3. المراجعة ثم الاستيراد",
      source: "استمارة Jotform",
      target: "إلى هذه الاستمارة",
      noTargets: "انشر استمارة أولًا؛ يتم الاستيراد إلى استمارة منشورة.",
      inspect: "مطابقة الأسئلة",
      field: "السؤال في استمارتنا",
      fromJotform: "سؤال Jotform",
      skip: "عدم الاستيراد",
      offset: "البدء من الصف",
      limit: "عدد الصفوف",
      dryRun: "فحص الصفوف",
      total: "الصفوف",
      valid: "جاهزة",
      duplicates: "مستوردة سابقًا",
      errors: "بها مشكلات",
      sample: "الصفوف الأولى",
      commit: "استيراد الصفوف الجاهزة",
      importedToast: "اكتمل الاستيراد.",
      history: "عمليات استيراد سابقة",
      noHistory: "لا توجد عمليات استيراد بعد.",
      imported: "تم استيرادها",
      exceptions: "استثناءات",
      matched: "مطابقة",
      markMatched: "تحديد كمطابقة",
      markException: "تحديد كاستثناء",
      reconciledToast: "تم تحديث الصف.",
      rowsNeedingReview: "صفوف تحتاج مراجعة",
      submissions: "ردود",
    },
    roles: {
      student: "الطلاب",
      teacher: "المعلمون",
      registrar: "المسجلون ومسؤولو دعم الطلاب",
      headofdepartment: "رؤساء الأقسام",
      branchadmin: "مديرو الفروع ونوابهم",
      superadmin: "المديرون العامون",
    },
  },
  admissions: {
    money: {
      toBePaid: "الإجمالي",
      paid: "المدفوع",
      remaining: "المتبقي",
      settled: "مدفوع بالكامل",
      paidTooHigh: "لا يمكن أن يزيد المدفوع على الإجمالي.",
      invalidAmount: "أدخل رقمًا يساوي صفرًا أو أكثر.",
    },
    mode: {
      label: "نمط الدراسة",
      online: "عن بُعد",
      onsite: "في الفرع",
      both: "عن بُعد أو في الفرع",
      unknown: "لم يُحدَّد",
      onlineBranch: "فرع عن بُعد",
      onsiteBranch: "فرع حضوري",
    },
    leads: {
      title: "العملاء المحتملون",
      description: "الأشخاص الذين سألوا عن دورة، من أول تواصل حتى التسجيل.",
      add: "إضافة عميل محتمل",
      createTitle: "إضافة عميل محتمل",
      editTitle: "تعديل العميل المحتمل",
      createDescription: "سجّل من سأل، وماذا يريد، وكيف نتواصل معه.",
      editDescription: "حدّث بيانات التواصل أو الاهتمام أو المسؤول.",
      createSubmit: "إنشاء العميل المحتمل",
      createdToast: "تم إنشاء العميل المحتمل.",
      updatedToast: "تم تحديث العميل المحتمل.",
      empty: "لا يوجد عملاء محتملون مطابقون.",
      emptyHint: "أضف عميلًا محتملًا أو امسح التصفية.",
      noAccess: "العملاء المحتملون من اختصاص فريق القبول.",
      person: "الشخص",
      stage: "المرحلة",
      interest: "الاهتمام",
      owner: "المسؤول",
      group: "المجموعة",
      added: "تاريخ الإضافة",
      branch: "الفرع",
      anyMode: "أي نمط دراسة",
      anyOwner: "أي مسؤول",
      unassigned: "بلا مسؤول",
      anyArea: "أي مجال دراسة",
      anyType: "أي نوع",
      allBranches: "كل الفروع",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      wantsOnline: "دروس عن بُعد",
      wantsOnsite: "دروس في الفرع",
      preferredCourses: "الدورات المفضّلة",
      anyCourse: "بلا تفضيل",
      coursesNoun: "دورات",
      areaOfStudy: "مجال الدراسة",
      noArea: "بلا مجال",
      source: "المصدر",
      sourceHint: "مثل: الموقع، أو زيارة الفرع، أو ترشيح.",
      notes: "ملاحظات",
      leadType: "نوع العميل",
      typeNew: "جديد",
      typeOld: "عميل سابق",
      typeOldStudent: "طالب سابق",
      typeCurrentStudent: "طالب حالي",
      required: "مطلوب.",
      invalidEmail: "أدخل بريدًا إلكترونيًا صحيحًا.",
      chooseBranch: "اختر فرعًا.",
      journey: "المسار",
      nextStep: "الخطوة التالية",
      stepContact: "أول تواصل",
      stepPlacement: "اختبار تحديد المستوى",
      stepTrial: "درس تجريبي",
      stepFee: "رسوم التسجيل",
      stepStudent: "طالب",
      stepDone: "تمّ",
      stepNow: "الآن",
      stepSkipped: "تم تخطيه",
      stepLater: "لاحقًا",
      nextBookPlacement: "احجز اختبار تحديد المستوى لمعرفة المستوى المناسب.",
      nextRecordPlacement: "سجّل نتيجة الاختبار بعد انعقاده.",
      nextBookTrial: "احجز درسًا تجريبيًا، أو سجّل رسوم التسجيل.",
      nextRecordTrial: "سجّل نتيجة الدرس التجريبي.",
      nextFee: "سجّل رسوم التسجيل.",
      nextConvert: "تم تسجيل الرسوم. أنشئ سجل الطالب.",
      nextStudent: "أصبح هذا العميل طالبًا.",
      nextLost: "أُغلق هذا العميل كعميل مفقود.",
      bookPlacement: "حجز اختبار تحديد المستوى",
      bookTrial: "حجز درس تجريبي",
      recordFee: "تسجيل رسوم التسجيل",
      editFee: "تعديل الرسوم",
      convert: "إنشاء طالب",
      openStudent: "فتح ملف الطالب",
      markLost: "تحديده كمفقود",
      reopen: "إعادة فتح العميل",
      lostTitle: "تحديد هذا العميل كمفقود؟",
      lostBody: "اختر السبب. يمكنك إعادة فتحه لاحقًا.",
      lostReason: "سبب الفقد",
      noLostReasons:
        "لا توجد أسباب فقد متاحة لهذا الحساب. يمكن للمسؤول إضافتها ضمن أسباب الفقد.",
      openLostReasons: "افتح أسباب الفقد.",
      lostToast: "تم تحديد العميل كمفقود.",
      reopenToast: "تمت إعادة فتح العميل.",
      lostBecause: "سبب الفقد",
      details: "التفاصيل",
      placements: "اختبارات تحديد المستوى",
      trials: "الدروس التجريبية",
      fee: "رسوم التسجيل",
      noPlacements: "لا توجد اختبارات بعد.",
      noTrials: "لا توجد دروس تجريبية بعد.",
      noFee: "لم تُسجَّل رسوم بعد.",
      feeTitle: "رسوم التسجيل",
      feeDescription: "سجّل الإجمالي وما دفعه الشخص حتى الآن.",
      feeToast: "تم حفظ رسوم التسجيل.",
      groupMembers: "ضمن مجموعة مع",
      primaryContact: "جهة التواصل الرئيسية",
      convertTitle: "إنشاء طالب",
      convertDescription:
        "أضف بيانات الهوية التي يحتاجها النظام. بيانات التواصل تأتي من العميل.",
      convertToast: "تم إنشاء الطالب.",
    },
    booking: {
      placementTitle: "حجز اختبار تحديد المستوى",
      trialTitle: "حجز درس تجريبي",
      editTitle: "تعديل الحجز",
      when: "التاريخ والوقت",
      hour: "وقت البدء",
      onTheHour: "تبدأ الحجوزات في بداية الساعة.",
      timeZone: "المنطقة الزمنية",
      room: "القاعة",
      chooseRoom: "اختر قاعة. الحجز في الفرع يحتاج إلى قاعة.",
      meetingRequired: "أضف رابط الاجتماع.",
      noRoom: "بلا قاعة بعد",
      meetingLink: "رابط الاجتماع",
      meetingHint: "استخدم رابط https. الروابط للفروع عن بُعد فقط.",
      meetingInvalid: "استخدم رابطًا يبدأ بـ https://",
      topic: "موضوع الدرس",
      byCourse: "دورة",
      byArea: "مجال دراسة",
      course: "الدورة",
      chooseCourse: "اختر دورة.",
      chooseArea: "اختر مجال دراسة.",
      placementCourseMissing:
        "لا توجد دورة اختبار في Moodle لهذا المجال. اطلب من المدير العام ربط دورة.",
      book: "حجز",
      saveChanges: "حفظ التغييرات",
      bookedToast: "تم حفظ الحجز.",
      updatedToast: "تم تحديث الحجز.",
      moodlePassword: "كلمة مرور Moodle للاختبار",
      resultTitle: "تسجيل النتيجة",
      resultDescription: "احفظ النتيجة. يُغلق الحجز كمكتمل.",
      score: "الدرجة أو المستوى",
      scoreHint: "مثل: B1 أو 72.",
      mentor: "المعلم المرشد",
      noMentors: "لا يوجد معلمون في هذا الفرع.",
      recommended: "الدورة المقترحة",
      noRecommendation: "بلا اقتراح",
      notes: "ملاحظات",
      resultToast: "تم حفظ النتيجة.",
      syncMoodle: "جلب النتيجة من Moodle",
      syncToast: "تم تحديث النتيجة من Moodle.",
      fromMoodle: "من Moodle",
      recordedBy: "سجّلها",
      noShow: "تحديده كغائب",
      noShowTitle: "تحديده كغائب؟",
      noShowBody: "لم يحضر الشخص. يمكنك حجز موعد جديد.",
      noShowToast: "تم تحديده كغائب.",
      cancel: "إلغاء الحجز",
      cancelTitle: "إلغاء هذا الحجز؟",
      cancelBody: "اختر السبب. يصبح الموعد متاحًا.",
      cancelToast: "تم إلغاء الحجز.",
      change: "تعديل",
      joinLink: "فتح رابط الاجتماع",
      result: "النتيجة",
    },
    agenda: {
      placementsTitle: "اختبارات تحديد المستوى",
      placementsDescription:
        "كل اختبارات تحديد المستوى في نطاقك، حسب اليوم. احجزها من صفحة العميل أو الطالب.",
      trialsTitle: "الدروس التجريبية",
      trialsDescription:
        "كل الدروس التجريبية في نطاقك، حسب اليوم. احجزها من صفحة العميل أو الطالب.",
      upcoming: "القادمة",
      needsResult: "بانتظار النتيجة",
      completed: "مكتملة",
      missed: "غياب",
      cancelled: "ملغاة",
      today: "اليوم",
      tomorrow: "غدًا",
      emptyUpcoming: "لا توجد حجوزات.",
      emptyNeedsResult: "كل الحجوزات السابقة لها نتيجة.",
      emptyOther: "لا شيء هنا بعد.",
      emptyHint: "احجز من صفحة مسار العميل.",
      subjectLead: "عميل محتمل",
      subjectStudent: "طالب",
      allBranches: "كل الفروع",
      branch: "الفرع",
    },
    students: {
      title: "الطلاب",
      description: "كل المسجلين في مركز النيل، ودوراتهم، ورصيدهم، ووصولهم إلى Moodle.",
      add: "إضافة طالب",
      createTitle: "إضافة طالب",
      editTitle: "تعديل الطالب",
      createDescription: "أنشئ طالبًا لم يأتِ عن طريق عميل محتمل.",
      editDescription: "حدّث بيانات التواصل أو الهوية أو المسؤول.",
      createSubmit: "إنشاء الطالب",
      createdToast: "تم إنشاء الطالب.",
      updatedToast: "تم تحديث الطالب.",
      empty: "لا يوجد طلاب مطابقون.",
      emptyHint: "أضف طالبًا أو امسح التصفية.",
      noAccess: "الطلاب من اختصاص فريق القبول.",
      person: "الشخص",
      branch: "الفرع الأساسي",
      owner: "المسؤول",
      moodle: "Moodle",
      moodleLinked: "مرتبط",
      moodleMissing: "غير مرتبط",
      registration: "رسوم التسجيل",
      noFee: "بلا رسوم",
      added: "تاريخ الإضافة",
      note: "ملاحظة",
      allBranches: "كل الفروع",
      contact: "التواصل",
      identity: "الهوية",
      guardians: "أولياء الأمور",
      noGuardians: "لا يوجد أولياء أمور مسجلون.",
      tabOverview: "نظرة عامة",
      tabCourses: "الدورات",
      tabLearning: "التعلّم",
      tabBookings: "الاختبارات والدروس التجريبية",
      tabReport: "التقرير",
      warnings: "ملاحظات من النظام",
      moodleCreate: "إنشاء حساب Moodle",
      moodleLink: "ربط حساب Moodle",
      moodleReset: "إعادة تعيين كلمة مرور Moodle",
      moodlePassword: "كلمة مرور Moodle",
      moodleToast: "تم تحديث حساب Moodle.",
      moodleResetTitle: "إعادة تعيين كلمة مرور Moodle؟",
      moodleResetBody: "يضع النظام كلمة مرور عشوائية جديدة. شاركها مع الطالب مرة واحدة.",
      disable: "تعطيل الطالب",
      disableTitle: "تعطيل هذا الطالب؟",
      disableBody: "لن يحصل على التحاقات جديدة. يبقى سجلّه كما هو.",
      disabledToast: "تم تعطيل الطالب.",
      enable: "تفعيل الطالب",
      enableTitle: "تفعيل هذا الطالب؟",
      enableBody: "يمكنه الحصول على التحاقات جديدة مرة أخرى.",
      enabledToast: "تم تفعيل الطالب.",
      learningEmpty: "لا توجد درجات من Moodle بعد.",
      learningClass: "الفصل",
      learningGrade: "درجة الدورة",
      learningCompletion: "الإكمال",
      learningDone: "مكتمل",
      learningOngoing: "قيد التقدم",
      print: "طباعة التقرير",
      reportTitle: "التقرير الأكاديمي",
      reportGenerated: "تاريخ الإنشاء",
      reportLearningError: "درجات Moodle غير متاحة الآن.",
      fromLead: "من عميل محتمل",
    },
    enrolments: {
      title: "الالتحاقات",
      description: "مبيعات الدورات من الدفع حتى الفصل. أضف المبيعات المدفوعة إلى فصل فيه مقاعد.",
      empty: "لا توجد التحاقات مطابقة.",
      emptyHint: "بِع دورة من صفحة الطالب.",
      noAccess: "الالتحاقات من اختصاص فريق القبول.",
      waiting: "بانتظار الإجراء",
      sell: "بيع دورة",
      saleTitle: "بيع دورة",
      saleDescription: "افتح عملية بيع دورة. يمكن أن يأتي الدفع لاحقًا.",
      saleToast: "تم فتح بيع الدورة.",
      student: "الطالب",
      findStudent: "ابحث في الطلاب",
      typeToSearch: "اكتب حرفين على الأقل.",
      noStudents: "لا يوجد طلاب مطابقون.",
      course: "الدورة",
      kind: "نوع الفصل",
      group: "مجموعة",
      individual: "فردي",
      branch: "الفرع",
      class: "الفصل",
      balance: "الرصيد",
      opened: "تاريخ الفتح",
      noClass: "بلا فصل بعد",
      nextLevel: "المستوى التالي",
      recordPayment: "تسجيل دفعة",
      paymentTitle: "تسجيل دفعة",
      paymentDescription: "حدّث الإجمالي أو ما دفعه الطالب حتى الآن.",
      paymentToast: "تم حفظ الدفعة.",
      attach: "إضافة إلى فصل",
      attachTitle: "إضافة إلى فصل",
      attachDescription: "الفصول النشطة لهذه الدورة في هذا الفرع. الفصول الممتلئة لا تقبل طلابًا.",
      seatsLeft: "مقاعد متاحة",
      full: "ممتلئ",
      noClasses: "لا يوجد فصل نشط لهذه الدورة في هذا الفرع بعد.",
      attachToast: "تمت إضافة الطالب إلى الفصل.",
      moodleRequired: "يحتاج الطالب إلى حساب Moodle قبل الانضمام إلى فصل.",
      complete: "تحديده كمكتمل",
      completeTitle: "تحديد هذا الالتحاق كمكتمل؟",
      completeBody: "استخدم هذا عندما ينهي الطالب الدورة.",
      completeToast: "اكتمل الالتحاق.",
      leave: "تحديده كمنسحب",
      leaveTitle: "تحديد بيع المستوى التالي كمنسحب؟",
      leaveBody: "اختر سبب عدم أخذ الطالب لهذا المستوى.",
      leaveToast: "تم تحديد الالتحاق كمنسحب.",
      cancel: "إلغاء البيع",
      cancelTitle: "إلغاء بيع هذه الدورة؟",
      cancelBody: "اختر السبب. لا يمكن التراجع عن ذلك.",
      cancelToast: "تم إلغاء بيع الدورة.",
      schedule: "الجدول",
      teachers: "المعلمون",
    },
    identity: {
      nationality: "الجنسية",
      nationalityHint: "رمز من ثلاثة أحرف، مثل EGY.",
      address: "العنوان",
      gender: "النوع",
      male: "ذكر",
      female: "أنثى",
      dateOfBirth: "تاريخ الميلاد",
      nationalId: "الرقم القومي",
      nationalIdHint: "14 رقمًا. مطلوب للمصريين.",
      passport: "رقم جواز السفر",
      guardian: "ولي الأمر",
      secondGuardian: "ولي الأمر الثاني",
      guardianHint: "الطلاب دون 18 عامًا يحتاجون إلى ولي أمر واحد على الأقل.",
      guardianName: "الاسم",
      guardianPhone: "الهاتف",
      guardianEmail: "البريد الإلكتروني",
      relationship: "صلة القرابة",
      relationshipHint: "مثل: الأم، أو الأب، أو العم.",
      addGuardian: "إضافة ولي أمر ثانٍ",
      removeGuardian: "إزالة",
      invalidNationality: "استخدم رمزًا من ثلاثة أحرف.",
      invalidNationalId: "استخدم 14 رقمًا.",
      nationalIdRequired: "مطلوب للمصريين.",
      guardianRequired: "الطلاب دون 18 عامًا يحتاجون إلى ولي أمر.",
      guardianIncomplete: "املأ كل حقول ولي الأمر.",
    },
  },
  dateOfBirth: {
    day: "اليوم",
    month: "الشهر",
    year: "السنة",
    monthPlaceholder: "الشهر",
    clear: "مسح التاريخ",
    hint: "مثال: 4 مارس 2012.",
    incompleteDate: "أدخل اليوم والشهر وسنة من أربعة أرقام.",
    invalidDate: "هذا التاريخ غير موجود. راجع اليوم والشهر.",
    futureDate: "لا يمكن أن يكون تاريخ الميلاد في المستقبل.",
    tooEarly: "أدخل سنة من 1900 أو بعدها.",
    age: "العمر {n} سنة",
  },
  datePicker: {
    placeholder: "اختر تاريخًا",
    today: "اليوم",
    clear: "مسح",
    previousMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    previousYear: "السنة السابقة",
    nextYear: "السنة التالية",
    chooseMonth: "اختر الشهر والسنة",
    unavailable: "غير متاح",
    calendar: "التقويم",
  },
  language: {
    label: "اللغة",
  },
  reports: {
    title: "التقارير",
    description: "اقرأ تقريرًا، ثم صدّره. الأرقام تأتي مباشرة من EMS.",
    report: "التقرير",
    tabs: {
      admissions: "القبول",
      bookings: "الحجوزات",
      enrolments: "الالتحاقات",
      classes: "الفصول",
    },
    period: "الفترة",
    asOfToday: "حتى اليوم",
    branch: "الفرع",
    allBranches: "كل الفروع",
    exportCsv: "تصدير CSV",
    truncated: "يُعرض أول {n} من أصل {total} صفًا من EMS.",
    showAll: "عرض الكل ({n})",
    showLess: "عرض أقل",
    emptyTitle: "لا شيء للإبلاغ عنه",
    emptyAdmissions: "لم يُنشأ أي عميل محتمل في هذه الفترة.",
    emptyBookings: "لم تُجدول أي اختبارات أو حصص تجريبية في هذه الفترة.",
    emptyEnrolments: "لا توجد التحاقات.",
    emptyClasses: "لا توجد فصول نشطة حاليًا.",
    emptyPlacements: "لا توجد اختبارات تحديد مستوى في هذه الفترة.",
    emptyTrialLessons: "لا توجد حصص تجريبية في هذه الفترة.",
    emptyTrialResults: "لم تُسجل نتائج للحصص التجريبية في هذه الفترة.",
    emptyScores: "لا توجد اختبارات تحديد مستوى بدرجات في هذه الفترة.",
    emptyLostReasons: "لا يوجد عملاء مفقودون في هذه الفترة.",
    emptyWeekdays: "لا توجد أيام مجدولة للفصول.",
    changePeriod: "تغيير الفترة",
    liveFootnote: "كل رقم محسوب مباشرة من بيانات EMS عبر واجهة الموظفين.",
    footnoteAdmissions:
      "الحالات هي حالات اليوم للعملاء المحتملين الذين أُنشئوا في الفترة المحددة.",
    footnoteBookings: "تُحسب الحجوزات حسب تاريخها المجدول.",
    footnoteEnrolments:
      "تُحسب الالتحاقات حسب تاريخ الالتحاق أو الإلغاء. المبالغ مجمعة كما هي مسجلة في EMS، من دون عملة.",
    footnoteClasses: "قراءة لحظية للفصول النشطة.",
    newLeads: "عملاء محتملون جدد",
    registered: "مسجلون",
    lost: "مفقودون",
    open: "مفتوحون",
    conversion: "معدل التحويل",
    rate: "التحويل",
    intake: "تدفق العملاء",
    intakePerWeek: "عملاء جدد كل أسبوع",
    intakePerMonth: "عملاء جدد كل شهر",
    funnel: "من الاستفسار إلى التسجيل",
    funnelDecided: "تم البت فيهم",
    bySource: "حسب المصدر",
    byLostReason: "حسب سبب الفقدان",
    byOwner: "حسب المسؤول",
    byArea: "حسب مجال الدراسة",
    byBranch: "حسب الفرع",
    studyMode: "نمط الدراسة",
    leadType: "نوع العميل",
    noSource: "من دون مصدر",
    noReason: "لم يُسجل سبب",
    noOwner: "من دون مسؤول",
    notSet: "غير محدد",
    modes: {
      online: "عن بُعد فقط",
      onsite: "حضوري فقط",
      both: "كلاهما",
      unset: "لم يُختر",
    },
    leadTypes: {
      new: "جديد",
      old: "قديم",
      old_student: "طالب سابق",
      current_student: "طالب حالي",
    },
    count: "العدد",
    share: "النسبة",
    leads: "العملاء",
    placementTests: "اختبارات تحديد المستوى",
    trialLessons: "الحصص التجريبية",
    scheduled: "مجدول",
    completed: "مكتمل",
    noShow: "لم يحضر",
    cancelled: "ملغى",
    showRate: "نسبة الحضور",
    scoreSummary: "درجات تحديد المستوى",
    scoreAverage: "المتوسط",
    scoreMin: "الأدنى",
    scoreMax: "الأعلى",
    scoreBands: "توزيع الدرجات",
    trialResults: "نتائج الحصص التجريبية",
    trialsByCourse: "الحصص التجريبية حسب المقرر",
    trialToRegistered: "الحصص المكتملة التي أصبحت طلابًا",
    trials: "الحصص",
    pipeline: "المسار",
    rightNow: "الآن",
    inThisPeriod: "في هذه الفترة",
    enrolledInPeriod: "التحقوا في الفترة",
    cancelledInPeriod: "أُلغوا في الفترة",
    allTime: "كل الوقت",
    money: "الأموال",
    billed: "المفوتر",
    collected: "المحصَّل",
    outstanding: "المتبقي",
    outstandingPending: "متبقٍ للسداد (بانتظار الدفع)",
    collectionRate: "نسبة التحصيل",
    moneyNote: "المبالغ كما هي مسجلة في EMS، من دون عملة.",
    byCourse: "حسب المقرر",
    byKind: "حسب النوع",
    kinds: { individual: "فردي", group: "جماعي" },
    activeClasses: "فصول نشطة",
    seatsTaken: "مقاعد محجوزة",
    capacity: "السعة",
    fill: "نسبة الامتلاء",
    freeSeats: "مقاعد شاغرة",
    fillByCourse: "الامتلاء حسب المقرر",
    fillByDepartment: "الامتلاء حسب القسم",
    teacherLoad: "أعباء المعلمين",
    noTeacher: "من دون معلم",
    endingSoon: "تنتهي قريبًا",
    endingSoonEmpty: "لا تنتهي أي فصول خلال 30 يومًا القادمة.",
    daysLeft: "أيام متبقية",
    weekdayLoad: "الفصول حسب اليوم",
    classes: "الفصول",
    students: "الطلاب",
    seats: "المقاعد",
    active: "نشط",
    pending: "معلق",
    leftCancelled: "غادر / أُلغي",
    enrolled: "ملتحق",
    placements: "الاختبارات",
    score: "الدرجة",
    course: "المقرر",
    department: "القسم",
    name: "الاسم",
    endDate: "تاريخ الانتهاء",
    csv: {
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      branch: "الفرع",
      source: "المصدر",
      status: "الحالة",
      lostReason: "سبب الفقدان",
      owner: "المسؤول",
      area: "مجال الدراسة",
      studyMode: "نمط الدراسة",
      created: "تاريخ الإنشاء",
      type: "النوع",
      person: "الشخص",
      scheduled: "الموعد المجدول",
      result: "النتيجة",
      courseOrArea: "المقرر / المجال",
      recommended: "المقرر الموصى به",
      student: "الطالب",
      course: "المقرر",
      className: "الفصل",
      enrolled: "تاريخ الالتحاق",
      cancelled: "تاريخ الإلغاء",
      toBePaid: "المستحق",
      paid: "المدفوع",
      remaining: "المتبقي",
      department: "القسم",
      teachers: "المعلمون",
      schedule: "الجدول",
      capacity: "السعة",
      taken: "المحجوز",
      fill: "نسبة الامتلاء %",
      start: "البداية",
      end: "النهاية",
    },
  },
};
