import type { StaffMessages } from "./copy";

/** Staff app copy in Chinese (Simplified). Keys mirror copy.ts; TypeScript enforces it. */
export const zh: StaffMessages = {
  brand: {
    name: "尼罗中心",
    product: "教育管理"
  },
  nav: {
    overview: "首页",
    dashboard: "仪表板",
    reports: "报告",
    forms: "表单",
    notifications: "通知",
    admissions: "招生",
    students: "学生",
    leads: "潜在学员",
    enrolments: "报名",
    placementTests: "分级测试",
    trialLessons: "试听课",
    delivery: "教学",
    courses: "课程",
    classes: "班级",
    sessions: "我的一周",
    rooms: "教室",
    organisation: "人员与场所",
    staffUsers: "员工",
    branches: "校区",
    departments: "部门",
    setup: "设置",
    lostReasons: "流失原因",
    actionReasons: "操作原因",
    areasOfStudy: "学习领域",
    customFields: "自定义字段",
    system: "系统",
    moodleSite: "Moodle",
    systemHealth: "系统状态",
    auditLog: "审计日志",
    profile: "个人资料"
  },
  roles: {
    super_admin: "超级管理员",
    branch_admin: "校区管理员",
    vice_manager: "副经理",
    hod: "系主任",
    registrar: "教务登记员",
    ssa: "学生成功顾问",
    teacher: "教师"
  },
  shell: {
    backTo: "返回{page}",
    collapseSidebar: "收起侧边栏",
    expandSidebar: "展开侧边栏",
    staffNav: "员工导航",
    openMenu: "打开菜单",
    closeMenu: "关闭菜单",
    displaySize: "显示尺寸",
    displayStandard: "标准",
    displayLarge: "大",
    displayXLarge: "特大",
    workspace: "工作区",
    chooseWorkspace: "选择校区",
    workspaceHint: "你的角色每次只在一个校区内工作。请选择要工作的校区。",
    noWorkspaces: "目前还没有为你分配任何启用的校区。",
    notifications: "通知",
    markAllRead: "全部标为已读",
    viewAll: "查看所有通知",
    userMenu: "用户菜单",
    signOut: "退出登录",
    signOutEverywhere: "在所有设备上退出",
    roleView: "角色视图",
    roleViewTitle: "角色视图",
    roleViewBody: "以较低权限的角色查看应用。可将数据限定在所选校区、部门或班级。",
    viewingAs: "当前查看身份",
    ownRole: "你的角色",
    roleViewChanged: "角色视图已更新。",
    scopesApplied: "范围已应用。",
    roleViewEnded: "你已回到自己的角色。",
    returnToRole: "回到我的角色",
    applyScopes: "应用",
    viewAsRole: "以其他角色查看",
    editRoleView: "编辑",
    scopeBranches: "校区",
    scopeBranch: "校区",
    scopeDepartments: "部门",
    scopeClasses: "班级",
    allBranches: "所有校区",
    allDepartments: "所有部门",
    allClasses: "所有班级",
    branchesNoun: "个校区",
    departmentsNoun: "个部门",
    classesNoun: "个班级",
    searchBranches: "搜索校区",
    searchDepartments: "搜索部门",
    searchClasses: "搜索班级",
    chooseWorkspaceOption: "选择一个校区",
    noAccess: "无访问权限",
    noAccessHint: "你当前的角色无法打开此页面。请返回仪表板。",
    backToDashboard: "返回仪表板",
    checkingSession: "正在检查会话",
    signedInAs: "当前登录身份",
    search: "搜索或跳转",
    breadcrumb: "导航路径",
    commandPages: "页面",
    commandPeople: "员工",
    commandActions: "操作",
    commandEmpty: "没有结果。"
  },
  state: {
    loading: "加载中",
    notSet: "未设置",
    retry: "重试",
    empty: "这里还没有内容。",
    error403: "你无权访问此页面。",
    error404: "此记录已不存在。",
    error409: "此更改与较新的更新冲突。请重新加载后重试。",
    error422: "请检查标出的字段后重试。",
    error429: "请求过多。请稍等片刻再试。",
    error503: "此服务当前未启用。请稍后再试。",
    errorNetwork: "网络连接失败。请检查你的网络。",
    errorGeneric: "请求失败。请重试。"
  },
  status: {
    active: "启用",
    disabled: "已停用",
    invited: "已邀请",
    canceled: "已取消",
    cancelled: "已取消",
    enrolled: "已报名",
    completed: "已完成",
    registered: "已注册",
    scheduled: "已安排",
    pending: "待处理",
    pending_payment: "待付款",
    pending_class: "待分班",
    pending_group: "待成组",
    in_process: "处理中",
    follow_up: "待跟进",
    future_registration: "未来注册",
    trial_lesson: "试听课",
    placement_test: "分级测试",
    left: "已退出",
    lost: "已流失",
    no_show: "未到场",
    healthy: "正常",
    degraded: "性能下降",
    unhealthy: "异常",
    ok: "正常",
    warning: "警告",
    error: "错误",
    not_configured: "未配置"
  },
  notifications: {
    title: "通知",
    description: "仅限你的收件箱。",
    all: "全部",
    unread: "未读",
    empty: "你没有任何通知。",
    markRead: "标为已读",
    markAllRead: "全部标为已读",
    delete: "删除",
    deleteAll: "全部删除",
    deleteAllTitle: "删除所有通知？",
    deleteAllBody: "这将永久删除你的副本。其他员工的副本不受影响。",
    read: "已读",
    unreadBadge: "未读",
    markedRead: "通知已标为已读。",
    allMarkedRead: "所有通知已标为已读。",
    deleted: "通知已删除。",
    allDeleted: "所有通知已删除。",
    actionFailed: "通知操作失败。请重试。"
  },
  profile: {
    title: "个人资料",
    description: "管理你的资料、密码和活跃会话。",
    details: "你的资料",
    role: "分配的角色",
    email: "电子邮箱",
    name: "姓名",
    nameNotSet: "未设置",
    phone: "电话",
    unknownDevice: "未知设备",
    password: "密码",
    currentPassword: "当前密码",
    newPassword: "新密码",
    confirmPassword: "确认新密码",
    changePassword: "修改密码",
    passwordChanged: "密码已修改。",
    passwordFailed: "密码修改失败。请检查你的输入。",
    passwordsDiffer: "两次输入的新密码不一致。",
    sessions: "活跃会话",
    sessionsHint: "如有你不认识的会话，请将其退出。",
    thisSession: "当前会话",
    lastSeen: "最近活动",
    issued: "登录时间",
    signOutSession: "退出此会话",
    sessionRevoked: "会话已退出。",
    signOutEverywhere: "在所有设备上退出",
    signOutEverywhereTitle: "在所有设备上退出？",
    signOutEverywhereBody: "这会让你在所有设备上退出登录。你需要重新登录。"
  },
  actions: {
    save: "保存",
    cancel: "取消",
    saving: "正在保存",
    discardTitle: "放弃更改？",
    discardBody: "你的更改尚未保存。",
    discard: "放弃",
    keepEditing: "继续编辑",
    search: "搜索",
    filter: "筛选",
    columns: "列",
    selected: "已选",
    clearSelection: "清除选择",
    previous: "上一页",
    next: "下一页",
    pageOf: "/",
    create: "创建",
    edit: "编辑",
    rowActions: "行操作",
    enable: "启用",
    disable: "停用",
    close: "关闭",
    import: "导入",
    refresh: "刷新",
    noReasons: "请先为此操作添加一个操作原因。",
    openActionReasons: "打开操作原因。",
    status: "状态",
    activeOnly: "仅启用的",
    selectAll: "选择所有行",
    selectRow: "选择此行",
    pagination: "分页"
  },
  catalog: {
    shared: {
      name: "名称",
      nameRequired: "请输入名称。",
      code: "代码",
      codeHint: "小写字母、数字和下划线。",
      codePattern: "只能使用小写字母、数字和下划线。",
      sortOrder: "排序",
      created: "创建时间",
      status: "状态",
      active: "启用",
      disabled: "已停用",
      allStatuses: "所有状态",
      access: "你的权限",
      accessManage: "管理",
      accessView: "查看",
      customFields: "自定义字段",
      customFieldsEmpty: "此记录没有适用的自定义字段。",
      enableTitle: "启用此记录？",
      disableTitle: "停用此记录？",
      enableBody: "此记录将重新可用。",
      createdToast: "已创建。",
      updatedToast: "更改已保存。",
      enabledToast: "已启用。",
      disabledToast: "已停用。",
      saveChanges: "保存更改"
    },
    branches: {
      title: "校区",
      description: "尼罗中心运营的地点。",
      empty: "还没有校区。",
      emptyHint: "创建第一个校区。",
      add: "添加校区",
      createTitle: "添加校区",
      editTitle: "编辑校区",
      createDescription: "创建一个启用的校区。",
      editDescription: "更新名称、代码或设置。",
      createSubmit: "创建校区",
      timezone: "时区",
      online: "线上校区",
      onlineYes: "线上",
      onlineNo: "线下",
      searchBranches: "搜索校区",
      disableBody: "该校区将不再接受新工作。在此校区的会话将失去其工作区。",
      statisticsTitle: "活动",
      detailMissing: "此校区已不存在。",
      statActiveStudents: "在读学生",
      statOpenLeads: "未结潜在学员",
      statActiveClasses: "开课中的班级",
      statEnrolmentFill: "已占座位",
      statEnrolmentCapacity: "报名容量",
      statPendingEnrolments: "待处理报名",
      statPlacements: "已安排的分级测试",
      statTrials: "已安排的试听课",
      statStaff: "员工",
      bulkDisable: "停用所选",
      bulkEnable: "启用所选",
      bulkDone: "所选内容已更新。"
    },
    departments: {
      title: "部门",
      description: "班级和课程背后的教学部门。",
      empty: "还没有部门。",
      emptyHint: "创建第一个部门。",
      add: "添加部门",
      createTitle: "添加部门",
      editTitle: "编辑部门",
      createSubmit: "创建部门",
      disableBody: "该部门不再用于新工作。"
    },
    lostReasons: {
      title: "流失原因",
      description: "潜在学员被标为流失的原因。",
      empty: "还没有流失原因。",
      emptyHint: "创建第一个流失原因。",
      add: "添加流失原因",
      createTitle: "添加流失原因",
      editTitle: "编辑流失原因",
      createSubmit: "创建原因",
      disableBody: "该原因不再用于新工作。"
    },
    actionReasons: {
      title: "操作原因",
      description: "受保护操作所需的命名原因。",
      empty: "还没有操作原因。",
      emptyHint: "创建或导入第一个原因。",
      add: "添加操作原因",
      createTitle: "添加操作原因",
      editTitle: "编辑操作原因",
      createSubmit: "创建原因",
      disableBody: "该原因不再用于新工作。",
      kind: "类型",
      allKinds: "所有类型",
      import: "导入 CSV",
      importTitle: "导入操作原因",
      importDescription: "粘贴 CSV 行或选择文件。先预览，再导入。",
      chooseFile: "选择 CSV 文件",
      downloadTemplate: "下载模板",
      orPaste: "或粘贴 CSV 行",
      importPreview: "预览",
      importRowCount: "行",
      rowError: "错误",
      rowErrorColumns: "应为 6 列。",
      rowErrorKind: "未知类型。",
      rowErrorName: "名称为必填项。",
      importEmpty: "粘贴 CSV 行以预览。",
      importSubmit: "导入",
      importDone: "导入完成。",
      importCreated: "已创建",
      importUpdated: "已更新",
      csvPlaceholder: "id,action,name,status,sort_order,created_at",
      kindLost: "潜在学员流失",
      kindLeft_enrolment: "退出报名",
      kindCancel_enrolment: "取消报名",
      kindCancel_placement_test: "取消分级测试",
      kindCancel_trial_lesson: "取消试听课",
      kindDisable_student: "停用学生",
      kindDisable_course: "停用课程",
      kindDisable_class: "停用班级",
      kindDisable_branch: "停用校区",
      kindDisable_department: "停用部门",
      kindDisable_room: "停用教室",
      kindDisable_staff: "停用员工",
      kindDisable_area_of_study: "停用学习领域",
      kindDisable_custom_field: "停用自定义字段"
    },
    areasOfStudy: {
      title: "学习领域",
      description: "学生可被分入的科目。",
      empty: "还没有学习领域。",
      emptyHint: "创建第一个学习领域。",
      add: "添加学习领域",
      createTitle: "添加学习领域",
      editTitle: "编辑学习领域",
      createSubmit: "创建领域",
      disableBody: "该领域不再用于新的分级。",
      placementCourses: "分级测试课程",
      placementCoursesHint: "选择承载分级测试的 Moodle 课程。",
      addCourse: "添加 Moodle 课程",
      searchCourses: "搜索 Moodle 课程",
      coursesEmpty: "没有匹配的课程。",
      coursesLoading: "正在加载课程",
      coursesError: "Moodle 课程不可用。"
    },
    customFields: {
      title: "自定义字段",
      description: "应用中各类记录的额外字段。",
      empty: "还没有自定义字段。",
      emptyHint: "创建第一个自定义字段。",
      add: "添加自定义字段",
      createTitle: "添加自定义字段",
      editTitle: "编辑自定义字段",
      createSubmit: "创建字段",
      disableBody: "该字段不再显示在表单中。",
      entity: "对象",
      allEntities: "所有对象",
      fieldKey: "字段键",
      fieldKeyHint: "数据模型中使用的小写标识符。创建后无法更改。",
      fieldType: "类型",
      required: "必填字段",
      requiredYes: "必填",
      optional: "选填",
      helpText: "帮助文字",
      options: "选项",
      optionsHint: "每行一个选项。",
      entityUser_profile: "员工资料",
      entityStudent: "学生",
      entityLead: "潜在学员",
      entityBranch: "校区",
      entityDepartment: "部门",
      entityClass: "班级",
      entityCourse: "课程",
      entityRoom: "教室"
    }
  },
  staffUsers: {
    title: "员工",
    description: "在尼罗中心工作的每个人，他们的角色、工作地点和登录方式。",
    add: "添加员工",
    createTitle: "添加员工",
    editTitle: "编辑员工",
    createDescription: "创建带有角色和范围的员工账户。",
    editDescription: "更新角色、资料或范围。",
    createSubmit: "创建员工",
    empty: "还没有员工用户。",
    emptyHint: "邀请第一位员工用户。",
    noAccess: "员工账户由超级管理员和校区管理员管理。",
    person: "人员",
    email: "电子邮箱",
    role: "角色",
    worksAt: "工作地点",
    branches: "校区",
    departments: "部门",
    courses: "课程",
    moodle: "Moodle",
    status: "状态",
    lastSignIn: "最近登录",
    added: "添加时间",
    you: "你",
    all: "全部",
    results: "结果",
    clearFilters: "清除筛选",
    teachersNoMoodle: "未关联 Moodle 的教师",
    allRoles: "所有角色",
    allBranches: "所有校区",
    allDepartments: "所有部门",
    globalScope: "所有校区",
    branchScope: "校区范围",
    branchScopeHint: "副经理只能有一个校区。教务登记员、学生成功顾问和教师至少需要一个。",
    workspaceScopeHint: "新账户必须包含你的工作区校区。",
    invited: "已邀请",
    moodleLinked: "已关联",
    moodleMissing: "未关联",
    provisioning: "开通方式",
    provisioningInvitation: "邀请链接",
    provisioningManual: "手动设置密码",
    provisioningHint: "邀请会生成一次性链接。手动方式会生成临时密码。",
    firstName: "名",
    lastName: "姓",
    phone: "电话",
    address: "地址",
    nationality: "国籍",
    nationalityHint: "三个字母的国家代码。",
    dateOfBirth: "出生日期",
    notes: "备注",
    canTakePlacementTest: "可以主持分级测试",
    yourPassword: "你的密码",
    yourPasswordHint: "此超级管理员更改需要输入你自己的密码才能继续。",
    yourPasswordRequired: "请输入你自己的密码以继续。",
    firstNameRequired: "名为必填项。",
    lastNameRequired: "姓为必填项。",
    emailRequired: "请输入有效的电子邮箱。",
    branchScopeRequired: "请至少选择一个校区。",
    viceManagerScope: "副经理只能有一个校区。",
    invite: "邀请",
    resendInvite: "重新发送邀请",
    inviteTitle: "发送新的邀请？",
    inviteBody: "之前的邀请链接将失效。",
    cancelInvite: "取消邀请",
    cancelInviteTitle: "取消此邀请？",
    cancelInviteBody: "邀请链接将立即失效。",
    setPassword: "设置密码",
    setPasswordTitle: "设置新密码？",
    setPasswordBody: "临时密码只生成一次。请通过安全渠道分享。",
    moodleAccount: "Moodle 账户",
    moodleCreate: "创建 Moodle 账户",
    moodleLink: "关联 Moodle 账户",
    moodleReset: "重置 Moodle 密码",
    moodleResetTitle: "重置 Moodle 密码？",
    moodleResetBody: "新的 Moodle 密码只生成一次。请通过安全渠道分享。",
    moodleSearch: "搜索 Moodle 账户",
    moodleSearchHint: "按姓名、用户名或邮箱搜索。",
    moodleSearchMin: "请至少输入 2 个字符。",
    moodleSearchEmpty: "没有匹配的 Moodle 账户。",
    moodleCreateHint: "创建一个与此员工关联的 Moodle 账户。",
    moodleLinkHint: "将现有的 Moodle 账户关联到此员工。",
    disableTitle: "停用此员工用户？",
    disableBody: "该账户将无法再登录。",
    enableTitle: "启用此员工用户？",
    enableBody: "该账户可以重新登录。",
    bulkDisable: "停用所选",
    bulkEnable: "启用所选",
    bulkDone: "所选内容已更新。",
    createdToast: "员工用户已创建。",
    updatedToast: "更改已保存。",
    invitedToast: "邀请已创建。",
    cancelledToast: "邀请已取消。",
    passwordToast: "密码已重置。",
    moodleToast: "Moodle 账户已更新。",
    disabledToast: "员工用户已停用。",
    enabledToast: "员工用户已启用。",
    secretTitle: "一次性凭据",
    secretBody: "请立即复制。之后不会再显示。",
    secretShare: "只能通过安全渠道分享凭据。",
    secretDone: "完成",
    copyValue: "复制",
    copied: "已复制。",
    invitationLink: "邀请链接",
    temporaryPassword: "临时密码",
    moodlePassword: "Moodle 密码",
    moreActions: "更多操作",
    copyEmail: "复制邮箱",
    emailCopied: "邮箱已复制。",
    tabOverview: "概览",
    tabCourses: "课程",
    tabAvailability: "可上课时间",
    tabActivity: "活动",
    sectionContact: "联系方式",
    sectionAccess: "访问权限",
    sectionMore: "更多详情",
    neverSignedIn: "从未登录",
    statsAdmissions: "招生",
    statsTeaching: "教学",
    statLeadsCreated: "已创建的潜在学员",
    statLeadsAssigned: "已分配的潜在学员",
    statLeadsOpen: "未结潜在学员",
    statLeadsRegistered: "已注册",
    statLeadsLost: "已流失",
    statStudentsAssigned: "已分配的学生",
    statClassesTeaching: "任教班级",
    statSessionsScheduled: "已安排的课次",
    statStudentsTaught: "教过的学生",
    statsEmpty: "还没有活动记录。",
    coursesTitle: "可教授的课程",
    coursesHint: "列表为空表示无法把此教师分配到班级。",
    coursesSaved: "课程已更新。",
    coursesSearchPlaceholder: "搜索课程",
    placementCapability: "分级测试",
    placementYes: "可以主持分级测试",
    placementNo: "不能主持分级测试",
    availabilityTitle: "可上课时间",
    availabilityHint: "涂选此教师的工作时段。已预订的课次无法更改。",
    penAvailable: "可用",
    penUnavailable: "不可用",
    penClear: "清除",
    showAllHours: "显示全部时段",
    showWorkHours: "显示工作时段",
    timezoneLabel: "时区",
    unsavedBar: "你有未保存的更改。",
    saveChanges: "保存更改",
    discardChanges: "放弃",
    discardTitle: "放弃可上课时间的更改？",
    discardBody: "你涂选的更改尚未保存。",
    cellsSaved: "可上课时间已保存。",
    cellsSkippedBooked: "已跳过已预订的课次。",
    weekToday: "今天",
    weekPrevious: "上一周",
    weekNext: "下一周",
    bookedSession: "已预订"
  },
  moodleSite: {
    title: "Moodle 站点",
    description: "连接为课程、分组和考勤提供支持的 Moodle 站点。",
    noAccess: "只有超级管理员可以配置 Moodle 站点。",
    connection: "连接",
    connectionHint: "Moodle 实例的 Web 服务凭据。令牌只能写入。",
    siteUrl: "站点网址",
    token: "Web 服务令牌",
    tokenHint: "已安全存储。仅在更换令牌时重新输入。",
    tokenKeep: "留空以保留当前令牌。",
    autoCreate: "自动创建学生 Moodle 账户",
    autoCreateHint: "开启后，创建学生时也会尝试在 Moodle 中创建账户。",
    ptCourse: "分级测试 Moodle 课程 ID",
    ptCourseHint: "承载分级测试的 Moodle 课程。留空可清除。",
    save: "保存更改",
    connect: "连接 Moodle",
    test: "测试连接",
    disconnect: "断开连接",
    disconnectTitle: "断开 Moodle？",
    disconnectBody: "已存储的令牌将被删除。重新连接前，课程和分组将停止同步。",
    saved: "Moodle 配置已保存。",
    disconnected: "Moodle 已断开。",
    testOk: "连接测试成功。",
    testVersionWarn: "可以访问，但 Moodle 版本不在预期的 4.5.x 范围内。",
    testFailed: "无法访问 Moodle。",
    statusTitle: "状态",
    statConfigured: "已配置",
    statToken: "已存储令牌",
    statReachable: "可访问",
    statVersion: "版本符合预期",
    statSitename: "站点名称",
    statRelease: "发行版本",
    statLastChecked: "最近检查",
    statWarnings: "警告",
    statLastError: "最近错误",
    unknown: "未知",
    yes: "是",
    no: "否"
  },
  system: {
    title: "系统状态",
    description: "核心服务和 Moodle 集成的实时状态。",
    noAccess: "只有超级管理员可以查看系统状态。",
    refresh: "刷新",
    checked: "检查时间",
    componentApi: "API",
    componentDatabase: "数据库",
    componentSchema: "结构检查",
    componentMigration: "迁移",
    componentMoodle: "Moodle",
    operational: "运行正常。",
    version: "版本",
    configured: "已配置",
    token: "令牌",
    reachable: "可访问",
    site: "站点",
    release: "发行版本",
    expected: "预期 4.5.x",
    warnings: "警告"
  },
  audit: {
    title: "审计日志",
    description: "谁在何时做了什么。最新的在前。",
    noAccess: "只有超级管理员和校区管理员可以查看审计事件。",
    stream: "事件流",
    allStreams: "所有事件流",
    search: "搜索事件",
    empty: "没有审计事件。",
    emptyHint: "操作发生时会记录在这里。",
    payload: "数据内容",
    actor: "操作人",
    system: "系统",
    today: "今天",
    yesterday: "昨天",
    latest: "最近 {n} 个事件",
    failedSignIn: "有人",
    groups: {
      all: "全部",
      auth: "登录",
      admissions: "招生",
      teaching: "教学",
      setup: "设置"
    },
    nouns: {
      auth: "账户",
      branch: "校区",
      department: "部门",
      course: "课程",
      custom_field: "自定义字段",
      moodle_site: "Moodle 连接",
      student: "学生",
      lead: "潜在学员",
      placement_test: "分级测试",
      class: "班级",
      enrolment: "报名",
      room: "教室",
      session: "课次"
    },
    verbs: {
      created: "创建了{noun}",
      updated: "更新了{noun}",
      disabled: "停用了{noun}",
      enabled: "启用了{noun}",
      cancelled: "取消了{noun}",
      completed: "完成了{noun}",
      refreshed: "刷新了{noun}",
      tested: "测试了{noun}",
      other: "对{noun}执行了{action}"
    },
    actions: {
      login_success: "登录了",
      login_failed: "登录失败",
      logout: "退出了登录",
      workspace_switched: "切换了校区",
      role_switched: "更改了角色视图",
      invitation_sent: "发送了邀请给",
      invitation_accepted: "接受了邀请",
      user_created: "创建了员工账户",
      moodle_group_created: "创建了 Moodle 分组：",
      moodle_group_deleted: "移除了 Moodle 分组：",
      moodle_group_synced: "已与 Moodle 同步：",
      moodle_linked: "关联了 Moodle 账户：",
      converted: "转为学生：",
      enrolled: "为学生办理了报名"
    },
    streams: {
      auth: "登录",
      branch: "校区",
      department: "部门",
      course: "课程",
      custom_field: "自定义字段",
      moodle_site: "Moodle 站点",
      student: "学生",
      lead: "潜在学员",
      placement_test: "分级测试",
      class: "班级",
      enrolment: "报名",
      room: "教室",
      session: "课次"
    }
  },
  dashboard: {
    morning: "早上好",
    afternoon: "下午好",
    evening: "晚上好",
    nameSeparator: "，",
    intro: "以下是今天需要你处理的事项。",
    openLeads: "未结潜在学员",
    openLeadsNote: "尚未注册或流失",
    bookings: "即将进行的预约",
    tests: "测试",
    trials: "试听",
    waitingSales: "待处理的课程销售",
    waitingSalesNote: "仍缺少付款或班级",
    classFill: "班级满员率",
    seatsOf: "/",
    seats: "个座位已占",
    activeStudents: "在读学生",
    activeStudentsNote: "有启用的记录",
    today: "今天",
    todayEmpty: "今天没有预约。",
    overdue: "个过去的预约需要记录结果",
    openAgenda: "打开日程",
    attention: "需要关注",
    allClear: "一切正常",
    resultsToRecord: "待记录的结果",
    unpaid: "未付款的课程销售",
    waitingClass: "已付款，等待分班",
    unowned: "没有负责人的未结潜在学员",
    formResponses: "新的表单回复",
    period: "时间段",
    periods: {
      "7d": "7 天",
      "30d": "30 天",
      "90d": "90 天",
      "12m": "12 个月",
      all: "全部时间"
    },
    vsPrevious: "与上一时段相比",
    noChange: "无变化",
    pts: " 个百分点",
    newLeads: "新潜在学员",
    conversion: "转化率",
    conversionNote: "已决定的潜在学员中已注册的比例",
    intake: "潜在学员来源",
    intakeNote: "每周新潜在学员",
    weekOf: "周次",
    outcomes: "潜在学员结果",
    open: "未结",
    registered: "已注册",
    lost: "已流失",
    noData: "此时间段内没有潜在学员。",
    funnel: "从咨询到成为学生",
    funnelLeads: "潜在学员",
    funnelBooked: "已完成测试和试听",
    bookingsTitle: "测试和试听",
    placementTests: "分级测试",
    trialLessons: "试听课",
    completed: "已完成",
    scheduledLabel: "已安排",
    noShow: "未到场",
    cancelled: "已取消",
    showRate: "已到场",
    pipeline: "潜在学员进度",
    pipelineEmpty: "没有未结潜在学员。",
    branches: "校区",
    branch: "校区",
    students: "学生",
    classes: "班级",
    fill: "满员率",
    waiting: "等待中",
    placement: "分级测试",
    trial: "试听课",
    myClasses: "我的班级",
    myStudents: "我班上的学生",
    nextSession: "下一节课",
    noNextSession: "没有已预订的课次",
    sessions: "即将进行的课次",
    sessionsEmpty: "还没有已预订的课次。",
    classesEmpty: "还没有为你分配班级。",
    openMoodle: "在 Moodle 中打开",
    departmentClasses: "部门班级",
    seatsFree: "空余座位",
    noTeacher: "没有教师的班级",
    departmentEmpty: "你的部门还没有班级。",
    teachers: "教师",
    schedule: "时间安排",
    unassignedTeacher: "无教师",
    enrolled: "已报名",
    loadError: "部分数据无法加载。"
  },
  teaching: {
    hourUnit: "小时",
    seats: "个座位",
    seatsLeft: "剩余",
    full: "已满",
    allBranches: "所有校区",
    branch: "校区",
    required: "必填。",
    wholeNumber: "请输入大于零的整数。",
    openMoodle: "在 Moodle 中打开",
    courses: {
      title: "课程",
      description: "从 Moodle 关联的课程，包括课时、部门和实时需求。",
      empty: "没有匹配的课程。",
      emptyHint: "关联一门 Moodle 课程即可开始销售。",
      course: "课程",
      department: "部门",
      allDepartments: "所有部门",
      area: "学习领域",
      noArea: "无领域",
      hours: "课时",
      totalHours: "总教学课时",
      moodle: "Moodle",
      moodleVisible: "可见",
      moodleHidden: "隐藏",
      moodleChecked: "Moodle 检查时间",
      refreshError: "Moodle 刷新失败",
      refreshAll: "从 Moodle 刷新",
      refreshAllToast: "已从 Moodle 刷新课程。",
      refreshOne: "从 Moodle 刷新",
      refreshOneToast: "已从 Moodle 刷新此课程。",
      link: "关联 Moodle 课程",
      linkTitle: "关联一门 Moodle 课程",
      linkDescription: "课程来自 Moodle。选择一门尚未关联的课程并设置课时。",
      linkSubmit: "关联课程",
      linkToast: "课程已关联。",
      editTitle: "编辑课程",
      editDescription: "部门、课时、学习领域，以及在它之前的课程。",
      editToast: "课程已更新。",
      chooseMoodle: "请选择一门 Moodle 课程。",
      noUnmapped: "所有 Moodle 课程都已关联。",
      searchMoodle: "搜索 Moodle 课程",
      previous: "前置课程",
      noPrevious: "无前置课程",
      attendanceId: "Moodle 考勤活动",
      attendanceHint: "考勤需要此项。它是 Moodle 课程中考勤活动的 ID。",
      noAttendance: "未设置，因此无法考勤。",
      disable: "停用课程",
      disableTitle: "停用此课程？",
      disableBody: "此课程将无法再销售或新开班级。现有班级保留。",
      disabledToast: "课程已停用。",
      enable: "启用课程",
      enableTitle: "启用此课程？",
      enableBody: "此课程可以重新销售并新开班级。",
      enabledToast: "课程已启用。",
      demand: "当前需求",
      activeClasses: "开课中的班级",
      seatsTaken: "已占座位",
      waitingSales: "待处理的课程销售",
      interestedLeads: "感兴趣的潜在学员",
      classes: "班级",
      noClasses: "此课程还没有班级。",
      writeNote: "只有超级管理员可以更改课程。"
    },
    classes: {
      title: "班级",
      description: "每个班级及其教师、常规时间、座位和 Moodle 分组。",
      empty: "没有匹配的班级。",
      emptyHint: "为一门启用的课程创建班级。",
      add: "添加班级",
      createTitle: "添加班级",
      editTitle: "编辑班级",
      createDescription: "课程、日期、座位、教师和每周常规时间。",
      editDescription: "日期、座位、教师、常规时间和会议链接。",
      createSubmit: "创建班级",
      createdToast: "班级已创建。",
      updatedToast: "班级已更新。",
      name: "班级名称",
      course: "课程",
      allCourses: "所有课程",
      kind: "班级类型",
      group: "小组",
      individual: "一对一",
      capacity: "座位",
      starts: "开始",
      ends: "结束",
      dates: "日期",
      teachers: "教师",
      noTeachers: "此校区还没有教师。",
      noTeacher: "无教师",
      usualDays: "常规上课日",
      from: "从",
      to: "到",
      usualTime: "常规时间",
      noSchedule: "无常规时间",
      meetingLink: "会议链接",
      meetingHint: "用于线上班级。请使用 https 链接。",
      meetingInvalid: "请使用以 https:// 开头的链接",
      endBeforeStart: "结束日期必须晚于开始日期。",
      timeOrder: "结束时间必须晚于开始时间。",
      timeBoth: "请同时设置两个时间，或都不设置。",
      daysNeedTime: "请同时选择上课日和时间。",
      fill: "座位",
      moodleGroup: "Moodle 分组",
      moodleLinked: "已关联",
      moodleMissing: "未关联",
      lastSynced: "最近同步",
      neverSynced: "从未同步",
      tabOverview: "概览",
      tabStudents: "学生",
      tabSessions: "课次",
      tabAttendance: "考勤",
      tabGrades: "成绩",
      disable: "停用班级",
      disableTitle: "停用此班级？",
      disableBody: "此班级不再接收新学生。已报名的学生和历史记录保留。",
      disabledToast: "班级已停用。",
      enable: "启用班级",
      enableTitle: "启用此班级？",
      enableBody: "此班级可以重新接收学生。",
      enabledToast: "班级已启用。",
      moodleCreate: "创建 Moodle 分组",
      moodleLink: "关联 Moodle 分组",
      moodleTitle: "Moodle 分组",
      moodleDescription: "在 Moodle 课程中创建新分组，或关联已有的分组。",
      moodleSearch: "搜索 Moodle 分组",
      moodleBound: "Moodle 分组已关联。",
      sync: "与 Moodle 同步",
      syncTitle: "Moodle 同步",
      syncDone: "已与 Moodle 同步。",
      syncPartial: "同步完成，但有部分问题。",
      stepGroup: "分组",
      stepTeachers: "教师",
      stepStudents: "学生",
      stepSessions: "考勤课次",
      stepGrades: "成绩",
      stepOk: "完成",
      stepError: "失败",
      students: "学生",
      studentsEmpty: "此班级还没有学生。",
      addStudents: "添加已付款的学生",
      addStudentsHint: "此校区中等待此课程的已付款课程销售。",
      noWaiting: "此处没有等待此课程的已付款销售。",
      attachToast: "学生已加入班级。",
      noMoodleAccount: "没有 Moodle 账户",
      readOnly: "你可以查看此班级。更改由校区团队负责。"
    },
    sessions: {
      upcoming: "即将进行",
      past: "已结束",
      cancelled: "已取消",
      empty: "还没有课次。",
      emptyHint: "根据教师和教室的可用时间安排课次。",
      plan: "安排课次",
      planTitle: "安排课次",
      planDescription: "为每个工作日设置课时。EMS 会找出教师和教室都空闲的最早时间。",
      weekday: "星期",
      hours: "课时",
      addDay: "添加一天",
      removeDay: "删除这一天",
      fromDate: "从",
      toDate: "到",
      findTimes: "查找时间",
      proposed: "建议时间",
      noMatch: "没有适合每一天的时间。请释放教师或教室的时段，或更改上课日。",
      book: "预订这些课次",
      bookedToast: "课次已预订。",
      reschedule: "更改时间",
      rescheduleTitle: "更改课次时间",
      rescheduleDescription: "选择新的开始时间。它必须符合教师和教室的可用时间。",
      movedToast: "课次已调整。",
      cancel: "取消课次",
      cancelTitle: "取消此课次？",
      cancelBody: "学生和教师的日程中将不再有此课次。",
      cancelledToast: "课次已取消。",
      length: "时长",
      room: "教室",
      teacher: "教师",
      online: "线上",
      today: "今天",
      dayRequired: "请至少添加一天。",
      dayTwice: "每天只能出现一次。",
      rangeInvalid: "结束日期必须等于或晚于开始日期。",
      pastLocked: "过去的课次无法更改。",
      attendance: "考勤"
    },
    week: {
      title: "我的一周",
      description: "你本周的课次，每节课后需要考勤。",
      thisWeek: "本周",
      previous: "上一周",
      next: "下一周",
      sessions: "节课",
      hours: "小时",
      needAttendance: "需要考勤",
      empty: "本周没有课次。",
      noMoodle: "还没有 Moodle 课次",
      dayOff: "空闲"
    },
    attendance: {
      empty: "还没有 Moodle 考勤课次。",
      emptyHint: "将班级与 Moodle 同步，即可根据课表创建课次。",
      take: "考勤",
      sheetTitle: "考勤",
      sheetEmpty: "此课次还没有学生。",
      markAll: "全部标为出勤",
      save: "保存考勤",
      savedToast: "考勤已保存。",
      notTaken: "未考勤",
      taken: "已考勤",
      notMarked: "未标记",
      marked: "已标记",
      of: "/",
      needsActivity: "请先设置课程的 Moodle 考勤活动。"
    },
    grades: {
      empty: "Moodle 中还没有成绩。",
      student: "学生",
      courseGrade: "课程成绩"
    },
    rooms: {
      title: "教室",
      description: "各校区的教室、座位数以及可预订的时段。",
      add: "添加教室",
      createTitle: "添加教室",
      editTitle: "编辑教室",
      createDescription: "为教室命名并设置容纳人数。",
      name: "教室名称",
      capacity: "座位",
      createSubmit: "创建教室",
      createdToast: "教室已创建。",
      updatedToast: "教室已更新。",
      empty: "没有匹配的教室。",
      emptyHint: "添加教室后即可预订班级和测试。",
      disable: "停用教室",
      disableTitle: "停用此教室？",
      disableBody: "此教室将无法再被预订。过去的预订保留。",
      disabledToast: "教室已停用。",
      enable: "启用教室",
      enableTitle: "启用此教室？",
      enableBody: "此教室可以重新被预订。",
      enabledToast: "教室已启用。",
      availability: "可用时间",
      availabilityHint: "涂选此教室可预订的时段。已预订的时段保持锁定。",
      availabilityToast: "可用时间已保存。",
      unlimited: "未设置"
    }
  },
  forms: {
    title: "表单",
    description: "创建自己的表单，与家庭或员工分享，并处理每一份回复。",
    intro: "简介",
    yes: "是",
    no: "否",
    agreed: "已同意",
    form: "表单",
    tabForms: "我的表单",
    tabResponses: "回复",
    tabToFill: "待填写",
    newForm: "新建表单",
    newTitle: "新建表单",
    newDescription: "从空白或模板开始。发布前可以修改所有内容。",
    createSubmit: "创建表单",
    createdToast: "表单已创建。",
    titleEn: "标题（英文）",
    titleAr: "标题（阿拉伯文）",
    category: "类别",
    template: "起始方式",
    blank: "空白表单",
    branch: "校区",
    allBranchesForm: "所有校区",
    empty: "还没有表单。",
    emptyHint: "创建表单来替代 Jotform 或纸质表格。",
    responsesEmpty: "还没有回复。",
    toFillEmpty: "目前没有需要填写的内容。",
    toFillHint: "分配给你或你的角色的表单会显示在这里。",
    status: {
      draft: "草稿",
      active: "已发布",
      retired: "已停用"
    },
    categories: {
      admissions: "招生",
      student_support: "学生支持",
      attendance: "考勤",
      consent: "同意书",
      branch_operations: "校区运营"
    },
    responseStatus: {
      submitted: "新的",
      under_review: "审核中",
      accepted: "已接受",
      rejected: "已拒绝",
      promoted: "已处理",
      withdrawn: "已撤回",
      quarantined: "暂存"
    },
    responses: "回复",
    updated: "更新时间",
    live: "公开链接",
    notLive: "未分享",
    open: "打开",
    fill: "填写",
    filled: "已提交",
    due: "截止",
    tabBuild: "编辑",
    tabShare: "分享",
    tabResponses2: "回复",
    editDraft: "编辑新版本",
    editingDraft: "草稿",
    publishedVersion: "已发布版本",
    version: "版本",
    save: "保存草稿",
    savedToast: "草稿已保存。",
    unsaved: "有未保存的更改",
    preview: "预览",
    hidePreview: "隐藏预览",
    page: "页面",
    addPage: "添加页面",
    removePage: "删除页面",
    addField: "添加问题",
    question: "问题",
    questionEn: "问题（英文）",
    questionAr: "问题（阿拉伯文）",
    help: "帮助文字",
    required: "必填",
    options: "选项",
    addOption: "添加选项",
    optionEn: "选项（英文）",
    optionAr: "选项（阿拉伯文）",
    moveUp: "上移",
    moveDown: "下移",
    remove: "删除",
    duplicate: "复制",
    logicNote: "此表单有条件规则。保存时会保留这些规则。",
    usedByLogic: "有规则使用了此问题。请先删除该规则。",
    readOnlyVersion: "此版本已发布，无法更改。请新建版本后再编辑。",
    problems: "保存前请先修正以下问题：",
    problemLabel: "有问题缺少英文文字。",
    problemArabic: "每个问题和选项也需要阿拉伯文文字。",
    recordLinkNote: "此问题关联的是旧记录，无法为你的校区显示选项。",
    recordLinkBanner: "这里有问题使用了旧的记录链接。发布前请打开它并改用你的校区列表。",
    useBranchList: "使用我们的校区列表",
    needsAttention: "需要处理",
    problemOptions: "选择题至少需要一个选项。",
    problemEmpty: "请至少添加一个问题。",
    types: {
      heading: "标题",
      instructions: "说明",
      short_text: "简答",
      long_text: "段落",
      email: "电子邮箱",
      phone: "电话",
      number: "数字",
      date: "日期",
      time: "时间",
      single_choice: "单选",
      multiple_choice: "多选",
      yes_no: "是或否",
      rating: "评分",
      consent: "同意",
      entity_reference: "记录链接"
    },
    typeGroups: {
      text: "文字",
      choice: "选择",
      value: "数字和日期",
      layout: "版式"
    },
    publish: "发布",
    publishTitle: "发布此版本",
    publishDescription: "选择谁可以作答。公开链接会一直有效，直到你停用它。",
    publishSubmit: "发布",
    publishedToast: "表单已发布。",
    slug: "链接名称",
    slugHint: "小写字母、数字和连字符。",
    audience: "谁可以作答",
    audiencePublic: "任何拥有链接的人",
    audiencePublicHint: "家庭和访客，无需登录。",
    audienceAuthenticated: "任何已登录的员工",
    audienceAuthenticatedHint: "所有登录尼罗中心的人。",
    audienceAssigned: "仅限我分配的人",
    audienceAssignedHint: "接下来选择角色、校区、部门或人员。",
    opensAt: "开放时间",
    closesAt: "截止时间",
    allowMultiple: "允许每人提交多份回复",
    allowDrafts: "允许保存后稍后完成",
    publicationStatus: {
      scheduled: "已安排",
      open: "开放中",
      closed: "已截止",
      retired: "已停用"
    },
    publications: "链接",
    noPublications: "此表单尚未分享。",
    copyLink: "复制链接",
    copied: "链接已复制。",
    openLink: "打开",
    retire: "停用链接",
    retireTitle: "停用此链接？",
    retireBody: "之后将无法再通过此链接作答。已有回复保留。",
    retiredToast: "链接已停用。",
    assignments: "已分配给",
    noAssignments: "还没有分配给任何人。",
    assign: "分配",
    assignTitle: "分配此表单",
    assignDescription: "选择应填写此表单的人。他们会在“待填写”中看到它。",
    assignedToast: "表单已分配。",
    target: "分配给",
    targetRole: "角色",
    targetBranch: "校区",
    targetDepartment: "部门",
    targetPeople: "人员",
    peopleModeStaff: "员工",
    peopleModeClass: "某个班级的教师",
    peopleClass: "班级",
    staffSearch: "按姓名或邮箱搜索员工…",
    noStaffFound: "未找到员工。",
    classNoTeachers: "此班级还没有教师。",
    peopleSelected: "已选 {n} 个",
    assignToOne: "分配给 1 人",
    assignToMany: "分配给 {n} 人",
    publishBlockedRecordLinks: "发布前请在“编辑”中修正标出的问题。",
    assignedPeopleToast: "已分配 {n} 个。",
    assignFailures: "无法分配：",
    personFallback: "员工",
    revoke: "删除",
    revokedToast: "分配已删除。",
    expires: "截至",
    respondent: "来自",
    anonymous: "公开链接",
    submitted: "提交时间",
    answers: "回答",
    noAnswer: "未作答",
    review: "决定",
    accept: "接受",
    reject: "拒绝",
    startReview: "标为审核中",
    comment: "备注",
    reviewedToast: "决定已保存。",
    history: "历史记录",
    createLead: "创建潜在学员",
    createLeadHint: "将此咨询转为招生中的潜在学员，并自动填入回答。",
    leadCreated: "潜在学员已创建",
    openLead: "打开潜在学员",
    export: "导出 CSV",
    exportedToast: "导出已就绪。",
    allForms: "所有表单",
    allStatuses: "所有状态",
    import: "从 Jotform 导入",
    backToForms: "返回表单",
    importer: {
      title: "从 Jotform 导入",
      description: "将过去的 Jotform 回复导入你自己的表单，先检查再导入，并保留每一行的记录。",
      notConnected: "此服务器未连接 Jotform，因此无法列出其表单。已完成的导入仍显示在下方。",
      step1: "1. 选择表单",
      step2: "2. 匹配问题",
      step3: "3. 检查后导入",
      source: "Jotform 表单",
      target: "导入到此表单",
      noTargets: "请先发布一个表单；回复只能导入已发布的表单。",
      inspect: "匹配问题",
      field: "我们表单中的问题",
      fromJotform: "Jotform 问题",
      skip: "不导入",
      offset: "起始行",
      limit: "行数",
      dryRun: "检查行",
      total: "行",
      valid: "可导入",
      duplicates: "已导入",
      errors: "有问题",
      sample: "前几行",
      commit: "导入可导入的行",
      importedToast: "导入完成。",
      history: "过去的导入",
      noHistory: "还没有导入记录。",
      imported: "已导入",
      exceptions: "异常",
      matched: "已匹配",
      markMatched: "标为已匹配",
      markException: "标为异常",
      reconciledToast: "行已更新。",
      rowsNeedingReview: "需要审核的行",
      submissions: "份回复"
    },
    roles: {
      student: "学生",
      teacher: "教师",
      registrar: "教务登记员和学生成功顾问",
      headofdepartment: "系主任",
      branchadmin: "校区管理员和副经理",
      superadmin: "超级管理员"
    }
  },
  admissions: {
    money: {
      toBePaid: "总额",
      paid: "已付",
      remaining: "剩余",
      settled: "已全额付清",
      paidTooHigh: "已付金额不能超过总额。",
      invalidAmount: "请输入零或更大的数字。"
    },
    mode: {
      label: "学习方式",
      online: "线上",
      onsite: "线下",
      both: "线上或线下",
      unknown: "未选择",
      onlineBranch: "线上校区",
      onsiteBranch: "线下校区"
    },
    leads: {
      title: "潜在学员",
      description: "咨询过课程的人，从首次联系到注册。",
      add: "添加潜在学员",
      createTitle: "添加潜在学员",
      editTitle: "编辑潜在学员",
      createDescription: "记录咨询人、需求和联系方式。",
      editDescription: "更新联系方式、兴趣或负责人。",
      createSubmit: "创建潜在学员",
      createdToast: "潜在学员已创建。",
      updatedToast: "潜在学员已更新。",
      empty: "没有匹配的潜在学员。",
      emptyHint: "添加潜在学员或清除筛选。",
      noAccess: "潜在学员由招生人员管理。",
      person: "人员",
      stage: "阶段",
      interest: "兴趣",
      owner: "负责人",
      group: "小组",
      added: "添加时间",
      branch: "校区",
      anyMode: "任何学习方式",
      anyOwner: "任何负责人",
      unassigned: "无负责人",
      anyArea: "任何学习领域",
      anyType: "任何潜在学员类型",
      allBranches: "所有校区",
      firstName: "名",
      lastName: "姓",
      email: "电子邮箱",
      phone: "电话",
      wantsOnline: "线上课程",
      wantsOnsite: "校区课程",
      preferredCourses: "意向课程",
      anyCourse: "无偏好",
      coursesNoun: "门课程",
      areaOfStudy: "学习领域",
      noArea: "无领域",
      source: "来源",
      sourceHint: "例如：网站、到访或推荐。",
      notes: "备注",
      leadType: "潜在学员类型",
      typeNew: "新的",
      typeOld: "回访潜在学员",
      typeOldStudent: "往届学生",
      typeCurrentStudent: "在读学生",
      required: "必填。",
      invalidEmail: "请输入有效的电子邮箱。",
      chooseBranch: "请选择校区。",
      journey: "流程",
      nextStep: "下一步",
      stepContact: "首次联系",
      stepPlacement: "分级测试",
      stepTrial: "试听课",
      stepFee: "注册费",
      stepStudent: "学生",
      stepDone: "已完成",
      stepNow: "当前",
      stepSkipped: "已跳过",
      stepLater: "尚未进行",
      nextBookPlacement: "预约分级测试以确定合适的级别。",
      nextRecordPlacement: "测试结束后记录分级结果。",
      nextBookTrial: "预约试听课，或记录注册费。",
      nextRecordTrial: "记录试听课的情况。",
      nextFee: "记录注册费。",
      nextConvert: "注册费已记录。请创建学生档案。",
      nextStudent: "此潜在学员已成为学生。",
      nextLost: "此潜在学员已标为流失并关闭。",
      bookPlacement: "预约分级测试",
      bookTrial: "预约试听课",
      recordFee: "记录注册费",
      editFee: "修改费用",
      convert: "创建学生",
      openStudent: "打开学生",
      markLost: "标为流失",
      reopen: "重新打开潜在学员",
      lostTitle: "将此潜在学员标为流失？",
      lostBody: "请选择原因。之后可以重新打开。",
      lostReason: "流失原因",
      noLostReasons: "此账户没有可用的流失原因。管理员可以在“流失原因”中添加。",
      openLostReasons: "打开流失原因。",
      lostToast: "潜在学员已标为流失。",
      reopenToast: "潜在学员已重新打开。",
      lostBecause: "流失原因",
      details: "详情",
      placements: "分级测试",
      trials: "试听课",
      fee: "注册费",
      noPlacements: "还没有分级测试。",
      noTrials: "还没有试听课。",
      noFee: "还没有注册费。",
      feeTitle: "注册费",
      feeDescription: "记录总额以及此人目前已付的金额。",
      feeToast: "注册费已保存。",
      groupMembers: "同组成员",
      primaryContact: "主要联系人",
      convertTitle: "创建学生",
      convertDescription: "添加 EMS 所需的身份信息。联系方式来自潜在学员。",
      convertToast: "学生已创建。"
    },
    booking: {
      placementTitle: "预约分级测试",
      trialTitle: "预约试听课",
      editTitle: "修改预约",
      when: "日期和时间",
      hour: "开始时间",
      onTheHour: "预约从整点开始。",
      timeZone: "时区",
      room: "教室",
      chooseRoom: "请选择教室。线下预约需要教室。",
      meetingRequired: "请添加会议链接。",
      noRoom: "暂无教室",
      meetingLink: "会议链接",
      meetingHint: "请使用 https 链接。只有线上校区使用链接。",
      meetingInvalid: "请使用以 https:// 开头的链接",
      topic: "课程主题",
      byCourse: "一门课程",
      byArea: "一个学习领域",
      course: "课程",
      chooseCourse: "请选择课程。",
      chooseArea: "请选择学习领域。",
      placementCourseMissing: "此学习领域在 Moodle 中没有分级课程。请联系超级管理员关联一门。",
      book: "预约",
      saveChanges: "保存更改",
      bookedToast: "预约已保存。",
      updatedToast: "预约已更新。",
      moodlePassword: "测试用 Moodle 密码",
      resultTitle: "记录结果",
      resultDescription: "保存结果。预约将以已完成状态关闭。",
      score: "分数或级别",
      scoreHint: "例如：B1 或 72。",
      mentor: "指导教师",
      noMentors: "此校区没有找到教师。",
      recommended: "推荐课程",
      noRecommendation: "无推荐",
      notes: "备注",
      resultToast: "结果已保存。",
      syncMoodle: "从 Moodle 获取结果",
      syncToast: "已从 Moodle 更新结果。",
      fromMoodle: "来自 Moodle",
      recordedBy: "记录人",
      noShow: "标为未到场",
      noShowTitle: "标为未到场？",
      noShowBody: "此人未到场。你可以预约新的时间。",
      noShowToast: "已标为未到场。",
      cancel: "取消预约",
      cancelTitle: "取消此预约？",
      cancelBody: "请选择原因。该时段将被释放。",
      cancelToast: "预约已取消。",
      change: "更改",
      joinLink: "打开会议链接",
      result: "结果"
    },
    agenda: {
      placementsTitle: "分级测试",
      placementsDescription: "你范围内的所有分级测试，按天排列。请从潜在学员或学生页面预约。",
      trialsTitle: "试听课",
      trialsDescription: "你范围内的所有试听课，按天排列。请从潜在学员或学生页面预约。",
      upcoming: "即将进行",
      needsResult: "待记录结果",
      completed: "已完成",
      missed: "未到场",
      cancelled: "已取消",
      today: "今天",
      tomorrow: "明天",
      emptyUpcoming: "没有预约。",
      emptyNeedsResult: "所有过去的预约都已有结果。",
      emptyOther: "这里还没有内容。",
      emptyHint: "请从潜在学员流程页面预约。",
      subjectLead: "潜在学员",
      subjectStudent: "学生",
      allBranches: "所有校区",
      branch: "校区"
    },
    students: {
      title: "学生",
      description: "在尼罗中心注册的每位学生，包括课程、余额和 Moodle 访问。",
      add: "添加学生",
      createTitle: "添加学生",
      editTitle: "编辑学生",
      createDescription: "创建一位不是通过潜在学员来的学生。",
      editDescription: "更新联系方式、身份信息或负责人。",
      createSubmit: "创建学生",
      createdToast: "学生已创建。",
      updatedToast: "学生已更新。",
      empty: "没有匹配的学生。",
      emptyHint: "添加学生或清除筛选。",
      noAccess: "学生由招生人员管理。",
      person: "人员",
      branch: "所属校区",
      owner: "负责人",
      moodle: "Moodle",
      moodleLinked: "已关联",
      moodleMissing: "未关联",
      registration: "注册费",
      noFee: "无费用",
      added: "添加时间",
      note: "备注",
      allBranches: "所有校区",
      contact: "联系方式",
      identity: "身份信息",
      guardians: "监护人",
      noGuardians: "没有监护人记录。",
      tabOverview: "概览",
      tabCourses: "课程",
      tabLearning: "学习",
      tabBookings: "分级测试和试听",
      tabReport: "报告",
      warnings: "来自 EMS 的备注",
      moodleCreate: "创建 Moodle 账户",
      moodleLink: "关联 Moodle 账户",
      moodleReset: "重置 Moodle 密码",
      moodlePassword: "Moodle 密码",
      moodleToast: "Moodle 账户已更新。",
      moodleResetTitle: "重置 Moodle 密码？",
      moodleResetBody: "EMS 会设置一个新的随机密码。请只与学生分享一次。",
      disable: "停用学生",
      disableTitle: "停用此学生？",
      disableBody: "此学生将无法再报名。历史记录保留。",
      disabledToast: "学生已停用。",
      enable: "启用学生",
      enableTitle: "启用此学生？",
      enableBody: "此学生可以重新报名。",
      enabledToast: "学生已启用。",
      learningEmpty: "还没有 Moodle 成绩。",
      learningClass: "班级",
      learningGrade: "课程成绩",
      learningCompletion: "完成情况",
      learningDone: "已完成",
      learningOngoing: "进行中",
      print: "打印报告",
      reportTitle: "学业报告",
      reportGenerated: "生成时间",
      reportLearningError: "Moodle 成绩目前不可用。",
      fromLead: "来自潜在学员"
    },
    enrolments: {
      title: "报名",
      description: "从付款到分班的课程销售。将已付款的销售加入有空位的班级。",
      empty: "没有匹配的报名。",
      emptyHint: "请在学生页面销售课程。",
      noAccess: "报名由招生人员管理。",
      waiting: "等待中",
      sell: "销售课程",
      saleTitle: "销售课程",
      saleDescription: "开启一笔课程销售。付款可以稍后完成。",
      saleToast: "课程销售已开启。",
      student: "学生",
      findStudent: "搜索学生",
      typeToSearch: "请至少输入两个字。",
      noStudents: "没有匹配的学生。",
      course: "课程",
      kind: "班级类型",
      group: "小组",
      individual: "一对一",
      branch: "校区",
      class: "班级",
      balance: "余额",
      opened: "开启时间",
      noClass: "尚未分班",
      nextLevel: "下一级",
      recordPayment: "记录付款",
      paymentTitle: "记录付款",
      paymentDescription: "更新总额或学生目前已付的金额。",
      paymentToast: "付款已保存。",
      attach: "加入班级",
      attachTitle: "加入一个班级",
      attachDescription: "此校区中此课程的开课班级。已满的班级不再接收学生。",
      seatsLeft: "个座位剩余",
      full: "已满",
      noClasses: "此校区还没有此课程的开课班级。",
      attachToast: "学生已加入班级。",
      moodleRequired: "学生需要先有 Moodle 账户才能加入班级。",
      complete: "标为已完成",
      completeTitle: "将此报名标为已完成？",
      completeBody: "在学生完成课程后使用此操作。",
      completeToast: "报名已完成。",
      leave: "标为已退出",
      leaveTitle: "将此下一级销售标为已退出？",
      leaveBody: "请选择学生不参加此级别的原因。",
      leaveToast: "报名已标为已退出。",
      cancel: "取消销售",
      cancelTitle: "取消此课程销售？",
      cancelBody: "请选择原因。此操作无法撤销。",
      cancelToast: "课程销售已取消。",
      schedule: "时间安排",
      teachers: "教师"
    },
    identity: {
      nationality: "国籍",
      nationalityHint: "三个字母的代码，例如 EGY。",
      address: "地址",
      gender: "性别",
      male: "男",
      female: "女",
      dateOfBirth: "出生日期",
      nationalId: "身份证号",
      nationalIdHint: "14 位数字。埃及公民必填。",
      passport: "护照号码",
      guardian: "监护人",
      secondGuardian: "第二监护人",
      guardianHint: "未满 18 岁的学生至少需要一位监护人。",
      guardianName: "姓名",
      guardianPhone: "电话",
      guardianEmail: "电子邮箱",
      relationship: "关系",
      relationshipHint: "例如：母亲、父亲或叔叔。",
      addGuardian: "添加第二监护人",
      removeGuardian: "删除",
      invalidNationality: "请使用三个字母的代码。",
      invalidNationalId: "请使用 14 位数字。",
      nationalIdRequired: "埃及公民必填。",
      guardianRequired: "未满 18 岁的学生需要监护人。",
      guardianIncomplete: "请填写所有监护人字段。"
    }
  },
  dateOfBirth: {
    day: "日",
    month: "月",
    year: "年",
    monthPlaceholder: "月份",
    clear: "清除日期",
    hint: "例如：2012 年 3 月 4 日。",
    incompleteDate: "请输入日、月和四位数的年份。",
    invalidDate: "此日期不存在。请检查日和月。",
    futureDate: "出生日期不能在未来。",
    tooEarly: "请输入 1900 年或之后的年份。",
    age: "{n} 岁"
  },
  datePicker: {
    placeholder: "选择日期",
    today: "今天",
    clear: "清除",
    previousMonth: "上个月",
    nextMonth: "下个月",
    previousYear: "上一年",
    nextYear: "下一年",
    chooseMonth: "选择月份和年份",
    unavailable: "不可选",
    calendar: "日历"
  },
  language: {
    label: "语言"
  },
  reports: {
    title: "报告",
    description: "查看报告，然后导出。数据实时来自 EMS。",
    report: "报告",
    tabs: {
      admissions: "招生",
      bookings: "预约",
      enrolments: "报名",
      classes: "班级"
    },
    period: "时间段",
    asOfToday: "截至今天",
    branch: "校区",
    allBranches: "所有校区",
    exportCsv: "导出 CSV",
    truncated: "显示 EMS 中 {total} 行的前 {n} 行。",
    showAll: "显示全部 {n} 行",
    showLess: "收起",
    emptyTitle: "没有可报告的内容",
    emptyAdmissions: "此时间段内没有创建潜在学员。",
    emptyBookings: "此时间段内没有安排分级测试或试听课。",
    emptyEnrolments: "没有找到报名。",
    emptyClasses: "目前没有开课中的班级。",
    emptyPlacements: "此时间段内没有分级测试。",
    emptyTrialLessons: "此时间段内没有试听课。",
    emptyTrialResults: "此时间段内没有记录试听结果。",
    emptyScores: "此时间段内没有已评分的分级测试。",
    emptyLostReasons: "此时间段内没有流失的潜在学员。",
    emptyWeekdays: "没有班级安排了上课日。",
    changePeriod: "更改时间段",
    liveFootnote: "所有数据都通过员工 API 根据 EMS 数据实时计算。",
    footnoteAdmissions: "状态为所选时间段内创建的潜在学员的当前状态。",
    footnoteBookings: "预约按安排日期统计。",
    footnoteEnrolments: "报名按报名或取消日期统计。金额按 EMS 中的记录汇总，不含币种。",
    footnoteClasses: "开课班级的某一时点数据。",
    newLeads: "新潜在学员",
    registered: "已注册",
    lost: "已流失",
    open: "未结",
    conversion: "转化率",
    rate: "比率",
    intake: "潜在学员来源",
    intakePerWeek: "每周新潜在学员",
    intakePerMonth: "每月新潜在学员",
    funnel: "从咨询到注册",
    funnelDecided: "已决定",
    bySource: "按来源",
    byLostReason: "按流失原因",
    byOwner: "按负责人",
    byArea: "按学习领域",
    byBranch: "按校区",
    studyMode: "学习方式",
    leadType: "潜在学员类型",
    noSource: "无来源",
    noReason: "未记录原因",
    noOwner: "无负责人",
    notSet: "未设置",
    modes: {
      online: "仅线上",
      onsite: "仅线下",
      both: "两者皆可",
      unset: "未选择"
    },
    leadTypes: {
      new: "新的",
      old: "旧的",
      old_student: "往届学生",
      current_student: "在读学生"
    },
    count: "数量",
    share: "占比",
    leads: "潜在学员",
    placementTests: "分级测试",
    trialLessons: "试听课",
    scheduled: "已安排",
    completed: "已完成",
    noShow: "未到场",
    cancelled: "已取消",
    showRate: "到场率",
    scoreSummary: "分级测试分数",
    scoreAverage: "平均",
    scoreMin: "最低",
    scoreMax: "最高",
    scoreBands: "分数分布",
    trialResults: "试听结果",
    trialsByCourse: "按课程统计的试听",
    trialToRegistered: "成为学生的已完成试听",
    trials: "试听",
    pipeline: "进度",
    rightNow: "当前",
    inThisPeriod: "此时间段内",
    enrolledInPeriod: "时间段内报名",
    cancelledInPeriod: "时间段内取消",
    allTime: "全部时间",
    money: "金额",
    billed: "应收",
    collected: "已收",
    outstanding: "未收",
    outstandingPending: "尚需支付（待付款）",
    collectionRate: "收款率",
    moneyNote: "金额按 EMS 中的记录显示，不含币种。",
    byCourse: "按课程",
    byKind: "按类型",
    kinds: {
      individual: "个人",
      group: "小组"
    },
    activeClasses: "开课中的班级",
    seatsTaken: "已占座位",
    capacity: "容量",
    fill: "满员率",
    freeSeats: "空余座位",
    fillByCourse: "按课程统计满员率",
    fillByDepartment: "按部门统计满员率",
    teacherLoad: "教师工作量",
    noTeacher: "未分配教师",
    endingSoon: "即将结束",
    endingSoonEmpty: "未来 30 天内没有班级结束。",
    daysLeft: "剩余天数",
    weekdayLoad: "按星期统计的班级",
    classes: "班级",
    students: "学生",
    seats: "座位",
    active: "启用",
    pending: "待处理",
    leftCancelled: "已退出／已取消",
    enrolled: "已报名",
    placements: "分级测试",
    score: "分数",
    course: "课程",
    department: "部门",
    name: "名称",
    endDate: "结束日期",
    csv: {
      name: "姓名",
      email: "电子邮箱",
      phone: "电话",
      branch: "校区",
      source: "来源",
      status: "状态",
      lostReason: "流失原因",
      owner: "负责人",
      area: "学习领域",
      studyMode: "学习方式",
      created: "创建时间",
      type: "类型",
      person: "人员",
      scheduled: "安排时间",
      result: "结果",
      courseOrArea: "课程／领域",
      recommended: "推荐课程",
      student: "学生",
      course: "课程",
      className: "班级",
      enrolled: "报名时间",
      cancelled: "取消时间",
      toBePaid: "应付",
      paid: "已付",
      remaining: "剩余",
      department: "部门",
      teachers: "教师",
      schedule: "时间安排",
      capacity: "容量",
      taken: "已占",
      fill: "满员率 %",
      start: "开始",
      end: "结束"
    }
  }
};
