import type { PlatformModule } from "./types";

export const platformModules: PlatformModule[] = [
  {
    id: "public_site",
    label: "Public site",
    ownerRole: "registrar",
    purpose: "Course discovery, trial requests, placement bookings, and conversion into EMS records.",
    routeRoot: "/",
    dataEntities: ["Lead", "Application", "PlacementTestBooking", "Program", "Course"],
    services: ["lead intake", "placement booking", "course catalog"],
    integrations: ["EMS import", "email/WhatsApp templates"],
    remainingWork: ["Real CMS content source", "Conversion attribution", "Automated follow-up sequences"],
  },
  {
    id: "auth_rbac",
    label: "Auth and RBAC",
    ownerRole: "superadmin",
    purpose: "Identity, role selection, permissions, route guards, and audit boundaries.",
    routeRoot: "/auth",
    dataEntities: ["User", "Role", "Permission", "UserSession", "AuditLog"],
    services: ["session service", "permission map", "route guard"],
    integrations: ["future SSO/OAuth provider"],
    remainingWork: ["Password reset delivery", "Multi-role assignment UI", "Admin session revocation controls"],
  },
  {
    id: "admissions_ems",
    label: "Admissions and EMS",
    ownerRole: "registrar",
    purpose: "Lead, application, placement, enrollment, payment readiness, and LMS account workflow.",
    routeRoot: "/app/registrar",
    dataEntities: ["Lead", "Application", "PlacementTestBooking", "Enrollment", "Invoice"],
    services: ["pipeline transitions", "communication log", "LMS account link"],
    integrations: ["EMS", "Moodle", "payment provider"],
    remainingWork: ["Real workflow state machine", "Bulk import", "Duplicate lead matching"],
  },
  {
    id: "student_learning",
    label: "Student learning",
    ownerRole: "student",
    purpose: "Course access, lesson progress, live class, assignments, quizzes, grades, attendance, support, and certificates.",
    routeRoot: "/app/student",
    dataEntities: ["Enrollment", "LessonProgress", "AssignmentSubmission", "QuizAttempt", "Certificate"],
    services: ["progress tracking", "submission workflow", "certificate eligibility"],
    integrations: ["Moodle content", "meeting provider"],
    remainingWork: ["Real lesson player", "File uploads", "Offline/download policy"],
  },
  {
    id: "teaching",
    label: "Teaching workspace",
    ownerRole: "teacher",
    purpose: "Class management, sessions, materials, attendance, grading, quizzes, reports, and Quran review.",
    routeRoot: "/app/teacher",
    dataEntities: ["ClassGroup", "ClassSession", "AttendanceRecord", "Assignment", "Quiz"],
    services: ["attendance save", "grading queue", "materials publishing"],
    integrations: ["Moodle assignments", "meeting recordings"],
    remainingWork: ["Teacher availability sync", "Audio feedback storage", "Question-bank import"],
  },
  {
    id: "academic_management",
    label: "Academic management",
    ownerRole: "headofdepartment",
    purpose: "Department ownership, programs, courses, levels, curriculum, teachers, assessments, certificates, and quality reports.",
    routeRoot: "/app/hod",
    dataEntities: ["Department", "Program", "Course", "CourseLevel", "CurriculumItem", "Certificate"],
    services: ["curriculum publishing", "teacher load review", "certificate approval"],
    integrations: ["Moodle course sync"],
    remainingWork: ["Versioned curriculum publishing", "Outcome analytics", "Observation forms"],
  },
  {
    id: "branch_operations",
    label: "Branch operations",
    ownerRole: "branchadmin",
    purpose: "Branch students, teachers, classes, rooms, local schedule, attendance exceptions, payments, and branch settings.",
    routeRoot: "/app/branch",
    dataEntities: ["Branch", "Room", "ClassGroup", "CalendarEvent", "Invoice"],
    services: ["room conflict detection", "branch reporting", "local templates"],
    integrations: ["meeting provider", "payments"],
    remainingWork: ["Room booking rules", "Front desk check-in", "Branch permission scope"],
  },
  {
    id: "assessment",
    label: "Assessment engine",
    ownerRole: "headofdepartment",
    purpose: "Question bank, quizzes, attempts, rubrics, auto-grading, manual grading, reports, and placement mapping.",
    routeRoot: "/app/*/quizzes",
    dataEntities: ["Quiz", "QuizQuestion", "QuizAttempt", "Grade", "Rubric"],
    services: ["auto grading", "manual review", "gradebook publishing"],
    integrations: ["Moodle quizzes"],
    remainingWork: ["Real attempt engine", "Question editor", "Secure timers"],
  },
  {
    id: "attendance",
    label: "Attendance engine",
    ownerRole: "teacher",
    purpose: "Mark attendance, store notes, raise absence alerts, expose history, and feed certificate eligibility.",
    routeRoot: "/app/*/attendance",
    dataEntities: ["ClassSession", "AttendanceRecord", "ExcuseRequest"],
    services: ["bulk save", "absence alerts", "attendance reports"],
    integrations: ["notifications"],
    remainingWork: ["Server-side save", "Excuse approval flow", "Parent/guardian alerts"],
  },
  {
    id: "scheduling",
    label: "Calendar and scheduling",
    ownerRole: "branchadmin",
    purpose: "Unified events for sessions, trials, placement tests, deadlines, rooms, reminders, and conflict checks.",
    routeRoot: "/app/*/calendar",
    dataEntities: ["CalendarEvent", "Room", "TeacherAvailability", "MeetingLink"],
    services: ["conflict detection", "event filters", "reminders"],
    integrations: ["meeting provider", "calendar export"],
    remainingWork: ["Drag/drop calendar", "Recurring rules", "External calendar sync"],
  },
  {
    id: "communication",
    label: "Communication",
    ownerRole: "registrar",
    purpose: "Messages, templates, announcements, notifications, and communication logs across roles.",
    routeRoot: "/app/*/messages",
    dataEntities: ["Message", "Notification", "MessageTemplate", "CommunicationLog"],
    services: ["template rendering", "read state", "notification preferences"],
    integrations: ["email", "WhatsApp"],
    remainingWork: ["External send providers", "Attachment storage", "Delivery tracking"],
  },
  {
    id: "certificates",
    label: "Certificates",
    ownerRole: "headofdepartment",
    purpose: "Eligibility review, approvals, issuing, verification codes, downloads, history, and revocation controls.",
    routeRoot: "/app/*/certificates",
    dataEntities: ["Certificate", "Grade", "Enrollment", "AttendanceRecord", "AuditLog"],
    services: ["eligibility rules", "approval workflow", "verification lookup"],
    integrations: ["notifications", "future PDF renderer"],
    remainingWork: ["PDF certificate renderer", "Public verification page", "Revocation workflow"],
  },
  {
    id: "finance",
    label: "Finance and payments",
    ownerRole: "registrar",
    purpose: "Invoices, payment status, discounts, receipts, branch payment follow-up, and finance-ready reporting.",
    routeRoot: "/app/*/payments",
    dataEntities: ["Invoice", "Payment", "Package", "Discount", "CommunicationLog"],
    services: ["invoice creation", "payment tracking", "receipt placeholder"],
    integrations: ["payment provider", "EMS"],
    remainingWork: ["Payment gateway", "Receipt generation", "Refund workflow"],
  },
  {
    id: "reports",
    label: "Reports and analytics",
    ownerRole: "superadmin",
    purpose: "Role-specific analytics for learning progress, enrollment funnel, branch performance, attendance, and system activity.",
    routeRoot: "/app/*/reports",
    dataEntities: ["Enrollment", "Grade", "AttendanceRecord", "Invoice", "AuditLog"],
    services: ["filters", "chart summaries", "CSV export placeholders"],
    integrations: ["future warehouse/export"],
    remainingWork: ["Saved report definitions", "Scheduled exports", "Backend aggregate queries"],
  },
  {
    id: "quran",
    label: "Quran specialization",
    ownerRole: "teacher",
    purpose: "Memorization plans, Surah/Juz progress, recitation submissions, tajweed feedback, revision, and ijazah milestones.",
    routeRoot: "/app/*/quran",
    dataEntities: ["QuranMemorizationPlan", "QuranProgressRecord", "RecitationSubmission", "TajweedFeedback"],
    services: ["recitation review", "revision schedule", "ijazah milestone tracking"],
    integrations: ["audio storage"],
    remainingWork: ["Audio upload/review player", "Mistake taxonomy", "Ijazah approval workflow"],
  },
  {
    id: "integrations",
    label: "Integrations",
    ownerRole: "superadmin",
    purpose: "Server-only connector configuration, sync status, mock mode visibility, and import/export boundaries.",
    routeRoot: "/app/admin/integrations",
    dataEntities: ["IntegrationConfig", "AuditLog"],
    services: ["Supabase adapter", "Moodle adapter", "EMS adapter", "provider status"],
    integrations: ["Supabase", "Moodle", "EMS", "email", "WhatsApp", "meeting", "payment"],
    remainingWork: ["Apply Supabase migrations in the owner project", "Server-side sync jobs", "Retry and dead-letter queues"],
  },
  {
    id: "system_admin",
    label: "System admin",
    ownerRole: "superadmin",
    purpose: "Users, roles, permissions, branches, departments, settings, audit logs, reports, and system health.",
    routeRoot: "/app/admin",
    dataEntities: ["User", "Permission", "Branch", "Department", "AuditLog"],
    services: ["permission registry", "audit export", "health checks"],
    integrations: ["all providers"],
    remainingWork: ["Real backend health probes", "Admin mutation APIs", "Backup/export policy"],
  },
];
