import { rolePermissions } from "../platformData.js";
import type { PlatformState } from "./types.js";

export const seedPlatformState: PlatformState = {
  settings: {
    organization: "Nile Center",
    defaultLanguage: "English",
    academicTerm: "Summer 2026",
    retentionDays: 365,
    updatedAt: "2026-06-26T08:00:00+03:00",
    updatedBy: "usr_admin_demo",
  },
  portalSettings: [
    {
      role: "registrar",
      scopeId: "br_cairo",
      label: "Admissions desk",
      language: "English",
      timezone: "Africa/Cairo",
      notifications: true,
      reviewCadenceDays: 2,
      paymentReminderDays: 5,
      updatedAt: "2026-06-26T08:00:00+03:00",
      updatedBy: "usr_registrar_demo",
    },
    {
      role: "branchadmin",
      scopeId: "br_cairo",
      label: "Cairo branch operations",
      language: "English",
      timezone: "Africa/Cairo",
      notifications: true,
      attendanceCutoffMinutes: 15,
      paymentReminderDays: 3,
      updatedAt: "2026-06-26T08:00:00+03:00",
      updatedBy: "usr_branch_demo",
    },
    {
      role: "headofdepartment",
      scopeId: "dep_arabic",
      label: "Arabic academic review",
      language: "English",
      timezone: "Africa/Cairo",
      notifications: true,
      reviewCadenceDays: 7,
      attendanceCutoffMinutes: 10,
      updatedAt: "2026-06-26T08:00:00+03:00",
      updatedBy: "usr_hod_demo",
    },
  ],
  users: [
    { id: "usr_student_demo", name: "Student Demo", email: "student.demo@nilelearn.local", roles: ["student"], activeRole: "student", branchId: "br_online", departmentId: "dep_arabic", status: "active" },
    { id: "usr_student_cairo_demo", name: "Cairo Student Demo", email: "cairo.student.demo@nilelearn.local", roles: ["student"], activeRole: "student", branchId: "br_cairo", departmentId: "dep_arabic", status: "active" },
    { id: "usr_student_alex_demo", name: "Alex Student Demo", email: "alex.student.demo@nilelearn.local", roles: ["student"], activeRole: "student", branchId: "br_alex", departmentId: "dep_foundations", status: "active" },
    { id: "usr_student_ready_demo", name: "Ready Student Demo", email: "ready.student.demo@nilelearn.local", roles: ["student"], activeRole: "student", branchId: "br_alex", departmentId: "dep_quran", status: "pending" },
    { id: "usr_student_paused_demo", name: "Paused Student Demo", email: "paused.student.demo@nilelearn.local", roles: ["student"], activeRole: "student", branchId: "br_alex", departmentId: "dep_foundations", status: "paused" },
    { id: "usr_student_completed_demo", name: "Completed Student Demo", email: "completed.student.demo@nilelearn.local", roles: ["student"], activeRole: "student", branchId: "br_alex", departmentId: "dep_foundations", status: "completed" },
    { id: "usr_teacher_demo", name: "Teacher Demo", email: "teacher.demo@nilelearn.local", roles: ["teacher"], activeRole: "teacher", branchId: "br_online", departmentId: "dep_arabic", status: "active" },
    { id: "usr_teacher_spare", name: "Teacher Spare", email: "teacher.spare@nilelearn.local", roles: ["teacher"], activeRole: "teacher", branchId: "br_online", departmentId: "dep_arabic", status: "active" },
    { id: "usr_teacher_quran_demo", name: "Quran Teacher Demo", email: "quran.teacher.demo@nilelearn.local", roles: ["teacher"], activeRole: "teacher", branchId: "br_alex", departmentId: "dep_quran", status: "active" },
    { id: "usr_teacher_alex_demo", name: "Alex Teacher Demo", email: "alex.teacher.demo@nilelearn.local", roles: ["teacher"], activeRole: "teacher", branchId: "br_alex", departmentId: "dep_foundations", status: "active" },
    { id: "usr_registrar_demo", name: "Registrar Demo", email: "registrar.demo@nilelearn.local", roles: ["registrar"], activeRole: "registrar", branchId: "br_cairo", departmentId: "dep_admissions", status: "active" },
    { id: "usr_registrar_online_demo", name: "Online Registrar Demo", email: "online.registrar.demo@nilelearn.local", roles: ["registrar"], activeRole: "registrar", branchId: "br_online", departmentId: "dep_admissions", status: "active" },
    { id: "usr_hod_demo", name: "HOD Demo", email: "hod.demo@nilelearn.local", roles: ["headofdepartment"], activeRole: "headofdepartment", branchId: "br_global", departmentId: "dep_arabic", status: "active" },
    { id: "usr_hod_quran_demo", name: "Quran HOD Demo", email: "quran.hod.demo@nilelearn.local", roles: ["headofdepartment"], activeRole: "headofdepartment", branchId: "br_global", departmentId: "dep_quran", status: "active" },
    { id: "usr_branch_demo", name: "Branch Demo", email: "branch.demo@nilelearn.local", roles: ["branchadmin"], activeRole: "branchadmin", branchId: "br_cairo", departmentId: "dep_operations", status: "active" },
    { id: "usr_branch_alex_demo", name: "Alex Branch Demo", email: "alex.branch.demo@nilelearn.local", roles: ["branchadmin"], activeRole: "branchadmin", branchId: "br_alex", departmentId: "dep_operations", status: "active" },
    { id: "usr_admin_demo", name: "Admin Demo", email: "admin.demo@nilelearn.local", roles: ["superadmin"], activeRole: "superadmin", branchId: "br_global", departmentId: "dep_platform", status: "active" },
    { id: "usr_admin_ops_demo", name: "Operations Admin Demo", email: "ops.admin.demo@nilelearn.local", roles: ["superadmin"], activeRole: "superadmin", branchId: "br_global", departmentId: "dep_platform", status: "active" },
  ],
  branches: [
    { id: "br_global", name: "Global", code: "GLOBAL", timezone: "Africa/Cairo", address: "Global online operations", status: "active" },
    { id: "br_cairo", name: "Cairo B1", code: "B1", timezone: "Africa/Cairo", address: "Cairo branch", status: "active" },
    { id: "br_alex", name: "Alexandria B2", code: "B2", timezone: "Africa/Cairo", address: "Alexandria branch", status: "active" },
    { id: "br_online", name: "Online", code: "ONLINE", timezone: "Africa/Cairo", address: "Online classroom", status: "active" },
  ],
  departments: [
    { id: "dep_arabic", name: "Arabic and Quran", ownerUserId: "usr_hod_demo", branchIds: ["br_cairo", "br_online", "br_alex"], status: "active" },
    { id: "dep_foundations", name: "Foundations", ownerUserId: "usr_hod_quran_demo", branchIds: ["br_alex"], status: "active" },
    { id: "dep_quran", name: "Quran Programs", ownerUserId: "usr_hod_quran_demo", branchIds: ["br_online", "br_alex"], status: "active" },
    { id: "dep_admissions", name: "Admissions", ownerUserId: "usr_registrar_demo", branchIds: ["br_cairo", "br_online"], status: "active" },
    { id: "dep_operations", name: "Branch Operations", ownerUserId: "usr_branch_demo", branchIds: ["br_cairo", "br_alex"], status: "active" },
    { id: "dep_platform", name: "Platform", ownerUserId: "usr_admin_demo", branchIds: ["br_global"], status: "active" },
  ],
  programs: [
    { id: "prog_arabic", title: "Arabic Language", category: "Arabic", departmentId: "dep_arabic", language: "English", status: "active" },
    { id: "prog_foundations", title: "Arabic Foundations", category: "Arabic", departmentId: "dep_foundations", language: "English", status: "active" },
    { id: "prog_quran", title: "Quran and Tajweed", category: "Quran & Tajweed", departmentId: "dep_arabic", language: "English", status: "active" },
    { id: "prog_hifz_demo", title: "Hifz Demo Track", category: "Quran & Tajweed", departmentId: "dep_quran", language: "English", status: "active" },
    { id: "prog_islamic", title: "Islamic Studies", category: "Islamic Studies", departmentId: "dep_arabic", language: "English", status: "active" },
  ],
  levels: [
    { id: "lvl_ar_l3", programId: "prog_arabic", title: "Level 3", order: 3, prerequisites: ["Level 2 completion or placement"], completionRules: ["80% attendance", "70% grade"] },
    { id: "lvl_qt_1", programId: "prog_quran", title: "Tajweed 1", order: 1, prerequisites: ["Can read Arabic letters"], completionRules: ["90% recitation review", "Teacher approval"] },
    { id: "lvl_ar_l1", programId: "prog_foundations", title: "Level 1", order: 1, prerequisites: ["New learner placement"], completionRules: ["80% attendance", "Foundation conversation check"] },
    { id: "lvl_hifz_1", programId: "prog_hifz_demo", title: "Hifz Foundations", order: 2, prerequisites: ["Tajweed 1 or teacher approval"], completionRules: ["Weekly revision", "Teacher recitation approval"] },
  ],
  courses: [
    { id: "course_ar_l3", programId: "prog_arabic", levelId: "lvl_ar_l3", slug: "standard-arabic-l3", title: "Standard Arabic Level 3", description: "Intermediate grammar, reading, writing, and conversation.", outcomes: ["Use conditional sentences", "Write short essays", "Read graded texts"], status: "active" },
    { id: "course_qt_1", programId: "prog_quran", levelId: "lvl_qt_1", slug: "quran-tajweed-1", title: "Quran Tajweed 1", description: "Tajweed foundations with recitation feedback.", outcomes: ["Apply madd rules", "Improve makharij", "Track revision"], status: "active" },
    { id: "course_ar_l1", programId: "prog_foundations", levelId: "lvl_ar_l1", slug: "standard-arabic-l1", title: "Standard Arabic Level 1", description: "Arabic reading, core vocabulary, and first conversation routines.", outcomes: ["Read simple words", "Introduce yourself", "Use classroom vocabulary"], status: "active" },
    { id: "course_hifz_1", programId: "prog_hifz_demo", levelId: "lvl_hifz_1", slug: "hifz-foundations", title: "Hifz Foundations", description: "Structured memorization with revision cycles and teacher feedback.", outcomes: ["Build memorization routine", "Submit recitations", "Track revision quality"], status: "active" },
  ],
  modules: [
    { id: "mod_ar_3_grammar", courseId: "course_ar_l3", title: "Grammar and syntax", order: 1, outcomes: ["Conditional sentences", "Verb patterns"] },
    { id: "mod_ar_3_reading", courseId: "course_ar_l3", title: "Reading and listening", order: 2, outcomes: ["Read graded passages", "Recognize connected speech"] },
    { id: "mod_ar_3_writing", courseId: "course_ar_l3", title: "Writing studio", order: 3, outcomes: ["Draft short essays", "Use teacher feedback"] },
    { id: "mod_qt_madd", courseId: "course_qt_1", title: "Madd rules", order: 1, outcomes: ["Recognize madd", "Apply timing"] },
    { id: "mod_qt_recitation", courseId: "course_qt_1", title: "Recitation practice", order: 2, outcomes: ["Submit recordings", "Apply tajweed correction"] },
    { id: "mod_ar_1_letters", courseId: "course_ar_l1", title: "Letters and sounds", order: 1, outcomes: ["Recognize letters", "Practice short vowels"] },
    { id: "mod_ar_1_intro", courseId: "course_ar_l1", title: "First conversations", order: 2, outcomes: ["Greet classmates", "Ask simple questions"] },
    { id: "mod_hifz_revision", courseId: "course_hifz_1", title: "Revision rhythm", order: 1, outcomes: ["Plan weekly revision", "Track memorized portions"] },
    { id: "mod_hifz_submission", courseId: "course_hifz_1", title: "Teacher recitation", order: 2, outcomes: ["Submit recitation", "Apply teacher correction"] },
  ],
  lessons: [
    { id: "lesson_ar_conditional", moduleId: "mod_ar_3_grammar", title: "Conditional Sentences", type: "video", durationMinutes: 42, resourceIds: ["res_ar_pdf"] },
    { id: "lesson_ar_patterns", moduleId: "mod_ar_3_grammar", title: "Verb Patterns in Context", type: "practice", durationMinutes: 35, resourceIds: ["res_ar_patterns"] },
    { id: "lesson_ar_reading_market", moduleId: "mod_ar_3_reading", title: "Reading: A Day at the Market", type: "reading", durationMinutes: 28, resourceIds: ["res_ar_reading_market"] },
    { id: "lesson_ar_listening_dialogue", moduleId: "mod_ar_3_reading", title: "Listening Dialogue Lab", type: "video", durationMinutes: 31, resourceIds: ["res_ar_dialogue_audio"] },
    { id: "lesson_ar_writing_outline", moduleId: "mod_ar_3_writing", title: "Writing a Paragraph Outline", type: "practice", durationMinutes: 40, resourceIds: ["res_ar_outline_doc"] },
    { id: "lesson_qt_madd", moduleId: "mod_qt_madd", title: "Madd Tabi'i Practice", type: "live", durationMinutes: 60, resourceIds: ["res_qt_audio"] },
    { id: "lesson_qt_munfasil", moduleId: "mod_qt_madd", title: "Madd Munfasil Drill", type: "practice", durationMinutes: 36, resourceIds: ["res_qt_munfasil_audio"] },
    { id: "lesson_qt_recording", moduleId: "mod_qt_recitation", title: "Submit a Recitation Clip", type: "assessment", durationMinutes: 25, resourceIds: ["res_qt_recording_guide"] },
    { id: "lesson_ar_letters", moduleId: "mod_ar_1_letters", title: "Arabic Letter Shapes", type: "video", durationMinutes: 32, resourceIds: ["res_ar_letters_pdf"] },
    { id: "lesson_ar_greetings", moduleId: "mod_ar_1_intro", title: "Greeting and Introductions", type: "practice", durationMinutes: 30, resourceIds: ["res_ar_greetings_cards"] },
    { id: "lesson_hifz_revision", moduleId: "mod_hifz_revision", title: "Weekly Revision Map", type: "reading", durationMinutes: 20, resourceIds: ["res_hifz_revision_map"] },
    { id: "lesson_hifz_submit", moduleId: "mod_hifz_submission", title: "Submit Hifz Recitation", type: "assessment", durationMinutes: 25, resourceIds: ["res_hifz_submit_guide"] },
  ],
  resources: [
    { id: "res_ar_pdf", lessonId: "lesson_ar_conditional", title: "Grammar handout", type: "pdf", url: "#mock-resource", published: true },
    { id: "res_ar_patterns", lessonId: "lesson_ar_patterns", title: "Verb pattern worksheet", type: "document", url: "#mock-resource", published: true },
    { id: "res_ar_reading_market", lessonId: "lesson_ar_reading_market", title: "Reading passage and vocabulary", type: "pdf", url: "#mock-resource", published: true },
    { id: "res_ar_dialogue_audio", lessonId: "lesson_ar_listening_dialogue", title: "Dialogue audio track", type: "audio", url: "#mock-resource", published: true },
    { id: "res_ar_outline_doc", lessonId: "lesson_ar_writing_outline", title: "Paragraph outline template", type: "document", url: "#mock-resource", published: true },
    { id: "res_qt_audio", lessonId: "lesson_qt_madd", title: "Madd practice audio", type: "audio", url: "#mock-resource", published: true },
    { id: "res_qt_munfasil_audio", lessonId: "lesson_qt_munfasil", title: "Madd munfasil examples", type: "audio", url: "#mock-resource", published: true },
    { id: "res_qt_recording_guide", lessonId: "lesson_qt_recording", title: "Recording checklist", type: "document", url: "#mock-resource", published: true },
    { id: "res_ar_letters_pdf", lessonId: "lesson_ar_letters", title: "Letter shapes guide", type: "pdf", url: "#mock-resource", published: true },
    { id: "res_ar_greetings_cards", lessonId: "lesson_ar_greetings", title: "Greeting practice cards", type: "document", url: "#mock-resource", published: true },
    { id: "res_hifz_revision_map", lessonId: "lesson_hifz_revision", title: "Revision planning sheet", type: "pdf", url: "#mock-resource", published: true },
    { id: "res_hifz_submit_guide", lessonId: "lesson_hifz_submit", title: "Hifz submission guide", type: "document", url: "#mock-resource", published: true },
  ],
  courseRuns: [
    { id: "run_ar_l3_2026", courseId: "course_ar_l3", branchId: "br_online", teacherId: "usr_teacher_demo", term: "Summer 2026", startsOn: "2026-06-01", endsOn: "2026-08-31", status: "active" },
    { id: "run_ar_l3_cairo_2026", courseId: "course_ar_l3", branchId: "br_cairo", teacherId: "usr_teacher_demo", term: "Summer 2026 Cairo", startsOn: "2026-06-01", endsOn: "2026-08-31", status: "active" },
    { id: "run_qt_1_2026", courseId: "course_qt_1", branchId: "br_online", teacherId: "usr_teacher_demo", term: "Summer 2026", startsOn: "2026-06-01", endsOn: "2026-08-31", status: "active" },
    { id: "run_ar_l3_assign_qa", courseId: "course_ar_l3", branchId: "br_online", teacherId: "usr_teacher_demo", term: "Summer 2026 QA", startsOn: "2026-07-01", endsOn: "2026-07-31", status: "active" },
    { id: "run_ar_l1_alex_2026", courseId: "course_ar_l1", branchId: "br_alex", teacherId: "usr_teacher_alex_demo", term: "Summer 2026 Alexandria", startsOn: "2026-06-08", endsOn: "2026-08-31", status: "active" },
    { id: "run_hifz_1_2026", courseId: "course_hifz_1", branchId: "br_alex", teacherId: "usr_teacher_quran_demo", term: "Summer 2026 Hifz", startsOn: "2026-06-09", endsOn: "2026-08-29", status: "active" },
  ],
  classGroups: [
    { id: "class_ar_l3_a", courseRunId: "run_ar_l3_2026", name: "Arabic L3 - Group A", capacity: 16, schedule: "Mon/Wed/Fri 09:00", roomId: "room_online_a", meetingLinkId: "meet_ar_l3", studentIds: ["stu_demo"] },
    { id: "class_ar_l3_cairo", courseRunId: "run_ar_l3_cairo_2026", name: "Arabic L3 - Cairo Group", capacity: 20, schedule: "Sun/Tue 14:00", roomId: "room_cairo_4", meetingLinkId: "meet_ar_l3", studentIds: ["stu_cairo_demo"] },
    { id: "class_qt_1_b", courseRunId: "run_qt_1_2026", name: "Quran Tajweed - Group B", capacity: 12, schedule: "Tue/Thu 10:30", roomId: "room_online_b", meetingLinkId: "meet_qt_1", studentIds: ["stu_demo"] },
    { id: "class_ar_l3_assign_qa", courseRunId: "run_ar_l3_assign_qa", name: "Arabic L3 - Assignment QA", capacity: 8, schedule: "Fri 09:00", roomId: "room_online_a", meetingLinkId: "meet_ar_l3", studentIds: ["stu_demo"] },
    { id: "class_ar_l1_alex", courseRunId: "run_ar_l1_alex_2026", name: "Arabic L1 - Alexandria", capacity: 18, schedule: "Mon/Wed 16:00", roomId: "room_alex_2", meetingLinkId: "meet_ar_l1", studentIds: ["stu_alex_demo", "stu_completed_demo"] },
    { id: "class_hifz_1_online", courseRunId: "run_hifz_1_2026", name: "Hifz Foundations - Online", capacity: 10, schedule: "Sun/Thu 18:00", roomId: "room_alex_2", meetingLinkId: "meet_hifz_1", studentIds: ["stu_ready_demo", "stu_paused_demo"] },
  ],
  students: [
    { id: "stu_demo", userId: "usr_student_demo", status: "active", source: "direct", currentLevel: "Arabic Level 3", ageGroup: "Adult", courseInterest: "Arabic Language", country: "Demo Country", preferredLanguage: "English", timezone: "Africa/Cairo" },
    { id: "stu_cairo_demo", userId: "usr_student_cairo_demo", status: "active", source: "direct", currentLevel: "Arabic Level 3", ageGroup: "Adult", courseInterest: "Arabic Language", country: "Egypt", preferredLanguage: "English", timezone: "Africa/Cairo" },
    { id: "stu_alex_demo", userId: "usr_student_alex_demo", status: "active", source: "application", currentLevel: "Arabic Level 1", ageGroup: "Teen", courseInterest: "Arabic Language", country: "Egypt", preferredLanguage: "English", timezone: "Africa/Cairo" },
    { id: "stu_ready_demo", userId: "usr_student_ready_demo", status: "ready_to_enroll", source: "placement", currentLevel: "Tajweed 1", ageGroup: "Adult", courseInterest: "Quran and Tajweed", country: "United Kingdom", preferredLanguage: "English", timezone: "Europe/London" },
    { id: "stu_paused_demo", userId: "usr_student_paused_demo", status: "paused", source: "direct", currentLevel: "Arabic Level 3", ageGroup: "Adult", courseInterest: "Arabic Language", country: "United States", preferredLanguage: "English", timezone: "America/New_York", notes: "Paused for travel until August." },
    { id: "stu_completed_demo", userId: "usr_student_completed_demo", status: "completed", source: "direct", currentLevel: "Arabic Level 3", ageGroup: "Adult", courseInterest: "Arabic Language", country: "Egypt", preferredLanguage: "Arabic", timezone: "Africa/Cairo" },
  ],
  teachers: [
    {
      id: "tch_demo",
      userId: "usr_teacher_demo",
      departmentId: "dep_arabic",
      branchId: "br_online",
      subjects: ["Arabic grammar", "Tajweed"],
      teachingLevels: ["Arabic Level 3", "Tajweed 1"],
      specialties: ["Arabic grammar", "Tajweed"],
      availability: ["Mon 09:00", "Tue 10:30", "Thu 10:30"],
      availabilityStatus: "available",
      assignedClassIds: ["class_ar_l3_a", "class_ar_l3_cairo", "class_qt_1_b", "class_ar_l3_assign_qa"],
      status: "active",
    },
    {
      id: "tch_quran_demo",
      userId: "usr_teacher_quran_demo",
      departmentId: "dep_quran",
      branchId: "br_alex",
      subjects: ["Quran memorization", "Tajweed"],
      teachingLevels: ["Tajweed 1", "Hifz Foundations"],
      specialties: ["Hifz revision", "Makharij"],
      availability: ["Sun 18:00", "Thu 18:00"],
      availabilityStatus: "available",
      assignedClassIds: ["class_hifz_1_online"],
      status: "active",
    },
    {
      id: "tch_alex_demo",
      userId: "usr_teacher_alex_demo",
      departmentId: "dep_foundations",
      branchId: "br_alex",
      subjects: ["Arabic foundations"],
      teachingLevels: ["Arabic Level 1"],
      specialties: ["New learners", "Reading foundations"],
      availability: ["Mon 16:00", "Wed 16:00"],
      availabilityStatus: "limited",
      assignedClassIds: ["class_ar_l1_alex"],
      status: "active",
    },
  ],
  staffProfiles: [
    { id: "staff_teacher_demo", userId: "usr_teacher_demo", role: "teacher", branchIds: ["br_online"], departmentIds: ["dep_arabic"], permissionScope: "department", title: "Teacher", subjects: ["Arabic grammar", "Tajweed"], teachingLevels: ["Arabic Level 3", "Tajweed 1"], availabilityStatus: "available", operationalScope: ["classes", "attendance", "grading"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_teacher_spare", userId: "usr_teacher_spare", role: "teacher", branchIds: ["br_online"], departmentIds: ["dep_arabic"], permissionScope: "department", title: "Substitute Teacher", subjects: ["Arabic support"], teachingLevels: ["Arabic Level 1", "Arabic Level 3"], availabilityStatus: "limited", operationalScope: ["classes", "materials"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_teacher_quran_demo", userId: "usr_teacher_quran_demo", role: "teacher", branchIds: ["br_alex"], departmentIds: ["dep_quran"], permissionScope: "department", title: "Quran Teacher", subjects: ["Hifz", "Tajweed"], teachingLevels: ["Tajweed 1", "Hifz Foundations"], availabilityStatus: "available", operationalScope: ["classes", "quran_reviews", "grading"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_teacher_alex_demo", userId: "usr_teacher_alex_demo", role: "teacher", branchIds: ["br_alex"], departmentIds: ["dep_foundations"], permissionScope: "department", title: "Arabic Foundations Teacher", subjects: ["Arabic foundations"], teachingLevels: ["Arabic Level 1"], availabilityStatus: "limited", operationalScope: ["classes", "attendance"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_registrar_demo", userId: "usr_registrar_demo", role: "registrar", branchIds: ["br_cairo"], departmentIds: ["dep_admissions"], permissionScope: "admissions", title: "Registrar", subjects: [], teachingLevels: [], availabilityStatus: "not_applicable", operationalScope: ["leads", "placement", "enrollments", "payments"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_registrar_online_demo", userId: "usr_registrar_online_demo", role: "registrar", branchIds: ["br_online"], departmentIds: ["dep_admissions"], permissionScope: "admissions", title: "Online Registrar", subjects: [], teachingLevels: [], availabilityStatus: "not_applicable", operationalScope: ["leads", "placement", "enrollments", "messages"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_hod_demo", userId: "usr_hod_demo", role: "headofdepartment", branchIds: ["br_global"], departmentIds: ["dep_arabic"], permissionScope: "department", title: "Head of Department", subjects: [], teachingLevels: ["Arabic Language", "Quran and Tajweed"], availabilityStatus: "not_applicable", operationalScope: ["curriculum", "teachers", "certificates", "reports"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_hod_quran_demo", userId: "usr_hod_quran_demo", role: "headofdepartment", branchIds: ["br_global", "br_alex"], departmentIds: ["dep_quran", "dep_foundations"], permissionScope: "department", title: "Quran Program Lead", subjects: [], teachingLevels: ["Tajweed 1", "Hifz Foundations"], availabilityStatus: "not_applicable", operationalScope: ["curriculum", "quran_reviews", "certificates"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_branch_demo", userId: "usr_branch_demo", role: "branchadmin", branchIds: ["br_cairo"], departmentIds: ["dep_operations"], permissionScope: "operations", title: "Branch Admin", subjects: [], teachingLevels: [], availabilityStatus: "not_applicable", operationalScope: ["rooms", "schedule", "attendance", "payments"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_branch_alex_demo", userId: "usr_branch_alex_demo", role: "branchadmin", branchIds: ["br_alex"], departmentIds: ["dep_operations"], permissionScope: "operations", title: "Alexandria Branch Admin", subjects: [], teachingLevels: [], availabilityStatus: "not_applicable", operationalScope: ["rooms", "schedule", "attendance", "payments"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_admin_demo", userId: "usr_admin_demo", role: "superadmin", branchIds: ["br_global"], departmentIds: ["dep_platform"], permissionScope: "global", title: "Super Admin", subjects: [], teachingLevels: [], availabilityStatus: "not_applicable", operationalScope: ["users", "roles", "permissions", "audit"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
    { id: "staff_admin_ops_demo", userId: "usr_admin_ops_demo", role: "superadmin", branchIds: ["br_global"], departmentIds: ["dep_platform"], permissionScope: "global", title: "Operations Admin", subjects: [], teachingLevels: [], availabilityStatus: "not_applicable", operationalScope: ["users", "branches", "reports", "connections"], status: "active", createdAt: "2026-06-26T08:00:00+03:00", updatedAt: "2026-06-26T08:00:00+03:00" },
  ],
  enrollments: [
    { id: "enr_ar_l1_alex", studentId: "stu_alex_demo", courseRunId: "run_ar_l1_alex_2026", levelId: "lvl_ar_l1", classGroupId: "class_ar_l1_alex", teacherId: "usr_teacher_alex_demo", source: "application", status: "active", progress: 24, attendanceRate: 88, currentGrade: 79, createdAt: "2026-06-08T16:00:00+03:00" },
    { id: "enr_ar_l3", studentId: "stu_demo", courseRunId: "run_ar_l3_2026", levelId: "lvl_ar_l3", classGroupId: "class_ar_l3_a", teacherId: "usr_teacher_demo", source: "direct", status: "active", progress: 68, attendanceRate: 94, currentGrade: 88, createdAt: "2026-06-01T09:00:00+03:00" },
    { id: "enr_ar_l3_cairo", studentId: "stu_cairo_demo", courseRunId: "run_ar_l3_cairo_2026", levelId: "lvl_ar_l3", classGroupId: "class_ar_l3_cairo", teacherId: "usr_teacher_demo", source: "direct", status: "active", progress: 52, attendanceRate: 90, currentGrade: 84, createdAt: "2026-06-01T09:00:00+03:00" },
    { id: "enr_qt_1", studentId: "stu_demo", courseRunId: "run_qt_1_2026", levelId: "lvl_qt_1", classGroupId: "class_qt_1_b", teacherId: "usr_teacher_demo", source: "direct", status: "active", progress: 45, attendanceRate: 91, currentGrade: 92, createdAt: "2026-06-01T09:00:00+03:00" },
    { id: "enr_hifz_ready", studentId: "stu_ready_demo", courseRunId: "run_hifz_1_2026", levelId: "lvl_hifz_1", classGroupId: "class_hifz_1_online", teacherId: "usr_teacher_quran_demo", source: "placement", status: "ready_to_enroll", progress: 8, attendanceRate: 100, currentGrade: 0, createdAt: "2026-06-20T18:00:00+03:00" },
    { id: "enr_ar_l3_paused", studentId: "stu_paused_demo", courseRunId: "run_hifz_1_2026", levelId: "lvl_hifz_1", classGroupId: "class_hifz_1_online", teacherId: "usr_teacher_quran_demo", source: "direct", status: "paused", progress: 41, attendanceRate: 76, currentGrade: 72, createdAt: "2026-06-01T09:00:00+03:00" },
    { id: "enr_ar_l3_completed", studentId: "stu_completed_demo", courseRunId: "run_ar_l1_alex_2026", levelId: "lvl_ar_l1", classGroupId: "class_ar_l1_alex", teacherId: "usr_teacher_alex_demo", source: "direct", status: "completed", progress: 100, attendanceRate: 96, currentGrade: 93, createdAt: "2026-03-01T09:00:00+03:00" },
  ],
  lessonProgress: [
    { id: "lp_ar_letters_alex", studentId: "stu_alex_demo", lessonId: "lesson_ar_letters", status: "completed", completedAt: "2026-06-16T17:00:00+03:00" },
    { id: "lp_ar_greetings_alex", studentId: "stu_alex_demo", lessonId: "lesson_ar_greetings", status: "in_progress", notes: "Needs speaking practice." },
    { id: "lp_ar_conditional", studentId: "stu_demo", lessonId: "lesson_ar_conditional", status: "in_progress", notes: "Watched once, needs quiz." },
    { id: "lp_ar_patterns", studentId: "stu_demo", lessonId: "lesson_ar_patterns", status: "completed", completedAt: "2026-06-24T10:15:00+03:00" },
    { id: "lp_ar_reading_market", studentId: "stu_demo", lessonId: "lesson_ar_reading_market", status: "not_started" },
    { id: "lp_ar_listening_dialogue", studentId: "stu_demo", lessonId: "lesson_ar_listening_dialogue", status: "not_started" },
    { id: "lp_ar_writing_outline", studentId: "stu_demo", lessonId: "lesson_ar_writing_outline", status: "not_started" },
    { id: "lp_qt_madd", studentId: "stu_demo", lessonId: "lesson_qt_madd", status: "not_started" },
    { id: "lp_qt_munfasil", studentId: "stu_demo", lessonId: "lesson_qt_munfasil", status: "not_started" },
    { id: "lp_qt_recording", studentId: "stu_demo", lessonId: "lesson_qt_recording", status: "not_started" },
    { id: "lp_hifz_revision_ready", studentId: "stu_ready_demo", lessonId: "lesson_hifz_revision", status: "in_progress", notes: "Review cycle introduced during placement follow-up." },
    { id: "lp_ar_completed_conditional", studentId: "stu_completed_demo", lessonId: "lesson_ar_conditional", status: "completed", completedAt: "2026-05-14T10:15:00+03:00" },
  ],
  assignments: [
    { id: "asg_ar_grammar", courseRunId: "run_ar_l3_2026", title: "Grammar worksheet", dueAt: "2026-06-30T18:00:00+03:00", submissionType: "text", rubric: ["Accuracy", "Examples", "Clarity"], status: "active" },
    { id: "asg_qt_audio", courseRunId: "run_qt_1_2026", title: "Audio recitation", dueAt: "2026-07-01T18:00:00+03:00", submissionType: "audio", rubric: ["Makharij", "Madd", "Fluency"], status: "active" },
    { id: "asg_ar_l1_letters", courseRunId: "run_ar_l1_alex_2026", title: "Letter shapes practice", dueAt: "2026-07-02T18:00:00+03:00", submissionType: "file", rubric: ["Letter shape", "Short vowels", "Neat submission"], status: "active" },
    { id: "asg_hifz_revision", courseRunId: "run_hifz_1_2026", title: "Weekly revision log", dueAt: "2026-07-05T18:00:00+03:00", submissionType: "text", rubric: ["Consistency", "Memorized portion", "Revision notes"], status: "active" },
  ],
  assignmentSubmissions: [
    { id: "sub_ar_grammar_draft", assignmentId: "asg_ar_grammar", studentId: "stu_demo", submittedAt: "2026-06-25T17:30:00+03:00", status: "pending", response: "Draft answer saved locally." },
    { id: "sub_ar_l1_letters_alex", assignmentId: "asg_ar_l1_letters", studentId: "stu_alex_demo", submittedAt: "2026-06-24T17:05:00+03:00", status: "approved", response: "Uploaded letter worksheet.", score: 82, feedback: "Good control of connected letters." },
    { id: "sub_ar_grammar_paused", assignmentId: "asg_ar_grammar", studentId: "stu_paused_demo", submittedAt: "2026-06-22T19:30:00+03:00", status: "rejected", response: "Partial response before travel pause.", score: 52, feedback: "Needs full examples before resubmission." },
    { id: "sub_hifz_revision_ready", assignmentId: "asg_hifz_revision", studentId: "stu_ready_demo", submittedAt: "2026-06-28T18:20:00+03:00", status: "pending", response: "Reviewed Al-Mulk 1-10 and marked weak ayat." },
  ],
  quizzes: [
    { id: "quiz_ar_3", courseRunId: "run_ar_l3_2026", title: "Grammar Quiz 3", dueAt: "2026-07-03T18:00:00+03:00", durationMinutes: 30, questionTypes: ["multiple_choice", "short_answer"], questionIds: ["qbi_ar_conditional_mcq", "qbi_ar_market_short"], attemptsAllowed: 2, status: "active" },
    { id: "quiz_qt_madd", courseRunId: "run_qt_1_2026", title: "Madd Rules Check", dueAt: "2026-07-04T18:00:00+03:00", durationMinutes: 18, questionTypes: ["oral_record", "multiple_choice"], questionIds: ["qbi_qt_madd_oral"], attemptsAllowed: 2, status: "active" },
    { id: "quiz_ar_l1_letters", courseRunId: "run_ar_l1_alex_2026", title: "Letter Recognition Check", dueAt: "2026-07-03T18:00:00+03:00", durationMinutes: 20, questionTypes: ["multiple_choice", "short_answer"], questionIds: ["qbi_ar_l1_letter_mcq"], attemptsAllowed: 2, status: "active" },
    { id: "quiz_hifz_revision", courseRunId: "run_hifz_1_2026", title: "Revision Readiness Check", dueAt: "2026-07-06T18:00:00+03:00", durationMinutes: 15, questionTypes: ["oral_record"], questionIds: ["qbi_hifz_revision_oral"], attemptsAllowed: 1, status: "active" },
  ],
  questionBankItems: [
    {
      id: "qbi_ar_conditional_mcq",
      courseRunId: "run_ar_l3_2026",
      prompt: "Choose the correct conditional particle for a real condition.",
      type: "multiple_choice",
      difficulty: "core",
      tags: ["grammar", "conditionals"],
      choices: ["إذا", "لو", "لولا", "ليت"],
      answerKey: "إذا",
      rubric: ["Correct particle", "Understands real condition"],
      createdBy: "usr_teacher_demo",
      updatedAt: "2026-06-25T10:00:00+03:00",
      status: "active",
    },
    {
      id: "qbi_ar_market_short",
      courseRunId: "run_ar_l3_2026",
      prompt: "Write two sentences describing a market visit using past tense verbs.",
      type: "short_answer",
      difficulty: "foundation",
      tags: ["writing", "past-tense"],
      choices: [],
      answerKey: "Accept any accurate two-sentence response.",
      rubric: ["Two complete sentences", "Correct past tense", "Readable meaning"],
      createdBy: "usr_teacher_demo",
      updatedAt: "2026-06-25T10:10:00+03:00",
      status: "active",
    },
    {
      id: "qbi_qt_madd_oral",
      courseRunId: "run_qt_1_2026",
      prompt: "Record one example of Madd Munfasil and identify the stretch length.",
      type: "oral_record",
      difficulty: "challenge",
      tags: ["tajweed", "madd"],
      choices: [],
      rubric: ["Correct example", "Clear recitation", "Accurate stretch length"],
      createdBy: "usr_teacher_demo",
      updatedAt: "2026-06-25T10:20:00+03:00",
      status: "active",
    },
    {
      id: "qbi_ar_l1_letter_mcq",
      courseRunId: "run_ar_l1_alex_2026",
      prompt: "Choose the letter that starts the word bayt.",
      type: "multiple_choice",
      difficulty: "foundation",
      tags: ["letters", "reading"],
      choices: ["ب", "ت", "ث", "ن"],
      answerKey: "ب",
      rubric: ["Recognizes initial sound", "Selects correct letter"],
      createdBy: "usr_teacher_alex_demo",
      updatedAt: "2026-06-25T09:00:00+03:00",
      status: "active",
    },
    {
      id: "qbi_hifz_revision_oral",
      courseRunId: "run_hifz_1_2026",
      prompt: "Recite the assigned revision passage and identify one correction area.",
      type: "oral_record",
      difficulty: "core",
      tags: ["hifz", "revision"],
      choices: [],
      answerKey: "Teacher reviewed oral response.",
      rubric: ["Consistent memorization", "Clear correction note", "Revision discipline"],
      createdBy: "usr_teacher_quran_demo",
      updatedAt: "2026-06-25T11:20:00+03:00",
      status: "active",
    },
  ],
  quizQuestionPreviews: [],
  quizAttempts: [
    { id: "attempt_ar_3_demo", quizId: "quiz_ar_3", studentId: "stu_demo", startedAt: "2026-06-24T12:00:00+03:00", submittedAt: "2026-06-24T12:22:00+03:00", status: "completed", score: 88, maxScore: 100, answers: { q1: "Correct", q2: "Needs review" } },
    { id: "attempt_ar_l1_alex", quizId: "quiz_ar_l1_letters", studentId: "stu_alex_demo", startedAt: "2026-06-24T16:30:00+03:00", submittedAt: "2026-06-24T16:48:00+03:00", status: "completed", score: 81, maxScore: 100, answers: { q1: "ب" } },
    { id: "attempt_ar_3_paused", quizId: "quiz_ar_3", studentId: "stu_paused_demo", startedAt: "2026-06-23T12:00:00+03:00", submittedAt: "2026-06-23T12:25:00+03:00", status: "completed", score: 64, maxScore: 100, answers: { q1: "لو", q2: "Incomplete" } },
    { id: "attempt_hifz_ready", quizId: "quiz_hifz_revision", studentId: "stu_ready_demo", startedAt: "2026-06-28T19:00:00+03:00", status: "pending", score: 0, maxScore: 100, answers: { oral: "Waiting for teacher review" } },
  ],
  grades: [
    { id: "gr_ar_quiz_3", studentId: "stu_demo", courseRunId: "run_ar_l3_2026", itemTitle: "Grammar Quiz 3", score: 88, maxScore: 100, feedback: "Strong syntax control." },
    { id: "gr_ar_l1_letters", studentId: "stu_alex_demo", courseRunId: "run_ar_l1_alex_2026", itemTitle: "Letter Recognition Check", score: 81, maxScore: 100, feedback: "Good start; keep practicing connected forms." },
    { id: "gr_ar_paused_quiz", studentId: "stu_paused_demo", courseRunId: "run_ar_l3_2026", itemTitle: "Grammar Quiz 3", score: 64, maxScore: 100, feedback: "Review conditional particles after returning." },
    { id: "gr_ar_completed_final", studentId: "stu_completed_demo", courseRunId: "run_ar_l3_cairo_2026", itemTitle: "Arabic L3 final review", score: 93, maxScore: 100, feedback: "Ready for certificate issue." },
  ],
  events: [
    { id: "evt_ar_l1_alex", type: "class_session", title: "Arabic L1 Alexandria class", startsAt: "2026-06-29T16:00:00+03:00", endsAt: "2026-06-29T17:15:00+03:00", ownerId: "usr_teacher_alex_demo", branchId: "br_alex", roomId: "room_alex_2", classGroupId: "class_ar_l1_alex", status: "active" },
    { id: "evt_ar_live", type: "live_session", title: "Arabic L3 live class", startsAt: "2026-06-26T09:00:00+03:00", endsAt: "2026-06-26T10:30:00+03:00", ownerId: "usr_teacher_demo", branchId: "br_online", classGroupId: "class_ar_l3_a", status: "active" },
    { id: "evt_ar_cairo_live", type: "live_session", title: "Arabic L3 Cairo live class", startsAt: "2026-06-27T14:00:00+03:00", endsAt: "2026-06-27T15:15:00+03:00", ownerId: "usr_teacher_demo", branchId: "br_cairo", roomId: "room_cairo_4", classGroupId: "class_ar_l3_cairo", status: "active" },
    { id: "evt_hifz_online", type: "live_session", title: "Hifz revision circle", startsAt: "2026-06-28T18:00:00+03:00", endsAt: "2026-06-28T19:00:00+03:00", ownerId: "usr_teacher_quran_demo", branchId: "br_alex", roomId: "room_alex_2", classGroupId: "class_hifz_1_online", status: "active" },
    { id: "evt_ar_l3_assign_qa", type: "class_session", title: "Arabic L3 assignment QA session", startsAt: "2026-07-10T09:00:00+03:00", endsAt: "2026-07-10T10:30:00+03:00", ownerId: "usr_teacher_demo", branchId: "br_online", roomId: "room_online_a", classGroupId: "class_ar_l3_assign_qa", status: "active" },
    { id: "evt_pt_demo", type: "placement_test", title: "Placement test booking", startsAt: "2026-06-27T13:00:00+03:00", endsAt: "2026-06-27T13:30:00+03:00", ownerId: "usr_registrar_demo", branchId: "br_online", status: "pending" },
    { id: "evt_room_conflict_demo", type: "room_booking", title: "Cairo room schedule review", startsAt: "2026-07-01T14:00:00+03:00", endsAt: "2026-07-01T14:30:00+03:00", ownerId: "usr_branch_demo", branchId: "br_cairo", roomId: "room_cairo_4", status: "pending" },
  ],
  classSessions: [
    { id: "session_ar_l1_alex", classGroupId: "class_ar_l1_alex", eventId: "evt_ar_l1_alex", title: "Arabic L1 Alexandria class", startsAt: "2026-06-29T16:00:00+03:00", endsAt: "2026-06-29T17:15:00+03:00", status: "active", attendanceSaved: true },
    { id: "session_ar_live", classGroupId: "class_ar_l3_a", eventId: "evt_ar_live", title: "Arabic L3 live class", startsAt: "2026-06-26T09:00:00+03:00", endsAt: "2026-06-26T10:30:00+03:00", status: "active", attendanceSaved: false },
    { id: "session_ar_cairo_live", classGroupId: "class_ar_l3_cairo", eventId: "evt_ar_cairo_live", title: "Arabic L3 Cairo live class", startsAt: "2026-06-27T14:00:00+03:00", endsAt: "2026-06-27T15:15:00+03:00", status: "active", attendanceSaved: false },
    { id: "session_hifz_online", classGroupId: "class_hifz_1_online", eventId: "evt_hifz_online", title: "Hifz revision circle", startsAt: "2026-06-28T18:00:00+03:00", endsAt: "2026-06-28T19:00:00+03:00", status: "active", attendanceSaved: false },
  ],
  teacherAvailability: [
    { id: "avail_teacher_mon", teacherId: "usr_teacher_demo", weekday: "Monday", startsAt: "09:00", endsAt: "13:00", branchId: "br_online" },
    { id: "avail_teacher_sun_cairo", teacherId: "usr_teacher_demo", weekday: "Sunday", startsAt: "13:00", endsAt: "17:00", branchId: "br_cairo" },
    { id: "avail_teacher_thu", teacherId: "usr_teacher_demo", weekday: "Thursday", startsAt: "10:00", endsAt: "15:00", branchId: "br_online" },
    { id: "avail_teacher_quran_sun", teacherId: "usr_teacher_quran_demo", weekday: "Sunday", startsAt: "18:00", endsAt: "20:00", branchId: "br_alex" },
    { id: "avail_teacher_quran_thu", teacherId: "usr_teacher_quran_demo", weekday: "Thursday", startsAt: "18:00", endsAt: "20:00", branchId: "br_alex" },
    { id: "avail_teacher_alex_mon", teacherId: "usr_teacher_alex_demo", weekday: "Monday", startsAt: "16:00", endsAt: "18:00", branchId: "br_alex" },
  ],
  rooms: [
    { id: "room_online_a", branchId: "br_online", name: "Online Room A", capacity: 38, equipment: ["Meeting link", "Recording placeholder"], status: "active" },
    { id: "room_online_b", branchId: "br_online", name: "Online Room B", capacity: 24, equipment: ["Meeting link", "Audio review"], status: "active" },
    { id: "room_cairo_4", branchId: "br_cairo", name: "Cairo Room 4", capacity: 20, equipment: ["Projector", "Whiteboard"], status: "active" },
    { id: "room_cairo_2", branchId: "br_cairo", name: "Cairo Room 2", capacity: 14, equipment: ["Whiteboard"], status: "paused" },
    { id: "room_alex_2", branchId: "br_alex", name: "Alexandria Room 2", capacity: 18, equipment: ["Projector", "Whiteboard"], status: "active" },
  ],
  meetingLinks: [
    { id: "meet_ar_l1", provider: "mock", url: "https://meet.nilelearn.local/arabic-l1", status: "active" },
    { id: "meet_ar_l3", provider: "mock", url: "https://meet.nilelearn.local/arabic-l3", status: "active" },
    { id: "meet_qt_1", provider: "mock", url: "https://meet.nilelearn.local/quran-tajweed-1", status: "active" },
    { id: "meet_hifz_1", provider: "mock", url: "https://meet.nilelearn.local/hifz-foundations", status: "active" },
  ],
  attendance: [
    { id: "att_ar_l1_alex_1", classGroupId: "class_ar_l1_alex", studentId: "stu_alex_demo", sessionId: "evt_ar_l1_alex", status: "late", notes: "Joined 8 minutes late" },
    { id: "att_ar_1", classGroupId: "class_ar_l3_a", studentId: "stu_demo", sessionId: "evt_ar_live", status: "present", notes: "On time" },
    { id: "att_ar_ready_1", classGroupId: "class_hifz_1_online", studentId: "stu_ready_demo", sessionId: "evt_hifz_online", status: "excused", notes: "Placement follow-up appointment" },
    { id: "att_ar_paused_1", classGroupId: "class_hifz_1_online", studentId: "stu_paused_demo", sessionId: "evt_hifz_online", status: "absent", notes: "Pause request pending review" },
    { id: "att_ar_cairo_1", classGroupId: "class_ar_l3_cairo", studentId: "stu_cairo_demo", sessionId: "evt_ar_cairo_live", status: "present", notes: "Checked in at Cairo branch" },
    { id: "att_ar_completed_1", classGroupId: "class_ar_l1_alex", studentId: "stu_completed_demo", sessionId: "evt_ar_l1_alex", status: "present", notes: "Final review completed" },
    { id: "att_hifz_ready_1", classGroupId: "class_hifz_1_online", studentId: "stu_ready_demo", sessionId: "evt_hifz_online", status: "present", notes: "Submitted revision notes" },
  ],
  leads: [
    { id: "lead_demo_1", fullName: "Lead Demo", email: "lead.demo@nilelearn.local", phone: "+20 100 000 0020", subject: "Arabic Language", source: "website", status: "lead", notes: "Interested in evening classes", createdAt: "2026-06-26T09:00:00+03:00" },
    { id: "lead_alex_parent", fullName: "Mariam Parent Demo", email: "mariam.parent@nilelearn.local", phone: "+20 100 000 0021", country: "Egypt", subject: "Arabic Level 1", source: "manual", status: "enrolled", notes: "Teen learner for Alexandria branch.", createdAt: "2026-06-24T11:00:00+03:00" },
    { id: "lead_quran_ready", fullName: "Omar Quran Demo", email: "omar.quran@nilelearn.local", phone: "+44 7000 000022", country: "United Kingdom", subject: "Quran and Tajweed", source: "placement_form", status: "placement_completed", notes: "Recommended for Hifz Foundations.", createdAt: "2026-06-20T15:15:00+03:00" },
    { id: "lead_payment_followup", fullName: "Sara Followup Demo", email: "sara.followup@nilelearn.local", phone: "+20 100 000 0023", country: "Egypt", subject: "Arabic Language", source: "whatsapp", status: "ready_to_enroll", notes: "Needs payment follow-up before enrollment.", createdAt: "2026-06-23T10:10:00+03:00" },
  ],
  applications: [
    { id: "app_demo_1", leadId: "lead_demo_1", branchId: "br_online", courseInterest: "Arabic Language", schedulePreference: "Evening", status: "pending" },
    { id: "app_alex_parent", leadId: "lead_alex_parent", branchId: "br_alex", courseInterest: "Arabic Level 1", schedulePreference: "After school", status: "approved" },
    { id: "app_quran_ready", leadId: "lead_quran_ready", branchId: "br_alex", courseInterest: "Hifz Foundations", schedulePreference: "Evening online", status: "approved" },
    { id: "app_payment_followup", leadId: "lead_payment_followup", branchId: "br_alex", courseInterest: "Arabic Language", schedulePreference: "Weekend", status: "pending" },
  ],
  placementTests: [
    { id: "pt_demo_1", leadId: "lead_demo_1", fullName: "Lead Demo", email: "lead.demo@nilelearn.local", phone: "+20 100 000 0020", branchId: "br_online", subject: "Arabic Language", preferredDate: "2026-06-27", currentLevel: "Some reading ability", status: "pending" },
    { id: "pt_alex_parent", leadId: "lead_alex_parent", fullName: "Mariam Parent Demo", email: "mariam.parent@nilelearn.local", phone: "+20 100 000 0021", branchId: "br_alex", subject: "Arabic Level 1", preferredDate: "2026-06-25", currentLevel: "New learner", status: "approved", recommendedLevel: "Arabic Level 1" },
    { id: "pt_quran_ready", leadId: "lead_quran_ready", fullName: "Omar Quran Demo", email: "omar.quran@nilelearn.local", phone: "+44 7000 000022", branchId: "br_alex", subject: "Quran and Tajweed", preferredDate: "2026-06-22", currentLevel: "Can recite with basic tajweed", status: "completed", recommendedLevel: "Hifz Foundations" },
    { id: "pt_cancelled_demo", leadId: "lead_payment_followup", fullName: "Sara Followup Demo", email: "sara.followup@nilelearn.local", phone: "+20 100 000 0023", branchId: "br_alex", subject: "Arabic Language", preferredDate: "2026-06-26", currentLevel: "Unknown", status: "cancelled" },
  ],
  placementResults: [
    { id: "ptr_demo_1", bookingId: "pt_demo_1", examinerId: "usr_teacher_demo", score: 74, recommendedLevel: "Arabic Level 2", notes: "Good reading base, needs grammar review.", createdAt: "2026-06-26T12:00:00+03:00" },
    { id: "ptr_alex_parent", bookingId: "pt_alex_parent", examinerId: "usr_teacher_alex_demo", score: 42, recommendedLevel: "Arabic Level 1", notes: "Start with letters and guided speaking.", createdAt: "2026-06-25T12:00:00+03:00" },
    { id: "ptr_quran_ready", bookingId: "pt_quran_ready", examinerId: "usr_teacher_quran_demo", score: 86, recommendedLevel: "Hifz Foundations", notes: "Strong recitation base; ready for revision cycle.", createdAt: "2026-06-22T19:00:00+03:00" },
  ],
  enrollmentWorkflows: [
    { id: "ew_demo_1", leadId: "lead_demo_1", applicationId: "app_demo_1", placementTestId: "pt_demo_1", targetCourseId: "course_ar_l3", targetLevelId: "lvl_ar_l3", recommendedLevel: "Arabic Level 2", source: "placement", status: "ready_to_enroll", nextStep: "Confirm package and create invoice", updatedAt: "2026-06-26T12:10:00+03:00" },
    { id: "ew_alex_parent", leadId: "lead_alex_parent", applicationId: "app_alex_parent", studentId: "stu_alex_demo", placementTestId: "pt_alex_parent", targetCourseId: "course_ar_l1", courseRunId: "run_ar_l1_alex_2026", targetLevelId: "lvl_ar_l1", recommendedLevel: "Arabic Level 1", classGroupId: "class_ar_l1_alex", source: "application", status: "enrolled", nextStep: "Attend first Alexandria class", updatedAt: "2026-06-26T14:00:00+03:00" },
    { id: "ew_quran_ready", leadId: "lead_quran_ready", applicationId: "app_quran_ready", studentId: "stu_ready_demo", placementTestId: "pt_quran_ready", targetCourseId: "course_hifz_1", courseRunId: "run_hifz_1_2026", targetLevelId: "lvl_hifz_1", recommendedLevel: "Hifz Foundations", classGroupId: "class_hifz_1_online", source: "placement", status: "ready_to_enroll", nextStep: "Collect first invoice payment", updatedAt: "2026-06-26T14:10:00+03:00" },
    { id: "ew_payment_followup", leadId: "lead_payment_followup", applicationId: "app_payment_followup", targetCourseId: "course_ar_l3", targetLevelId: "lvl_ar_l3", source: "application", status: "ready_to_enroll", nextStep: "Call family about payment options", updatedAt: "2026-06-26T15:15:00+03:00" },
  ],
  invoices: [
    { id: "inv_demo_1", studentId: "stu_demo", amount: 2400, currency: "EGP", dueAt: "2026-06-30", status: "pending" },
    { id: "inv_cairo_demo_1", studentId: "stu_cairo_demo", amount: 2400, currency: "EGP", dueAt: "2026-07-05", status: "pending" },
    { id: "inv_alex_demo_1", studentId: "stu_alex_demo", amount: 1800, currency: "EGP", dueAt: "2026-07-02", status: "paid" },
    { id: "inv_ready_demo_1", studentId: "stu_ready_demo", amount: 1800, currency: "EGP", dueAt: "2026-06-29", status: "overdue" },
    { id: "inv_paused_demo_1", studentId: "stu_paused_demo", amount: 2400, currency: "EGP", dueAt: "2026-06-15", status: "cancelled" },
    { id: "inv_completed_demo_1", studentId: "stu_completed_demo", amount: 2400, currency: "EGP", dueAt: "2026-05-01", status: "paid" },
  ],
  payments: [
    { id: "pay_demo_1", invoiceId: "inv_demo_1", amount: 1200, method: "manual", paidAt: "2026-06-20", status: "paid" },
    { id: "pay_alex_demo_1", invoiceId: "inv_alex_demo_1", amount: 1800, method: "cash", reference: "ALEX-LOCAL-001", paidAt: "2026-06-24", status: "paid" },
    { id: "pay_completed_demo_1", invoiceId: "inv_completed_demo_1", amount: 2400, method: "bank_transfer", reference: "BT-DEMO-2026-05", paidAt: "2026-04-28", status: "paid" },
    { id: "pay_paused_refund_demo", invoiceId: "inv_paused_demo_1", amount: 800, method: "manual", reference: "REFUND-DEMO", paidAt: "2026-06-18", status: "refunded" },
  ],
  packages: [
    { id: "pkg_ar_l1_month", title: "Arabic L1 monthly", courseId: "course_ar_l1", amount: 1800, currency: "EGP", sessions: 8, status: "active" },
    { id: "pkg_ar_l3_month", title: "Arabic L3 monthly", courseId: "course_ar_l3", amount: 2400, currency: "EGP", sessions: 12, status: "active" },
    { id: "pkg_qt_month", title: "Quran Tajweed monthly", courseId: "course_qt_1", amount: 1800, currency: "EGP", sessions: 12, status: "active" },
    { id: "pkg_hifz_month", title: "Hifz Foundations monthly", courseId: "course_hifz_1", amount: 1800, currency: "EGP", sessions: 10, status: "active" },
  ],
  discounts: [
    { id: "disc_family", code: "FAMILY10", amount: 240, currency: "EGP", status: "active" },
  ],
  certificates: [
    { id: "cert_ar_2", studentId: "stu_demo", courseId: "course_ar_l3", status: "pending_approval", grade: 88, attendanceRate: 94, verificationCode: "NCL-AR2-DEMO" },
    { id: "cert_ar_reject_demo", studentId: "stu_demo", courseId: "course_ar_l3", status: "pending_approval", grade: 86, attendanceRate: 91, verificationCode: "NCL-AR-REJECT-QA" },
    { id: "cert_ar_completed_issued", studentId: "stu_completed_demo", courseId: "course_ar_l1", status: "issued", grade: 93, attendanceRate: 96, verificationCode: "NCL-AR1-ISSUED-DEMO", approvedBy: "usr_hod_quran_demo", approvedAt: "2026-06-18T10:00:00+03:00", issuedBy: "usr_admin_demo", issuedAt: "2026-06-19T10:00:00+03:00" },
    { id: "cert_quran_ready_approved", studentId: "stu_ready_demo", courseId: "course_qt_1", status: "approved", grade: 91, attendanceRate: 95, verificationCode: "NCL-QT-APPROVED-DEMO", approvedBy: "usr_hod_quran_demo", approvedAt: "2026-06-24T12:00:00+03:00" },
    { id: "cert_paused_rejected", studentId: "stu_paused_demo", courseId: "course_hifz_1", status: "rejected", grade: 64, attendanceRate: 76, verificationCode: "NCL-HF-REJECTED-DEMO", rejectedBy: "usr_hod_quran_demo", rejectedAt: "2026-06-23T12:00:00+03:00", rejectionReason: "Completion requirements not met before pause." },
  ],
  quranPlans: [
    { id: "qp_demo", studentId: "stu_demo", target: "Juz 1-5", currentJuz: "Juz 2", revisionCycle: "Every 7 days", teacherId: "usr_teacher_demo" },
    { id: "qp_ready_hifz", studentId: "stu_ready_demo", target: "Juz Amma", currentJuz: "Juz 30", revisionCycle: "Every 5 days", teacherId: "usr_teacher_quran_demo" },
  ],
  quranProgress: [
    { id: "qr_demo", studentId: "stu_demo", surah: "Al-Baqarah", juz: "2", memorizedPercent: 72, tajweedScore: 88, notes: "Madd timing improved." },
    { id: "qr_ready_mulk", studentId: "stu_ready_demo", surah: "Al-Mulk", juz: "29", memorizedPercent: 38, tajweedScore: 84, notes: "Stable memorization, needs waqf review." },
    { id: "qr_completed_naba", studentId: "stu_completed_demo", surah: "An-Naba", juz: "30", memorizedPercent: 100, tajweedScore: 94, notes: "Completed revision cycle." },
  ],
  recitationSubmissions: [
    { id: "rec_demo", studentId: "stu_demo", teacherId: "usr_teacher_demo", title: "Surah Al-Baqarah 24-29", submittedAt: "2026-06-25T18:00:00+03:00", status: "pending" },
    { id: "rec_ready_mulk", studentId: "stu_ready_demo", teacherId: "usr_teacher_quran_demo", title: "Surah Al-Mulk 1-10", submittedAt: "2026-06-27T18:30:00+03:00", status: "pending" },
    { id: "rec_completed_naba", studentId: "stu_completed_demo", teacherId: "usr_teacher_quran_demo", title: "Surah An-Naba final review", submittedAt: "2026-06-18T18:30:00+03:00", status: "approved", feedback: "Clear recitation and strong revision discipline." },
  ],
  messages: [
    { id: "msg_demo_1", fromUserId: "usr_teacher_demo", toUserId: "usr_student_demo", subject: "Class reminder", body: "Arabic L3 starts at 09:00 Cairo time.", read: false, createdAt: "2026-06-26T08:30:00+03:00" },
    { id: "msg_registrar_ready", fromUserId: "usr_registrar_online_demo", toUserId: "usr_student_ready_demo", subject: "Enrollment follow-up", body: "Your Hifz placement is complete. Please review the invoice before class starts.", read: false, createdAt: "2026-06-26T14:30:00+03:00" },
    { id: "msg_teacher_feedback", fromUserId: "usr_teacher_alex_demo", toUserId: "usr_student_alex_demo", subject: "Letter practice feedback", body: "Good progress this week. Practice connected forms before Monday.", read: true, createdAt: "2026-06-25T17:30:00+03:00" },
    { id: "msg_branch_schedule", fromUserId: "usr_branch_demo", toUserId: "usr_teacher_demo", subject: "Cairo room check", body: "Please confirm the Cairo Room 4 schedule before the next session.", read: false, createdAt: "2026-06-26T11:00:00+03:00" },
  ],
  communicationLogs: [
    { id: "comm_demo_1", actorId: "usr_registrar_demo", channel: "in_app", subject: "Placement confirmation", body: "Placement test confirmed for tomorrow.", relatedUserId: "usr_student_demo", status: "completed", createdAt: "2026-06-26T10:00:00+03:00" },
    { id: "comm_ready_payment", actorId: "usr_registrar_online_demo", channel: "phone", subject: "Payment follow-up", body: "Called family about Hifz invoice and next class.", relatedUserId: "usr_student_ready_demo", status: "completed", createdAt: "2026-06-26T14:45:00+03:00" },
    { id: "comm_alex_welcome", actorId: "usr_registrar_demo", channel: "in_app", subject: "Alexandria welcome note", body: "Sent first-class details to Alexandria learner.", relatedUserId: "usr_student_alex_demo", status: "completed", createdAt: "2026-06-25T16:00:00+03:00" },
    { id: "comm_paused_note", actorId: "usr_branch_demo", channel: "manual", subject: "Pause request", body: "Recorded pause request and attendance exception.", relatedUserId: "usr_student_paused_demo", status: "pending", createdAt: "2026-06-24T10:00:00+03:00" },
  ],
  messageTemplates: [
    { id: "tmpl_trial", title: "Trial lesson confirmation", channel: "whatsapp", subject: "Trial lesson confirmed", body: "Your Nile Center trial lesson is confirmed.", category: "admissions", status: "active" },
    { id: "tmpl_payment", title: "Payment reminder", channel: "email", subject: "Payment reminder", body: "Your invoice is ready for review.", category: "finance", status: "active" },
  ],
  documents: [
    { id: "doc_cert_demo", ownerId: "stu_demo", title: "Certificate preview", type: "certificate", url: "#certificate-preview", status: "draft" },
    { id: "doc_cert_issued_completed", ownerId: "stu_completed_demo", title: "Issued Arabic L3 certificate", type: "certificate", url: "#certificate-preview", status: "issued" },
    { id: "doc_receipt_alex", ownerId: "stu_alex_demo", title: "Alexandria payment receipt", type: "receipt", url: "#receipt-preview", status: "issued" },
  ],
  notifications: [
    { id: "not_demo_1", userId: "usr_student_demo", title: "Class reminder", body: "Arabic L3 starts in 30 minutes.", href: "/app/student/calendar", read: false, createdAt: "2026-06-26T08:30:00+03:00" },
    { id: "not_ready_payment", userId: "usr_student_ready_demo", title: "Payment follow-up", body: "Your Hifz invoice needs attention.", href: "/app/student/billing", read: false, createdAt: "2026-06-26T14:35:00+03:00" },
    { id: "not_teacher_grading", userId: "usr_teacher_demo", title: "Submissions waiting", body: "Two Arabic submissions are ready for review.", href: "/app/teacher/grading", read: false, createdAt: "2026-06-26T09:15:00+03:00" },
    { id: "not_hod_cert", userId: "usr_hod_demo", title: "Certificate approval", body: "A completed student certificate is ready to verify.", href: "/app/hod/certificates", read: false, createdAt: "2026-06-26T09:45:00+03:00" },
  ],
  supportTickets: [
    { id: "ticket_demo_1", requesterId: "usr_student_demo", subject: "Need recording link", status: "pending", priority: "normal", lastUpdatedAt: "2026-06-25T15:00:00+03:00" },
    { id: "ticket_ready_payment", requesterId: "usr_student_ready_demo", subject: "Invoice question", status: "pending", priority: "high", lastUpdatedAt: "2026-06-26T14:50:00+03:00" },
    { id: "ticket_alex_room", requesterId: "usr_branch_alex_demo", subject: "Projector check for Alexandria Room 2", status: "active", priority: "normal", lastUpdatedAt: "2026-06-26T12:00:00+03:00" },
  ],
  reportPresets: [
    {
      id: "rptpreset_admin_finance",
      ownerUserId: "usr_admin_demo",
      role: "superadmin",
      label: "Executive finance snapshot",
      reportType: "finance",
      search: "",
      status: "pending",
      rowCount: 2,
      createdAt: "2026-06-26T08:05:00+03:00",
    },
    {
      id: "rptpreset_branch_attendance",
      ownerUserId: "usr_branch_demo",
      role: "branchadmin",
      label: "Cairo attendance exceptions",
      reportType: "attendance",
      search: "cairo",
      status: "all",
      rowCount: 1,
      createdAt: "2026-06-26T08:10:00+03:00",
    },
    {
      id: "rptpreset_registrar_pipeline",
      ownerUserId: "usr_registrar_demo",
      role: "registrar",
      label: "Admissions follow-up queue",
      reportType: "enrollments",
      search: "ready",
      status: "ready_to_enroll",
      rowCount: 3,
      createdAt: "2026-06-26T08:20:00+03:00",
    },
    {
      id: "rptpreset_hod_certificates",
      ownerUserId: "usr_hod_demo",
      role: "headofdepartment",
      label: "Certificate approval queue",
      reportType: "audit",
      search: "certificate",
      status: "pending_approval",
      rowCount: 2,
      createdAt: "2026-06-26T08:25:00+03:00",
    },
  ],
  auditLogs: [
    { id: "audit_seed_1", actorId: "usr_admin_demo", action: "seed.loaded", entityType: "PlatformState", entityId: "seed", summary: "Loaded local demo platform state.", createdAt: "2026-06-26T08:00:00+03:00" },
    { id: "audit_user_teacher_created", actorId: "usr_admin_demo", action: "user.created", entityType: "User", entityId: "usr_teacher_quran_demo", summary: "Created Quran teacher demo account.", createdAt: "2026-06-26T08:05:00+03:00" },
    { id: "audit_role_scope_updated", actorId: "usr_admin_demo", action: "user.scope.updated", entityType: "StaffProfile", entityId: "staff_branch_alex_demo", summary: "Assigned Alexandria branch access.", createdAt: "2026-06-26T08:08:00+03:00" },
    { id: "audit_lead_converted", actorId: "usr_registrar_demo", action: "lead.converted", entityType: "EnrollmentWorkflow", entityId: "ew_alex_parent", summary: "Converted Alexandria lead to enrolled student.", createdAt: "2026-06-26T14:00:00+03:00" },
    { id: "audit_attendance_saved", actorId: "usr_teacher_alex_demo", action: "attendance.saved", entityType: "ClassSession", entityId: "session_ar_l1_alex", summary: "Saved attendance for Alexandria Level 1 class.", createdAt: "2026-06-29T17:20:00+03:00" },
    { id: "audit_certificate_seeded", actorId: "usr_admin_demo", action: "certificate.seeded", entityType: "Certificate", entityId: "cert_ar_completed_issued", summary: "Seeded issued certificate for completed demo student.", createdAt: "2026-06-19T10:00:00+03:00" },
  ],
  integrations: [
    { id: "supabase", label: "Supabase data platform", status: "connected", envVars: ["VITE_SUPABASE_URL", "VITE_SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_ANON_KEY"], serverOnly: false, lastSyncAt: "2026-06-26T08:00:00+03:00", notes: "Browser code uses only publishable or anon keys. Admin/service credentials are validated server-side and must never appear in browser setup fields." },
    { id: "moodle", label: "Moodle LMS", status: "mock_mode", envVars: ["MOODLE_BASE_URL", "MOODLE_SERVICE", "MOODLE_TOKEN"], serverOnly: true, notes: "Content, courses, grades, and assignments should sync server-side." },
    { id: "ems", label: "EMS registration portal", status: "mock_mode", envVars: ["EMS_BASE_URL"], serverOnly: true, notes: "Admissions and enrollment import boundary." },
    { id: "email", label: "Email provider", status: "not_configured", envVars: ["EMAIL_PROVIDER"], serverOnly: true, notes: "Templates are logged until delivery is connected." },
    { id: "whatsapp", label: "WhatsApp provider", status: "not_configured", envVars: ["WHATSAPP_PROVIDER"], serverOnly: true, notes: "No external sending from the browser." },
    { id: "meeting", label: "Meeting provider", status: "not_configured", envVars: ["MEETING_PROVIDER"], serverOnly: true, notes: "Live class links and recordings." },
    { id: "payment", label: "Payment provider", status: "not_configured", envVars: ["PAYMENT_PROVIDER"], serverOnly: true, notes: "Invoices stay manual until connected." },
    { id: "jotform", label: "Jotform/import", status: "not_configured", envVars: [], serverOnly: true, notes: "Future import adapter for legacy forms." },
  ],
  permissions: rolePermissions,
};
