/**
 * Landing page copy. English is the source; Arabic and Turkish must match its
 * shape (TypeScript enforces it). Facts come from nilecenter.edu.eg and the
 * previous landing page: founded 1998, Nasr City campuses, live online.
 */
export type LandingLocale = "en" | "ar" | "tr";

const en = {
  langName: "English",
  notice: "Admissions are open. Placement tests and trial lessons are free.",
  where: "Nasr City, Cairo · Live online worldwide",
  nav: {
    programmes: "Programmes",
    start: "How to start",
    modes: "Online & campus",
    contact: "Contact",
    signIn: "Sign in",
    menu: "Menu",
    close: "Close menu",
    language: "Language",
    skip: "Skip to content",
  },
  hero: {
    eyebrow: "Arabic, Qur’an and Islamic studies since 1998",
    line1: "Learn with passion.",
    line2: "Succeed with",
    accent: "distinction.",
    lead: "Certified teachers, a plan built around your level, and classes live online or on campus in Nasr City, Cairo.",
    trial: "Book a free trial lesson",
    placement: "Book a placement test",
    note: "Every learner starts with a free 30-minute placement test.",
    chipOnline: "Live online, worldwide",
    chipCampus: "Two campuses in Nasr City",
    chipCertified: "Certified teachers",
  },
  stats: [
    { value: "1998", label: "Founded in Cairo" },
    { value: "120,000+", label: "Learners taught" },
    { value: "120", label: "Nationalities" },
    { value: "150", label: "Teachers" },
  ],
  programmes: {
    title: "Programmes",
    lead: "Eight paths, one standard of teaching. Every path begins at your level.",
    all: "See every programme",
    open: "Explore",
    items: [
      { slug: "quran", name: "Qur’an", desc: "Recitation for beginners, Tajweed, Hifz, Ijāzah, the seven and ten Qirā’āt.", meta: "Beginner to Ijāzah" },
      { slug: "arabic", name: "Arabic", desc: "Modern Standard, Egyptian Ammiyya, conversation, grammar and calligraphy.", meta: "A1 to advanced" },
      { slug: "islamic-studies", name: "Islamic studies", desc: "Qur’anic Arabic and guided foundations of Islamic studies.", meta: "Weekly live cohorts" },
      { slug: "kids", name: "Kids", desc: "Qur’an, Arabic and Islamic studies paths built for young learners.", meta: "Ages 5 to 14" },
      { slug: "turkish", name: "Turkish", desc: "Modern Turkish for study, travel and daily life.", meta: "A1 to B2" },
      { slug: "english", name: "English", desc: "General and academic English in small, focused groups.", meta: "All levels" },
      { slug: "teacher-training", name: "Teacher training", desc: "Method, classroom craft and assessment for teachers of Arabic and Qur’an.", meta: "For practising teachers" },
      { slug: "enterprise", name: "Organisations", desc: "Programmes designed with schools, companies, mosques and communities.", meta: "Built with you" },
    ],
  },
  wisdom: {
    meaning: "Knowledge is light.",
    text: "An old Arabic saying, and the reason Nile Center exists: every lesson should leave a learner seeing a little more clearly.",
  },
  teach: {
    title: "How we teach",
    lead: "Three habits every class shares, from a child’s first letters to an Ijāzah.",
    items: [
      { title: "A plan built to your level", text: "Every learner, from absolute beginner to Ijāzah candidate, gets a plan that starts where the placement test found them." },
      { title: "Live and interactive", text: "Real teachers, real conversation, in morning, afternoon and evening groups, with recordings to revise from." },
      { title: "Progress on record", text: "Attendance, grades and teacher feedback stay in one account, so you and your family always know where you stand." },
    ],
  },
  start: {
    title: "How you start",
    lead: "The same four steps for every learner, whatever the level.",
    steps: [
      { title: "Tell us your goal", text: "Send a short enquiry. An admissions advisor replies with the right options." },
      { title: "Free placement test", text: "Thirty minutes, online or on campus, so you start at exactly your level." },
      { title: "Free trial lesson", text: "Sit a real lesson with a certified teacher before you decide anything." },
      { title: "Join your class", text: "Pick a morning, afternoon or evening group. Your plan and progress live in one place." },
    ],
  },
  modes: {
    title: "Online or on campus",
    lead: "The same teachers and the same standard, wherever you learn.",
    online: {
      title: "Live online",
      text: "Interactive live classes with recorded lessons on your learning platform.",
      points: ["Join from anywhere in the world", "Morning, afternoon and evening groups", "Recordings and materials included"],
      phoneLabel: "Online courses",
    },
    campus: {
      title: "On campus in Cairo",
      text: "Two campuses in Nasr City with quiet classrooms and calligraphy studios.",
      points: ["Branch 1: 37 Abd Al-Shafy Mohammed, 7th District", "Branch 2: 6 Fadl ibn Rabea, 7th District", "Placement tests and trials on site"],
      phoneLabel: "Onsite courses",
    },
  },
  quotes: {
    title: "In our learners’ words",
    items: [
      { text: "My teachers guided me through the full memorisation programme in eight months. I received my Ijāzah and now teach beginners at home.", name: "Ahmed", context: "Hifz and Ijāzah, UAE" },
      { text: "I went from no Arabic to fluent conversation in six months, and gave a live presentation in Cairo.", name: "Sarah", context: "Arabic, United Kingdom" },
      { text: "Personal coaching and interactive lessons took me to confident Egyptian Ammiyya in three months.", name: "Yasmine", context: "Egyptian Ammiyya, Turkey" },
    ],
  },
  films: {
    title: "See a real class",
    lead: "Two short films from Nile Center’s own channel, on learning online and on campus.",
    online: { title: "Learning online", note: "Nile Center’s film on its live online courses" },
    campus: { title: "Learning on campus", note: "Nile Center’s film on its Nasr City courses" },
    play: "Play film",
    source: "Plays from YouTube",
    close: "Close film",
  },
  faq: {
    title: "Questions people ask first",
    lead: "Short answers. For anything else, message an admissions advisor on WhatsApp.",
    items: [
      { q: "What happens in the free placement test?", a: "It takes about 30 minutes, online or on campus. A teacher checks your level and tells you where to start." },
      { q: "Can I try a lesson before I pay?", a: "Yes. Book a free trial lesson with a certified teacher, then decide." },
      { q: "When are classes held?", a: "There are morning, afternoon and evening groups, online and on campus." },
      { q: "Do you teach children?", a: "Yes. The Kids path covers Qur’an, Arabic and Islamic studies for ages 5 to 14." },
      { q: "Can I study from outside Egypt?", a: "Yes. Live online classes run worldwide, with recordings and materials to revise from." },
      { q: "Where are the campuses?", a: "Two branches in the 7th District of Nasr City, Cairo: 37 Abd Al-Shafy Mohammed and 6 Fadl ibn Rabea." },
    ],
  },
  cta: {
    title: "Start with a free trial lesson.",
    text: "Tell us what you want to learn. We reply with a time for your placement test and trial lesson.",
    trial: "Book a free trial lesson",
    whatsapp: "Message us on WhatsApp",
  },
  footer: {
    tagline: "Education for a brighter future, one learner at a time.",
    programmes: "Programmes",
    school: "School",
    contact: "Contact",
    about: "About us",
    faq: "Questions",
    verify: "Verify a certificate",
    privacy: "Privacy",
    terms: "Terms",
    staff: "Staff sign in",
    rights: "Nile Learning Center. All rights reserved.",
  },
};

export type LandingCopy = typeof en;

const ar: LandingCopy = {
  langName: "العربية",
  notice: "باب القبول مفتوح. اختبارات تحديد المستوى والحصص التجريبية مجانية.",
  where: "مدينة نصر، القاهرة · مباشر أونلاين حول العالم",
  nav: {
    programmes: "البرامج",
    start: "كيف تبدأ",
    modes: "أونلاين وحضوري",
    contact: "تواصل معنا",
    signIn: "تسجيل الدخول",
    menu: "القائمة",
    close: "إغلاق القائمة",
    language: "اللغة",
    skip: "تخطَّ إلى المحتوى",
  },
  hero: {
    eyebrow: "العربية والقرآن والدراسات الإسلامية منذ 1998",
    line1: "تعلّم بشغف.",
    line2: "وتفوّق",
    accent: "بامتياز.",
    lead: "معلمون معتمدون، وخطة مبنية على مستواك، وحصص مباشرة أونلاين أو في مقرّنا بمدينة نصر في القاهرة.",
    trial: "احجز حصة تجريبية مجانية",
    placement: "احجز اختبار تحديد المستوى",
    note: "يبدأ كل متعلم باختبار مجاني لتحديد المستوى مدته 30 دقيقة.",
    chipOnline: "مباشر أونلاين حول العالم",
    chipCampus: "فرعان في مدينة نصر",
    chipCertified: "معلمون معتمدون",
  },
  stats: [
    { value: "1998", label: "تأسس في القاهرة" },
    { value: "+120,000", label: "متعلم" },
    { value: "120", label: "جنسية" },
    { value: "150", label: "معلمًا" },
  ],
  programmes: {
    title: "البرامج",
    lead: "ثمانية مسارات بمعيار تعليم واحد. كل مسار يبدأ من مستواك.",
    all: "عرض كل البرامج",
    open: "اكتشف",
    items: [
      { slug: "quran", name: "القرآن الكريم", desc: "التلاوة للمبتدئين، والتجويد، والحفظ، والإجازة، والقراءات السبع والعشر.", meta: "من البداية حتى الإجازة" },
      { slug: "arabic", name: "اللغة العربية", desc: "الفصحى، والعامية المصرية، والمحادثة، والنحو، والخط العربي.", meta: "من A1 حتى المتقدم" },
      { slug: "islamic-studies", name: "الدراسات الإسلامية", desc: "العربية القرآنية وأسس الدراسات الإسلامية بإشراف معلم.", meta: "مجموعات مباشرة أسبوعية" },
      { slug: "kids", name: "الأطفال", desc: "مسارات في القرآن والعربية والدراسات الإسلامية مصممة للصغار.", meta: "من 5 إلى 14 سنة" },
      { slug: "turkish", name: "اللغة التركية", desc: "التركية الحديثة للدراسة والسفر والحياة اليومية.", meta: "من A1 حتى B2" },
      { slug: "english", name: "اللغة الإنجليزية", desc: "الإنجليزية العامة والأكاديمية في مجموعات صغيرة مركّزة.", meta: "كل المستويات" },
      { slug: "teacher-training", name: "إعداد المعلمين", desc: "طرق التدريس وإدارة الفصل والتقييم لمعلمي العربية والقرآن.", meta: "للمعلمين الممارسين" },
      { slug: "enterprise", name: "المؤسسات", desc: "برامج نصممها مع المدارس والشركات والمساجد والمجتمعات.", meta: "نصممها معكم" },
    ],
  },
  wisdom: {
    meaning: "العلم نور.",
    text: "حكمة عربية قديمة، وهي سبب وجود مركز النيل: أن يترك كل درس المتعلّم يرى أوضح قليلًا.",
  },
  teach: {
    title: "كيف نُعلّم",
    lead: "ثلاث عادات يشترك فيها كل فصل، من أول حروف الطفل حتى الإجازة.",
    items: [
      { title: "خطة على قدر مستواك", text: "كل متعلم، من المبتدئ تمامًا حتى طالب الإجازة، يحصل على خطة تبدأ من حيث وجده اختبار المستوى." },
      { title: "مباشر وتفاعلي", text: "معلمون حقيقيون وحوار حقيقي في مجموعات صباحية وظهرية ومسائية، مع تسجيلات للمراجعة." },
      { title: "تقدّم موثّق", text: "الحضور والدرجات وملاحظات المعلم في حساب واحد، لتعرف أنت وأسرتك موقعك دائمًا." },
    ],
  },
  start: {
    title: "كيف تبدأ",
    lead: "أربع خطوات نفسها لكل متعلم، مهما كان مستواه.",
    steps: [
      { title: "أخبرنا بهدفك", text: "أرسل استفسارًا قصيرًا، ويرد عليك مستشار القبول بالخيارات المناسبة." },
      { title: "اختبار مستوى مجاني", text: "ثلاثون دقيقة أونلاين أو في المقر، لتبدأ من مستواك بالضبط." },
      { title: "حصة تجريبية مجانية", text: "احضر حصة حقيقية مع معلم معتمد قبل أن تقرر أي شيء." },
      { title: "انضم إلى فصلك", text: "اختر مجموعة صباحية أو مسائية. خطتك وتقدمك في مكان واحد." },
    ],
  },
  modes: {
    title: "أونلاين أو حضوري",
    lead: "المعلمون أنفسهم والمعيار نفسه، أينما تعلّمت.",
    online: {
      title: "مباشر أونلاين",
      text: "حصص تفاعلية مباشرة مع دروس مسجلة على منصتك التعليمية.",
      points: ["انضم من أي مكان في العالم", "مجموعات صباحية وظهرية ومسائية", "التسجيلات والمواد مشمولة"],
      phoneLabel: "الدورات الأونلاين",
    },
    campus: {
      title: "حضوري في القاهرة",
      text: "فرعان في مدينة نصر بفصول هادئة واستوديوهات للخط العربي.",
      points: ["الفرع الأول: 37 شارع عبد الشافي محمد، الحي السابع", "الفرع الثاني: 6 شارع الفضل بن الربيع، الحي السابع", "اختبارات المستوى والحصص التجريبية في المقر"],
      phoneLabel: "الدورات الحضورية",
    },
  },
  quotes: {
    title: "بكلمات متعلمينا",
    items: [
      { text: "أرشدني معلميّ في برنامج الحفظ كاملًا خلال ثمانية أشهر. حصلت على الإجازة وأُدرّس المبتدئين الآن في بلدي.", name: "أحمد", context: "الحفظ والإجازة، الإمارات" },
      { text: "انتقلت من الصفر إلى محادثة طليقة بالعربية في ستة أشهر، وقدّمت عرضًا مباشرًا في القاهرة.", name: "سارة", context: "اللغة العربية، المملكة المتحدة" },
      { text: "بفضل التوجيه الشخصي والحصص التفاعلية أتقنت العامية المصرية في ثلاثة أشهر.", name: "ياسمين", context: "العامية المصرية، تركيا" },
    ],
  },
  films: {
    title: "شاهد حصة حقيقية",
    lead: "فيلمان قصيران من قناة مركز النيل عن التعلم أونلاين وفي المقر.",
    online: { title: "التعلم أونلاين", note: "فيلم مركز النيل عن دوراته المباشرة أونلاين" },
    campus: { title: "التعلم في المقر", note: "فيلم مركز النيل عن دوراته في مدينة نصر" },
    play: "تشغيل الفيلم",
    source: "يُعرض من يوتيوب",
    close: "إغلاق الفيلم",
  },
  faq: {
    title: "أسئلة يطرحها الناس أولًا",
    lead: "إجابات قصيرة. لأي سؤال آخر، راسل مستشار القبول على واتساب.",
    items: [
      { q: "ماذا يحدث في اختبار تحديد المستوى المجاني؟", a: "يستغرق نحو 30 دقيقة، أونلاين أو في المقر. يحدد المعلم مستواك ويخبرك من أين تبدأ." },
      { q: "هل يمكنني تجربة حصة قبل الدفع؟", a: "نعم. احجز حصة تجريبية مجانية مع معلم معتمد، ثم قرّر." },
      { q: "متى تُعقد الحصص؟", a: "توجد مجموعات صباحية وظهرية ومسائية، أونلاين وفي المقر." },
      { q: "هل تدرّسون الأطفال؟", a: "نعم. مسار الأطفال يشمل القرآن والعربية والدراسات الإسلامية من سن 5 إلى 14 سنة." },
      { q: "هل يمكنني الدراسة من خارج مصر؟", a: "نعم. الحصص المباشرة أونلاين متاحة حول العالم، مع تسجيلات ومواد للمراجعة." },
      { q: "أين يقع المقر؟", a: "فرعان في الحي السابع بمدينة نصر، القاهرة: 37 شارع عبد الشافي محمد، و6 شارع فضل بن ربيع." },
    ],
  },
  cta: {
    title: "ابدأ بحصة تجريبية مجانية.",
    text: "أخبرنا بما تريد تعلّمه، ونرد عليك بموعد اختبار المستوى والحصة التجريبية.",
    trial: "احجز حصة تجريبية مجانية",
    whatsapp: "راسلنا على واتساب",
  },
  footer: {
    tagline: "تعليم من أجل مستقبل أفضل، متعلمًا بعد متعلم.",
    programmes: "البرامج",
    school: "المركز",
    contact: "تواصل",
    about: "من نحن",
    faq: "الأسئلة الشائعة",
    verify: "التحقق من شهادة",
    privacy: "الخصوصية",
    terms: "الشروط",
    staff: "دخول الموظفين",
    rights: "مركز النيل التعليمي. جميع الحقوق محفوظة.",
  },
};

const tr: LandingCopy = {
  langName: "Türkçe",
  notice: "Kayıtlar açık. Seviye sınavları ve deneme dersleri ücretsiz.",
  where: "Nasr City, Kahire · Dünya genelinde canlı çevrim içi",
  nav: {
    programmes: "Programlar",
    start: "Nasıl başlanır",
    modes: "Çevrim içi ve kampüs",
    contact: "İletişim",
    signIn: "Giriş yap",
    menu: "Menü",
    close: "Menüyü kapat",
    language: "Dil",
    skip: "İçeriğe geç",
  },
  hero: {
    eyebrow: "1998’den beri Arapça, Kur’an ve İslami ilimler",
    line1: "Tutkuyla öğrenin.",
    line2: "Farkla",
    accent: "başarın.",
    lead: "Sertifikalı öğretmenler, seviyenize göre hazırlanan bir plan ve çevrim içi ya da Kahire Nasr City kampüsünde canlı dersler.",
    trial: "Ücretsiz deneme dersi alın",
    placement: "Seviye sınavı planlayın",
    note: "Her öğrenci 30 dakikalık ücretsiz bir seviye sınavıyla başlar.",
    chipOnline: "Dünya genelinde canlı",
    chipCampus: "Nasr City’de iki kampüs",
    chipCertified: "Sertifikalı öğretmenler",
  },
  stats: [
    { value: "1998", label: "Kahire’de kuruldu" },
    { value: "120.000+", label: "Öğrenci" },
    { value: "120", label: "Uyruk" },
    { value: "150", label: "Öğretmen" },
  ],
  programmes: {
    title: "Programlar",
    lead: "Sekiz yol, tek bir öğretim standardı. Her yol sizin seviyenizden başlar.",
    all: "Tüm programları görün",
    open: "İncele",
    items: [
      { slug: "quran", name: "Kur’an", desc: "Başlangıç tilaveti, tecvid, hıfz, icazet, yedi ve on kıraat.", meta: "Başlangıçtan icazete" },
      { slug: "arabic", name: "Arapça", desc: "Modern Standart Arapça, Mısır lehçesi, konuşma, dil bilgisi ve hat.", meta: "A1’den ileri seviyeye" },
      { slug: "islamic-studies", name: "İslami ilimler", desc: "Kur’an Arapçası ve rehberli İslami ilimler temelleri.", meta: "Haftalık canlı gruplar" },
      { slug: "kids", name: "Çocuklar", desc: "Küçük öğrenciler için Kur’an, Arapça ve İslami ilimler yolları.", meta: "5-14 yaş" },
      { slug: "turkish", name: "Türkçe", desc: "Eğitim, seyahat ve günlük yaşam için modern Türkçe.", meta: "A1’den B2’ye" },
      { slug: "english", name: "İngilizce", desc: "Küçük ve odaklı gruplarda genel ve akademik İngilizce.", meta: "Tüm seviyeler" },
      { slug: "teacher-training", name: "Öğretmen eğitimi", desc: "Arapça ve Kur’an öğretmenleri için yöntem, sınıf yönetimi ve ölçme.", meta: "Görevdeki öğretmenler için" },
      { slug: "enterprise", name: "Kurumlar", desc: "Okullar, şirketler, camiler ve topluluklarla birlikte tasarlanan programlar.", meta: "Sizinle birlikte" },
    ],
  },
  wisdom: {
    meaning: "İlim nurdur.",
    text: "Eski bir Arap sözü ve Nil Merkezi’nin var olma nedeni: her ders, öğrenciyi biraz daha net görür hâlde bırakmalı.",
  },
  teach: {
    title: "Nasıl öğretiyoruz",
    lead: "Bir çocuğun ilk harflerinden icazete kadar her sınıfın paylaştığı üç alışkanlık.",
    items: [
      { title: "Seviyenize göre bir plan", text: "Mutlak başlangıçtan icazet adayına kadar her öğrenci, seviye sınavının bulduğu yerden başlayan bir plan alır." },
      { title: "Canlı ve etkileşimli", text: "Sabah, öğleden sonra ve akşam gruplarında gerçek öğretmenler ve gerçek sohbet; tekrar için kayıtlar da var." },
      { title: "Kayıtlı ilerleme", text: "Devam, notlar ve öğretmen geri bildirimi tek hesapta; siz ve aileniz her zaman nerede olduğunuzu bilirsiniz." },
    ],
  },
  start: {
    title: "Nasıl başlarsınız",
    lead: "Seviyesi ne olursa olsun her öğrenci için aynı dört adım.",
    steps: [
      { title: "Hedefinizi anlatın", text: "Kısa bir başvuru gönderin. Kabul danışmanı size uygun seçeneklerle döner." },
      { title: "Ücretsiz seviye sınavı", text: "Çevrim içi veya kampüste otuz dakika; tam seviyenizden başlarsınız." },
      { title: "Ücretsiz deneme dersi", text: "Karar vermeden önce sertifikalı bir öğretmenle gerçek bir derse katılın." },
      { title: "Sınıfınıza katılın", text: "Sabah, öğleden sonra veya akşam grubunu seçin. Planınız ve ilerlemeniz tek yerde." },
    ],
  },
  modes: {
    title: "Çevrim içi veya kampüste",
    lead: "Nerede öğrenirseniz öğrenin, aynı öğretmenler ve aynı standart.",
    online: {
      title: "Canlı çevrim içi",
      text: "Öğrenme platformunuzda kayıtlı derslerle birlikte etkileşimli canlı dersler.",
      points: ["Dünyanın her yerinden katılın", "Sabah, öğleden sonra ve akşam grupları", "Kayıtlar ve materyaller dahil"],
      phoneLabel: "Çevrim içi kurslar",
    },
    campus: {
      title: "Kahire’de kampüste",
      text: "Nasr City’de sakin sınıfları ve hat atölyeleri olan iki kampüs.",
      points: ["1. Şube: 37 Abd Al-Shafy Mohammed, 7. Bölge", "2. Şube: 6 Fadl ibn Rabea, 7. Bölge", "Seviye sınavı ve deneme dersi kampüste"],
      phoneLabel: "Yüz yüze kurslar",
    },
  },
  quotes: {
    title: "Öğrencilerimizin sözleriyle",
    items: [
      { text: "Öğretmenlerim sekiz ayda tüm hıfz programında bana rehberlik etti. İcazetimi aldım ve şimdi ülkemde başlangıç sınıflarına ders veriyorum.", name: "Ahmed", context: "Hıfz ve icazet, BAE" },
      { text: "Altı ayda sıfırdan akıcı Arapça konuşmaya geçtim ve Kahire’de canlı bir sunum yaptım.", name: "Sarah", context: "Arapça, Birleşik Krallık" },
      { text: "Kişisel rehberlik ve etkileşimli derslerle üç ayda Mısır lehçesinde kendime güvendim.", name: "Yasmine", context: "Mısır lehçesi, Türkiye" },
    ],
  },
  films: {
    title: "Gerçek bir dersi izleyin",
    lead: "Nile Center'ın kendi kanalından, çevrim içi ve kampüste öğrenme üzerine iki kısa film.",
    online: { title: "Çevrim içi öğrenme", note: "Nile Center'ın canlı çevrim içi kursları hakkındaki filmi" },
    campus: { title: "Kampüste öğrenme", note: "Nile Center'ın Nasr City kursları hakkındaki filmi" },
    play: "Filmi oynat",
    source: "YouTube'dan oynatılır",
    close: "Filmi kapat",
  },
  faq: {
    title: "İlk sorulan sorular",
    lead: "Kısa cevaplar. Başka bir sorunuz için WhatsApp'tan kabul danışmanına yazın.",
    items: [
      { q: "Ücretsiz seviye sınavında ne olur?", a: "Çevrim içi veya kampüste yaklaşık 30 dakika sürer. Öğretmen seviyenizi belirler ve nereden başlayacağınızı söyler." },
      { q: "Ödeme yapmadan önce bir ders deneyebilir miyim?", a: "Evet. Sertifikalı bir öğretmenle ücretsiz deneme dersi alın, sonra karar verin." },
      { q: "Dersler ne zaman yapılıyor?", a: "Çevrim içi ve kampüste sabah, öğleden sonra ve akşam grupları vardır." },
      { q: "Çocuklara ders veriyor musunuz?", a: "Evet. Çocuk programı 5 ile 14 yaş arası için Kur’an, Arapça ve İslami ilimleri kapsar." },
      { q: "Mısır dışından ders alabilir miyim?", a: "Evet. Canlı çevrim içi dersler dünyanın her yerinden alınabilir; kayıtlar ve materyaller dahildir." },
      { q: "Kampüsler nerede?", a: "Kahire, Nasr City 7. Bölge'de iki şube: 37 Abd Al-Shafy Mohammed ve 6 Fadl ibn Rabea." },
    ],
  },
  cta: {
    title: "Ücretsiz bir deneme dersiyle başlayın.",
    text: "Ne öğrenmek istediğinizi yazın. Seviye sınavınız ve deneme dersiniz için size bir zaman önerelim.",
    trial: "Ücretsiz deneme dersi alın",
    whatsapp: "WhatsApp’tan yazın",
  },
  footer: {
    tagline: "Daha parlak bir gelecek için eğitim, her seferinde bir öğrenci.",
    programmes: "Programlar",
    school: "Merkez",
    contact: "İletişim",
    about: "Hakkımızda",
    faq: "Sorular",
    verify: "Sertifika doğrula",
    privacy: "Gizlilik",
    terms: "Koşullar",
    staff: "Personel girişi",
    rights: "Nil Eğitim Merkezi. Tüm hakları saklıdır.",
  },
};

export const LANDING_COPY: Record<LandingLocale, LandingCopy> = { en, ar, tr };
export const LANDING_LOCALES: LandingLocale[] = ["en", "ar", "tr"];
