import type { LandingLocale } from "./landing-copy";

/**
 * Copy for the public pages beyond the landing: programmes, course pages,
 * certificate check, booking fallback, questions, contact, about, legal and
 * not-found. English is the source; Arabic and Turkish must match its shape.
 * Facts follow nilecenter.edu.eg; legal pages summarise and link to the
 * official policies rather than invent terms.
 */
const en = {
  courses: {
    quran: { level: "Beginner to Ijāzah", schedule: "Live online and on campus", outcomes: ["Recite with correct Tajweed", "Memorise with a steady plan", "Prepare for an Ijāzah"] },
    arabic: { level: "A1 to advanced", schedule: "Morning, afternoon and evening groups", outcomes: ["Read connected Arabic text", "Build grammar you can use", "Speak with confidence"] },
    "islamic-studies": { level: "Foundations to intermediate", schedule: "Weekly live cohorts", outcomes: ["Understand Qur’anic Arabic", "Study core texts with a teacher", "Ask and discuss with care"] },
    kids: { level: "Ages 5 to 14", schedule: "After school and weekends", outcomes: ["Read and write Arabic letters", "Recite and memorise short surahs", "Learn in a warm small group"] },
    turkish: { level: "A1 to B2", schedule: "Small group classes", outcomes: ["Handle daily conversations", "Read everyday Turkish", "Prepare for study or travel"] },
    english: { level: "All levels", schedule: "Small focused groups", outcomes: ["Speak more fluently", "Write clearly", "Build academic skills"] },
    "teacher-training": { level: "For practising teachers", schedule: "Cohorts through the year", outcomes: ["Plan clear lessons", "Manage a lively classroom", "Assess fairly and usefully"] },
    enterprise: { level: "Built with you", schedule: "Designed around your group", outcomes: ["A programme fitted to your goals", "Reports on progress", "Online, on campus or on site"] },
  },
  catalog: {
    eyebrow: "Programmes",
    title: "Find your path at Nile Center.",
    lead: "Every programme starts with a free placement test, so you begin at your level.",
    search: "Search programmes",
    placeholder: "Arabic, Tajweed, kids…",
    all: "All",
    empty: "No programme matches that search.",
    clear: "Clear search",
    count: "programmes",
  },
  course: {
    back: "All programmes",
    level: "Level",
    schedule: "When",
    format: "Where",
    formatValue: "Online or on campus in Nasr City",
    outcomesTitle: "What you will be able to do",
    runTitle: "How a course runs",
    run: [
      { title: "Placement", text: "A free test finds your level and the right group." },
      { title: "Core lessons", text: "Live classes with a certified teacher, at your group’s time." },
      { title: "Practice and feedback", text: "Homework, recordings and notes from your teacher." },
      { title: "Assessment", text: "Regular checks, and a certificate when you complete the level." },
    ],
    certificateTitle: "Certificates you can verify",
    certificateText: "Each certificate carries a code anyone can check on our site.",
    verify: "Verify a certificate",
    ctaTitle: "Start with a free trial lesson.",
    ctaText: "Sit a real class before you decide. Placement tests are free too.",
    missingTitle: "We could not find that programme.",
    missingText: "It may have moved. See every programme instead.",
  },
  verify: {
    eyebrow: "Certificates",
    title: "Verify a Nile Center certificate.",
    lead: "Enter the code printed on the certificate. Only issued certificates can be checked.",
    label: "Verification code",
    placeholder: "e.g. NCL-AR2-1234",
    submit: "Verify",
    checking: "Checking",
    checkingText: "Looking for an issued certificate with this code.",
    found: "Certificate verified",
    verified: "Verified",
    issued: "Issued",
    print: "Print or save as PDF",
    required: "Enter the certificate code.",
    unavailable: "Verification is unavailable right now. Try again later.",
    notFound: "No issued certificate has this code",
    notFoundText: "Check the code for typing mistakes, or contact us.",
  },
  booking: {
    trialEyebrow: "Free trial lesson",
    placementEyebrow: "Free placement test",
    trialTitle: "Book a free trial lesson.",
    placementTitle: "Book a free placement test.",
    trialLead: "Tell us what you want to learn and when you are free. Our admissions team will contact you.",
    placementLead: "Pick a subject and a day that suits you. The test takes about thirty minutes.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone or WhatsApp",
    country: "Country",
    language: "Language you prefer",
    subject: "Subject",
    ageGroup: "Who is learning",
    schedule: "Times that suit you",
    schedulePlaceholder: "Weekday evenings, weekends…",
    branch: "Where",
    date: "Preferred day",
    level: "Current level",
    notes: "Anything else",
    choose: "Choose",
    languages: ["English", "Arabic", "Turkish", "French"],
    ages: ["Child", "Teen", "Adult", "A group or organisation"],
    levels: ["Complete beginner", "Can read a little", "Intermediate", "Advanced"],
    branches: [
      { value: "Cairo B1", label: "Nasr City campus" },
      { value: "Online", label: "Online" },
    ],
    submit: "Send request",
    sending: "Sending",
    invalid: "Fill in your name, a valid email, your phone and the other required choices.",
    failed: "We could not send your request. Try again, or message us on WhatsApp.",
    success: "Thank you. Your request is with our admissions team.",
  },
  faq: {
    eyebrow: "Questions",
    title: "Answers before you start.",
    lead: "The questions families and learners ask us most.",
    items: [
      { q: "How do I know which level to join?", a: "Every learner starts with a free placement test of about thirty minutes, online or on campus. Your teacher uses it to place you in the right group." },
      { q: "Can I try a class before I pay?", a: "Yes. Book a free trial lesson and sit a real class with a certified teacher before you decide." },
      { q: "Do you teach online?", a: "Yes. Live online classes run for learners around the world, with recordings and materials on your learning platform." },
      { q: "Where are your campuses?", a: "We have two campuses in Nasr City, Cairo: 37 Abd Al-Shafy Mohammed and 6 Fadl ibn Rabea, both in the 7th District." },
      { q: "When are classes held?", a: "Groups run in the morning, afternoon and evening, so you can choose a time that fits your day." },
      { q: "Do children have their own programme?", a: "Yes. Our kids programme covers Qur’an, Arabic and Islamic studies for ages 5 to 14, in small groups." },
      { q: "Will I get a certificate?", a: "When you complete a level you receive a certificate with a code that anyone can verify on this site." },
      { q: "Can you teach our school or organisation?", a: "Yes. We design programmes with schools, companies, mosques and communities. Contact us to talk it through." },
    ],
    moreTitle: "Still have a question?",
    moreText: "Message our admissions team and we will help you choose.",
    whatsapp: "Message us on WhatsApp",
  },
  contact: {
    eyebrow: "Contact",
    title: "Talk to our admissions team.",
    lead: "Message us on WhatsApp, call, or visit one of our two campuses in Nasr City.",
    campusesTitle: "Our campuses",
    campuses: [
      { name: "Branch 1", address: "37 Abd Al-Shafy Mohammed, 7th District, Nasr City, Cairo", query: "Nile Learning Center Branch 1 Nasr City" },
      { name: "Branch 2", address: "6 Fadl ibn Rabea, 7th District, Nasr City, Cairo", query: "Nile Learning Center Branch 2 Nasr City" },
    ],
    directions: "Get directions",
    reachTitle: "Reach us",
    emailLabel: "Email",
    startTitle: "Ready to begin?",
    startText: "Most learners start with one of these.",
  },
  about: {
    eyebrow: "About us",
    title: "Education for a brighter future.",
    lead: "Since 1998, Nile Center has taught Arabic, the Qur’an and Islamic studies to learners in Cairo and around the world.",
    storyTitle: "Our story",
    story: [
      "Nile Center began in Cairo with a simple aim: teach Arabic and the Qur’an with care, at each learner’s level.",
      "Today our teachers work with children, adults and organisations, live online and on two campuses in Nasr City, one learner at a time.",
    ],
    figuresTitle: "Nile Center in numbers",
    ctaTitle: "Come and see how we teach.",
    ctaText: "Book a free trial lesson, online or on campus.",
  },
  privacy: {
    eyebrow: "Privacy",
    title: "Your information at Nile Center.",
    lead: "A short summary of how this site handles what you share. The full policy is on our main site.",
    sections: [
      { h: "What we collect", p: "When you send a form, we receive what you type in it, such as your name, contact details and the course you are interested in." },
      { h: "Why we use it", p: "We use it to answer your enquiry, arrange placement tests and trial lessons, and run your classes if you join." },
      { h: "Who can see it", p: "Nile Center staff who need it for admissions and teaching. Staff sign in to a protected workspace." },
      { h: "Your choices", p: "You can ask to see, correct or delete your information by emailing us." },
    ],
    full: "Read the full privacy policy",
  },
  terms: {
    eyebrow: "Terms",
    title: "Terms for learning with us.",
    lead: "A short summary. The full terms and conditions are on our main site and apply to every enrolment.",
    sections: [
      { h: "Placement and trial", p: "Placement tests and trial lessons are free. They help us place you in the right group." },
      { h: "Enrolment", p: "Your place in a class is confirmed once your enrolment and payment are recorded by our team." },
      { h: "Attendance", p: "Regular attendance helps your progress. Your teacher records attendance for every session." },
      { h: "Certificates", p: "Certificates are issued when you complete a level, and each one can be verified on this site." },
    ],
    full: "Read the full terms and conditions",
  },
  notFound: {
    title: "We could not find that page.",
    text: "The link may be old, or the page has moved.",
    home: "Go to the home page",
    programmes: "See our programmes",
  },
};

export type PublicCopy = typeof en;

const ar: PublicCopy = {
  courses: {
    quran: { level: "من البداية حتى الإجازة", schedule: "مباشر أونلاين وحضوري", outcomes: ["التلاوة بتجويد صحيح", "الحفظ بخطة ثابتة", "الاستعداد للإجازة"] },
    arabic: { level: "من A1 حتى المتقدم", schedule: "مجموعات صباحية وظهرية ومسائية", outcomes: ["قراءة نصوص عربية متصلة", "نحو تستطيع استخدامه", "التحدث بثقة"] },
    "islamic-studies": { level: "من الأسس حتى المتوسط", schedule: "مجموعات مباشرة أسبوعية", outcomes: ["فهم العربية القرآنية", "دراسة المتون الأساسية مع معلم", "السؤال والنقاش بأدب"] },
    kids: { level: "من 5 إلى 14 سنة", schedule: "بعد المدرسة وفي العطلات", outcomes: ["قراءة الحروف العربية وكتابتها", "تلاوة قصار السور وحفظها", "التعلم في مجموعة صغيرة دافئة"] },
    turkish: { level: "من A1 حتى B2", schedule: "مجموعات صغيرة", outcomes: ["إدارة المحادثات اليومية", "قراءة التركية اليومية", "الاستعداد للدراسة أو السفر"] },
    english: { level: "كل المستويات", schedule: "مجموعات صغيرة مركّزة", outcomes: ["التحدث بطلاقة أكبر", "الكتابة بوضوح", "بناء المهارات الأكاديمية"] },
    "teacher-training": { level: "للمعلمين الممارسين", schedule: "دفعات على مدار العام", outcomes: ["تخطيط دروس واضحة", "إدارة فصل حيوي", "تقييم عادل ومفيد"] },
    enterprise: { level: "نصممه معكم", schedule: "يُصمَّم حول مجموعتكم", outcomes: ["برنامج يناسب أهدافكم", "تقارير عن التقدم", "أونلاين أو في مقرنا أو لديكم"] },
  },
  catalog: {
    eyebrow: "البرامج",
    title: "اعثر على مسارك في مركز النيل.",
    lead: "يبدأ كل برنامج باختبار مستوى مجاني، لتبدأ من مستواك.",
    search: "ابحث في البرامج",
    placeholder: "العربية، التجويد، الأطفال…",
    all: "الكل",
    empty: "لا يوجد برنامج يطابق هذا البحث.",
    clear: "مسح البحث",
    count: "برامج",
  },
  course: {
    back: "كل البرامج",
    level: "المستوى",
    schedule: "المواعيد",
    format: "المكان",
    formatValue: "أونلاين أو حضوري في مدينة نصر",
    outcomesTitle: "ما الذي ستتمكن منه",
    runTitle: "كيف تسير الدورة",
    run: [
      { title: "تحديد المستوى", text: "اختبار مجاني يحدد مستواك والمجموعة المناسبة." },
      { title: "الدروس الأساسية", text: "حصص مباشرة مع معلم معتمد في موعد مجموعتك." },
      { title: "التدريب والملاحظات", text: "واجبات وتسجيلات وملاحظات من معلمك." },
      { title: "التقييم", text: "متابعة منتظمة، وشهادة عند إتمام المستوى." },
    ],
    certificateTitle: "شهادات يمكن التحقق منها",
    certificateText: "تحمل كل شهادة رمزًا يمكن لأي أحد التحقق منه على موقعنا.",
    verify: "تحقق من شهادة",
    ctaTitle: "ابدأ بحصة تجريبية مجانية.",
    ctaText: "احضر حصة حقيقية قبل أن تقرر. اختبار المستوى مجاني أيضًا.",
    missingTitle: "لم نعثر على هذا البرنامج.",
    missingText: "ربما نُقل. اطّلع على كل البرامج.",
  },
  verify: {
    eyebrow: "الشهادات",
    title: "تحقق من شهادة مركز النيل.",
    lead: "أدخل الرمز المطبوع على الشهادة. يمكن التحقق من الشهادات الصادرة فقط.",
    label: "رمز التحقق",
    placeholder: "مثال: NCL-AR2-1234",
    submit: "تحقق",
    checking: "جارٍ التحقق",
    checkingText: "نبحث عن شهادة صادرة بهذا الرمز.",
    found: "تم التحقق من الشهادة",
    verified: "موثّقة",
    issued: "تاريخ الإصدار",
    print: "طباعة أو حفظ PDF",
    required: "أدخل رمز الشهادة.",
    unavailable: "التحقق غير متاح الآن. حاول لاحقًا.",
    notFound: "لا توجد شهادة صادرة بهذا الرمز",
    notFoundText: "راجع الرمز من أخطاء الكتابة، أو تواصل معنا.",
  },
  booking: {
    trialEyebrow: "حصة تجريبية مجانية",
    placementEyebrow: "اختبار مستوى مجاني",
    trialTitle: "احجز حصة تجريبية مجانية.",
    placementTitle: "احجز اختبار مستوى مجاني.",
    trialLead: "أخبرنا بما تريد تعلّمه ومتى تكون متاحًا، وسيتواصل معك فريق القبول.",
    placementLead: "اختر المادة واليوم المناسب لك. يستغرق الاختبار نحو ثلاثين دقيقة.",
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "الهاتف أو واتساب",
    country: "الدولة",
    language: "اللغة المفضلة",
    subject: "المادة",
    ageGroup: "من سيتعلم",
    schedule: "الأوقات المناسبة",
    schedulePlaceholder: "مساء أيام الأسبوع، العطلات…",
    branch: "المكان",
    date: "اليوم المفضل",
    level: "المستوى الحالي",
    notes: "ملاحظات أخرى",
    choose: "اختر",
    languages: ["الإنجليزية", "العربية", "التركية", "الفرنسية"],
    ages: ["طفل", "مراهق", "بالغ", "مجموعة أو مؤسسة"],
    levels: ["مبتدئ تمامًا", "أقرأ قليلًا", "متوسط", "متقدم"],
    branches: [
      { value: "Cairo B1", label: "مقر مدينة نصر" },
      { value: "Online", label: "أونلاين" },
    ],
    submit: "إرسال الطلب",
    sending: "جارٍ الإرسال",
    invalid: "أدخل اسمك وبريدًا صحيحًا وهاتفك وبقية الاختيارات المطلوبة.",
    failed: "تعذر إرسال طلبك. حاول مرة أخرى أو راسلنا على واتساب.",
    success: "شكرًا لك. وصل طلبك إلى فريق القبول.",
  },
  faq: {
    eyebrow: "الأسئلة",
    title: "إجابات قبل أن تبدأ.",
    lead: "أكثر الأسئلة التي تطرحها علينا الأسر والمتعلمون.",
    items: [
      { q: "كيف أعرف المستوى المناسب لي؟", a: "يبدأ كل متعلم باختبار مستوى مجاني مدته نحو ثلاثين دقيقة أونلاين أو في المقر، ويستخدمه المعلم لوضعك في المجموعة المناسبة." },
      { q: "هل يمكنني تجربة حصة قبل الدفع؟", a: "نعم. احجز حصة تجريبية مجانية واحضر حصة حقيقية مع معلم معتمد قبل أن تقرر." },
      { q: "هل تدرّسون أونلاين؟", a: "نعم. حصص مباشرة أونلاين لمتعلمين حول العالم، مع تسجيلات ومواد على منصتك التعليمية." },
      { q: "أين مقراتكم؟", a: "لدينا فرعان في مدينة نصر بالقاهرة: 37 شارع عبد الشافي محمد و6 شارع الفضل بن الربيع، وكلاهما في الحي السابع." },
      { q: "متى تُعقد الحصص؟", a: "تعمل المجموعات صباحًا وظهرًا ومساءً، لتختار وقتًا يناسب يومك." },
      { q: "هل للأطفال برنامج خاص؟", a: "نعم. يشمل برنامج الأطفال القرآن والعربية والدراسات الإسلامية للأعمار من 5 إلى 14 سنة في مجموعات صغيرة." },
      { q: "هل سأحصل على شهادة؟", a: "عند إتمام المستوى تحصل على شهادة برمز يمكن لأي أحد التحقق منه على هذا الموقع." },
      { q: "هل يمكنكم التدريس لمدرستنا أو مؤسستنا؟", a: "نعم. نصمم برامج مع المدارس والشركات والمساجد والمجتمعات. تواصل معنا لنتحدث." },
    ],
    moreTitle: "لديك سؤال آخر؟",
    moreText: "راسل فريق القبول وسنساعدك في الاختيار.",
    whatsapp: "راسلنا على واتساب",
  },
  contact: {
    eyebrow: "تواصل معنا",
    title: "تحدّث إلى فريق القبول.",
    lead: "راسلنا على واتساب، أو اتصل بنا، أو زر أحد فرعينا في مدينة نصر.",
    campusesTitle: "فروعنا",
    campuses: [
      { name: "الفرع الأول", address: "37 شارع عبد الشافي محمد، الحي السابع، مدينة نصر، القاهرة", query: "Nile Learning Center Branch 1 Nasr City" },
      { name: "الفرع الثاني", address: "6 شارع الفضل بن الربيع، الحي السابع، مدينة نصر، القاهرة", query: "Nile Learning Center Branch 2 Nasr City" },
    ],
    directions: "الاتجاهات",
    reachTitle: "طرق التواصل",
    emailLabel: "البريد الإلكتروني",
    startTitle: "مستعد للبدء؟",
    startText: "يبدأ معظم المتعلمين بأحد هذين.",
  },
  about: {
    eyebrow: "من نحن",
    title: "تعليم من أجل مستقبل أفضل.",
    lead: "منذ عام 1998 يُعلّم مركز النيل العربية والقرآن والدراسات الإسلامية لمتعلمين في القاهرة وحول العالم.",
    storyTitle: "قصتنا",
    story: [
      "بدأ مركز النيل في القاهرة بهدف بسيط: تعليم العربية والقرآن بعناية، وعلى قدر مستوى كل متعلم.",
      "واليوم يعمل معلمونا مع الأطفال والبالغين والمؤسسات، مباشرة أونلاين وفي فرعين بمدينة نصر، متعلمًا بعد متعلم.",
    ],
    figuresTitle: "مركز النيل بالأرقام",
    ctaTitle: "تعال وشاهد كيف نُعلّم.",
    ctaText: "احجز حصة تجريبية مجانية أونلاين أو في المقر.",
  },
  privacy: {
    eyebrow: "الخصوصية",
    title: "معلوماتك في مركز النيل.",
    lead: "ملخص قصير لكيفية تعامل هذا الموقع مع ما تشاركه. السياسة الكاملة على موقعنا الرئيسي.",
    sections: [
      { h: "ما الذي نجمعه", p: "عند إرسال استمارة نستلم ما تكتبه فيها، مثل اسمك وبيانات التواصل والدورة التي تهتم بها." },
      { h: "لماذا نستخدمه", p: "للرد على استفسارك، وترتيب اختبارات المستوى والحصص التجريبية، وإدارة حصصك إذا انضممت." },
      { h: "من يمكنه رؤيته", p: "موظفو مركز النيل الذين يحتاجونه للقبول والتدريس، عبر مساحة عمل محمية بتسجيل الدخول." },
      { h: "خياراتك", p: "يمكنك طلب الاطلاع على معلوماتك أو تصحيحها أو حذفها عبر مراسلتنا بالبريد الإلكتروني." },
    ],
    full: "اقرأ سياسة الخصوصية كاملة",
  },
  terms: {
    eyebrow: "الشروط",
    title: "شروط التعلّم معنا.",
    lead: "ملخص قصير. الشروط والأحكام الكاملة على موقعنا الرئيسي وتسري على كل التحاق.",
    sections: [
      { h: "تحديد المستوى والتجربة", p: "اختبارات المستوى والحصص التجريبية مجانية، وتساعدنا على وضعك في المجموعة المناسبة." },
      { h: "الالتحاق", p: "يتأكد مكانك في الفصل بعد أن يسجّل فريقنا التحاقك ودفعتك." },
      { h: "الحضور", p: "الحضور المنتظم يدعم تقدمك، ويسجّل معلمك الحضور في كل حصة." },
      { h: "الشهادات", p: "تصدر الشهادات عند إتمام المستوى، ويمكن التحقق من كل شهادة على هذا الموقع." },
    ],
    full: "اقرأ الشروط والأحكام كاملة",
  },
  notFound: {
    title: "لم نعثر على هذه الصفحة.",
    text: "ربما يكون الرابط قديمًا، أو نُقلت الصفحة.",
    home: "الذهاب إلى الصفحة الرئيسية",
    programmes: "اطّلع على برامجنا",
  },
};

const tr: PublicCopy = {
  courses: {
    quran: { level: "Başlangıçtan icazete", schedule: "Canlı çevrim içi ve kampüste", outcomes: ["Doğru tecvidle okumak", "Düzenli bir planla ezberlemek", "İcazete hazırlanmak"] },
    arabic: { level: "A1’den ileri seviyeye", schedule: "Sabah, öğleden sonra ve akşam grupları", outcomes: ["Bağlantılı Arapça metin okumak", "Kullanabileceğiniz dil bilgisi", "Kendinizden emin konuşmak"] },
    "islamic-studies": { level: "Temelden orta seviyeye", schedule: "Haftalık canlı gruplar", outcomes: ["Kur’an Arapçasını anlamak", "Temel metinleri öğretmenle çalışmak", "Saygıyla soru sorup tartışmak"] },
    kids: { level: "5-14 yaş", schedule: "Okul sonrası ve hafta sonu", outcomes: ["Arapça harfleri okuyup yazmak", "Kısa sureleri okuyup ezberlemek", "Sıcak küçük bir grupta öğrenmek"] },
    turkish: { level: "A1’den B2’ye", schedule: "Küçük gruplar", outcomes: ["Günlük konuşmaları yürütmek", "Gündelik Türkçe okumak", "Eğitim veya seyahate hazırlanmak"] },
    english: { level: "Tüm seviyeler", schedule: "Küçük odaklı gruplar", outcomes: ["Daha akıcı konuşmak", "Açık yazmak", "Akademik beceriler kazanmak"] },
    "teacher-training": { level: "Görevdeki öğretmenler için", schedule: "Yıl boyunca dönemler", outcomes: ["Net dersler planlamak", "Canlı bir sınıfı yönetmek", "Adil ve yararlı ölçmek"] },
    enterprise: { level: "Sizinle birlikte", schedule: "Grubunuza göre tasarlanır", outcomes: ["Hedeflerinize uygun bir program", "İlerleme raporları", "Çevrim içi, kampüste veya sizde"] },
  },
  catalog: {
    eyebrow: "Programlar",
    title: "Nil Merkezi’nde yolunuzu bulun.",
    lead: "Her program ücretsiz bir seviye sınavıyla başlar; böylece kendi seviyenizden başlarsınız.",
    search: "Programlarda ara",
    placeholder: "Arapça, tecvid, çocuklar…",
    all: "Tümü",
    empty: "Bu aramayla eşleşen program yok.",
    clear: "Aramayı temizle",
    count: "program",
  },
  course: {
    back: "Tüm programlar",
    level: "Seviye",
    schedule: "Zaman",
    format: "Yer",
    formatValue: "Çevrim içi veya Nasr City kampüsünde",
    outcomesTitle: "Neler yapabileceksiniz",
    runTitle: "Bir kurs nasıl ilerler",
    run: [
      { title: "Seviye belirleme", text: "Ücretsiz bir sınav seviyenizi ve doğru grubu bulur." },
      { title: "Temel dersler", text: "Grubunuzun saatinde sertifikalı bir öğretmenle canlı dersler." },
      { title: "Alıştırma ve geri bildirim", text: "Ödevler, kayıtlar ve öğretmeninizden notlar." },
      { title: "Değerlendirme", text: "Düzenli kontroller ve seviyeyi bitirdiğinizde bir sertifika." },
    ],
    certificateTitle: "Doğrulanabilir sertifikalar",
    certificateText: "Her sertifikada, sitemizde herkesin kontrol edebileceği bir kod bulunur.",
    verify: "Sertifika doğrula",
    ctaTitle: "Ücretsiz bir deneme dersiyle başlayın.",
    ctaText: "Karar vermeden gerçek bir derse katılın. Seviye sınavı da ücretsiz.",
    missingTitle: "Bu programı bulamadık.",
    missingText: "Taşınmış olabilir. Tüm programlara göz atın.",
  },
  verify: {
    eyebrow: "Sertifikalar",
    title: "Bir Nil Merkezi sertifikasını doğrulayın.",
    lead: "Sertifikadaki kodu girin. Yalnızca düzenlenmiş sertifikalar kontrol edilebilir.",
    label: "Doğrulama kodu",
    placeholder: "örn. NCL-AR2-1234",
    submit: "Doğrula",
    checking: "Kontrol ediliyor",
    checkingText: "Bu kodla düzenlenmiş bir sertifika aranıyor.",
    found: "Sertifika doğrulandı",
    verified: "Doğrulandı",
    issued: "Düzenlenme",
    print: "Yazdır veya PDF olarak kaydet",
    required: "Sertifika kodunu girin.",
    unavailable: "Doğrulama şu anda kullanılamıyor. Daha sonra tekrar deneyin.",
    notFound: "Bu kodla düzenlenmiş bir sertifika yok",
    notFoundText: "Kodu yazım hatalarına karşı kontrol edin veya bizimle iletişime geçin.",
  },
  booking: {
    trialEyebrow: "Ücretsiz deneme dersi",
    placementEyebrow: "Ücretsiz seviye sınavı",
    trialTitle: "Ücretsiz bir deneme dersi alın.",
    placementTitle: "Ücretsiz bir seviye sınavı planlayın.",
    trialLead: "Ne öğrenmek istediğinizi ve ne zaman uygun olduğunuzu yazın. Kabul ekibimiz size ulaşacak.",
    placementLead: "Bir konu ve size uygun bir gün seçin. Sınav yaklaşık otuz dakika sürer.",
    fullName: "Ad soyad",
    email: "E-posta",
    phone: "Telefon veya WhatsApp",
    country: "Ülke",
    language: "Tercih ettiğiniz dil",
    subject: "Konu",
    ageGroup: "Kim öğrenecek",
    schedule: "Size uygun saatler",
    schedulePlaceholder: "Hafta içi akşam, hafta sonu…",
    branch: "Nerede",
    date: "Tercih edilen gün",
    level: "Mevcut seviye",
    notes: "Eklemek istedikleriniz",
    choose: "Seçin",
    languages: ["İngilizce", "Arapça", "Türkçe", "Fransızca"],
    ages: ["Çocuk", "Genç", "Yetişkin", "Bir grup veya kurum"],
    levels: ["Tam başlangıç", "Biraz okuyabiliyorum", "Orta", "İleri"],
    branches: [
      { value: "Cairo B1", label: "Nasr City kampüsü" },
      { value: "Online", label: "Çevrim içi" },
    ],
    submit: "Talebi gönder",
    sending: "Gönderiliyor",
    invalid: "Adınızı, geçerli bir e-postayı, telefonunuzu ve diğer zorunlu seçimleri doldurun.",
    failed: "Talebiniz gönderilemedi. Tekrar deneyin veya WhatsApp’tan yazın.",
    success: "Teşekkürler. Talebiniz kabul ekibimize ulaştı.",
  },
  faq: {
    eyebrow: "Sorular",
    title: "Başlamadan önce yanıtlar.",
    lead: "Ailelerin ve öğrencilerin bize en çok sorduğu sorular.",
    items: [
      { q: "Hangi seviyeye katılacağımı nasıl bilirim?", a: "Her öğrenci, çevrim içi veya kampüste yaklaşık otuz dakikalık ücretsiz bir seviye sınavıyla başlar. Öğretmeniniz sizi buna göre doğru gruba yerleştirir." },
      { q: "Ödemeden önce bir dersi deneyebilir miyim?", a: "Evet. Ücretsiz bir deneme dersi alın ve karar vermeden sertifikalı bir öğretmenle gerçek bir derse katılın." },
      { q: "Çevrim içi ders veriyor musunuz?", a: "Evet. Dünyanın her yerindeki öğrenciler için canlı çevrim içi dersler var; kayıtlar ve materyaller öğrenme platformunuzda." },
      { q: "Kampüsleriniz nerede?", a: "Kahire Nasr City’de iki kampüsümüz var: 37 Abd Al-Shafy Mohammed ve 6 Fadl ibn Rabea, ikisi de 7. Bölge’de." },
      { q: "Dersler ne zaman?", a: "Gruplar sabah, öğleden sonra ve akşam çalışır; gününüze uyan bir saati seçebilirsiniz." },
      { q: "Çocuklar için ayrı bir program var mı?", a: "Evet. Çocuk programımız 5-14 yaş için Kur’an, Arapça ve İslami ilimleri küçük gruplarda kapsar." },
      { q: "Sertifika alacak mıyım?", a: "Bir seviyeyi tamamladığınızda, bu sitede herkesin doğrulayabileceği kodlu bir sertifika alırsınız." },
      { q: "Okulumuza veya kurumumuza ders verebilir misiniz?", a: "Evet. Okullar, şirketler, camiler ve topluluklarla programlar tasarlıyoruz. Konuşmak için bize ulaşın." },
    ],
    moreTitle: "Başka bir sorunuz mu var?",
    moreText: "Kabul ekibimize yazın, seçiminizde yardımcı olalım.",
    whatsapp: "WhatsApp’tan yazın",
  },
  contact: {
    eyebrow: "İletişim",
    title: "Kabul ekibimizle konuşun.",
    lead: "WhatsApp’tan yazın, arayın veya Nasr City’deki iki kampüsümüzden birini ziyaret edin.",
    campusesTitle: "Kampüslerimiz",
    campuses: [
      { name: "1. Şube", address: "37 Abd Al-Shafy Mohammed, 7. Bölge, Nasr City, Kahire", query: "Nile Learning Center Branch 1 Nasr City" },
      { name: "2. Şube", address: "6 Fadl ibn Rabea, 7. Bölge, Nasr City, Kahire", query: "Nile Learning Center Branch 2 Nasr City" },
    ],
    directions: "Yol tarifi al",
    reachTitle: "Bize ulaşın",
    emailLabel: "E-posta",
    startTitle: "Başlamaya hazır mısınız?",
    startText: "Çoğu öğrenci bunlardan biriyle başlar.",
  },
  about: {
    eyebrow: "Hakkımızda",
    title: "Daha parlak bir gelecek için eğitim.",
    lead: "Nil Merkezi 1998’den beri Kahire’de ve dünyanın dört bir yanında Arapça, Kur’an ve İslami ilimler öğretiyor.",
    storyTitle: "Hikâyemiz",
    story: [
      "Nil Merkezi Kahire’de basit bir amaçla başladı: Arapçayı ve Kur’an’ı özenle, her öğrencinin seviyesinde öğretmek.",
      "Bugün öğretmenlerimiz çocuklar, yetişkinler ve kurumlarla çevrim içi ve Nasr City’deki iki kampüste, her seferinde bir öğrenciyle çalışıyor.",
    ],
    figuresTitle: "Rakamlarla Nil Merkezi",
    ctaTitle: "Gelin, nasıl öğrettiğimizi görün.",
    ctaText: "Çevrim içi veya kampüste ücretsiz bir deneme dersi alın.",
  },
  privacy: {
    eyebrow: "Gizlilik",
    title: "Nil Merkezi’nde bilgileriniz.",
    lead: "Bu sitenin paylaştıklarınızı nasıl ele aldığının kısa özeti. Tam politika ana sitemizdedir.",
    sections: [
      { h: "Ne topluyoruz", p: "Bir form gönderdiğinizde adınız, iletişim bilgileriniz ve ilgilendiğiniz kurs gibi yazdıklarınızı alırız." },
      { h: "Neden kullanıyoruz", p: "Sorunuzu yanıtlamak, seviye sınavı ve deneme dersi ayarlamak ve katılırsanız derslerinizi yürütmek için." },
      { h: "Kimler görebilir", p: "Kabul ve öğretim için ihtiyaç duyan Nil Merkezi personeli; personel korumalı bir çalışma alanına giriş yapar." },
      { h: "Seçenekleriniz", p: "Bize e-posta göndererek bilgilerinizi görmeyi, düzeltmeyi veya silmeyi isteyebilirsiniz." },
    ],
    full: "Gizlilik politikasının tamamını okuyun",
  },
  terms: {
    eyebrow: "Koşullar",
    title: "Bizimle öğrenme koşulları.",
    lead: "Kısa bir özet. Tam şartlar ve koşullar ana sitemizdedir ve her kayıt için geçerlidir.",
    sections: [
      { h: "Seviye sınavı ve deneme", p: "Seviye sınavları ve deneme dersleri ücretsizdir; sizi doğru gruba yerleştirmemize yardım eder." },
      { h: "Kayıt", p: "Sınıftaki yeriniz, kaydınız ve ödemeniz ekibimizce işlendiğinde kesinleşir." },
      { h: "Devam", p: "Düzenli devam ilerlemenize yardım eder. Öğretmeniniz her oturumda yoklama alır." },
      { h: "Sertifikalar", p: "Sertifikalar bir seviyeyi tamamladığınızda düzenlenir ve her biri bu sitede doğrulanabilir." },
    ],
    full: "Şartlar ve koşulların tamamını okuyun",
  },
  notFound: {
    title: "Bu sayfayı bulamadık.",
    text: "Bağlantı eski olabilir veya sayfa taşınmış olabilir.",
    home: "Ana sayfaya git",
    programmes: "Programlarımızı görün",
  },
};

export const PUBLIC_COPY: Record<LandingLocale, PublicCopy> = { en, ar, tr };
export const OFFICIAL_PRIVACY = "https://nilecenter.edu.eg/privacy-policy/";
export const OFFICIAL_TERMS = "https://nilecenter.edu.eg/term_conditions/";
