import type { FormLocale } from "@shared/nileForms";
import type { Locale } from "@/lib/i18n";

export type RequestUiLocale = FormLocale;

export function requestUiLocale(locale: Locale): RequestUiLocale {
  return locale === "ar" || locale === "tr" ? locale : "en";
}

const copy = {
  en: {
    requests: "Requests",
    listDescription: "Track branch incidents and maintenance work.",
    reviewForms: "Review incident forms",
    refresh: "Refresh",
    search: "Search requests",
    allStatuses: "All statuses",
    loading: "Loading requests",
    loadFailed: "Requests could not be loaded.",
    retry: "Retry",
    empty: "No requests in this scope",
    emptyHelp:
      "Accepted incident forms will appear here after request creation.",
    requester: "Requester",
    assignee: "Assignee",
    unassigned: "Unassigned",
    due: "Due",
    branch: "Branch",
    category: "Category",
    priority: "Priority",
    status: "Status",
    back: "Back to requests",
    source: "Source evidence",
    submission: "Submission",
    version: "Version",
    details: "Request details",
    location: "Location",
    resolution: "Resolution",
    cancelled: "Cancellation reason",
    actions: "Next action",
    assign: "Assign request",
    assignmentReason: "Assignment reason",
    selectAssignee: "Select assignee",
    changePriority: "Change priority",
    priorityReason: "Priority change reason",
    start: "Start work",
    addComment: "Add comment",
    commentPlaceholder: "Add a factual update",
    sendComment: "Save comment",
    resolve: "Resolve request",
    resolutionPlaceholder: "Describe the completed resolution",
    cancel: "Cancel request",
    cancelPlaceholder: "Explain why this request is cancelled",
    activity: "Activity",
    comments: "Comments",
    noComments: "No comments yet.",
    noActivity: "No activity recorded.",
    saving: "Saving",
    saved: "Request updated.",
    createTitle: "Create operational request",
    createDescription:
      "Confirm the mapped request before creating operational work.",
    create: "Create request",
    sourceReview: "Reviewed source",
    immutable: "The reviewed Form submission remains immutable evidence.",
    existing: "A request already exists for this submission.",
    openRequest: "Open request",
  },
  ar: {
    requests: "الطلبات",
    listDescription: "متابعة بلاغات الفروع وأعمال الصيانة.",
    reviewForms: "مراجعة نماذج البلاغات",
    refresh: "تحديث",
    search: "البحث في الطلبات",
    allStatuses: "كل الحالات",
    loading: "جارٍ تحميل الطلبات",
    loadFailed: "تعذر تحميل الطلبات.",
    retry: "إعادة المحاولة",
    empty: "لا توجد طلبات ضمن هذا النطاق",
    emptyHelp: "تظهر نماذج البلاغات المقبولة هنا بعد إنشاء الطلب.",
    requester: "مقدم الطلب",
    assignee: "المسؤول",
    unassigned: "غير مسند",
    due: "موعد الاستحقاق",
    branch: "الفرع",
    category: "الفئة",
    priority: "الأولوية",
    status: "الحالة",
    back: "العودة إلى الطلبات",
    source: "دليل المصدر",
    submission: "الاستجابة",
    version: "الإصدار",
    details: "تفاصيل الطلب",
    location: "الموقع",
    resolution: "الحل",
    cancelled: "سبب الإلغاء",
    actions: "الإجراء التالي",
    assign: "إسناد الطلب",
    assignmentReason: "سبب الإسناد",
    selectAssignee: "اختر المسؤول",
    changePriority: "تغيير الأولوية",
    priorityReason: "سبب تغيير الأولوية",
    start: "بدء العمل",
    addComment: "إضافة تعليق",
    commentPlaceholder: "أضف تحديثًا واضحًا",
    sendComment: "حفظ التعليق",
    resolve: "حل الطلب",
    resolutionPlaceholder: "صف الحل المنجز",
    cancel: "إلغاء الطلب",
    cancelPlaceholder: "اشرح سبب إلغاء الطلب",
    activity: "النشاط",
    comments: "التعليقات",
    noComments: "لا توجد تعليقات بعد.",
    noActivity: "لا يوجد نشاط مسجل.",
    saving: "جارٍ الحفظ",
    saved: "تم تحديث الطلب.",
    createTitle: "إنشاء طلب تشغيلي",
    createDescription: "راجع البيانات المستخرجة قبل إنشاء العمل التشغيلي.",
    create: "إنشاء الطلب",
    sourceReview: "المصدر المراجع",
    immutable: "تبقى استجابة النموذج المراجعة دليلاً غير قابل للتعديل.",
    existing: "يوجد طلب مرتبط بهذه الاستجابة بالفعل.",
    openRequest: "فتح الطلب",
  },
  tr: {
    requests: "Talepler",
    listDescription: "Şube olaylarını ve bakım çalışmalarını takip edin.",
    reviewForms: "Olay formlarını incele",
    refresh: "Yenile",
    search: "Taleplerde ara",
    allStatuses: "Tüm durumlar",
    loading: "Talepler yükleniyor",
    loadFailed: "Talepler yüklenemedi.",
    retry: "Yeniden dene",
    empty: "Bu kapsamda talep yok",
    emptyHelp:
      "Kabul edilen olay formları talep oluşturulduktan sonra burada görünür.",
    requester: "Talep sahibi",
    assignee: "Sorumlu",
    unassigned: "Atanmamış",
    due: "Son tarih",
    branch: "Şube",
    category: "Kategori",
    priority: "Öncelik",
    status: "Durum",
    back: "Taleplere dön",
    source: "Kaynak kanıtı",
    submission: "Gönderim",
    version: "Sürüm",
    details: "Talep ayrıntıları",
    location: "Konum",
    resolution: "Çözüm",
    cancelled: "İptal nedeni",
    actions: "Sonraki işlem",
    assign: "Talebi ata",
    assignmentReason: "Atama nedeni",
    selectAssignee: "Sorumlu seçin",
    changePriority: "Önceliği değiştir",
    priorityReason: "Öncelik değişikliği nedeni",
    start: "Çalışmayı başlat",
    addComment: "Yorum ekle",
    commentPlaceholder: "Net bir güncelleme ekleyin",
    sendComment: "Yorumu kaydet",
    resolve: "Talebi çöz",
    resolutionPlaceholder: "Tamamlanan çözümü açıklayın",
    cancel: "Talebi iptal et",
    cancelPlaceholder: "İptal nedenini açıklayın",
    activity: "Etkinlik",
    comments: "Yorumlar",
    noComments: "Henüz yorum yok.",
    noActivity: "Kayıtlı etkinlik yok.",
    saving: "Kaydediliyor",
    saved: "Talep güncellendi.",
    createTitle: "Operasyon talebi oluştur",
    createDescription:
      "Operasyon çalışmasını oluşturmadan önce eşlenen talebi doğrulayın.",
    create: "Talep oluştur",
    sourceReview: "İncelenen kaynak",
    immutable: "İncelenen Form gönderimi değiştirilemez kanıt olarak kalır.",
    existing: "Bu gönderim için zaten bir talep var.",
    openRequest: "Talebi aç",
  },
} as const;

export type RequestCopyKey = keyof (typeof copy)["en"];

export function requestText(locale: RequestUiLocale, key: RequestCopyKey) {
  return copy[locale][key];
}
